uid: e10b4e7f-4c0f-4e62-b389-e486518af643
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: alpine_p_291_ks
created_at: '2025-12-12T08:37:03.738497+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:6fad93a0e497c69beabeda8f5151735441edf9b93933632b811f33b2a2f357f5
  name: ASLSBaseline_1
  path: ASLSBaseline_6fad93.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2025-12-12T08:37:03.901229+00:00'
  step: 1
- hash: sha256:9896eb89c564b635e39d9de9c124a7d5e86db5227e15bc8de8aae167d4331428
  name: y_StandardScaler
  path: StandardScaler_9896eb.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 445
  saved_at: '2025-12-12T08:37:04.105469+00:00'
  step: 4
- hash: sha256:747345dda2fee79224ad04020591950f3a28d46d4ee3d21812201d586ad0d2c0
  name: StandardScaler_1
  path: StandardScaler_747345.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 46651
  saved_at: '2025-12-12T08:37:04.117261+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T08:37:04.129494+00:00'
  step: 6
- hash: sha256:a970ff2440b3b3d4324c9ae4494a06e83ee210a53d80d142a6fa3abd0602a56a
  name: PCA_1
  path: PCA_a970ff.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 238927
  saved_at: '2025-12-12T08:37:04.228672+00:00'
  step: 7
- hash: sha256:b08f96168a3ebd455caa62cdf77b252f545ee98dff62c92cfc8c54925017a630
  name: StandardScaler_1
  path: StandardScaler_b08f96.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1001
  saved_at: '2025-12-12T08:37:04.262362+00:00'
  step: 8
- hash: sha256:0441a288d1dc4d733728c4920f7f5d7d94178368b67263f668815f8d8590ffc5
  name: PowerTransformer_1
  path: PowerTransformer_0441a2.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1362
  saved_at: '2025-12-12T08:37:04.311103+00:00'
  step: 9
- hash: sha256:9bc276ad5b66011fb6bb18fa25e4456a105d29b51627a0cdc457537f8d7f9dda
  name: AutoGluon_1.pkl
  path: TabularPredictor_9bc276.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 20204
  saved_at: '2025-12-12T08:37:25.011639+00:00'
  step: 10
- hash: sha256:4873f693b2fc9914a096b2b097d3356db5f954fcd1db71ee720ac4409bfc40c0
  name: AutoGluon_2.pkl
  path: TabularPredictor_4873f6.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 20222
  saved_at: '2025-12-12T08:37:25.012166+00:00'
  step: 10
- hash: sha256:e431f1a2b30adb9f6580c8d19d9d71018c5df416823a23a607842ef0cf2f4b16
  name: AutoGluon_3.pkl
  path: TabularPredictor_e431f1.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 20204
  saved_at: '2025-12-12T08:37:25.012667+00:00'
  step: 10
- hash: sha256:92d03eb525b1caad35295b11af7136a3ff49667bad46b99140e88258776f6aa8
  name: TabPFN_1.pkl
  path: TabPFNRegressor_92d03e.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42031395
  saved_at: '2025-12-12T08:37:50.221436+00:00'
  step: 11
- hash: sha256:ea9c5910d553f8fd370885f139d4f18a987d6ea1c09922ba167e087ad1e28d49
  name: TabPFN_2.pkl
  path: TabPFNRegressor_ea9c59.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42037603
  saved_at: '2025-12-12T08:37:50.278717+00:00'
  step: 11
- hash: sha256:7df23e7b8378e61d5c3ecdae0949553b5082153cd0d7dfdc42c40e524b3ac602
  name: TabPFN_3.pkl
  path: TabPFNRegressor_7df23e.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42037603
  saved_at: '2025-12-12T08:37:50.337187+00:00'
  step: 11
- hash: sha256:24b7c6515c4c36cb4883b3527d6b37712c4d2e6f9d5451612e6acbe11fc31552
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_24b7c6.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42031432
  saved_at: '2025-12-12T08:38:43.189839+00:00'
  step: 12
- hash: sha256:4b63136f30476866ffcce6876d38d9e083e9a7c4eb1b8db277b2b596166c07fa
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_4b6313.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42037640
  saved_at: '2025-12-12T08:38:43.234365+00:00'
  step: 12
- hash: sha256:d53139c4242626921699a40b96c8b65e89b04bc753bd318677fa11065b61e844
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_d53139.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42037640
  saved_at: '2025-12-12T08:38:43.277582+00:00'
  step: 12
predictions: []
