uid: 4d63899d-b770-492d-86f5-eeedc7861879
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: alpine_n_552_robustnessfennoscandia
created_at: '2025-12-12T08:43:58.271796+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:6fad93a0e497c69beabeda8f5151735441edf9b93933632b811f33b2a2f357f5
  name: ASLSBaseline_1
  path: ASLSBaseline_6fad93.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2025-12-12T08:43:58.577100+00:00'
  step: 1
- hash: sha256:7f0e63e6de53848011e7fe4abad33d7b592c78bd70f95a408b82b0eb2fd9fe55
  name: y_StandardScaler
  path: StandardScaler_7f0e63.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 445
  saved_at: '2025-12-12T08:43:58.881597+00:00'
  step: 4
- hash: sha256:4ab3bad2632c6ca67c644971174a46ea419153cf6ab9c3653ee0f0001f07a861
  name: StandardScaler_1
  path: StandardScaler_4ab3ba.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 46356
  saved_at: '2025-12-12T08:43:58.895211+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T08:43:58.935573+00:00'
  step: 6
- hash: sha256:44e1d1d7382fbcd0fa23854ad345c9e317a6665eb97f62fb90b98211f1726061
  name: PCA_1
  path: PCA_44e1d1.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 222864
  saved_at: '2025-12-12T08:43:59.029251+00:00'
  step: 7
- hash: sha256:a4c4562bfec1b2cf758b834347ddc0b4da666d772ec566dc4bd95ace0b6dc24c
  name: StandardScaler_1
  path: StandardScaler_a4c456.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 966
  saved_at: '2025-12-12T08:43:59.061854+00:00'
  step: 8
- hash: sha256:09e015b10cf7064145d1f4d1f4e9c9c306a999dc5b11f9fc9bc63b3baed89e7f
  name: PowerTransformer_1
  path: PowerTransformer_09e015.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1313
  saved_at: '2025-12-12T08:43:59.106970+00:00'
  step: 9
- hash: sha256:9e6bc95f3f9d203fd883b29d82f21202d894f7e0a3ca04c22e87e9393e8c4485
  name: AutoGluon_1.pkl
  path: TabularPredictor_9e6bc9.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 19492
  saved_at: '2025-12-12T08:44:25.002518+00:00'
  step: 10
- hash: sha256:00e6a31b8ca951456e6aa9b5dc6f5de2a55819e79582118abb9e8ac50696a8ce
  name: AutoGluon_2.pkl
  path: TabularPredictor_00e6a3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 19492
  saved_at: '2025-12-12T08:44:25.003043+00:00'
  step: 10
- hash: sha256:07a6de6eceec5b44737021464fdc4b9b9aa980643353da27260f485ba1eef8e1
  name: AutoGluon_3.pkl
  path: TabularPredictor_07a6de.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 19492
  saved_at: '2025-12-12T08:44:25.003659+00:00'
  step: 10
- hash: sha256:069c7e0f48f0d7d6d1abafcdd612ec394a6d6b4a72a57dda2326f98b2d62d9ab
  name: TabPFN_1.pkl
  path: TabPFNRegressor_069c7e.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41868888
  saved_at: '2025-12-12T08:44:52.990194+00:00'
  step: 11
- hash: sha256:062ac2dc1a512d57f5e00b4cbe14e19809646d5d741c94422df2f34658ebfc0f
  name: TabPFN_2.pkl
  path: TabPFNRegressor_062ac2.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41874648
  saved_at: '2025-12-12T08:44:53.032927+00:00'
  step: 11
- hash: sha256:9d4cd4e12e25a33f9de2e8241d7390b3e8ea05613b8455388b03cd73e84378d6
  name: TabPFN_3.pkl
  path: TabPFNRegressor_9d4cd4.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41874648
  saved_at: '2025-12-12T08:44:53.077199+00:00'
  step: 11
- hash: sha256:34f4bce19f71ae678405d10111722bfa3ccfad842cc5b0e48b8e769beea4054a
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_34f4bc.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41868925
  saved_at: '2025-12-12T08:45:53.284052+00:00'
  step: 12
- hash: sha256:bd060319ce1a1e287c714a3d15e2cf71c69122da513bbeeb3fbe33459ed1fef9
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_bd0603.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41874685
  saved_at: '2025-12-12T08:45:53.326119+00:00'
  step: 12
- hash: sha256:62736f67d52ca58bb774ff5b121e156d002e540886017f327ef0b4c3b9896abd
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_62736f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41874685
  saved_at: '2025-12-12T08:45:53.389185+00:00'
  step: 12
predictions: []
