uid: a21a71ac-25d0-4ffb-a256-ba40a355cc03
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: corn_protein_80_zhengchenpelegybasesplit
created_at: '2025-12-12T13:00:14.690439+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:26b2ddd51689b4d62afd0d8120bf3701bb34aecf8f7c42b134bb6c3d9b5f3096
  name: ASLSBaseline_1
  path: ASLSBaseline_26b2dd.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T13:00:14.711533+00:00'
  step: 1
- hash: sha256:3b745a96567e56d7273d748fa476c0726021fd6f960cf2e39fc6e6b632bd0f82
  name: y_StandardScaler
  path: StandardScaler_3b745a.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 444
  saved_at: '2025-12-12T13:00:14.765226+00:00'
  step: 4
- hash: sha256:029da016177956f939761a7f2aa0dd50292822b9bbda321c3b90d9d49a5a90bb
  name: StandardScaler_1
  path: StandardScaler_029da0.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 14519
  saved_at: '2025-12-12T13:00:14.773343+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T13:00:14.782800+00:00'
  step: 6
- hash: sha256:90194affec3d7d63b2c2fd54ea1ec2c503512bbddb8a5792e74f2ec7324fcc67
  name: PCA_1
  path: PCA_90194a.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 20742
  saved_at: '2025-12-12T13:00:14.807976+00:00'
  step: 7
- hash: sha256:a0f739e8bf074cf3eec203cb7fe7c66e212fa5e116245065ec2247b498d6be20
  name: StandardScaler_1
  path: StandardScaler_a0f739.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 543
  saved_at: '2025-12-12T13:00:14.843939+00:00'
  step: 8
- hash: sha256:4ff695549ca0bc94c3863d67c71cb78166cc41f818701c0bd9b3711a28de8d26
  name: PowerTransformer_1
  path: PowerTransformer_4ff695.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 744
  saved_at: '2025-12-12T13:00:14.872280+00:00'
  step: 9
- hash: sha256:742a1f4c4be1f4aa252e7a1ced064759f48797cfced54819578fefdeef3e3b90
  name: AutoGluon_1.pkl
  path: TabularPredictor_742a1f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12378
  saved_at: '2025-12-12T13:00:27.482131+00:00'
  step: 10
- hash: sha256:93cdc699d12f706a65dbd1bce243067c837553ce7538678678bd15d2ef7475ca
  name: AutoGluon_2.pkl
  path: TabularPredictor_93cdc6.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12378
  saved_at: '2025-12-12T13:00:27.482504+00:00'
  step: 10
- hash: sha256:eedba7a30bf65ba0b3660797035fa4b69063b73a3e342498b6adcdd5448633bb
  name: AutoGluon_3.pkl
  path: TabularPredictor_eedba7.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12387
  saved_at: '2025-12-12T13:00:27.482834+00:00'
  step: 10
- hash: sha256:c9e4311d65e1e0636be4e890171f5dd5213410be2a2f22186700cc43f8d6011b
  name: TabPFN_1.pkl
  path: TabPFNRegressor_c9e431.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41019403
  saved_at: '2025-12-12T13:00:33.692919+00:00'
  step: 11
- hash: sha256:b7c840d81c6ad793c05c533a5abc7bf12f5d8179638760f8de9df713a8343edd
  name: TabPFN_2.pkl
  path: TabPFNRegressor_b7c840.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41021003
  saved_at: '2025-12-12T13:00:33.751982+00:00'
  step: 11
- hash: sha256:6cb84a2af2e3c7423dde5aebd8f6ca319c8e330195c369f6e29c104530303f2c
  name: TabPFN_3.pkl
  path: TabPFNRegressor_6cb84a.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41021003
  saved_at: '2025-12-12T13:00:33.806131+00:00'
  step: 11
- hash: sha256:d97484a4c182fb5f6334cec191732592169f9cdb84ec7fbfc96e208ab94fdf5b
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_d97484.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41019440
  saved_at: '2025-12-12T13:00:44.823219+00:00'
  step: 12
- hash: sha256:a45c9bd373d9660b46a5b028dd3759277d3fbcf5dfaf6854ad65ed9561551bb7
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_a45c9b.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41021040
  saved_at: '2025-12-12T13:00:44.876630+00:00'
  step: 12
- hash: sha256:2d928158f51265ae6487ffaad8ac00390f41bf488cff675a9cd02dea4f400c87
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_2d9281.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41021040
  saved_at: '2025-12-12T13:00:44.930342+00:00'
  step: 12
predictions: []
