uid: d86fcd00-592b-40c2-8ce8-1d1cdbaa8ba5
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: poultry_manure_total_n_ks
created_at: '2026-01-07T09:22:44.566645+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:125d94dee500492a3bdb8dd8b9fa106b8b2b34e5f42944e4b15d55960ffb73d1
  name: ASLSBaseline_1
  path: ASLSBaseline_125d94.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2026-01-07T09:22:44.612349+00:00'
  step: 1
- hash: sha256:116cde38aabd6bccb2e89cea64d7506762ad4265816409ac35686bb6a5a6e0c5
  name: PCA_1
  path: PCA_116cde.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 19682
  saved_at: '2026-01-07T09:22:44.649896+00:00'
  step: 4
- hash: sha256:f225015e1a56e79449f2a9d4547101151ef939ff53a9938fd4df12666c2dd3dc
  name: AutoGluon_1.pkl
  path: TabularPredictor_f22501.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2026-01-07T09:22:55.993782+00:00'
  step: 5
- hash: sha256:643e4755c8d4d9901b5de935dcb9fa2bc7e893ad9cc501bd6bb2f25fd5baa6da
  name: AutoGluon_2.pkl
  path: TabularPredictor_643e47.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11196
  saved_at: '2026-01-07T09:22:55.994069+00:00'
  step: 5
- hash: sha256:bb35915d35bede20da3f9498802cbeadacee43ec34754e5324d7599fc5cc335d
  name: AutoGluon_3.pkl
  path: TabularPredictor_bb3591.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11196
  saved_at: '2026-01-07T09:22:55.994321+00:00'
  step: 5
- hash: sha256:3b40b9d707d3844a7faaeff8b66bdca414bc68c014516bda718d2cc3c7ec1699
  name: TabPFN_1.pkl
  path: TabPFNRegressor_3b40b9.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41016982
  saved_at: '2026-01-07T09:23:00.867741+00:00'
  step: 6
- hash: sha256:3061b95147e4a9741b67527a3543f6678d8776a690a5a241d1e49448843e682f
  name: TabPFN_2.pkl
  path: TabPFNRegressor_3061b9.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41018006
  saved_at: '2026-01-07T09:23:00.927295+00:00'
  step: 6
- hash: sha256:148e622a20cbc3d3ef13df369cfc24c439d5781a0d1f5db64c76dda0b281d43a
  name: TabPFN_3.pkl
  path: TabPFNRegressor_148e62.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41018006
  saved_at: '2026-01-07T09:23:00.988427+00:00'
  step: 6
- hash: sha256:20cfc72ba20dac7dd19adf8e35ca68c58360ff238044bc535f8f3e8e01f52fdf
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_20cfc7.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41017019
  saved_at: '2026-01-07T09:23:13.895974+00:00'
  step: 7
- hash: sha256:c712a42c9ce2b60d8314c5fb19a542eede86334635a2c2f58cf22e67540ae9ae
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_c712a4.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41018043
  saved_at: '2026-01-07T09:23:13.959156+00:00'
  step: 7
- hash: sha256:10bafdc08ae5c45013cbf56aca6b0d1b4fbb813be10e8d3d5e5502c8d230880d
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_10bafd.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41018043
  saved_at: '2026-01-07T09:23:14.021208+00:00'
  step: 7
predictions: []
