uid: 09ccb275-4831-4c50-9f11-0d48e5ec264b
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: milk_lactose_1224_ks
created_at: '2026-01-07T11:09:50.356466+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:b4db648a2547c1dc21ee2878cc4522bcc8f758afcdc997e89b71292698331f0a
  name: ASLSBaseline_1
  path: ASLSBaseline_b4db64.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2026-01-07T11:09:50.510352+00:00'
  step: 1
- hash: sha256:d677474660e8c77f7c3ccd70efa496f957194428fc75068fef1ae28095bc3f04
  name: PCA_1
  path: PCA_d67747.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 2626
  saved_at: '2026-01-07T11:09:51.861990+00:00'
  step: 4
- hash: sha256:e4470bfdf3528cd8078285dde96a74a6739a736c7473c3494a9777de8e7865c6
  name: AutoGluon_1.pkl
  path: TabularPredictor_e4470b.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 10123
  saved_at: '2026-01-07T11:10:10.147191+00:00'
  step: 5
- hash: sha256:3006dbc7e0889b4b864ffe276439b516d8cfc435fb18eafd0a6f51cacf1c119b
  name: AutoGluon_2.pkl
  path: TabularPredictor_3006db.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 10123
  saved_at: '2026-01-07T11:10:10.147483+00:00'
  step: 5
- hash: sha256:5d6eac3491a805eab88cc7f1328fb77f34c3e7b5128c1d6f4e791ca47e6f9764
  name: AutoGluon_3.pkl
  path: TabularPredictor_5d6eac.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 10066
  saved_at: '2026-01-07T11:10:10.147732+00:00'
  step: 5
- hash: sha256:20d31f634e51c16a244324eaa6d13a9a377660ce0472c0bbb8951173bbdd06ad
  name: TabPFN_1.pkl
  path: TabPFNRegressor_20d31f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41159518
  saved_at: '2026-01-07T11:10:26.366736+00:00'
  step: 6
- hash: sha256:4b4527ff290b764065166c9e2cdabb6f9f57d3547e07ff597a8d517b655920c3
  name: TabPFN_2.pkl
  path: TabPFNRegressor_4b4527.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41159902
  saved_at: '2026-01-07T11:10:26.414926+00:00'
  step: 6
- hash: sha256:ad6fb7834512e6db4979bdbfc99a36b5df763cde667dad871738c146a8ffb0b0
  name: TabPFN_3.pkl
  path: TabPFNRegressor_ad6fb7.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41159902
  saved_at: '2026-01-07T11:10:26.463202+00:00'
  step: 6
- hash: sha256:fa7eb2dcf77a090efabc931dc4c18b449ad01d3846c96661beb385b0b3ef855b
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_fa7eb2.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41159555
  saved_at: '2026-01-07T11:11:00.934772+00:00'
  step: 7
- hash: sha256:ea41cc51f9b60648a60e5e1e80e586032417bc430b1bdf604a97a555f5088834
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_ea41cc.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41159939
  saved_at: '2026-01-07T11:11:00.985347+00:00'
  step: 7
- hash: sha256:b7eea1f574d84a0239f136446b7c890d73bb1f57dfeb98c2b9b3a1e24a25ee09
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_b7eea1.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41159939
  saved_at: '2026-01-07T11:11:01.035566+00:00'
  step: 7
predictions: []
