uid: b4f8980a-2804-4e5a-8425-e1a4bc8ec8f1
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: diesel_visc_395_pengks
created_at: '2026-01-07T11:19:13.609477+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2026-01-07T11:19:13.685496+00:00'
  step: 1
- hash: sha256:aeae46dc8824c825574288056cc957d910425185fcc55e8ee28c73a4f92c6b37
  name: PCA_1
  path: PCA_aeae46.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 8354
  saved_at: '2026-01-07T11:19:13.796703+00:00'
  step: 4
- hash: sha256:f74cb1f8dbdcab1fc6943bbc504d70580472f9dc7ba3e351cc9a614a2b0a82d1
  name: AutoGluon_1.pkl
  path: TabularPredictor_f74cb1.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11196
  saved_at: '2026-01-07T11:19:28.845171+00:00'
  step: 5
- hash: sha256:e0ce7a8fc90ee99a50411750134d7f2298a231ac58ee976eef46729cd017ed24
  name: AutoGluon_2.pkl
  path: TabularPredictor_e0ce7a.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2026-01-07T11:19:28.845458+00:00'
  step: 5
- hash: sha256:226ddd71f8bc4205b101a5f73325790aafecc3fa8cf9af3795fc99c761d46b8f
  name: AutoGluon_3.pkl
  path: TabularPredictor_226ddd.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2026-01-07T11:19:28.845715+00:00'
  step: 5
- hash: sha256:4a18a268dbcb1a771acd8ad3f346b86cafe4fa8bc67cdb84a8f113b9e795add4
  name: TabPFN_1.pkl
  path: TabPFNRegressor_4a18a2.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41141672
  saved_at: '2026-01-07T11:19:38.597088+00:00'
  step: 6
- hash: sha256:40d43e097478cdd589a7f7246d493f346dce324bbe67d10856d4f5c879acea5a
  name: TabPFN_2.pkl
  path: TabPFNRegressor_40d43e.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41141672
  saved_at: '2026-01-07T11:19:38.654440+00:00'
  step: 6
- hash: sha256:26b2f4156bda4c04d6b451e8e061d39ba21a23682ee7378af7136186d7b1088b
  name: TabPFN_3.pkl
  path: TabPFNRegressor_26b2f4.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41141672
  saved_at: '2026-01-07T11:19:38.713234+00:00'
  step: 6
- hash: sha256:c58d33c0d4653ed30f1b3d77624fa8aed4460e4e25b7e59b4622f6d6ed7cd118
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_c58d33.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41141709
  saved_at: '2026-01-07T11:19:56.706437+00:00'
  step: 7
- hash: sha256:7737007dab901405ba1ccf7bdbd35bd9f8f081de96de65bc8de9409aa3db91fe
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_773700.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41141709
  saved_at: '2026-01-07T11:19:56.763913+00:00'
  step: 7
- hash: sha256:f3d208e7d62ea9a421f5892c83392f12b616db4969a5b0c3d21b2d9381cd81aa
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_f3d208.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41141709
  saved_at: '2026-01-07T11:19:56.821278+00:00'
  step: 7
predictions: []
