uid: eb8bdfc7-5f3e-4ed3-abf4-a28efad77f59
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: diesel_visc_395_zhengybase
created_at: '2025-12-12T11:01:52.343285+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T11:01:52.405368+00:00'
  step: 1
- hash: sha256:cd5d886361e138187cc01f4d64910761cf974a381d3b08bb59ce46541daaa8d0
  name: y_StandardScaler
  path: StandardScaler_cd5d88.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 446
  saved_at: '2025-12-12T11:01:52.666221+00:00'
  step: 4
- hash: sha256:f1ef4917011b920a8995ac49d901f35f71a4cb98adb2299dfe3de97ad961a21c
  name: StandardScaler_1
  path: StandardScaler_f1ef49.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9275
  saved_at: '2025-12-12T11:01:52.671958+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T11:01:52.680936+00:00'
  step: 6
- hash: sha256:e415f74ec79db4a8318bf6630723d471ae4705cbfbc8b80078216d7d5943e75e
  name: PCA_1
  path: PCA_e415f7.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 18552
  saved_at: '2025-12-12T11:01:52.731017+00:00'
  step: 7
- hash: sha256:de1d67e174bdd2ac3120f902696927ade15bdb81a77876ab00ea7ce2f6fa062d
  name: StandardScaler_1
  path: StandardScaler_de1d67.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 663
  saved_at: '2025-12-12T11:01:52.774714+00:00'
  step: 8
- hash: sha256:b4c10539ab550731e32ad8e0f7d9bc5cf02940d3fc63368c76c115a84ac320fd
  name: PowerTransformer_1
  path: PowerTransformer_b4c105.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 882
  saved_at: '2025-12-12T11:01:52.818304+00:00'
  step: 9
- hash: sha256:f6fa8a1bbf1a2044601d7e4ed8af8a43cd261759964b89a2d829335ed319840a
  name: AutoGluon_1.pkl
  path: TabularPredictor_f6fa8a.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 13805
  saved_at: '2025-12-12T11:02:10.751622+00:00'
  step: 10
- hash: sha256:c9b6a363d4631026fd2de4b6c1d05f484bc9eeb1732df2caf02873bca2a4febc
  name: AutoGluon_2.pkl
  path: TabularPredictor_c9b6a3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 13805
  saved_at: '2025-12-12T11:02:10.752109+00:00'
  step: 10
- hash: sha256:93fdd11df20df3a1bde68ff055a0c6f659c0be9885a4fa9e64002e7a916e8b33
  name: AutoGluon_3.pkl
  path: TabularPredictor_93fdd1.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 13787
  saved_at: '2025-12-12T11:02:10.752552+00:00'
  step: 10
- hash: sha256:c4d901d730c7072db2025847108dc7bc6a0e714646058847a16661666eda8f2e
  name: TabPFN_1.pkl
  path: TabPFNRegressor_c4d901.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41481455
  saved_at: '2025-12-12T11:02:25.245789+00:00'
  step: 11
- hash: sha256:712497b106a88d237301b9a6f4b8c9a67a2ad9bae8e993dfc7a2669fc0d31367
  name: TabPFN_2.pkl
  path: TabPFNRegressor_712497.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41483889
  saved_at: '2025-12-12T11:02:25.300864+00:00'
  step: 11
- hash: sha256:9226f3c59bb2d7391576bb07a10ba1f1eb4f03c50808273ce5b3da5fd0a93574
  name: TabPFN_3.pkl
  path: TabPFNRegressor_9226f3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41483896
  saved_at: '2025-12-12T11:02:25.355601+00:00'
  step: 11
- hash: sha256:b681dbb4aab31baf701d80312e9290867d929736445da4862ee0aeb69e350972
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_b681db.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41481498
  saved_at: '2025-12-12T11:02:57.467005+00:00'
  step: 12
- hash: sha256:18c101ebdedcb4d0be2e0f0876670db19c91ccb4d65d901106be4ffb1d62337d
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_18c101.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41483924
  saved_at: '2025-12-12T11:02:57.522341+00:00'
  step: 12
- hash: sha256:7c0a90592f977c376eceb3e6b9df160837e91d1542daf7363364a0c8e0ae75ae
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_7c0a90.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41483924
  saved_at: '2025-12-12T11:02:57.577499+00:00'
  step: 12
predictions: []
