uid: 2b12ad19-839a-44ef-925f-0f2608a0e7f9
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: cassava_tcc_4930_davrieuxrobustness2014
created_at: '2025-12-12T08:46:26.674774+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:e3981c22fe01bf6ba48b414ed19291553d7fa375224b447ff7d90a870e91f7c3
  name: ASLSBaseline_1
  path: ASLSBaseline_e3981c.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2025-12-12T08:46:28.036242+00:00'
  step: 1
- hash: sha256:be7697bbf46694a8a4fbe3b04b8e33bd573c3170f766072d13a9e343f166983d
  name: y_StandardScaler
  path: StandardScaler_be7697.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 441
  saved_at: '2025-12-12T08:49:16.054814+00:00'
  step: 4
- hash: sha256:11ae92ee3c7f0cc536eb57841b9e6b33ecc89a24b71a6754cf20604f42a1461e
  name: StandardScaler_1
  path: StandardScaler_11ae92.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 24207
  saved_at: '2025-12-12T08:49:16.150279+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T08:49:16.222859+00:00'
  step: 6
- hash: sha256:7d0f2c97c253d6dfdecaab1fdf349f8d3da023dc5130adad7b058b56671a5f95
  name: PCA_1
  path: PCA_7d0f2c.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 44037
  saved_at: '2025-12-12T08:49:16.481950+00:00'
  step: 7
- hash: sha256:00e93d56021f54605b9710b8334c4175df9cc6ac4591dc616b51345166eafc6f
  name: StandardScaler_1
  path: StandardScaler_00e93d.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 643
  saved_at: '2025-12-12T08:49:16.576158+00:00'
  step: 8
- hash: sha256:bedfd1947b706e8c20549c96217c71819b5abdebda635b0b25ad9972bd619917
  name: PowerTransformer_1
  path: PowerTransformer_bedfd1.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 844
  saved_at: '2025-12-12T08:49:16.662334+00:00'
  step: 9
- hash: sha256:a17fc2e02736f78077815161d194a3e6c6d46d00681a4078983a4a59e7893bbb
  name: AutoGluon_1.pkl
  path: TabularPredictor_a17fc2.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 13490
  saved_at: '2025-12-12T08:49:53.239307+00:00'
  step: 10
- hash: sha256:8a4916a21a12779a814fcefa29cf8d8ea7a51883f2dbbdba8cc07f306d86ac49
  name: AutoGluon_2.pkl
  path: TabularPredictor_8a4916.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 13481
  saved_at: '2025-12-12T08:49:53.239841+00:00'
  step: 10
- hash: sha256:c47408e8842d53503744a5cd8fde057f2ef6ac09515a4c6479b13cda5277bed6
  name: AutoGluon_3.pkl
  path: TabularPredictor_c47408.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 13490
  saved_at: '2025-12-12T08:49:53.240352+00:00'
  step: 10
- hash: sha256:9afcc01d4453cb4442f0a18af2a8ffc3e321e1d41b2e6f5f43cf192b70e538f2
  name: TabPFN_1.pkl
  path: TabPFNRegressor_9afcc0.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 47833683
  saved_at: '2025-12-12T08:57:03.646624+00:00'
  step: 11
- hash: sha256:c8e04d57fdc4b6cdeafff5dd1f77aba5ee0e5ef79453d2f628bb910ba6a77840
  name: TabPFN_2.pkl
  path: TabPFNRegressor_c8e04d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 47835923
  saved_at: '2025-12-12T08:57:03.713987+00:00'
  step: 11
- hash: sha256:7049467116523384c0929df61b38d504c104dc466862bde4c65379b61a11efb0
  name: TabPFN_3.pkl
  path: TabPFNRegressor_704946.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 47835923
  saved_at: '2025-12-12T08:57:03.781670+00:00'
  step: 11
- hash: sha256:3a07acd0320ac0ddf847684e85d0de5ade1028a0e0e27adf5faf6bd1feb9e224
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_3a07ac.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 47833720
  saved_at: '2025-12-12T09:14:11.579476+00:00'
  step: 12
- hash: sha256:230807cbb0291a7c3c3b462efc9ef289651f78dca50a51538575bcb8edcdfa51
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_230807.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 47835960
  saved_at: '2025-12-12T09:14:11.641375+00:00'
  step: 12
- hash: sha256:2747055b7cfb3c3808fba638ba7efa53787f789ccc2da75b100b8aacaa5ad1ab
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_274705.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 47835960
  saved_at: '2025-12-12T09:14:11.705953+00:00'
  step: 12
predictions: []
