schema_version: '2.0'
uid: 8f9a3ddc-81f1-4641-814e-9dd8fd729741
pipeline_id: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57
name: PLS_PP_SELECTION_NO_SAVE_6caa57
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:20:55.021361+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: null
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - nirs4all.operators.transforms.scalers.StandardNormalVariate
    - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
    - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
      params:
        window_length: 15
        deriv: 1
    - class: nirs4all.operators.transforms.nirs.Wavelet
      params:
        wavelet: coif3
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: null
- _cartesian_:
  - nirs4all.operators.transforms.scalers.StandardNormalVariate
  - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
  - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
    params:
      window_length: 15
      deriv: 1
  - class: nirs4all.operators.transforms.nirs.Wavelet
    params:
      wavelet: coif3
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:20:55.049462+00:00'
    params: {}
    version: 3
  - artifact_id: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$6e21be876a4d:all
    content_hash: sha256:f1b0d49d100fdce0b1f766631a2fc34c1b2477ed43ee4a120b8aedc3581c1d26
    path: transformer_StandardNormalVariate_f1b0d49d100f.joblib
    chain_path: s5.StandardNormalVariate[src=0,sub=0]
    source_index: 0
    pipeline_id: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: StandardNormalVariate
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 132
    created_at: '2026-01-08T17:20:55.059531+00:00'
    params: {}
    version: 3
  - artifact_id: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$43cfdb4b8dc0:all
    content_hash: sha256:691364ebf5c9cf5f03e16c3b48e170cf0041f7b9fd02c8c40dcdafece2312e1d
    path: transformer_ExtendedMultiplicativeScatterCorrection_691364ebf5c9.joblib
    chain_path: s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=1]
    source_index: 0
    pipeline_id: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: ExtendedMultiplicativeScatterCorrection
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 5683
    created_at: '2026-01-08T17:20:55.062899+00:00'
    params: {}
    version: 3
  - artifact_id: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$296923040127:all
    content_hash: sha256:d663934f32b4b5e8dba18585ed74e0c4e66ed1008ee606d100f374d3224f9c49
    path: transformer_SavitzkyGolay_d663934f32b4.joblib
    chain_path: s5.SavitzkyGolay[src=0,sub=2]
    source_index: 0
    pipeline_id: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57
    branch_path: []
    step_index: 5
    substep_index: 2
    fold_id: null
    artifact_type: transformer
    class_name: SavitzkyGolay
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 137
    created_at: '2026-01-08T17:20:55.064654+00:00'
    params: {}
    version: 3
  - artifact_id: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$3569153fa566:all
    content_hash: sha256:f2c1d06f4298f812e17b88a6602355856be25df4ed5fa680286d202bd476cb07
    path: transformer_Wavelet_f2c1d06f4298.joblib
    chain_path: s5.Wavelet[src=0,sub=3]
    source_index: 0
    pipeline_id: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57
    branch_path: []
    step_index: 5
    substep_index: 3
    fold_id: null
    artifact_type: transformer
    class_name: Wavelet
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 114
    created_at: '2026-01-08T17:20:55.066342+00:00'
    params: {}
    version: 3
  - artifact_id: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$9f79d59455ab:0
    content_hash: sha256:65c95078cf95e2525c04afcda22a9668c971f29edf7cad26769d11c806d2113d
    path: model_PLSRegression_65c95078cf95.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 196525
    created_at: '2026-01-08T17:20:55.760635+00:00'
    params: {}
    version: 3
  - artifact_id: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$9f79d59455ab:1
    content_hash: sha256:8a15d12c4cc0e606a38fb0f8f1094fc2321a2a870d2a69e860a962e967e446ef
    path: model_PLSRegression_8a15d12c4cc0.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 196907
    created_at: '2026-01-08T17:20:55.764828+00:00'
    params: {}
    version: 3
  - artifact_id: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$9f79d59455ab:2
    content_hash: sha256:186dc6326b3353e2c995298f110ae6d4bebb3de5c64024117b921ed01d495612
    path: model_PLSRegression_186dc6326b33.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 196889
    created_at: '2026-01-08T17:20:55.769037+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  9328a737-04c:
    trace_id: 9328a737-04c
    pipeline_uid: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57
    created_at: '2026-01-08T17:20:55.022494+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 2.493143081665039
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 1.505136489868164
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 26.67522430419922
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 4.262447357177734
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: StandardNormalVariate, ExtendedMultiplicativeScatterCorrection,
        SavitzkyGolay (+1)
      operator_config:
        feature_augmentation:
        - nirs4all.operators.transforms.scalers.StandardNormalVariate
        - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
        - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
          params:
            window_length: 15
            deriv: 1
        - class: nirs4all.operators.transforms.nirs.Wavelet
          params:
            wavelet: coif3
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$6e21be876a4d:all
        - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$43cfdb4b8dc0:all
        - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$296923040127:all
        - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$3569153fa566:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$6e21be876a4d:all
            - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$43cfdb4b8dc0:all
            - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$296923040127:all
            - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$3569153fa566:all
        by_source:
          0:
          - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$6e21be876a4d:all
          - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$43cfdb4b8dc0:all
          - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$296923040127:all
          - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$3569153fa566:all
        by_chain:
          s5.StandardNormalVariate[src=0,sub=0]: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$6e21be876a4d:all
          s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=1]: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$43cfdb4b8dc0:all
          s5.SavitzkyGolay[src=0,sub=2]: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$296923040127:all
          s5.Wavelet[src=0,sub=3]: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$3569153fa566:all
        metadata:
          class_name: Wavelet
          name: Wavelet_4
      branch_path: []
      branch_name: ''
      duration_ms: 21.70109748840332
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.StandardNormalVariate[src=0,sub=0]
      - s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=1]
      - s5.SavitzkyGolay[src=0,sub=2]
      - s5.Wavelet[src=0,sub=3]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 2880
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 5
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$9f79d59455ab:0
        - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$9f79d59455ab:1
        - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$9f79d59455ab:0
          1: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$9f79d59455ab:1
          2: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$9f79d59455ab:0
            - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$9f79d59455ab:1
            - 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0088_PLS_PP_SELECTION_NO_SAVE_6caa57$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 718.2867527008057
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 2880
      output_shape:
      - 60
      - 2880
      input_features_shape:
      - - 60
        - 5
        - 576
      output_features_shape:
      - - 60
        - 5
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: raw|SNV|ExtendedMSC|SG|Wavelet
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_6caa57
      n_steps: 6
      n_artifacts: 8
