uid: ae53cf93-af5b-491b-955f-4a97e7fa90a1
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: alpine_p_291_ks
created_at: '2026-01-07T09:32:37.704772+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:6fad93a0e497c69beabeda8f5151735441edf9b93933632b811f33b2a2f357f5
  name: ASLSBaseline_1
  path: ASLSBaseline_6fad93.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2026-01-07T09:32:37.876212+00:00'
  step: 1
- hash: sha256:c5bb3e2b4915b8f91794c3db4522c3c75675d534231faf4657d3752d34b2eaef
  name: PCA_1
  path: PCA_c5bb3e.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 137880
  saved_at: '2026-01-07T09:32:38.107840+00:00'
  step: 4
- hash: sha256:8cb46cecfee7c4000b164ff8a9dc5685e3727840cdc9d6c8644ae26a952dc555
  name: AutoGluon_1.pkl
  path: TabularPredictor_8cb46c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 15576
  saved_at: '2026-01-07T09:33:05.709266+00:00'
  step: 5
- hash: sha256:0b10f5426946c817bd58a494a0ccda3d327776b0fd6a717d0779d2570728579a
  name: AutoGluon_2.pkl
  path: TabularPredictor_0b10f5.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 15576
  saved_at: '2026-01-07T09:33:05.709753+00:00'
  step: 5
- hash: sha256:b6a2ce66566cce0e17eba45b52a974f480e17569b1fecc6f34a70a1f97a57e16
  name: AutoGluon_3.pkl
  path: TabularPredictor_b6a2ce.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 15576
  saved_at: '2026-01-07T09:33:05.710378+00:00'
  step: 5
- hash: sha256:933963dda71ef70fab7d4d76fa2cb6528ad60c96aa4f000b79e8d8421192147a
  name: TabPFN_1.pkl
  path: TabPFNRegressor_933963.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41556936
  saved_at: '2026-01-07T09:33:20.503537+00:00'
  step: 6
- hash: sha256:0c1e7accc3b65dee9fde786d64c35a518b6e6bc0234a664f05b7e7d2dda21313
  name: TabPFN_2.pkl
  path: TabPFNRegressor_0c1e7a.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41560460
  saved_at: '2026-01-07T09:33:20.547620+00:00'
  step: 6
- hash: sha256:f60cd499fa666d9f101732d0be1b50bbdae4d0f560de8ae138f28c3d772ee24b
  name: TabPFN_3.pkl
  path: TabPFNRegressor_f60cd4.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41560462
  saved_at: '2026-01-07T09:33:20.590956+00:00'
  step: 6
- hash: sha256:f5f8c70edd6d010a0c22275faa1b8fb579300d6ceec79ee63763cdf08b05e1ba
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_f5f8c7.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41556975
  saved_at: '2026-01-07T09:33:50.854509+00:00'
  step: 7
- hash: sha256:9b037a8e8c52ece76692dd31889cd907e771f42ba9ffd241ce7fafed8dcdbb76
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_9b037a.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41560499
  saved_at: '2026-01-07T09:33:50.897731+00:00'
  step: 7
- hash: sha256:bcb1267d4197ab3851a13ff754a6522f031b0f699ceb0669e669df2ce18a7a95
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_bcb126.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41560499
  saved_at: '2026-01-07T09:33:50.941227+00:00'
  step: 7
predictions: []
