uid: 6cb2d1fd-bc33-4ee3-8a65-9507bf4b55b9
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: poultry_manure_dm_ks
created_at: '2025-12-12T08:42:43.283488+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:125d94dee500492a3bdb8dd8b9fa106b8b2b34e5f42944e4b15d55960ffb73d1
  name: ASLSBaseline_1
  path: ASLSBaseline_125d94.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T08:42:43.341673+00:00'
  step: 1
- hash: sha256:20f3a2ae938fcba98d6d16debc248820e5de8c5343add8ee63a08a874237d189
  name: y_StandardScaler
  path: StandardScaler_20f3a2.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 440
  saved_at: '2025-12-12T08:42:43.445607+00:00'
  step: 4
- hash: sha256:b81dc395d1dd80940342c9d3237f852b94dbd4704afba86f452dc9b2bf4d63c4
  name: StandardScaler_1
  path: StandardScaler_b81dc3.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 21264
  saved_at: '2025-12-12T08:42:43.455466+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T08:42:43.464358+00:00'
  step: 6
- hash: sha256:5862dbfd9bfbdf7f0cbfc1c544cd73bf5e8f61dea119f9b4783de94b26d16912
  name: PCA_1
  path: PCA_5862db.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 111761
  saved_at: '2025-12-12T08:42:43.521750+00:00'
  step: 7
- hash: sha256:839f98ae517f3aa6a02b3903217ecb1645dff11963b361a4c3c6a436ae95334c
  name: StandardScaler_1
  path: StandardScaler_839f98.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 944
  saved_at: '2025-12-12T08:42:43.564371+00:00'
  step: 8
- hash: sha256:d84f5cbd3f747a7ec3dc5ab2623a45bce39a0502f058affcadd8ac7b3caed0b7
  name: PowerTransformer_1
  path: PowerTransformer_d84f5c.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1339
  saved_at: '2025-12-12T08:42:43.607346+00:00'
  step: 9
- hash: sha256:68e6d75c9e146ab78f7888043bc2e5c29581d3c63dea074613e62dfc4b471e51
  name: AutoGluon_1.pkl
  path: TabularPredictor_68e6d7.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 20213
  saved_at: '2025-12-12T08:42:57.735117+00:00'
  step: 10
- hash: sha256:a8659a55bafcd10e29fce8f116dc213cae079cf3c223f7ca8e4cc8161181aa05
  name: AutoGluon_2.pkl
  path: TabularPredictor_a8659a.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 20204
  saved_at: '2025-12-12T08:42:57.735699+00:00'
  step: 10
- hash: sha256:7c902d561b39e93493dc8c4a3f8b9692119020a38a0c9ade754d6ba5e7333266
  name: AutoGluon_3.pkl
  path: TabularPredictor_7c902d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 20195
  saved_at: '2025-12-12T08:42:57.736247+00:00'
  step: 10
- hash: sha256:26f20440705a9f2fef7b85132004c503cd821f29e763a9559cf331489c7ba6f4
  name: TabPFN_1.pkl
  path: TabPFNRegressor_26f204.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41403748
  saved_at: '2025-12-12T08:43:13.054551+00:00'
  step: 11
- hash: sha256:a4ed6627bcd0b05d0f8f9b2305e1ca00f7a96766b0e3d403f4a178b44672caf6
  name: TabPFN_2.pkl
  path: TabPFNRegressor_a4ed66.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41409956
  saved_at: '2025-12-12T08:43:13.097886+00:00'
  step: 11
- hash: sha256:e84cd43350d0f4cfb29a2303e9cdb07b78bcdbb8d8f2a52054d74ccea146d45f
  name: TabPFN_3.pkl
  path: TabPFNRegressor_e84cd4.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41409956
  saved_at: '2025-12-12T08:43:13.140714+00:00'
  step: 11
- hash: sha256:7563618a08998c7174206a2ca03128e0f324e9c4d877ff8775686db0329defdc
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_756361.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41403785
  saved_at: '2025-12-12T08:43:42.318715+00:00'
  step: 12
- hash: sha256:b650e19b4d6cf5e9d728f416f4c1c98173aa146efbabbe51d2bce9ebfe32b152
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_b650e1.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41409993
  saved_at: '2025-12-12T08:43:42.361715+00:00'
  step: 12
- hash: sha256:70c57036b92dc6d796c00e2870c6ab6cf8fbd630f759afc335fa17fcf62f880a
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_70c570.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41409993
  saved_at: '2025-12-12T08:43:42.404943+00:00'
  step: 12
predictions: []
