schema_version: '2.0'
uid: e98b2023-e457-49d5-86b8-fbfb867c13f1
pipeline_id: 0172_PLS_PP_SELECTION_NO_SAVE_78051a
name: PLS_PP_SELECTION_NO_SAVE_78051a
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:33:33.242176+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: null
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - nirs4all.operators.transforms.scalers.StandardNormalVariate
    - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
    - null
    - null
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: null
- _cartesian_:
  - nirs4all.operators.transforms.scalers.StandardNormalVariate
  - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
  - null
  - null
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0172_PLS_PP_SELECTION_NO_SAVE_78051a$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0172_PLS_PP_SELECTION_NO_SAVE_78051a
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:33:33.266271+00:00'
    params: {}
    version: 3
  - artifact_id: 0172_PLS_PP_SELECTION_NO_SAVE_78051a$6e21be876a4d:all
    content_hash: sha256:f1b0d49d100fdce0b1f766631a2fc34c1b2477ed43ee4a120b8aedc3581c1d26
    path: transformer_StandardNormalVariate_f1b0d49d100f.joblib
    chain_path: s5.StandardNormalVariate[src=0,sub=0]
    source_index: 0
    pipeline_id: 0172_PLS_PP_SELECTION_NO_SAVE_78051a
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: StandardNormalVariate
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 132
    created_at: '2026-01-08T17:33:33.281637+00:00'
    params: {}
    version: 3
  - artifact_id: 0172_PLS_PP_SELECTION_NO_SAVE_78051a$43cfdb4b8dc0:all
    content_hash: sha256:691364ebf5c9cf5f03e16c3b48e170cf0041f7b9fd02c8c40dcdafece2312e1d
    path: transformer_ExtendedMultiplicativeScatterCorrection_691364ebf5c9.joblib
    chain_path: s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=1]
    source_index: 0
    pipeline_id: 0172_PLS_PP_SELECTION_NO_SAVE_78051a
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: ExtendedMultiplicativeScatterCorrection
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 5683
    created_at: '2026-01-08T17:33:33.287917+00:00'
    params: {}
    version: 3
  - artifact_id: 0172_PLS_PP_SELECTION_NO_SAVE_78051a$9f79d59455ab:0
    content_hash: sha256:c4f52d0cddffbfb4fac9464fc31a8aec34cbca0c3c79f795ef3392d499008232
    path: model_PLSRegression_c4f52d0cddff.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0172_PLS_PP_SELECTION_NO_SAVE_78051a
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 118966
    created_at: '2026-01-08T17:33:33.999268+00:00'
    params: {}
    version: 3
  - artifact_id: 0172_PLS_PP_SELECTION_NO_SAVE_78051a$9f79d59455ab:1
    content_hash: sha256:0af195bb0d23a8d350d6cc9fae4c9b5653302dbd5fde74784fc9bbc8d9d6ebb7
    path: model_PLSRegression_0af195bb0d23.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0172_PLS_PP_SELECTION_NO_SAVE_78051a
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 119285
    created_at: '2026-01-08T17:33:34.003076+00:00'
    params: {}
    version: 3
  - artifact_id: 0172_PLS_PP_SELECTION_NO_SAVE_78051a$9f79d59455ab:2
    content_hash: sha256:44fe2f9c9cb342ece4656c1d8ac33dc4206199ff935a5e35b65c6ee51b8c1dea
    path: model_PLSRegression_44fe2f9c9cb3.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0172_PLS_PP_SELECTION_NO_SAVE_78051a
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 119334
    created_at: '2026-01-08T17:33:34.005819+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  322ba2b0-8d6:
    trace_id: 322ba2b0-8d6
    pipeline_uid: 0172_PLS_PP_SELECTION_NO_SAVE_78051a
    created_at: '2026-01-08T17:33:33.243114+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 1.949310302734375
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 1.650094985961914
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0172_PLS_PP_SELECTION_NO_SAVE_78051a$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0172_PLS_PP_SELECTION_NO_SAVE_78051a$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0172_PLS_PP_SELECTION_NO_SAVE_78051a$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 22.626638412475586
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 8.612632751464844
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: StandardNormalVariate, ExtendedMultiplicativeScatterCorrection,
        None (+1)
      operator_config:
        feature_augmentation:
        - nirs4all.operators.transforms.scalers.StandardNormalVariate
        - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
        - null
        - null
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0172_PLS_PP_SELECTION_NO_SAVE_78051a$6e21be876a4d:all
        - 0172_PLS_PP_SELECTION_NO_SAVE_78051a$43cfdb4b8dc0:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0172_PLS_PP_SELECTION_NO_SAVE_78051a$6e21be876a4d:all
            - 0172_PLS_PP_SELECTION_NO_SAVE_78051a$43cfdb4b8dc0:all
        by_source:
          0:
          - 0172_PLS_PP_SELECTION_NO_SAVE_78051a$6e21be876a4d:all
          - 0172_PLS_PP_SELECTION_NO_SAVE_78051a$43cfdb4b8dc0:all
        by_chain:
          s5.StandardNormalVariate[src=0,sub=0]: 0172_PLS_PP_SELECTION_NO_SAVE_78051a$6e21be876a4d:all
          s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=1]: 0172_PLS_PP_SELECTION_NO_SAVE_78051a$43cfdb4b8dc0:all
        metadata:
          class_name: ExtendedMultiplicativeScatterCorrection
          name: ExtendedMultiplicativeScatterCorrection_2
      branch_path: []
      branch_name: ''
      duration_ms: 19.318342208862305
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.StandardNormalVariate[src=0,sub=0]
      - s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 1728
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 3
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0172_PLS_PP_SELECTION_NO_SAVE_78051a$9f79d59455ab:0
        - 0172_PLS_PP_SELECTION_NO_SAVE_78051a$9f79d59455ab:1
        - 0172_PLS_PP_SELECTION_NO_SAVE_78051a$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0172_PLS_PP_SELECTION_NO_SAVE_78051a$9f79d59455ab:0
          1: 0172_PLS_PP_SELECTION_NO_SAVE_78051a$9f79d59455ab:1
          2: 0172_PLS_PP_SELECTION_NO_SAVE_78051a$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0172_PLS_PP_SELECTION_NO_SAVE_78051a$9f79d59455ab:0
            - 0172_PLS_PP_SELECTION_NO_SAVE_78051a$9f79d59455ab:1
            - 0172_PLS_PP_SELECTION_NO_SAVE_78051a$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0172_PLS_PP_SELECTION_NO_SAVE_78051a$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 733.6735725402832
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 1728
      output_shape:
      - 60
      - 1728
      input_features_shape:
      - - 60
        - 3
        - 576
      output_features_shape:
      - - 60
        - 3
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: raw|SNV|ExtendedMSC
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_78051a
      n_steps: 6
      n_artifacts: 6
