uid: 0cd19c68-717f-44fe-a4d1-c7a06f36a416
pipeline_id: 0002_SOTA_c52e86
name: SOTA_c52e86
dataset: wood_n_402_olale
created_at: '2025-12-12T08:23:55.167483+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:c420e3c9c457cb869a0040d36665a950c74a835cc5d0f10428fe7653df5fd30e
  name: ASLSBaseline_1
  path: ASLSBaseline_c420e3.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2025-12-12T08:23:56.252846+00:00'
  step: 1
- hash: sha256:99a8725f265b768e4aceabdc9b0df053a226e7aa01b56a99f60bde6ffc713ed3
  name: y_StandardScaler
  path: StandardScaler_99a872.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 444
  saved_at: '2025-12-12T08:23:56.464348+00:00'
  step: 4
- hash: sha256:5c7b91a3b0f7550a5bfec04484480180900040ea334f2e7c596d584d2e04e109
  name: StandardScaler_1
  path: StandardScaler_5c7b91.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 22554
  saved_at: '2025-12-12T08:23:56.609710+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T08:23:56.620750+00:00'
  step: 6
- hash: sha256:5553a5e6492689bb6bb16c2c698b28f8c32fbbe33fe75207bfd1381ed6b7b5d2
  name: PCA_1
  path: PCA_5553a5.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 57825
  saved_at: '2025-12-12T08:23:56.649926+00:00'
  step: 7
- hash: sha256:91f0e8363b0bb23d78c8de11263893739ce6a12c7a47a5149639785e2484599f
  name: StandardScaler_1
  path: StandardScaler_91f0e8.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 690
  saved_at: '2025-12-12T08:23:56.678309+00:00'
  step: 8
- hash: sha256:f77e20d7f94955f5b1424ad147de142b39fabc806b8028933399929606754e97
  name: PowerTransformer_1
  path: PowerTransformer_f77e20.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 965
  saved_at: '2025-12-12T08:23:56.731955+00:00'
  step: 9
- hash: sha256:876a8a29ae8618e2a404769dc2a89b390bce9e9582afaaf1badd51e8d293634e
  name: AutoGluon_1.pkl
  path: TabularPredictor_876a8a.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 14873
  saved_at: '2025-12-12T08:24:09.144710+00:00'
  step: 10
- hash: sha256:aa724531436f6257943b69b9ba5dcdc8ab7fa860795c3ee5f8ad2126a1d62a44
  name: AutoGluon_2.pkl
  path: TabularPredictor_aa7245.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 14864
  saved_at: '2025-12-12T08:24:09.145037+00:00'
  step: 10
- hash: sha256:4ad250161ba928a5108e2f5741bdb3550a4585e2a38f951e9c305a3e7177dd0c
  name: AutoGluon_3.pkl
  path: TabularPredictor_4ad250.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 14864
  saved_at: '2025-12-12T08:24:09.145322+00:00'
  step: 10
- hash: sha256:8dccfca74fe13ae4aeaf2f9098710bd5c3cc3f0f3f269f7b387754774b58710b
  name: TabPFN_1.pkl
  path: TabPFNRegressor_8dccfc.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41414454
  saved_at: '2025-12-12T08:24:24.671408+00:00'
  step: 11
- hash: sha256:18bd8829ed2489585cb84b61e13b25380d4bf854880e8fc78119543aac5259e0
  name: TabPFN_2.pkl
  path: TabPFNRegressor_18bd88.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41414454
  saved_at: '2025-12-12T08:24:24.732103+00:00'
  step: 11
- hash: sha256:9e8017cec999b19cb8fc96726b63a11f36dc5c744ad0d7aeece9cc85fa70d77e
  name: TabPFN_3.pkl
  path: TabPFNRegressor_9e8017.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41414454
  saved_at: '2025-12-12T08:24:24.786029+00:00'
  step: 11
- hash: sha256:ee3bcb4c4d0e12efb191dd9d8e16b9ae99d10f7e26d758d6e54371f5bb47355e
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_ee3bcb.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41414491
  saved_at: '2025-12-12T08:24:54.400110+00:00'
  step: 12
- hash: sha256:d219fc78146b6524716442d8cae23828429896ba1c3a71cb33d35c2a153f72f8
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_d219fc.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41414491
  saved_at: '2025-12-12T08:24:54.459967+00:00'
  step: 12
- hash: sha256:1eca227342d100f128be95f45a953d254031be838bdd6682b3519e41fe3a9d0c
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_1eca22.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41414491
  saved_at: '2025-12-12T08:24:54.512716+00:00'
  step: 12
predictions: []
