uid: 6b2d698f-ef51-4426-a0fe-85cea5d9fcdc
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: rice_ec
created_at: '2025-12-12T10:12:07.588870+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:b4db648a2547c1dc21ee2878cc4522bcc8f758afcdc997e89b71292698331f0a
  name: ASLSBaseline_1
  path: ASLSBaseline_b4db64.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2025-12-12T10:12:08.030474+00:00'
  step: 1
- hash: sha256:a809112b9554b25f30a5029af416417b811dac8b62c10500e2102f081333ab3a
  name: y_StandardScaler
  path: StandardScaler_a80911.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 442
  saved_at: '2025-12-12T10:12:41.386230+00:00'
  step: 4
- hash: sha256:13c79034c8bfb259ab601117f69b7822795922c6d2ffa12d5934e21c3f9a00aa
  name: StandardScaler_1
  path: StandardScaler_13c790.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 6349
  saved_at: '2025-12-12T10:12:41.397863+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T10:12:41.433329+00:00'
  step: 6
- hash: sha256:d8dbce50ae38eb541257def3c1dbe3205be700f68df8f162466598f4f50584ff
  name: PCA_1
  path: PCA_d8dbce.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9458
  saved_at: '2025-12-12T10:12:41.503220+00:00'
  step: 7
- hash: sha256:8403912546d7b1c498a36d3af3ed5c8a1f4c0b00713a6572a98881b593e68064
  name: StandardScaler_1
  path: StandardScaler_840391.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 597
  saved_at: '2025-12-12T10:12:41.554121+00:00'
  step: 8
- hash: sha256:3dfcade58de4f3d04236a3c25b3392b546e9aa9510b7ed4f4ccf2d583aba9921
  name: PowerTransformer_1
  path: PowerTransformer_3dfcad.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 786
  saved_at: '2025-12-12T10:12:41.621598+00:00'
  step: 9
- hash: sha256:5d019d9461231256ba3c1f62734eec3118b1168c3f73724ff6ab99b0429cd73d
  name: AutoGluon_1.pkl
  path: TabularPredictor_5d019d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12764
  saved_at: '2025-12-12T10:16:40.742247+00:00'
  step: 10
- hash: sha256:e35ac404916bf16ba3a9f294de7be22e5ddb1478e3d053d9c6d5df3bef1549c6
  name: AutoGluon_2.pkl
  path: TabularPredictor_e35ac4.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12764
  saved_at: '2025-12-12T10:16:40.742598+00:00'
  step: 10
- hash: sha256:d2b6e8ba6aa72d62d310d1c1d3212f94665db0fd138c17f6fc5cacf256214caa
  name: AutoGluon_3.pkl
  path: TabularPredictor_d2b6e8.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12764
  saved_at: '2025-12-12T10:16:40.742893+00:00'
  step: 10
- hash: sha256:dabc77966468e372a3a39b6974eb1f596ed4be373159d640c356e83d216e55e4
  name: TabPFN_1.pkl
  path: TabPFNRegressor_dabc77.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44273536
  saved_at: '2025-12-12T10:19:27.342543+00:00'
  step: 11
- hash: sha256:1b3d9087d2b3a0137c094ce20d68f26ea9391b74adc971aed23f314f425f5b07
  name: TabPFN_2.pkl
  path: TabPFNRegressor_1b3d90.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44275390
  saved_at: '2025-12-12T10:19:27.394976+00:00'
  step: 11
- hash: sha256:e29a3ee4b64e561fd4c705a161363c0a53df67ed9abefe7a528c587b59daa386
  name: TabPFN_3.pkl
  path: TabPFNRegressor_e29a3e.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44275394
  saved_at: '2025-12-12T10:19:27.447347+00:00'
  step: 11
- hash: sha256:00346ad80d282718b2e6254b748d9209dbc14733214042a62d32dc1857ca981c
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_00346a.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44273573
  saved_at: '2025-12-12T10:25:47.380647+00:00'
  step: 12
- hash: sha256:c293181113867a19afd8928ee5039585d1d82dbed12b7c9f18f20982bc723d9c
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_c29318.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44275427
  saved_at: '2025-12-12T10:25:47.431496+00:00'
  step: 12
- hash: sha256:ed59ff53b8b9a230dc3f253525bd9e4afddbb8045bbd5e5943bdd9acc72270ad
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_ed59ff.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44275431
  saved_at: '2025-12-12T10:25:47.482559+00:00'
  step: 12
predictions: []
