uid: b39ad94c-378d-42b3-b382-f62be4b7a6f9
pipeline_id: 0007_SOTA_d0c7aa
name: SOTA_d0c7aa
dataset: beer_originalextract_60_ks
created_at: '2025-12-11T14:19:53.289863+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:b4553481208e6d47e63ea320aba96e6244c0562bb0ff417a85f9518d4d8b3223
  name: ASLSBaseline_1
  path: ASLSBaseline_b45534.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2025-12-11T14:19:54.227268+00:00'
  step: 1
- hash: sha256:0b527dc6afe5fe4852109a07aa65b60ae57907dad06d920e9eccc3f4c44fb5d3
  name: y_StandardScaler
  path: StandardScaler_0b527d.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 438
  saved_at: '2025-12-11T14:19:54.251754+00:00'
  step: 4
- hash: sha256:a48c44c96eb6e87f190840766e4149504ee78eb8127eb9828168c8ca86ff894e
  name: StandardScaler_1
  path: StandardScaler_a48c44.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 12079
  saved_at: '2025-12-11T14:19:54.256758+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-11T14:19:54.262583+00:00'
  step: 6
- hash: sha256:bb5b26cec46f5da49aee6a23229eaf3d1e9805d3f4eff8e66f3cdf212bf08a31
  name: PCA_1
  path: PCA_bb5b26.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 75545
  saved_at: '2025-12-11T14:19:54.289783+00:00'
  step: 7
- hash: sha256:4f40eaff61acb828290589be013dcc6a2f73be6e803827ede6285f625e3d81cd
  name: StandardScaler_1
  path: StandardScaler_4f40ea.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 974
  saved_at: '2025-12-11T14:19:54.336961+00:00'
  step: 8
- hash: sha256:30bb9d168e6959636b7b3a06624c05e4276032ee4e96b1d70294bf3aaaa6a819
  name: PowerTransformer_1
  path: PowerTransformer_30bb9d.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1443
  saved_at: '2025-12-11T14:19:54.378690+00:00'
  step: 9
- hash: sha256:d5ea4e125f35e9ac7f05ec03115b0c6acb073480d2b02ae3823ad6186a666409
  name: AutoGluon_1.pkl
  path: TabularPredictor_d5ea4e.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 21975
  saved_at: '2025-12-11T14:20:54.369575+00:00'
  step: 10
- hash: sha256:34aed832118583a2ef4863d83d1a012dbc5e5a29409a5643c4759849cf14a89a
  name: AutoGluon_2.pkl
  path: TabularPredictor_34aed8.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 21975
  saved_at: '2025-12-11T14:20:54.369880+00:00'
  step: 10
- hash: sha256:dd0fee543938cbb169c49c5206414da4800228759bdbe7b5058cb4fe07206311
  name: AutoGluon_3.pkl
  path: TabularPredictor_dd0fee.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 21965
  saved_at: '2025-12-11T14:20:54.370151+00:00'
  step: 10
- hash: sha256:d0f8bf0920de823abc6c2d26fd18fb848c96bbc2586f7efc7ed7ff365411a1f0
  name: TabPFN_1.pkl
  path: TabPFNRegressor_d0f8bf.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41163120
  saved_at: '2025-12-11T14:21:05.859222+00:00'
  step: 11
- hash: sha256:c94ffb26bca0d38de516d60ad7ae461e6e24dcebd17af972b5872430499f92a3
  name: TabPFN_2.pkl
  path: TabPFNRegressor_c94ffb.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41170034
  saved_at: '2025-12-11T14:21:05.910265+00:00'
  step: 11
- hash: sha256:3884cb8631179d554ee62c8dd2c6ca3e284588ec7654177fe28677df26698c02
  name: TabPFN_3.pkl
  path: TabPFNRegressor_3884cb.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41170032
  saved_at: '2025-12-11T14:21:05.960840+00:00'
  step: 11
- hash: sha256:f1ae17bddeb31d3e8ee8de64c5fbf1ef024b618aa6b246649247894c66546e77
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_f1ae17.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41163161
  saved_at: '2025-12-11T14:21:25.251188+00:00'
  step: 12
- hash: sha256:929b6769813a7b81b7e78f077859862cd7bb6ae16dbfe42bd54cf0c0572da788
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_929b67.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41170077
  saved_at: '2025-12-11T14:21:25.301901+00:00'
  step: 12
- hash: sha256:8fd78b0b3f5d67d32cec571f2f31431d5f4dee3eee1cd2857aa9cda086a310b1
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_8fd78b.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41170099
  saved_at: '2025-12-11T14:21:25.352794+00:00'
  step: 12
predictions: []
