schema_version: '2.0'
uid: ea4f67f5-dd15-45d8-b23f-9f6e2cb0f6c7
pipeline_id: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2
name: PLS_PP_SELECTION_NO_SAVE_a643b2
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:47:51.900740+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: null
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - nirs4all.operators.transforms.signal.Detrend
    - null
    - null
    - nirs4all.operators.transforms.nirs.Haar
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      error_score: .nan
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: null
- _cartesian_:
  - nirs4all.operators.transforms.signal.Detrend
  - null
  - null
  - nirs4all.operators.transforms.nirs.Haar
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:47:51.933579+00:00'
    params: {}
    version: 3
  - artifact_id: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$51eb708c8a1f:all
    content_hash: sha256:11ce246bc67c631c59d4827a162f06b45fa0f87770f7d8325a0c50c7f6d72fcf
    path: transformer_Detrend_11ce246bc67c.joblib
    chain_path: s5.Detrend[src=0,sub=0]
    source_index: 0
    pipeline_id: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: Detrend
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 90
    created_at: '2026-01-08T17:47:51.952458+00:00'
    params: {}
    version: 3
  - artifact_id: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$f0e3446be7bb:all
    content_hash: sha256:2237293e62d5640680cb91d003382cdd194cbcc1496aee2fd76192fa547a78be
    path: transformer_Haar_2237293e62d5.joblib
    chain_path: s5.Haar[src=0,sub=1]
    source_index: 0
    pipeline_id: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: Haar
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 112
    created_at: '2026-01-08T17:47:51.964375+00:00'
    params: {}
    version: 3
  - artifact_id: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$9f79d59455ab:0
    content_hash: sha256:dbeabaa570c0e69ecf0f5166d4d4b86f0c40b39a3492c5a874cc939b70088746
    path: model_PLSRegression_dbeabaa570c0.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 118202
    created_at: '2026-01-08T17:47:52.543980+00:00'
    params: {}
    version: 3
  - artifact_id: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$9f79d59455ab:1
    content_hash: sha256:e8642380b80a6a3d4e1cf29ffc7623e5fffa35d35e6cd1a21858170c8412dd4a
    path: model_PLSRegression_e8642380b80a.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 118487
    created_at: '2026-01-08T17:47:52.548423+00:00'
    params: {}
    version: 3
  - artifact_id: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$9f79d59455ab:2
    content_hash: sha256:51202364492955c90eb2dde96b71a2028034795bff8486aa6e9f523efaf037ee
    path: model_PLSRegression_512023644929.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 118463
    created_at: '2026-01-08T17:47:52.551311+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  8485b32c-4af:
    trace_id: 8485b32c-4af
    pipeline_uid: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2
    created_at: '2026-01-08T17:47:51.902373+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 2.4535655975341797
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 1.9946098327636719
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 31.11433982849121
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 8.44264030456543
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: Detrend, None, None (+1)
      operator_config:
        feature_augmentation:
        - nirs4all.operators.transforms.signal.Detrend
        - null
        - null
        - nirs4all.operators.transforms.nirs.Haar
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$51eb708c8a1f:all
        - 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$f0e3446be7bb:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$51eb708c8a1f:all
            - 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$f0e3446be7bb:all
        by_source:
          0:
          - 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$51eb708c8a1f:all
          - 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$f0e3446be7bb:all
        by_chain:
          s5.Detrend[src=0,sub=0]: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$51eb708c8a1f:all
          s5.Haar[src=0,sub=1]: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$f0e3446be7bb:all
        metadata:
          class_name: Haar
          name: Haar_2
      branch_path: []
      branch_name: ''
      duration_ms: 44.10743713378906
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.Detrend[src=0,sub=0]
      - s5.Haar[src=0,sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 1728
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 3
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          error_score: .nan
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$9f79d59455ab:0
        - 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$9f79d59455ab:1
        - 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$9f79d59455ab:0
          1: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$9f79d59455ab:1
          2: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$9f79d59455ab:0
            - 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$9f79d59455ab:1
            - 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0377_PLS_PP_SELECTION_NO_SAVE_a643b2$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 586.9870185852051
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 1728
      output_shape:
      - 60
      - 1728
      input_features_shape:
      - - 60
        - 3
        - 576
      output_features_shape:
      - - 60
        - 3
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: raw|Detr|Haar
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_a643b2
      n_steps: 6
      n_artifacts: 6
