uid: 8ef49909-1d17-443d-a457-dbbc5c10794e
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: wood_sustainability_511_davrieux_rmse0_092
created_at: '2026-01-07T09:25:47.962108+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:e3981c22fe01bf6ba48b414ed19291553d7fa375224b447ff7d90a870e91f7c3
  name: ASLSBaseline_1
  path: ASLSBaseline_e3981c.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2026-01-07T09:25:48.140530+00:00'
  step: 1
- hash: sha256:56c22151f50c1824acd90b602da5be84e49ab353c7d1b52720d0360d18506f4b
  name: PCA_1
  path: PCA_56c221.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 40103
  saved_at: '2026-01-07T09:25:48.391456+00:00'
  step: 4
- hash: sha256:4153030dfe07874e03cbc8d53438a561c16ce22efc40b4e7e4c1672d8c9a28de
  name: AutoGluon_1.pkl
  path: TabularPredictor_415303.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 13086
  saved_at: '2026-01-07T09:26:03.628675+00:00'
  step: 5
- hash: sha256:44cb30b950a7286c084f3f2a56be4325880c0b211536301b27eeba4f49013a83
  name: AutoGluon_2.pkl
  path: TabularPredictor_44cb30.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 13077
  saved_at: '2026-01-07T09:26:03.629061+00:00'
  step: 5
- hash: sha256:460f8a98a80806d9f668835c9f1841bd37213fa0b9faf67423fc9efb72e62b9e
  name: AutoGluon_3.pkl
  path: TabularPredictor_460f8a.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 13095
  saved_at: '2026-01-07T09:26:03.629377+00:00'
  step: 5
- hash: sha256:4bd8aa2233b062e8be28df0958923b79db9c4bc0d6b9810fffa4d8f7927765b3
  name: TabPFN_1.pkl
  path: TabPFNRegressor_4bd8aa.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41455074
  saved_at: '2026-01-07T09:26:18.697465+00:00'
  step: 6
- hash: sha256:6ffc3be2fd75dd865cfdf720c69f93c11fd178d5f0b84cda867fad05f67a5afc
  name: TabPFN_2.pkl
  path: TabPFNRegressor_6ffc3b.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41455080
  saved_at: '2026-01-07T09:26:18.758303+00:00'
  step: 6
- hash: sha256:91c9fed4cede0d98e2841626f1523eab26d07327065e2493d3c2521f9107261e
  name: TabPFN_3.pkl
  path: TabPFNRegressor_91c9fe.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41455080
  saved_at: '2026-01-07T09:26:18.818707+00:00'
  step: 6
- hash: sha256:221b17b2790e4320add1c21e88d20894fe697a978f11208e76d70599ec17397d
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_221b17.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41455117
  saved_at: '2026-01-07T09:26:50.211542+00:00'
  step: 7
- hash: sha256:7d886f96e4cc94ee76c7f6870a6cbe4353f6fdada93a79674ad73171523693f4
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_7d886f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41455117
  saved_at: '2026-01-07T09:26:50.271862+00:00'
  step: 7
- hash: sha256:67cfcbf7db54832ef78eb51b99df402cc6d9777c66955066744009d3bfdbd8cb
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_67cfcb.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41455117
  saved_at: '2026-01-07T09:26:50.331992+00:00'
  step: 7
predictions: []
