schema_version: '2.0'
uid: 86b63eee-f9b8-43b1-bfa6-b153f808cdbb
pipeline_id: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d
name: PLS_PP_SELECTION_NO_SAVE_328c5d
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:32:49.905244+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: null
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - null
    - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
    - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
      params:
        window_length: 15
        deriv: 1
    - class: nirs4all.operators.transforms.nirs.Wavelet
      params:
        wavelet: coif3
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: null
- _cartesian_:
  - null
  - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
  - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
    params:
      window_length: 15
      deriv: 1
  - class: nirs4all.operators.transforms.nirs.Wavelet
    params:
      wavelet: coif3
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:32:49.934147+00:00'
    params: {}
    version: 3
  - artifact_id: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$33af94b1bf58:all
    content_hash: sha256:691364ebf5c9cf5f03e16c3b48e170cf0041f7b9fd02c8c40dcdafece2312e1d
    path: transformer_ExtendedMultiplicativeScatterCorrection_691364ebf5c9.joblib
    chain_path: s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=0]
    source_index: 0
    pipeline_id: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: ExtendedMultiplicativeScatterCorrection
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 5683
    created_at: '2026-01-08T17:32:49.955136+00:00'
    params: {}
    version: 3
  - artifact_id: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$eeb09d32a26b:all
    content_hash: sha256:d663934f32b4b5e8dba18585ed74e0c4e66ed1008ee606d100f374d3224f9c49
    path: transformer_SavitzkyGolay_d663934f32b4.joblib
    chain_path: s5.SavitzkyGolay[src=0,sub=1]
    source_index: 0
    pipeline_id: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: SavitzkyGolay
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 137
    created_at: '2026-01-08T17:32:49.959652+00:00'
    params: {}
    version: 3
  - artifact_id: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$509095d16b8c:all
    content_hash: sha256:f2c1d06f4298f812e17b88a6602355856be25df4ed5fa680286d202bd476cb07
    path: transformer_Wavelet_f2c1d06f4298.joblib
    chain_path: s5.Wavelet[src=0,sub=2]
    source_index: 0
    pipeline_id: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d
    branch_path: []
    step_index: 5
    substep_index: 2
    fold_id: null
    artifact_type: transformer
    class_name: Wavelet
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 114
    created_at: '2026-01-08T17:32:49.963765+00:00'
    params: {}
    version: 3
  - artifact_id: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$9f79d59455ab:0
    content_hash: sha256:aa47491adc445dc56614d08a543ca76a448a160ece00d67eb884a31bf4a8e421
    path: model_PLSRegression_aa47491adc44.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 158132
    created_at: '2026-01-08T17:32:50.855613+00:00'
    params: {}
    version: 3
  - artifact_id: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$9f79d59455ab:1
    content_hash: sha256:e50f48684a92d0577d62bdce307e843edbe989615b24bb4faf5da153e39f29b1
    path: model_PLSRegression_e50f48684a92.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 158421
    created_at: '2026-01-08T17:32:50.862080+00:00'
    params: {}
    version: 3
  - artifact_id: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$9f79d59455ab:2
    content_hash: sha256:0e9e3ad3810ce02eb41019df8960511dfc8051763052acaf91c6c45a7eb1dae7
    path: model_PLSRegression_0e9e3ad3810c.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 158397
    created_at: '2026-01-08T17:32:50.865579+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  d0c6861b-a4f:
    trace_id: d0c6861b-a4f
    pipeline_uid: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d
    created_at: '2026-01-08T17:32:49.906306+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 1.9054412841796875
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 1.9214153289794922
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 28.090715408325195
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 8.004426956176758
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: None, ExtendedMultiplicativeScatterCorrection, SavitzkyGolay
        (+1)
      operator_config:
        feature_augmentation:
        - null
        - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
        - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
          params:
            window_length: 15
            deriv: 1
        - class: nirs4all.operators.transforms.nirs.Wavelet
          params:
            wavelet: coif3
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$33af94b1bf58:all
        - 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$eeb09d32a26b:all
        - 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$509095d16b8c:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$33af94b1bf58:all
            - 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$eeb09d32a26b:all
            - 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$509095d16b8c:all
        by_source:
          0:
          - 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$33af94b1bf58:all
          - 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$eeb09d32a26b:all
          - 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$509095d16b8c:all
        by_chain:
          s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=0]: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$33af94b1bf58:all
          s5.SavitzkyGolay[src=0,sub=1]: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$eeb09d32a26b:all
          s5.Wavelet[src=0,sub=2]: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$509095d16b8c:all
        metadata:
          class_name: Wavelet
          name: Wavelet_3
      branch_path: []
      branch_name: ''
      duration_ms: 31.943798065185547
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=0]
      - s5.SavitzkyGolay[src=0,sub=1]
      - s5.Wavelet[src=0,sub=2]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 2304
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 4
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$9f79d59455ab:0
        - 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$9f79d59455ab:1
        - 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$9f79d59455ab:0
          1: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$9f79d59455ab:1
          2: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$9f79d59455ab:0
            - 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$9f79d59455ab:1
            - 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0121_PLS_PP_SELECTION_NO_SAVE_328c5d$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 922.5826263427734
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 2304
      output_shape:
      - 60
      - 2304
      input_features_shape:
      - - 60
        - 4
        - 576
      output_features_shape:
      - - 60
        - 4
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: raw|ExtendedMSC|SG|Wavelet
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_328c5d
      n_steps: 6
      n_artifacts: 7
