uid: 1fdf508b-5c70-4767-a3ce-f0c212e50aa2
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: cattle_manure_mgo_ks
created_at: '2026-01-07T09:12:32.370959+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:125d94dee500492a3bdb8dd8b9fa106b8b2b34e5f42944e4b15d55960ffb73d1
  name: ASLSBaseline_1
  path: ASLSBaseline_125d94.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2026-01-07T09:12:32.454500+00:00'
  step: 1
- hash: sha256:f3dbb1ab0948767bb8b88ae5f4acb9b37976f01b62b7152e644b9cd0bc31abc8
  name: PCA_1
  path: PCA_f3dbb1.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 19713
  saved_at: '2026-01-07T09:12:32.531928+00:00'
  step: 4
- hash: sha256:424ca38a1946c3096d1eb0acc065109d87d5a126bdd6b86cea1eade411ae1274
  name: AutoGluon_1.pkl
  path: TabularPredictor_424ca3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2026-01-07T09:12:43.359376+00:00'
  step: 5
- hash: sha256:741a3504dc8491271fd6136a0554f6df66355671b3db0fd7cd3e329b174d1c20
  name: AutoGluon_2.pkl
  path: TabularPredictor_741a35.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11262
  saved_at: '2026-01-07T09:12:43.359842+00:00'
  step: 5
- hash: sha256:a52c03b9769476f949499544026abef8e571413226858c9875a20fc141d04bfe
  name: AutoGluon_3.pkl
  path: TabularPredictor_a52c03.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11262
  saved_at: '2026-01-07T09:12:43.360272+00:00'
  step: 5
- hash: sha256:49d1506dbd7059ab3dc4b8ff9ed4d729800ce61c1452066f4f69a5c8bf64972e
  name: TabPFN_1.pkl
  path: TabPFNRegressor_49d150.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41082399
  saved_at: '2026-01-07T09:12:51.288234+00:00'
  step: 6
- hash: sha256:29123cf17f20fd94f52e0768067b4ddb6630d581cc76d40904c15b63ee61e62f
  name: TabPFN_2.pkl
  path: TabPFNRegressor_29123c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41083423
  saved_at: '2026-01-07T09:12:51.344403+00:00'
  step: 6
- hash: sha256:b96e20baec17325d6758bad8f695805ef7de6782c659f2c0078cb1230f4a519c
  name: TabPFN_3.pkl
  path: TabPFNRegressor_b96e20.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41083423
  saved_at: '2026-01-07T09:12:51.399885+00:00'
  step: 6
- hash: sha256:f255126c2e7c585a83b3ad062de66657a2175d717831791740682fef9a8000a0
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_f25512.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41082436
  saved_at: '2026-01-07T09:13:05.756690+00:00'
  step: 7
- hash: sha256:e7c6958f03a79623883d8f6b22343e0d08bcb2a778b0e7a0b17ed7b5f5439024
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_e7c695.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41083460
  saved_at: '2026-01-07T09:13:05.812676+00:00'
  step: 7
- hash: sha256:46b2d62704743ceb7ed20d821bcf2565afadbdcd780118e3b64805209f084325
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_46b2d6.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41083460
  saved_at: '2026-01-07T09:13:05.868683+00:00'
  step: 7
predictions: []
