uid: 9ec536d6-99ce-47a7-98f3-f523736aed5d
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: diesel_d_263_hla_b
created_at: '2025-12-12T12:59:30.401702+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T12:59:30.444934+00:00'
  step: 1
- hash: sha256:de2faec6a951a4d921b6e7ea872fc4a97713b4e2045004d255f9830c2b456141
  name: y_StandardScaler
  path: StandardScaler_de2fae.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 446
  saved_at: '2025-12-12T12:59:30.553950+00:00'
  step: 4
- hash: sha256:c69ea97c198c29becaad2b1820da0d6fb38e7e15a840ca1d602f98145f83c3ee
  name: StandardScaler_1
  path: StandardScaler_c69ea9.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9184
  saved_at: '2025-12-12T12:59:30.560586+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T12:59:30.572009+00:00'
  step: 6
- hash: sha256:f9b6bc8472a5bbc432a320eafdbe8e0af5e1c56f2847fe2ff962a6e5e9f87f69
  name: PCA_1
  path: PCA_f9b6bc.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9258
  saved_at: '2025-12-12T12:59:30.595384+00:00'
  step: 7
- hash: sha256:c20af31575e6173533c201b6e759f3c00947c4dd7acbcdcd8000d84f76d72e6c
  name: StandardScaler_1
  path: StandardScaler_c20af3.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 532
  saved_at: '2025-12-12T12:59:30.647137+00:00'
  step: 8
- hash: sha256:235adc4f253a8eda1989db8098d4d090b05f6ffa6b2109d1a5fd27151dcde6bf
  name: PowerTransformer_1
  path: PowerTransformer_235adc.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 692
  saved_at: '2025-12-12T12:59:30.680168+00:00'
  step: 9
- hash: sha256:2a3ff694a45cf39e3e18ddf691c8c27bad705cfdb13888e269307b9ad6cc9dfc
  name: AutoGluon_1.pkl
  path: TabularPredictor_2a3ff6.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11616
  saved_at: '2025-12-12T12:59:41.664262+00:00'
  step: 10
- hash: sha256:8ca53376764fb881092ea82914101c8b64c8815ab9c718832847d2217a603cc9
  name: AutoGluon_2.pkl
  path: TabularPredictor_8ca533.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11616
  saved_at: '2025-12-12T12:59:41.664544+00:00'
  step: 10
- hash: sha256:4c8dc4cefdec1a59e60eb831c45d64f3652093ab4126d30bdbe14ae57e3252d2
  name: AutoGluon_3.pkl
  path: TabularPredictor_4c8dc4.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11598
  saved_at: '2025-12-12T12:59:41.664795+00:00'
  step: 10
- hash: sha256:becfa7400d1230a242c7f0a1880efcf485be3591d5c7d6391f00cef153469339
  name: TabPFN_1.pkl
  path: TabPFNRegressor_becfa7.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41066176
  saved_at: '2025-12-12T12:59:51.297361+00:00'
  step: 11
- hash: sha256:7bcca82aa605af93443ff9b18145e2a7526171d89e36159dc9aacb01e3f48a89
  name: TabPFN_2.pkl
  path: TabPFNRegressor_7bcca8.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41067392
  saved_at: '2025-12-12T12:59:51.350475+00:00'
  step: 11
- hash: sha256:945a0324b6c7fe20a88c3590fd59a56e969ece954cf6019f14fcf3ba1f48ebbc
  name: TabPFN_3.pkl
  path: TabPFNRegressor_945a03.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41067392
  saved_at: '2025-12-12T12:59:51.403086+00:00'
  step: 11
- hash: sha256:df49452ce62c30962501562c5a6dd74964c3e2e81aeca2f5b545ddf6d6b9b053
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_df4945.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41066213
  saved_at: '2025-12-12T13:00:06.700975+00:00'
  step: 12
- hash: sha256:8ed6f3c767efbebe4c9159fb86a504311c7456936a3d343b6172298ee5a04fa8
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_8ed6f3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41067429
  saved_at: '2025-12-12T13:00:06.754467+00:00'
  step: 12
- hash: sha256:ac4e42d5e0352a13a9006de3a9830fa36c2fba362d3247b514bccdeb082c314a
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_ac4e42.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41067429
  saved_at: '2025-12-12T13:00:06.807384+00:00'
  step: 12
predictions: []
