schema_version: '2.0'
uid: e452ab6b-9307-4000-8c71-5e4e0334e889
pipeline_id: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a
name: PLS_PP_SELECTION_NO_SAVE_e4a68a
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:46:03.870083+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: null
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - nirs4all.operators.transforms.scalers.StandardNormalVariate
    - null
    - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
      params:
        window_length: 15
        deriv: 2
    - nirs4all.operators.transforms.nirs.AreaNormalization
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      error_score: .nan
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: null
- _cartesian_:
  - nirs4all.operators.transforms.scalers.StandardNormalVariate
  - null
  - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
    params:
      window_length: 15
      deriv: 2
  - nirs4all.operators.transforms.nirs.AreaNormalization
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:46:03.887943+00:00'
    params: {}
    version: 3
  - artifact_id: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$6e21be876a4d:all
    content_hash: sha256:f1b0d49d100fdce0b1f766631a2fc34c1b2477ed43ee4a120b8aedc3581c1d26
    path: transformer_StandardNormalVariate_f1b0d49d100f.joblib
    chain_path: s5.StandardNormalVariate[src=0,sub=0]
    source_index: 0
    pipeline_id: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: StandardNormalVariate
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 132
    created_at: '2026-01-08T17:46:03.898022+00:00'
    params: {}
    version: 3
  - artifact_id: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$eeb09d32a26b:all
    content_hash: sha256:5c353b1441d52f528075c64bd2477db6d0df3f619817bfa27a68d32928e99953
    path: transformer_SavitzkyGolay_5c353b1441d5.joblib
    chain_path: s5.SavitzkyGolay[src=0,sub=1]
    source_index: 0
    pipeline_id: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: SavitzkyGolay
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 137
    created_at: '2026-01-08T17:46:03.899560+00:00'
    params: {}
    version: 3
  - artifact_id: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$ac71c0f61352:all
    content_hash: sha256:3381c200ece0f7e7ac9f3c9a70feb2bc950b0271d9a3c4d8bfc727bd6a3bfbb5
    path: transformer_AreaNormalization_3381c200ece0.joblib
    chain_path: s5.AreaNormalization[src=0,sub=2]
    source_index: 0
    pipeline_id: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a
    branch_path: []
    step_index: 5
    substep_index: 2
    fold_id: null
    artifact_type: transformer
    class_name: AreaNormalization
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 103
    created_at: '2026-01-08T17:46:03.900815+00:00'
    params: {}
    version: 3
  - artifact_id: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$9f79d59455ab:0
    content_hash: sha256:ac566a7529d9f0f7763d70bab6808724f9007f591cf25bd1fee9243f52cc49da
    path: model_PLSRegression_ac566a7529d9.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 156954
    created_at: '2026-01-08T17:46:04.567912+00:00'
    params: {}
    version: 3
  - artifact_id: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$9f79d59455ab:1
    content_hash: sha256:750f7a884b62ab680b4193a5ec0456b98907f6b1d3725a15b7c8273527660e40
    path: model_PLSRegression_750f7a884b62.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 157337
    created_at: '2026-01-08T17:46:04.571380+00:00'
    params: {}
    version: 3
  - artifact_id: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$9f79d59455ab:2
    content_hash: sha256:474449c356cf1b352f3abd04df01b31030b1a3955ff5646283823a94fa2b9972
    path: model_PLSRegression_474449c356cf.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 157321
    created_at: '2026-01-08T17:46:04.574769+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  1028bc36-af1:
    trace_id: 1028bc36-af1
    pipeline_uid: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a
    created_at: '2026-01-08T17:46:03.871130+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 2.0346641540527344
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 1.4944076538085938
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 16.608476638793945
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 4.414796829223633
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: StandardNormalVariate, None, SavitzkyGolay (+1)
      operator_config:
        feature_augmentation:
        - nirs4all.operators.transforms.scalers.StandardNormalVariate
        - null
        - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
          params:
            window_length: 15
            deriv: 2
        - nirs4all.operators.transforms.nirs.AreaNormalization
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$6e21be876a4d:all
        - 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$eeb09d32a26b:all
        - 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$ac71c0f61352:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$6e21be876a4d:all
            - 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$eeb09d32a26b:all
            - 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$ac71c0f61352:all
        by_source:
          0:
          - 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$6e21be876a4d:all
          - 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$eeb09d32a26b:all
          - 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$ac71c0f61352:all
        by_chain:
          s5.StandardNormalVariate[src=0,sub=0]: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$6e21be876a4d:all
          s5.SavitzkyGolay[src=0,sub=1]: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$eeb09d32a26b:all
          s5.AreaNormalization[src=0,sub=2]: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$ac71c0f61352:all
        metadata:
          class_name: AreaNormalization
          name: AreaNormalization_3
      branch_path: []
      branch_name: ''
      duration_ms: 10.08915901184082
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.StandardNormalVariate[src=0,sub=0]
      - s5.SavitzkyGolay[src=0,sub=1]
      - s5.AreaNormalization[src=0,sub=2]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 2304
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 4
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          error_score: .nan
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$9f79d59455ab:0
        - 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$9f79d59455ab:1
        - 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$9f79d59455ab:0
          1: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$9f79d59455ab:1
          2: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$9f79d59455ab:0
            - 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$9f79d59455ab:1
            - 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0269_PLS_PP_SELECTION_NO_SAVE_e4a68a$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 695.0700283050537
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 2304
      output_shape:
      - 60
      - 2304
      input_features_shape:
      - - 60
        - 4
        - 576
      output_features_shape:
      - - 60
        - 4
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: raw|SNV|SG|AreaNormalization
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_e4a68a
      n_steps: 6
      n_artifacts: 7
