uid: a7276c30-1852-425d-bdad-6d8201779e59
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: sorghom_digest
created_at: '2025-12-12T07:31:40.110255+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:5fb86667892bba4894bd89751a7de3818e857670f4b382a951e8007787318d91
  name: ASLSBaseline_1
  path: ASLSBaseline_5fb866.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T07:31:40.626806+00:00'
  step: 1
- hash: sha256:db3b658cd0f3254c2196fe6f8fbab9769a6d1a26db850c4bf02957276d73d659
  name: y_StandardScaler
  path: StandardScaler_db3b65.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 442
  saved_at: '2025-12-12T07:31:48.299127+00:00'
  step: 4
- hash: sha256:dd74308cd73d5c80ede1af0460c23d0cfe8a61bc833d0a3d06da902789e0670d
  name: StandardScaler_1
  path: StandardScaler_dd7430.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 20831
  saved_at: '2025-12-12T07:31:48.321278+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T07:31:48.368909+00:00'
  step: 6
- hash: sha256:86319218ee63fac78461cf8996dfdc85dfe21c99ed9641823995750403a7a979
  name: PCA_1
  path: PCA_863192.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 64330
  saved_at: '2025-12-12T07:31:48.539424+00:00'
  step: 7
- hash: sha256:37d528937ea3ddf56a6611f4a3f0d84d3979c6d03f4e65fcb499ea0034d896fd
  name: StandardScaler_1
  path: StandardScaler_37d528.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 775
  saved_at: '2025-12-12T07:31:48.619803+00:00'
  step: 8
- hash: sha256:0d17926760f4fc949c5beba36191739090a7748dcd7184556f7df4ed500bfa96
  name: PowerTransformer_1
  path: PowerTransformer_0d1792.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1047
  saved_at: '2025-12-12T07:31:48.675985+00:00'
  step: 9
- hash: sha256:dfdbf377f0d107d7265455827749764dd6f8ac06ed95f57b6abbdbe4c8cbab1e
  name: AutoGluon_1.pkl
  path: TabularPredictor_dfdbf3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 15955
  saved_at: '2025-12-12T07:34:39.685028+00:00'
  step: 10
- hash: sha256:991ce37bca551188c165d07da2e9fa02a5affb3acfb8e089575a72e6f4741d2f
  name: AutoGluon_2.pkl
  path: TabularPredictor_991ce3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 15955
  saved_at: '2025-12-12T07:34:39.685795+00:00'
  step: 10
- hash: sha256:7d0efcd75f41ca184b534379a56b0bac69736d8bf045d68099e2b43c944da842
  name: AutoGluon_3.pkl
  path: TabularPredictor_7d0efc.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 15964
  saved_at: '2025-12-12T07:34:39.686160+00:00'
  step: 10
- hash: sha256:9b3bb17894c668d3f3ca3338310a549220c10f246a3927d8ad4f995520439b0a
  name: TabPFN_1.pkl
  path: TabPFNRegressor_9b3bb1.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44798115
  saved_at: '2025-12-12T07:36:56.166094+00:00'
  step: 11
- hash: sha256:ec65edfece4b25addf0d23b5bf1c5a0ed350bacc83c4f85ee9ce25dc7250ba59
  name: TabPFN_2.pkl
  path: TabPFNRegressor_ec65ed.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44801841
  saved_at: '2025-12-12T07:36:56.228888+00:00'
  step: 11
- hash: sha256:581b46ee68f67493b75b2d361cf28fdc3464da682d47549760256ead98f42b73
  name: TabPFN_3.pkl
  path: TabPFNRegressor_581b46.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44801843
  saved_at: '2025-12-12T07:36:56.291220+00:00'
  step: 11
- hash: sha256:46c771feebaff9ed78788a4f92c9fbfbc897dca188b0ca866b8bfc0ad559cf26
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_46c771.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44798156
  saved_at: '2025-12-12T07:42:02.107192+00:00'
  step: 12
- hash: sha256:8f1730b6dbe28c5bf6b781f1a4afb945e86a4896456863f1aa15c078ba01e9e8
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_8f1730.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44801876
  saved_at: '2025-12-12T07:42:02.156323+00:00'
  step: 12
- hash: sha256:4b17586c0ad18033be3bc7051ab03e61118abe7f2882433e6a0774813103871f
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_4b1758.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44801880
  saved_at: '2025-12-12T07:42:02.204967+00:00'
  step: 12
predictions: []
