#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Adaptive diverse selection via graph pruning:
- Build per-(model, preprocessing) performance profiles across datasets (normalized RRMSE).
- Test pairwise profile correlation with a one-sided Spearman permutation test (H1: rho > 0).
  Apply BH-FDR across all tested pairs to identify significant positive-correlation edges.
- Iterate candidates in order of increasing median normalized RRMSE (best first).
  For each candidate j and the current kept set S:
    * Identify neighbors k in S that are significantly (FDR) positively correlated with j.
    * For those k, run an exact one-sided sign test on Δ = R_j - R_k with H1: median(Δ) > 0
      (candidate strictly worse). Apply BH-FDR within the comparisons of the same j.
    * If any k yields a significant result after FDR (i.e., j is worse than at least one correlated k),
      prune j; otherwise keep j.

Outputs:
- A CSV report with keep/prune decision and the statistical reasons.
- Correlation matrices (rho and adjusted p-values) for traceability.

Author: Generated by ChatGPT (comments in English).
"""

from __future__ import annotations

import os
import re
import argparse
from typing import List, Tuple, Optional, Dict
import numpy as np
import pandas as pd

# ---------------- I/O and discovery defaults ----------------

DEFAULT_ROOT = "Results/assoc_pp_model"
FILENAME_PREFIX = "results_"
# Exclude result CSV filenames that contain any of these substrings
FILENAME_EXCLUDE_SUBSTR = ["NICON", "CNN", "Ridge", "LGBM", "PLS"]

MODEL_COL = "Model"
EXCLUDE_PREPS = {"PCA"}   # preprocessings to drop globally (optional)

# ---------------- Stats / selection hyperparameters ----------------

ALPHA = 0.05                     # target FDR level
N_PERM = 10000                   # permutations for Spearman one-sided test (H1: rho > 0)
RANDOM_SEED = 42                 # reproducibility
MIN_OVERLAP = 3                  # min datasets overlap to test correlation or performance
NORMALIZE_PER_DATASET = True     # normalize RRMSE per dataset by the best value (min)
REPORT_DIR = "Results/assoc_pp_model/All_datasets"
REPORT_PREFIX = "adaptive_diverse_selection"

# ---------------- Utilities ----------------

def discover_dataset_csvs(root: str) -> List[Tuple[str, str]]:
    """Find (dataset_name, csv_path) where csv file starts with FILENAME_PREFIX and ends with .csv,
    and does NOT contain any excluded substring.
    """
    pairs: List[Tuple[str, str]] = []
    if not os.path.isdir(root):
        print(f"[WARN] Root not found: {root}")
        return pairs
    for ds in sorted(os.listdir(root)):
        ds_dir = os.path.join(root, ds)
        if not os.path.isdir(ds_dir):
            continue
        cands = [f for f in os.listdir(ds_dir)
                 if f.startswith(FILENAME_PREFIX) and f.lower().endswith(".csv")]
        cands = [f for f in cands if not any(excl in f for excl in FILENAME_EXCLUDE_SUBSTR)]
        if not cands:
            continue
        cands.sort()
        pairs.append((ds, os.path.join(ds_dir, cands[0])))
    return pairs


def benjamini_hochberg(pvals: List[Optional[float]]) -> List[Optional[float]]:
    """BH-FDR adjustment. None values are preserved."""
    n = len(pvals)
    idx_p = [(i, p) for i, p in enumerate(pvals) if p is not None and np.isfinite(p)]
    m = len(idx_p)
    if m == 0:
        return [None] * n
    # sort ascending
    idx_p.sort(key=lambda t: t[1])
    qs_sorted = [min(1.0, p * m / (rank + 1)) for rank, (_, p) in enumerate(idx_p)]
    # enforce monotonicity (non-increasing when traversed reversed)
    for k in range(m - 2, -1, -1):
        qs_sorted[k] = min(qs_sorted[k], qs_sorted[k + 1])
    qvals = [None] * n
    for (pos, (i, _)) in enumerate(idx_p):
        qvals[i] = qs_sorted[pos]
    return qvals


def exact_sign_test_one_sided_greater(diffs: np.ndarray) -> Tuple[Optional[float], int, int]:
    """Exact one-sided sign test for H1: median(diffs) > 0.
    Removes ties (diff == 0). Returns (p_value, n_eff, n_pos).
    p-value = P[Binom(n_eff, 0.5) >= n_pos]
    """
    y = diffs[np.isfinite(diffs)]
    y = y[y != 0.0]
    n_eff = y.size
    if n_eff == 0:
        return None, 0, 0
    n_pos = int(np.sum(y > 0))
    # exact binomial tail
    from math import comb
    p = sum(comb(n_eff, k) * (0.5 ** n_eff) for k in range(n_pos, n_eff + 1))
    return float(p), n_eff, n_pos


def spearman_rho_one_sided_perm(x: np.ndarray, y: np.ndarray, n_perm: int, rng: np.random.Generator) -> Tuple[float, float, int]:
    """One-sided Spearman permutation test for H1: rho > 0.
    Returns (rho_obs, p_value, n_used).
    """
    mask = np.isfinite(x) & np.isfinite(y)
    x0, y0 = x[mask], y[mask]
    n_used = x0.size
    if n_used < MIN_OVERLAP:
        return np.nan, np.nan, n_used
    # Spearman (with ties handled by rank)
    from scipy.stats import spearmanr
    rho_obs, _ = spearmanr(x0, y0)
    if not np.isfinite(rho_obs):
        return np.nan, np.nan, n_used
    # Permutation tail (>= observed)
    cnt = 0
    for _ in range(n_perm):
        y_perm = rng.permutation(y0)
        rho_perm, _ = spearmanr(x0, y_perm)
        if np.isfinite(rho_perm) and rho_perm >= rho_obs:
            cnt += 1
    p = (cnt + 1.0) / (n_perm + 1.0)  # add-one smoothing
    return float(rho_obs), float(p), n_used


# ---------------- Data assembly ----------------

def load_long_table(csv_path: str) -> pd.DataFrame:
    """Load a result CSV where rows are models and columns are preprocessings.
    Returns a long df with columns: [model, prep, rrmse].
    """
    wide = pd.read_csv(csv_path)
    if MODEL_COL not in wide.columns:
        raise ValueError(f"Missing '{MODEL_COL}' in {csv_path}")
    long = wide.melt(id_vars=[MODEL_COL], var_name="prep", value_name="rrmse").rename(columns={MODEL_COL: "model"})
    long["rrmse"] = pd.to_numeric(long["rrmse"], errors="coerce")
    long = long.dropna(subset=["rrmse"])
    # Drop globally excluded preprocessings
    if EXCLUDE_PREPS:
        long = long[~long["prep"].isin(EXCLUDE_PREPS)]
    return long


def build_profiles(root: str) -> pd.DataFrame:
    """Construct a matrix with rows=(model, prep), columns=datasets, values=normalized RRMSE."""
    ds_csvs = discover_dataset_csvs(root)
    rows = []
    for ds, path in ds_csvs:
        try:
            df = load_long_table(path)
        except Exception as e:
            print(f"[WARN] Skipping {path}: {e}")
            continue
        # Normalization per dataset by best (min RRMSE)
        if NORMALIZE_PER_DATASET:
            best = df.groupby("prep")["rrmse"].transform("min")
            # We normalize across all (model, prep) in the dataset by the global min (not per-prep),
            # to reflect absolute difficulty. If you prefer per-dataset-global min:
            # best = df["rrmse"].transform(lambda x: x.min())
            # Here we choose global per-dataset min (not per-prep), typical for RRMSE normalization:
            best = df["rrmse"].min()
            df["rrmse_norm"] = df["rrmse"] / best if best > 0 else df["rrmse"]
            val_col = "rrmse_norm"
        else:
            val_col = "rrmse"
        # pivot to (model,prep) x dataset
        piv = df.pivot_table(index=["model", "prep"], columns=None, values=val_col, aggfunc="mean")
        piv.name = ds
        for (m, p), v in piv.items():
            rows.append({"model": m, "prep": p, "dataset": ds, "value": float(v)})

    tidy = pd.DataFrame(rows)
    if tidy.empty:
        return pd.DataFrame()
    profiles = tidy.pivot_table(index=["model", "prep"], columns="dataset", values="value", aggfunc="mean")
    return profiles


# ---------------- Pruning algorithm ----------------

def adaptive_pruning(profiles: pd.DataFrame,
                     alpha: float = ALPHA,
                     n_perm: int = N_PERM,
                     seed: int = RANDOM_SEED) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Perform adaptive pruning:
    - Compute one-sided Spearman permutation p-values for all pairs (i<j); BH-FDR across all.
    - Iterate candidates sorted by median profile (ascending). Keep j unless:
        exists k in kept such that:
          (i) corr_sig(j,k) True after FDR  AND
          (ii) sign-test (H1: median Δ > 0) significant after BH-FDR within j.
    Returns:
      decisions_df: per (model,prep) keep/prune + reasons,
      rho_df: Spearman rho matrix,
      q_df: BH-FDR adjusted p-value matrix for correlation (upper triangle filled, symmetrized).
    """
    rng = np.random.default_rng(seed)
    items = list(profiles.index)
    D = profiles.shape[1]

    # 1) Pairwise correlation tests (one-sided, rho > 0)
    n = len(items)
    rho_mat = np.full((n, n), np.nan, dtype=float)
    p_mat = np.full((n, n), np.nan, dtype=float)
    for i in range(n):
        xi = profiles.iloc[i].to_numpy(dtype=float)
        for j in range(i + 1, n):
            yj = profiles.iloc[j].to_numpy(dtype=float)
            rho, p, n_used = spearman_rho_one_sided_perm(xi, yj, n_perm, rng)
            rho_mat[i, j] = rho
            p_mat[i, j] = p

    # BH-FDR across all tested pairs
    p_list = [p_mat[i, j] for i in range(n) for j in range(i + 1, n)]
    q_list = benjamini_hochberg(p_list)
    q_iter = iter(q_list)
    q_mat = np.full((n, n), np.nan, dtype=float)
    for i in range(n):
        for j in range(i + 1, n):
            q_mat[i, j] = next(q_iter)

    # Symmetrize (rho is symmetric; we keep p/q mirrored for convenience)
    rho_mat = rho_mat + rho_mat.T
    p_sym = np.where(np.isnan(p_mat.T), p_mat, p_mat)  # keep upper only; mirrored separately if needed
    q_sym = q_mat + q_mat.T

    rho_df = pd.DataFrame(rho_mat, index=items, columns=items)
    q_df = pd.DataFrame(q_sym, index=items, columns=items)

    # 2) Order candidates by median performance (ascending)
    med = profiles.median(axis=1)
    order = med.sort_values(ascending=True).index.tolist()

    kept: List[Tuple[str, str]] = []
    decisions = []

    for j in order:
        j_idx = items.index(j)
        # correlated neighbors already kept (FDR significant positive correlation)
        neighbors = []
        for k in kept:
            k_idx = items.index(k)
            qjk = q_df.iloc[j_idx, k_idx]
            rhojk = rho_df.iloc[j_idx, k_idx]
            if np.isfinite(qjk) and qjk < alpha and np.isfinite(rhojk) and rhojk > 0:
                neighbors.append(k)

        if not neighbors:
            kept.append(j)
            decisions.append({"model": j[0], "prep": j[1], "status": "kept",
                              "reason": "no_significant_positive_correlation_to_kept"})
            continue

        # For those neighbors, run exact sign tests H1: median(Δ) > 0 (candidate worse)
        pvals = []
        details = []
        xj = profiles.loc[j].to_numpy(dtype=float)
        for k in neighbors:
            xk = profiles.loc[k].to_numpy(dtype=float)
            mask = np.isfinite(xj) & np.isfinite(xk)
            if np.sum(mask) < MIN_OVERLAP:
                pvals.append(None)
                details.append((k, None, int(np.sum(mask))))
                continue
            diffs = xj[mask] - xk[mask]
            p, n_eff, n_pos = exact_sign_test_one_sided_greater(diffs)
            pvals.append(p)
            details.append((k, p, n_eff))

        # BH-FDR within the comparisons of the same j
        qvals = benjamini_hochberg(pvals)

        # If any neighbor yields q < alpha, prune j
        prune = False
        culprit = None
        cul_q = None
        for (k, p, n_eff), q in zip(details, qvals):
            if q is not None and q < alpha:
                prune = True
                culprit = k
                cul_q = q
                break

        if prune:
            kept_flag = "pruned"
            reason = f"worse_than_correlated_kept:{culprit} (FDR q={cul_q:.3g})"
        else:
            kept_flag = "kept"
            reason = "not_significantly_worse_than_correlated_kept"

        if kept_flag == "kept":
            kept.append(j)

        decisions.append({
            "model": j[0],
            "prep": j[1],
            "status": kept_flag,
            "reason": reason,
            "median_profile": float(med.loc[j]),
            "n_neighbors_corrpos": int(len(neighbors))
        })

    decisions_df = pd.DataFrame(decisions).sort_values(["status", "median_profile", "model", "prep"]).reset_index(drop=True)
    return decisions_df, rho_df, q_df


# ---------------- Main ----------------

def main():
    parser = argparse.ArgumentParser(description="Adaptive diverse selection with correlation-pruning and exact sign tests.")
    parser.add_argument("--root", type=str, default=DEFAULT_ROOT, help="Root folder with dataset subfolders.")
    parser.add_argument("--alpha", type=float, default=ALPHA, help="FDR / test level.")
    parser.add_argument("--permutations", type=int, default=N_PERM, help="Number of permutations for correlation tests.")
    parser.add_argument("--min_overlap", type=int, default=MIN_OVERLAP, help="Min datasets overlap to test.")
    parser.add_argument("--seed", type=int, default=RANDOM_SEED, help="Random seed.")
    parser.add_argument("--report_dir", type=str, default=REPORT_DIR, help="Output directory for reports.")
    parser.add_argument("--report_prefix", type=str, default=REPORT_PREFIX, help="Filename prefix for outputs.")
    args = parser.parse_args()

    global ALPHA, N_PERM, MIN_OVERLAP
    ALPHA = args.alpha
    N_PERM = args.permutations
    MIN_OVERLAP = args.min_overlap

    os.makedirs(args.report_dir, exist_ok=True)

    profiles = build_profiles(args.root)
    if profiles.empty:
        print("[ERROR] No profiles could be built. Check input structure.")
        return

    decisions_df, rho_df, q_df = adaptive_pruning(profiles, alpha=args.alpha, n_perm=args.permutations, seed=args.seed)

    # Save reports
    dec_path = os.path.join(args.report_dir, f"{args.report_prefix}_decisions.csv")
    rho_path = os.path.join(args.report_dir, f"{args.report_prefix}_rho.csv")
    q_path   = os.path.join(args.report_dir, f"{args.report_prefix}_rho_q.csv")

    decisions_df.to_csv(dec_path, index=False)
    rho_df.to_csv(rho_path)
    q_df.to_csv(q_path)

    print(f"[INFO] Decisions saved to: {dec_path}")
    print(f"[INFO] Spearman rho matrix saved to: {rho_path}")
    print(f"[INFO] FDR-adjusted p-values (correlation) saved to: {q_path}")


if __name__ == "__main__":
    main()
