#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Non-inferiority tests for model + preprocessing pairs using RRMSE tables.

Repository layout expected:
  /Results/asso_pp_model/<dataset_name>/*.csv

Each CSV must start with "results_" and must NOT contain any of the substrings in `FILENAME_EXCLUDE_SUBSTRINGS`.
The CSV structure is expected to be:
  - one row per model (column "Model")
  - one column per preprocessing (all other columns), values are RRMSE (float)

We compare Δ = RRMSE(candidate_model, prep, dataset) - RRMSE(reference, prep, dataset).
Two reference modes are available:
  1) fixed reference model (e.g., "Ridge_reg")
  2) per-dataset best model for the SAME preprocessing (lowest RRMSE in that dataset & prep)

For each (candidate_model, prep), we aggregate Δ across datasets (optionally across folds if present in your CSVs)
and compute three non-parametric procedures:
  a) Exact sign test (binomial) on Y = Δ - δ (H0: median(Y) >= 0 vs H1: < 0). We remove ties Y == 0.
  b) Wilcoxon signed-rank on Y = Δ - δ, one-sided (alternative='less'), ties handled as zeros.
  c) Bootstrap percentile CI for the median(Δ). Non-inferiority if UpperCI < δ.

Multiple testing is handled via Benjamini-Hochberg FDR separately for sign test and Wilcoxon.

Output: a CSV with one row per (candidate_model, preprocessing) combination, including
  counts, p-values, FDR-adjusted p-values, bootstrap CIs, and non-inferiority decisions.

Author: Generated by ChatGPT (comments in English).
"""

import os
import re
import math
import json
from dataclasses import dataclass
from typing import List, Tuple, Optional

import numpy as np
import pandas as pd

try:
    from scipy.stats import wilcoxon, binom
    SCIPY_AVAILABLE = True
except Exception:
    SCIPY_AVAILABLE = False


# ------------------------- Configuration -------------------------

# Root directory containing dataset subdirectories
RESULTS_ROOT = "/Results/asso_pp_model"

# CSV file selection rules
FILENAME_PREFIX = "results_"
FILENAME_EXCLUDE_SUBSTRINGS = ["NICON", "CNN", "Ridge", "LGBM", "PLS"]  # case-sensitive
FILENAME_REGEX = None  # Optional: provide a regex to further filter files (None = ignore)

# Column that identifies the model in the CSV
MODEL_COL = "Model"

# Reference mode: "fixed_model" or "per_dataset_best"
REFERENCE_MODE = "fixed_model"  # or "per_dataset_best"

# If REFERENCE_MODE == "fixed_model", provide the reference model name here
REFERENCE_MODEL_NAME = "Ridge_reg"  # example; replace as needed

# Margin delta for non-inferiority (Δ - δ < 0 means candidate non-inferior)
DELTA_MARGIN = 0.01

# Significance level for one-sided tests
ALPHA = 0.05

# Number of bootstrap resamples for CI of the median
BOOTSTRAP_B = 2000

# CI level
CI_LEVEL = 0.95

# Random seed for reproducibility
RANDOM_SEED = 42

# Whether to treat pre-processing names case-sensitively
PREP_CASE_SENSITIVE = True

# If not None, restrict computations to these preprocessings (set of names)
RESTRICT_TO_PREPS = None  # e.g., {"MSC", "SNV"} or None to use all

# If not None, restrict computations to these candidate models (set of names)
RESTRICT_TO_MODELS = None  # e.g., {"PLS_reg","LGBM_reg"} or None to use all

# Output file
OUTPUT_CSV = "noninferiority_report.csv"


# ------------------------- Utilities -------------------------

def discover_dataset_csvs(root: str) -> List[Tuple[str, str]]:
    """Discover (dataset_name, csv_path) pairs under root.
    We pick the FIRST CSV in each dataset dir that matches the rules.
    """
    pairs = []
    if not os.path.isdir(root):
        print(f"[WARN] Root directory not found: {root}")
        return pairs

    for ds in sorted(os.listdir(root)):
        ds_dir = os.path.join(root, ds)
        if not os.path.isdir(ds_dir):
            continue
        # List files that start with prefix and end with .csv
        candidates = [f for f in os.listdir(ds_dir)
                      if f.startswith(FILENAME_PREFIX) and f.lower().endswith(".csv")]
        # Apply exclusion by substring
        candidates = [f for f in candidates
                      if not any(excl in f for excl in FILENAME_EXCLUDE_SUBSTRINGS)]
        # Optional regex
        if FILENAME_REGEX is not None:
            rx = re.compile(FILENAME_REGEX)
            candidates = [f for f in candidates if rx.search(f)]

        if not candidates:
            # No matching file for this dataset, skip
            continue

        # Select the first (sorted) candidate
        candidates.sort()
        csv_path = os.path.join(ds_dir, candidates[0])
        pairs.append((ds, csv_path))

    return pairs


def load_rrmse_table(csv_path: str) -> pd.DataFrame:
    """Load a result CSV and return a tidy DataFrame:
    columns: ['dataset', 'model', 'prep', 'rrmse']
    """
    raw = pd.read_csv(csv_path)
    if MODEL_COL not in raw.columns:
        raise ValueError(f"{csv_path}: missing '{MODEL_COL}' column")

    # Melt wide table into tidy long format
    df = raw.melt(id_vars=[MODEL_COL], var_name="prep", value_name="rrmse")
    df = df.rename(columns={MODEL_COL: "model"})
    # Ensure numeric
    df["rrmse"] = pd.to_numeric(df["rrmse"], errors="coerce")
    # Drop rows with missing rrmse
    df = df.dropna(subset=["rrmse"])
    # Optionally restrict to certain preprocessings / models
    if RESTRICT_TO_PREPS is not None:
        if PREP_CASE_SENSITIVE:
            df = df[df["prep"].isin(RESTRICT_TO_PREPS)]
        else:
            lower_set = {p.lower() for p in RESTRICT_TO_PREPS}
            df = df[df["prep"].str.lower().isin(lower_set)]
    if RESTRICT_TO_MODELS is not None:
        df = df[df["model"].isin(RESTRICT_TO_MODELS)]
    return df


def benjamini_hochberg(pvals: List[float]) -> List[float]:
    """Benjamini-Hochberg FDR adjustment. Returns q-values in the original order.
    If pval is None (missing), returns None at the same position.
    """
    n = len(pvals)
    indexed = [(i, p) for i, p in enumerate(pvals)]
    # Filter out None
    valid = [(i, p) for i, p in indexed if p is not None]
    m = len(valid)
    if m == 0:
        return [None] * n
    # Sort by ascending p
    valid.sort(key=lambda t: t[1])
    ranks = {i: (rank+1) for rank, (i, _) in enumerate(valid)}
    qvals = [None] * n
    # Compute raw q = p * m / rank
    raw = [(i, min(1.0, p * m / ranks[i])) for (i, p) in valid]
    # Enforce monotonicity (non-increasing when traversing from high to low rank)
    # We process in reverse order of p (from largest rank to smallest)
    # and take cumulative minimum.
    # First, create a list in the same order as 'valid'
    qs_sorted = [min(1.0, p * m / (idx+1)) for idx, (_, p) in enumerate(valid)]
    # Now enforce monotone non-decreasing in rank (non-increasing when traversed reverse)
    for k in range(m - 2, -1, -1):
        qs_sorted[k] = min(qs_sorted[k], qs_sorted[k + 1])
    # Map back to original indices
    for (pos, (i, _)) in enumerate(valid):
        qvals[i] = qs_sorted[pos]
    return qvals


def exact_sign_test_pvalue(diffs: np.ndarray, delta: float) -> Tuple[Optional[float], int]:
    """Exact one-sided sign test for non-inferiority on Y = diffs - delta.
    H0: median(Y) >= 0  vs  H1: median(Y) < 0
    We remove ties where Y == 0.
    Returns (p_value, n_effective).
    """
    # Center by delta
    y = diffs - delta
    # Remove ties (zeros)
    mask = np.abs(y) > 0
    eff = y[mask]
    n_eff = eff.size
    if n_eff == 0:
        return None, 0

    # Count number of negatives
    s = np.sum(eff < 0)
    if SCIPY_AVAILABLE:
        # p = P[Binom(n, 0.5) <= s]
        from scipy.stats import binom
        p = binom.cdf(s, n_eff, 0.5)
    else:
        # Fallback exact computation (iterative sum) to avoid SciPy dependency
        from math import comb
        p = sum(comb(n_eff, k) * (0.5 ** n_eff) for k in range(0, int(s) + 1))
    return float(p), int(n_eff)


def wilcoxon_less_pvalue(diffs: np.ndarray, delta: float) -> Tuple[Optional[float], int]:
    """One-sided Wilcoxon signed-rank test on Y = diffs - delta with alternative='less'.
    Returns (p_value, n_effective) where n_effective excludes zeros as per Wilcoxon definition.
    """
    y = diffs - delta
    # SciPy wilcoxon handles zeros with zero_method='wilcox' by default in recent versions.
    # We explicitly set zero_method to 'wilcox' to drop zero-differences.
    if not SCIPY_AVAILABLE:
        return None, int(np.sum(np.abs(y) > 0))

    # If all are zeros or insufficient pairs, SciPy raises a warning / returns nan
    try:
        stat, p = wilcoxon(y, alternative='less', zero_method='wilcox', correction=False, mode='auto')
        # n_effective: count of non-zero pairs
        n_eff = int(np.sum(np.abs(y) > 0))
        if isinstance(p, float):
            return float(p), n_eff
        else:
            return None, n_eff
    except Exception:
        n_eff = int(np.sum(np.abs(y) > 0))
        return None, n_eff


def bootstrap_ci_median(diffs: np.ndarray, ci: float = 0.95, B: int = 2000, seed: int = 42) -> Tuple[float, float]:
    """Bootstrap percentile CI for the median of diffs.
    Returns (lower, upper).
    """
    rng = np.random.default_rng(seed)
    n = len(diffs)
    if n == 0:
        return np.nan, np.nan
    meds = []
    for _ in range(B):
        idx = rng.integers(0, n, n)
        sample = diffs[idx]
        meds.append(np.median(sample))
    lower = np.quantile(meds, (1 - ci) / 2.0)
    upper = np.quantile(meds, 1 - (1 - ci) / 2.0)
    return float(lower), float(upper)


# ------------------------- Core computation -------------------------

def collect_diffs_across_datasets(dataset_csvs: List[Tuple[str, str]],
                                  reference_mode: str,
                                  reference_model: Optional[str]) -> pd.DataFrame:
    """For each dataset, build a tidy table and compute all usable Δ values
    for each (candidate_model, prep).

    Returns a DataFrame with columns:
      ['candidate_model', 'prep', 'dataset', 'delta_value'] where
      delta_value = RRMSE(candidate) - RRMSE(reference) for the specified reference_mode.
    """
    rows = []
    for ds_name, csv_path in dataset_csvs:
        try:
            df = pd.read_csv(csv_path)
        except Exception as e:
            print(f"[WARN] Failed to read {csv_path}: {e}")
            continue

        if MODEL_COL not in df.columns:
            print(f"[WARN] Missing '{MODEL_COL}' in {csv_path}, skipping.")
            continue

        # Melt into long format
        tidy = df.melt(id_vars=[MODEL_COL], var_name="prep", value_name="rrmse").rename(columns={MODEL_COL: "model"})
        tidy["rrmse"] = pd.to_numeric(tidy["rrmse"], errors="coerce")
        tidy = tidy.dropna(subset=["rrmse"])

        # Optional restrictions
        if RESTRICT_TO_PREPS is not None:
            if PREP_CASE_SENSITIVE:
                tidy = tidy[tidy["prep"].isin(RESTRICT_TO_PREPS)]
            else:
                lower_set = {p.lower() for p in RESTRICT_TO_PREPS}
                tidy = tidy[tidy["prep"].str.lower().isin(lower_set)]
        if RESTRICT_TO_MODELS is not None:
            tidy = tidy[tidy["model"].isin(RESTRICT_TO_MODELS)]

        # Pivot to model x prep for quick lookup
        pivot = tidy.pivot_table(index="model", columns="prep", values="rrmse", aggfunc="mean")

        # Candidate models are all models except the reference (if fixed)
        models = list(pivot.index)

        if reference_mode == "fixed_model":
            if reference_model is None:
                raise ValueError("REFERENCE_MODE == 'fixed_model' but REFERENCE_MODEL_NAME is None")
            if reference_model not in models:
                # No reference in this dataset, cannot compute diffs here
                continue
            ref_row = pivot.loc[reference_model]

            for cand in models:
                if cand == reference_model:
                    continue
                for prep in pivot.columns:
                    cand_val = pivot.loc[cand].get(prep, np.nan)
                    ref_val = ref_row.get(prep, np.nan)
                    if pd.notna(cand_val) and pd.notna(ref_val):
                        rows.append({
                            "candidate_model": cand,
                            "prep": prep,
                            "dataset": ds_name,
                            "delta_value": float(cand_val - ref_val)
                        })

        elif reference_mode == "per_dataset_best":
            # For each prep, find the model with the minimum RRMSE in this dataset
            for prep in pivot.columns:
                col = pivot[prep].dropna()
                if col.empty:
                    continue
                best_model = col.idxmin()
                best_val = col.loc[best_model]
                for cand in pivot.index:
                    # Skip if candidate is the best; comparing to itself gives zero and is not informative
                    if pd.isna(pivot.loc[cand, prep]) or cand == best_model:
                        continue
                    rows.append({
                        "candidate_model": cand,
                        "prep": prep,
                        "dataset": ds_name,
                        "delta_value": float(pivot.loc[cand, prep] - best_val)
                    })
        else:
            raise ValueError(f"Unknown reference_mode: {reference_mode}")

    return pd.DataFrame(rows)


def run_tests(diffs_df: pd.DataFrame,
              delta_margin: float,
              alpha: float,
              ci_level: float,
              bootstrap_B: int,
              seed: int) -> pd.DataFrame:
    """Run sign test, Wilcoxon, and bootstrap CI for each (candidate_model, prep) over datasets.
    Returns a tidy summary DataFrame.
    """
    results = []
    grouped = diffs_df.groupby(["candidate_model", "prep"], sort=False)
    for (cand, prep), g in grouped:
        diffs = g["delta_value"].to_numpy(dtype=float)
        # Remove NaNs
        diffs = diffs[np.isfinite(diffs)]
        if diffs.size == 0:
            continue

        # Exact sign test
        sign_p, sign_n = exact_sign_test_pvalue(diffs, delta_margin)

        # Wilcoxon (one-sided 'less')
        wil_p, wil_n = wilcoxon_less_pvalue(diffs, delta_margin)

        # Bootstrap CI for median(Δ)
        ci_lo, ci_hi = bootstrap_ci_median(diffs, ci=ci_level, B=bootstrap_B, seed=seed)

        # Point estimates
        median_diff = float(np.median(diffs))
        mean_diff = float(np.mean(diffs))

        # Decisions
        noninf_sign = (sign_p is not None) and (sign_p < alpha)
        noninf_wil = (wil_p is not None) and (wil_p < alpha)
        noninf_boot = (not math.isnan(ci_hi)) and (ci_hi < delta_margin)

        results.append({
            "candidate_model": cand,
            "prep": prep,
            "n_datasets": int(len(g["dataset"].unique())),
            "n_pairs": int(diffs.size),
            "median_diff": median_diff,
            "mean_diff": mean_diff,
            "sign_p": sign_p,
            "sign_n_eff": sign_n,
            "wilcoxon_p": wil_p,
            "wilcoxon_n_eff": wil_n,
            "boot_ci_low": ci_lo,
            "boot_ci_high": ci_hi,
            "noninferior_sign": noninf_sign,
            "noninferior_wilcoxon": noninf_wil,
            "noninferior_bootstrap": noninf_boot
        })

    out = pd.DataFrame(results)

    # FDR (BH) for p-values separately
    if not out.empty:
        out["sign_q"] = benjamini_hochberg(out["sign_p"].tolist())
        out["wilcoxon_q"] = benjamini_hochberg(out["wilcoxon_p"].tolist())

        # Add FDR-based decisions
        out["noninferior_sign_fdr"] = out["sign_q"].apply(lambda q: (q is not None) and (q < alpha))
        out["noninferior_wilcoxon_fdr"] = out["wilcoxon_q"].apply(lambda q: (q is not None) and (q < alpha))

    return out.sort_values(["candidate_model", "prep"]).reset_index(drop=True)



import matplotlib.pyplot as plt
import seaborn as sns

def make_visualizations(summary: pd.DataFrame, delta_margin: float, alpha: float, output_prefix: str):
    """Generate volcano plot, forest plot, and heatmap for quick exclusion/retention decisions."""

    if summary.empty:
        print("[WARN] No summary to visualize.")
        return

    # 1) Volcano plot (Wilcoxon p-value vs median_diff)
    plt.figure(figsize=(8,6))
    x = summary["median_diff"]
    y = -np.log10(summary["wilcoxon_p"].fillna(1.0))
    colors = []
    for md, p in zip(summary["median_diff"], summary["wilcoxon_p"]):
        if p is None or np.isnan(p):
            colors.append("gray")
        elif (p < alpha) and (md < delta_margin):
            colors.append("green")  # keep
        elif (p < alpha) and (md >= delta_margin):
            colors.append("red")    # worse
        else:
            colors.append("orange") # ambiguous
    plt.scatter(x, y, c=colors, alpha=0.7)
    plt.axvline(delta_margin, color="black", linestyle="--", label=f"delta={delta_margin}")
    plt.xlabel("Median Δ (RRMSE candidate - reference)")
    plt.ylabel("-log10 p-value (Wilcoxon)")
    plt.title("Volcano plot for non-inferiority")
    plt.legend()
    plt.tight_layout()
    plt.savefig(f"{output_prefix}_volcano.png")
    plt.close()

    # 2) Forest plot (bootstrap CI of median Δ)
    fig, ax = plt.subplots(figsize=(8, max(6, 0.3*len(summary))))
    sorted_summary = summary.sort_values("median_diff")
    y_positions = range(len(sorted_summary))
    ax.errorbar(x=sorted_summary["median_diff"], y=y_positions,
                xerr=[sorted_summary["median_diff"]-sorted_summary["boot_ci_low"],
                      sorted_summary["boot_ci_high"]-sorted_summary["median_diff"]],
                fmt='o', ecolor="gray", capsize=3)
    ax.axvline(delta_margin, color="red", linestyle="--", label=f"delta={delta_margin}")
    ax.set_yticks(y_positions)
    labels = [f"{m}|{p}" for m,p in zip(sorted_summary["candidate_model"], sorted_summary["prep"])]
    ax.set_yticklabels(labels, fontsize=6)
    ax.set_xlabel("Median Δ with bootstrap CI")
    ax.set_title("Forest plot of bootstrap CIs")
    ax.legend()
    plt.tight_layout()
    plt.savefig(f"{output_prefix}_forest.png")
    plt.close()

    # 3) Heatmap of decisions (Wilcoxon)
    # Decision matrix: rows=model, cols=prep
    decision_matrix = summary.pivot(index="candidate_model", columns="prep",
                                    values="noninferior_wilcoxon")
    # Map True/False/None to numeric codes
    cmap = {True:1, False:0, None:np.nan}
    mat = decision_matrix.applymap(lambda v: cmap.get(v, np.nan))
    plt.figure(figsize=(12, max(6,0.4*len(mat))))
    sns.heatmap(mat, cmap=sns.color_palette(["red","green"]), cbar=False, linewidths=0.5, linecolor="gray")
    plt.title("Heatmap of non-inferiority (Wilcoxon)")
    plt.xlabel("Preprocessing")
    plt.ylabel("Model")
    plt.tight_layout()
    plt.savefig(f"{output_prefix}_heatmap.png")
    plt.close()



def main():
    import argparse
    parser = argparse.ArgumentParser(description="Non-inferiority tests on RRMSE tables (sign test, Wilcoxon, bootstrap CI).")
    parser.add_argument("--root", type=str, default=RESULTS_ROOT, help="Root directory containing dataset subfolders.")
    parser.add_argument("--reference_mode", type=str, choices=["fixed_model", "per_dataset_best"], default=REFERENCE_MODE,
                        help="Reference choice: fixed model or per-dataset best (same preprocessing).")
    parser.add_argument("--reference_model", type=str, default=REFERENCE_MODEL_NAME,
                        help="Reference model name when reference_mode=fixed_model.")
    parser.add_argument("--delta", type=float, default=DELTA_MARGIN, help="Non-inferiority margin δ (in RRMSE units).")
    parser.add_argument("--alpha", type=float, default=ALPHA, help="Significance level for tests (one-sided).")
    parser.add_argument("--bootstrap", type=int, default=BOOTSTRAP_B, help="Number of bootstrap resamples for median CI.")
    parser.add_argument("--ci", type=float, default=CI_LEVEL, help="Confidence level for bootstrap CI.")
    parser.add_argument("--restrict_models", type=str, default=None,
                        help="JSON array of model names to include (or None).")
    parser.add_argument("--restrict_preps", type=str, default=None,
                        help="JSON array of preprocessing names to include (or None).")
    parser.add_argument("--output", type=str, default=OUTPUT_CSV, help="Output CSV file path.")
    args = parser.parse_args()

    # Apply restrictions if provided
    global RESTRICT_TO_MODELS, RESTRICT_TO_PREPS
    if args.restrict_models:
        RESTRICT_TO_MODELS = set(json.loads(args.restrict_models))
    if args.restrict_preps:
        RESTRICT_TO_PREPS = set(json.loads(args.restrict_preps))

    # Discover CSVs
    dataset_csvs = discover_dataset_csvs(args.root)
    if not dataset_csvs:
        print(f"[WARN] No dataset CSVs discovered under {args.root}.")
        return

    # Collect Δ across datasets
    diffs_df = collect_diffs_across_datasets(dataset_csvs, args.reference_mode, args.reference_model)
    if diffs_df.empty:
        print("[WARN] No comparable pairs could be formed. Check reference mode and data availability.")
        return

    # Run tests
    summary = run_tests(diffs_df,
                        delta_margin=args.delta,
                        alpha=args.alpha,
                        ci_level=args.ci,
                        bootstrap_B=args.bootstrap,
                        seed=RANDOM_SEED)

    # Save results
    summary.to_csv(args.output, index=False)
    print(f"[INFO] Saved report to: {args.output}")
    # Also save the raw diffs for traceability
    diffs_df.to_csv(os.path.splitext(args.output)[0] + "_diffs.csv", index=False)

    # Visualizations
    output_prefix = os.path.splitext(args.output)[0]
    make_visualizations(summary, delta_margin=args.delta, alpha=args.alpha, output_prefix=output_prefix)
    print(f"[INFO] Saved visualizations to {output_prefix}_*.png")


if __name__ == "__main__":
    main()