schema_version: '2.0'
uid: a0df34f9-2d01-44b4-8397-99ba2d0fc858
pipeline_id: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c
name: PLS_PP_SELECTION_NO_SAVE_e2ea1c
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:50:33.580934+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: sklearn.preprocessing._data.StandardScaler
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - nirs4all.operators.transforms.scalers.StandardNormalVariate
    - null
    - null
    - nirs4all.operators.transforms.signal.Detrend
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      error_score: .nan
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: sklearn.preprocessing._data.StandardScaler
- _cartesian_:
  - nirs4all.operators.transforms.scalers.StandardNormalVariate
  - null
  - null
  - nirs4all.operators.transforms.signal.Detrend
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$e8256e270180:all
    content_hash: sha256:62fbca7e67132ee4c3eac6fcd60d6652d6e5c748d596fbba7aa83af04e3a52fc
    path: transformer_StandardScaler_62fbca7e6713.joblib
    chain_path: s2.StandardScaler[src=0,sub=0]
    source_index: 0
    pipeline_id: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c
    branch_path: []
    step_index: 2
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: StandardScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 12015
    created_at: '2026-01-08T17:50:33.587503+00:00'
    params: {}
    version: 3
  - artifact_id: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:50:33.622735+00:00'
    params: {}
    version: 3
  - artifact_id: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$6e21be876a4d:all
    content_hash: sha256:f1b0d49d100fdce0b1f766631a2fc34c1b2477ed43ee4a120b8aedc3581c1d26
    path: transformer_StandardNormalVariate_f1b0d49d100f.joblib
    chain_path: s5.StandardNormalVariate[src=0,sub=0]
    source_index: 0
    pipeline_id: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: StandardNormalVariate
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 132
    created_at: '2026-01-08T17:50:33.643520+00:00'
    params: {}
    version: 3
  - artifact_id: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$7d0f17e27058:all
    content_hash: sha256:11ce246bc67c631c59d4827a162f06b45fa0f87770f7d8325a0c50c7f6d72fcf
    path: transformer_Detrend_11ce246bc67c.joblib
    chain_path: s5.Detrend[src=0,sub=1]
    source_index: 0
    pipeline_id: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: Detrend
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 90
    created_at: '2026-01-08T17:50:33.647385+00:00'
    params: {}
    version: 3
  - artifact_id: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$9f79d59455ab:0
    content_hash: sha256:7da2181a285ec168f7968bb33b2e2789ec52bf8801b65a9502e3f83c35ef64eb
    path: model_PLSRegression_7da2181a285e.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 118603
    created_at: '2026-01-08T17:50:34.169402+00:00'
    params: {}
    version: 3
  - artifact_id: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$9f79d59455ab:1
    content_hash: sha256:cae21bbddbb536b222de75774b55004138bb8d4daf15ca43ae4b49ee93678aaa
    path: model_PLSRegression_cae21bbddbb5.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 118903
    created_at: '2026-01-08T17:50:34.174382+00:00'
    params: {}
    version: 3
  - artifact_id: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$9f79d59455ab:2
    content_hash: sha256:76386a1b7a62176d6b6ed6d17fe16ce1989df289414742ee1800ea6df9118446
    path: model_PLSRegression_76386a1b7a62.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 118899
    created_at: '2026-01-08T17:50:34.177651+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  6b959c19-d01:
    trace_id: 6b959c19-d01
    pipeline_uid: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c
    created_at: '2026-01-08T17:50:33.581976+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 2.921581268310547
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: StandardScaler
      operator_config:
        feature_augmentation: sklearn.preprocessing._data.StandardScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$e8256e270180:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$e8256e270180:all
        by_source:
          0:
          - 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$e8256e270180:all
        by_chain:
          s2.StandardScaler[src=0,sub=0]: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$e8256e270180:all
        metadata:
          class_name: StandardScaler
          name: StandardScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 7.0781707763671875
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s2.StandardScaler[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 37.7659797668457
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 8.774042129516602
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: StandardNormalVariate, None, None (+1)
      operator_config:
        feature_augmentation:
        - nirs4all.operators.transforms.scalers.StandardNormalVariate
        - null
        - null
        - nirs4all.operators.transforms.signal.Detrend
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$6e21be876a4d:all
        - 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$7d0f17e27058:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$6e21be876a4d:all
            - 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$7d0f17e27058:all
        by_source:
          0:
          - 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$6e21be876a4d:all
          - 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$7d0f17e27058:all
        by_chain:
          s5.StandardNormalVariate[src=0,sub=0]: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$6e21be876a4d:all
          s5.Detrend[src=0,sub=1]: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$7d0f17e27058:all
        metadata:
          class_name: Detrend
          name: Detrend_2
      branch_path: []
      branch_name: ''
      duration_ms: 34.833669662475586
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.StandardNormalVariate[src=0,sub=0]
      - s5.Detrend[src=0,sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 1728
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 3
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          error_score: .nan
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$9f79d59455ab:0
        - 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$9f79d59455ab:1
        - 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$9f79d59455ab:0
          1: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$9f79d59455ab:1
          2: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$9f79d59455ab:0
            - 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$9f79d59455ab:1
            - 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0498_PLS_PP_SELECTION_NO_SAVE_e2ea1c$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 530.5187702178955
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 1728
      output_shape:
      - 60
      - 1728
      input_features_shape:
      - - 60
        - 3
        - 576
      output_features_shape:
      - - 60
        - 3
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: Std|Std>SNV|Std>Detr
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_e2ea1c
      n_steps: 6
      n_artifacts: 7
