uid: 6247fe23-314b-4cc7-bdf9-44cc2927743f
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: eucalyptus_density_1654_chaix_rmse0_03
created_at: '2026-01-07T11:12:14.499213+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:34005a2c7c5ff861a0775079a6532f62293e570a2e21a4860d129591ee9165cc
  name: ASLSBaseline_1
  path: ASLSBaseline_34005a.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2026-01-07T11:12:15.132780+00:00'
  step: 1
- hash: sha256:128b98d132b794bba51e50828423ba23db235c8911b6260ab3288665072a056d
  name: PCA_1
  path: PCA_128b98.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 35762
  saved_at: '2026-01-07T11:12:18.269560+00:00'
  step: 4
- hash: sha256:d600aceb1aefcd16ba48a1d63df812a2c10c24e53a4a98b4d291bca0e540a718
  name: AutoGluon_1.pkl
  path: TabularPredictor_d600ac.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11621
  saved_at: '2026-01-07T11:12:42.166756+00:00'
  step: 5
- hash: sha256:18012de21a0f3bbeec6698fd381ba55c8aa35cb89d3baee9603ddd345427a111
  name: AutoGluon_2.pkl
  path: TabularPredictor_18012d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11630
  saved_at: '2026-01-07T11:12:42.167259+00:00'
  step: 5
- hash: sha256:b30cef87efa3603893a6d1f14116b9c5a6ca4534a015cb8b99f618ff435031f3
  name: AutoGluon_3.pkl
  path: TabularPredictor_b30cef.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11630
  saved_at: '2026-01-07T11:12:42.167713+00:00'
  step: 5
- hash: sha256:295a69bf99eb49e0b93768b01af317a49f3d7d46f7518f4ab4c66e9fda7598c1
  name: TabPFN_1.pkl
  path: TabPFNRegressor_295a69.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41869088
  saved_at: '2026-01-07T11:13:22.578211+00:00'
  step: 6
- hash: sha256:17d14d5763f43eb2e1a69d9ea205975465905f9ef345d27fa7194070fbabbed5
  name: TabPFN_2.pkl
  path: TabPFNRegressor_17d14d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41870304
  saved_at: '2026-01-07T11:13:22.626978+00:00'
  step: 6
- hash: sha256:2ba8b0e1985b5626a751272e9a84e33fade5f8e702517afd7ca8f56ac51284bb
  name: TabPFN_3.pkl
  path: TabPFNRegressor_2ba8b0.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41870304
  saved_at: '2026-01-07T11:13:22.675813+00:00'
  step: 6
- hash: sha256:f37ab30074e74cd5e7ecb6711e0b2675e636b540977aef9aeb88e55c7a4cd2ee
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_f37ab3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41869125
  saved_at: '2026-01-07T11:14:53.872483+00:00'
  step: 7
- hash: sha256:6ca3157ae3a575e88d82ea81f9174aab8993a4c6cdda6a26a56300d5b6e83650
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_6ca315.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41870341
  saved_at: '2026-01-07T11:14:53.926391+00:00'
  step: 7
- hash: sha256:f79c36c951f02f2b081d9d02874a0152f217e3b74a8f36446f3c140d3475e4ef
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_f79c36.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41870341
  saved_at: '2026-01-07T11:14:53.980950+00:00'
  step: 7
predictions: []
