uid: f63ffac9-a9e9-481e-90e5-9313d835027b
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: diesel_freeze_395_zhengybase
created_at: '2025-12-12T10:55:22.362731+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T10:55:22.424620+00:00'
  step: 1
- hash: sha256:4326f42ad315e110e2839aa45d6ca2208fb84d454d8445b050404076ea84f52d
  name: y_StandardScaler
  path: StandardScaler_4326f4.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 440
  saved_at: '2025-12-12T10:55:22.700254+00:00'
  step: 4
- hash: sha256:953eea2d76aad9a6782e198bb7d974d3fa5574d07ddab967bc3752e2585682c4
  name: StandardScaler_1
  path: StandardScaler_953eea.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9301
  saved_at: '2025-12-12T10:55:22.706413+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T10:55:22.719458+00:00'
  step: 6
- hash: sha256:1465bf0ac97a828aa5c3ae5e0a4d32f3d285c628eda3dd1f88c49487cb69df83
  name: PCA_1
  path: PCA_1465bf.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 20051
  saved_at: '2025-12-12T10:55:22.795232+00:00'
  step: 7
- hash: sha256:171128add4230ce7419ff268f32ca1488c9665f5a5b8bb149f7db5933f999d0e
  name: StandardScaler_1
  path: StandardScaler_171128.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 683
  saved_at: '2025-12-12T10:55:22.849389+00:00'
  step: 8
- hash: sha256:2248a76919fd7e60676d7325205474b129e49453774410c0e86e0442f81ed5af
  name: PowerTransformer_1
  path: PowerTransformer_2248a7.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 905
  saved_at: '2025-12-12T10:55:22.880330+00:00'
  step: 9
- hash: sha256:0fae74d9173f3888e2caff26b1560f549acc8d30cf0997c22feba7af9041be92
  name: AutoGluon_1.pkl
  path: TabularPredictor_0fae74.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 14143
  saved_at: '2025-12-12T10:55:47.896547+00:00'
  step: 10
- hash: sha256:af28af2201a6f03d76462a203205fc2a456ec35815440022c671b1a32de5c8f0
  name: AutoGluon_2.pkl
  path: TabularPredictor_af28af.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 14133
  saved_at: '2025-12-12T10:55:47.896875+00:00'
  step: 10
- hash: sha256:962b4b33819fbd2e733b33d11b5b19316f2447a600f8e51438cc9c069a03a1dd
  name: AutoGluon_3.pkl
  path: TabularPredictor_962b4b.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 14161
  saved_at: '2025-12-12T10:55:47.897152+00:00'
  step: 10
- hash: sha256:759e2c32e10cfe419b3466cc38b867e417bf2ddea44692dfe6d278dd89473378
  name: TabPFN_1.pkl
  path: TabPFNRegressor_759e2c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41538603
  saved_at: '2025-12-12T10:56:05.473161+00:00'
  step: 11
- hash: sha256:541d3f9cf882b9599b5f33ef2f432326d904d2989515689f6fbd90135bba7241
  name: TabPFN_2.pkl
  path: TabPFNRegressor_541d3f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41541291
  saved_at: '2025-12-12T10:56:05.529137+00:00'
  step: 11
- hash: sha256:6269f13be8383092b1facc52a47d201e32221930cdb670636a93eb2073233b81
  name: TabPFN_3.pkl
  path: TabPFNRegressor_6269f1.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41541291
  saved_at: '2025-12-12T10:56:05.584786+00:00'
  step: 11
- hash: sha256:bddd662ad0bb8c552eb385b66536c0a5b64f72ede139cd17ae8a3e9c7c0030b6
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_bddd66.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41538640
  saved_at: '2025-12-12T10:56:41.436430+00:00'
  step: 12
- hash: sha256:144600b862f18588697457029548ee3469705efbe56033f9a2187e6a9cc12c59
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_144600.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41541328
  saved_at: '2025-12-12T10:56:41.492371+00:00'
  step: 12
- hash: sha256:a62cbd9b025c7465fec67236f25ef9fe22df54b4c6d03d85f6d15da22667b2c2
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_a62cbd.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41541328
  saved_at: '2025-12-12T10:56:41.548196+00:00'
  step: 12
predictions: []
