uid: 601741cd-546d-48c5-8001-be6bcbd05d9d
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: cattle_manure_cao_ks
created_at: '2025-12-12T07:29:20.330300+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:125d94dee500492a3bdb8dd8b9fa106b8b2b34e5f42944e4b15d55960ffb73d1
  name: ASLSBaseline_1
  path: ASLSBaseline_125d94.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T07:29:20.417011+00:00'
  step: 1
- hash: sha256:143420965827cfd3120b1f3784ea94b1942e65b45398134ad2c95157367e217e
  name: y_StandardScaler
  path: StandardScaler_143420.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 440
  saved_at: '2025-12-12T07:29:20.555604+00:00'
  step: 4
- hash: sha256:df0e6280c238a24e3ec44b22bc9fcddcc1b0841f6575f06d1895df2a2a9f9e68
  name: StandardScaler_1
  path: StandardScaler_df0e62.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 21800
  saved_at: '2025-12-12T07:29:20.561843+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T07:29:20.570588+00:00'
  step: 6
- hash: sha256:1db9f9a5c127ba70f1a3c850c51f8c31351d192ca9288bef332a16093bc131d5
  name: PCA_1
  path: PCA_1db9f9.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 157683
  saved_at: '2025-12-12T07:29:20.621248+00:00'
  step: 7
- hash: sha256:aa283d53aea94e1aeb1f92ca04c3f881e60fecf4e1a17dbd5969fc572e87762a
  name: StandardScaler_1
  path: StandardScaler_aa283d.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1208
  saved_at: '2025-12-12T07:29:20.659534+00:00'
  step: 8
- hash: sha256:240cec9e317bfdf6b756d83c6eb6f5bc6c227fbaa0b8266ef8b6256547d93ed2
  name: PowerTransformer_1
  path: PowerTransformer_240cec.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1679
  saved_at: '2025-12-12T07:29:20.720840+00:00'
  step: 9
- hash: sha256:e6056c34d9c824c9f85e0a12cf0c94e633ccbbb058c7e31663b680e47eab7110
  name: AutoGluon_1.pkl
  path: TabularPredictor_e6056c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 24494
  saved_at: '2025-12-12T07:29:33.787484+00:00'
  step: 10
- hash: sha256:c1034e1e9c75e4e838a99c85fd46e18a90e6ff845261d006933acbc15c1753a7
  name: AutoGluon_2.pkl
  path: TabularPredictor_c1034e.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 24476
  saved_at: '2025-12-12T07:29:33.787847+00:00'
  step: 10
- hash: sha256:69a61078506d50af5dfccd69a1dfb20ff0601dc5f63762c7c5ef9d8e12ab1f07
  name: AutoGluon_3.pkl
  path: TabularPredictor_69a610.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 24467
  saved_at: '2025-12-12T07:29:33.788169+00:00'
  step: 10
- hash: sha256:99b0181df9170342225511073441360ee949c22544fb8afed2e9e8655f33c650
  name: TabPFN_1.pkl
  path: TabPFNRegressor_99b018.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42153203
  saved_at: '2025-12-12T07:30:02.494741+00:00'
  step: 11
- hash: sha256:a7bb0240c47e31d4f586ad9518a34309c7b6a567a924364ddc7acd4ef11eae95
  name: TabPFN_2.pkl
  path: TabPFNRegressor_a7bb02.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42161915
  saved_at: '2025-12-12T07:30:02.551590+00:00'
  step: 11
- hash: sha256:016e68eb54238f1ffcb81443f6691d00fe89cd260840becc0e4668ba9f0a5445
  name: TabPFN_3.pkl
  path: TabPFNRegressor_016e68.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42161915
  saved_at: '2025-12-12T07:30:02.607832+00:00'
  step: 11
- hash: sha256:df6e938491e57b275ac533e90fdfa828c3372c201f6ee9ad209543f93daefc90
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_df6e93.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42153232
  saved_at: '2025-12-12T07:31:05.239900+00:00'
  step: 12
- hash: sha256:c022331272c220e572e49d4b6f5b987902493be33f41acda102dfdcbd9f2993a
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_c02233.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42161944
  saved_at: '2025-12-12T07:31:05.284520+00:00'
  step: 12
- hash: sha256:25135b45923d81e9c4233cc1459ccc1b49118abdd9e725b993de4df04ed6507e
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_25135b.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42161952
  saved_at: '2025-12-12T07:31:05.327718+00:00'
  step: 12
predictions: []
