uid: 8f218699-c166-45d6-9548-d86e50821d5a
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: diesel_bp50_246_hla_b
created_at: '2025-12-12T12:49:55.036512+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T12:49:55.077016+00:00'
  step: 1
- hash: sha256:e0374d0e48f86eeed1e81934164d026b71aa558d5d0ddc4c911a96269f32ccfb
  name: y_StandardScaler
  path: StandardScaler_e0374d.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 443
  saved_at: '2025-12-12T12:49:55.249388+00:00'
  step: 4
- hash: sha256:4002acf6a4c2643ec126e1ad9ce21b978cce917be79dffb1e9876abd981bc884
  name: StandardScaler_1
  path: StandardScaler_4002ac.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9303
  saved_at: '2025-12-12T12:49:55.254850+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T12:49:55.263201+00:00'
  step: 6
- hash: sha256:044690296ce755171965b3e9609de7b53def7a4311216be0b50f6a7ddc399a6f
  name: PCA_1
  path: PCA_044690.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9378
  saved_at: '2025-12-12T12:49:55.366583+00:00'
  step: 7
- hash: sha256:735aee76ead2b8bf62c5bb76229b463001789faa7b15f11c1414870d0a1656b3
  name: StandardScaler_1
  path: StandardScaler_735aee.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 539
  saved_at: '2025-12-12T12:49:55.394390+00:00'
  step: 8
- hash: sha256:5acef09ba5558d7c5ee777feb28082a2b558606cf4d8ab2a4c5bad9b5229b657
  name: PowerTransformer_1
  path: PowerTransformer_5acef0.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 693
  saved_at: '2025-12-12T12:49:55.427958+00:00'
  step: 9
- hash: sha256:b4c3bec7bd71f21606a231ee2ec3a40fb6599896e0c937c22757de4f5d386827
  name: AutoGluon_1.pkl
  path: TabularPredictor_b4c3be.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11607
  saved_at: '2025-12-12T12:50:06.467912+00:00'
  step: 10
- hash: sha256:4304ade2cae47592dbe83326b582fc8fa6464ef7450706cb07acd0722edea985
  name: AutoGluon_2.pkl
  path: TabularPredictor_4304ad.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11607
  saved_at: '2025-12-12T12:50:06.468193+00:00'
  step: 10
- hash: sha256:cc4ea4ee193f0c0854685ae68c6bc2c88034f980f0dd8cd15d448c869a769111
  name: AutoGluon_3.pkl
  path: TabularPredictor_cc4ea4.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11688
  saved_at: '2025-12-12T12:50:06.468455+00:00'
  step: 10
- hash: sha256:b1893f419383d22d95e5cc90d8679322fa7b8ca8df3f1881375b4783c13f0043
  name: TabPFN_1.pkl
  path: TabPFNRegressor_b1893f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41058496
  saved_at: '2025-12-12T12:50:14.234196+00:00'
  step: 11
- hash: sha256:09a7d5ccd55e972e9de47228710f48eaf41bc7dc8f22a9f552f8b53c89306a97
  name: TabPFN_2.pkl
  path: TabPFNRegressor_09a7d5.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41059712
  saved_at: '2025-12-12T12:50:14.277374+00:00'
  step: 11
- hash: sha256:eeedbd117ece9b6189c5987d5ff3104e09bf9e92c5855d208268342613c68acc
  name: TabPFN_3.pkl
  path: TabPFNRegressor_eeedbd.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41059712
  saved_at: '2025-12-12T12:50:14.319770+00:00'
  step: 11
- hash: sha256:6d8e2909b1c668881e2fc1cbedcd9c2684e66b2d68a805a0480c345dbba0643b
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_6d8e29.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41058533
  saved_at: '2025-12-12T12:50:29.495253+00:00'
  step: 12
- hash: sha256:57c968573dc32486a2bc7c4f75376602fb2664b810c46fd5f057cf4c9ecf2ba3
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_57c968.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41059749
  saved_at: '2025-12-12T12:50:29.538212+00:00'
  step: 12
- hash: sha256:512197da1f60c93313fa1487fa74193a3eb5b9ca4fc7437e1f17484cdfce7daf
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_512197.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41059749
  saved_at: '2025-12-12T12:50:29.580250+00:00'
  step: 12
predictions: []
