schema_version: '2.0'
uid: 458b1c23-e6ed-4f20-a863-8b26f4b65a96
pipeline_id: 0001_SOTA_033cb7
name: SOTA_033cb7
dataset: lucas_soc_all_26650_nocitaks
created_at: '2026-01-07T17:30:37.736734+00:00'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0001_SOTA_033cb7$bb12ee38a89c:all
    content_hash: sha256:4b8c179b0caedba3ee8a4a4945ad287c925324d79180bc4f973c334322e0dd6a
    path: transformer_ASLSBaseline_4b8c179b0cae.joblib
    chain_path: s1.ASLSBaseline[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 1
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: ASLSBaseline
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 215
    created_at: '2026-01-07T17:31:03.246863+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_033cb7$dfc251e3a6b4:all
    content_hash: sha256:d3cb35fa38f1fa4d9489e2fd361472ba6cf55c58656f07b1fe53d7061a8f6551
    path: transformer_PCA_d3cb35fa38f1.joblib
    chain_path: s3.PCA[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 3
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: PCA
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 205457
    created_at: '2026-01-07T18:21:40.611017+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_033cb7$9d98c9f5abc5:0
    content_hash: sha256:dd28b519f6b932ddf07604e256e86660d96d12f63c91cf193604bd042188bd6a
    path: model_TabPFNRegressor_dd28b519f6b9.pkl
    chain_path: s4.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 4
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 65573417
    created_at: '2026-01-07T19:11:11.483453+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_033cb7$9d98c9f5abc5:1
    content_hash: sha256:9e2f78f7325da8a76a10b763efac2cf10339f1c32ba00c066a8e5b41697ea419
    path: model_TabPFNRegressor_9e2f78f7325d.pkl
    chain_path: s4.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 4
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 65573439
    created_at: '2026-01-07T19:11:11.566911+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_033cb7$9d98c9f5abc5:2
    content_hash: sha256:ea14046ec48fe965fdb1ae4a5030934693227aac95bdeeb810f670b265b9daf3
    path: model_TabPFNRegressor_ea14046ec48f.pkl
    chain_path: s4.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 4
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 65576119
    created_at: '2026-01-07T19:11:11.649600+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  abfc0819-12b:
    trace_id: abfc0819-12b
    pipeline_uid: 0001_SOTA_033cb7
    created_at: '2026-01-07T17:30:37.737535+00:00'
    steps:
    - step_index: 1
      operator_type: transform
      operator_class: ASLSBaseline
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_033cb7$bb12ee38a89c:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_033cb7$bb12ee38a89c:all
        by_source:
          0:
          - 0001_SOTA_033cb7$bb12ee38a89c:all
        by_chain:
          s1.ASLSBaseline[src=0,sub=0]: 0001_SOTA_033cb7$bb12ee38a89c:all
        metadata:
          class_name: ASLSBaseline
          name: ASLSBaseline_1
      branch_path: []
      branch_name: ''
      duration_ms: 25963.655948638916
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s1.ASLSBaseline[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 19036
      - 4200
      output_shape:
      - 19036
      - 4200
      input_features_shape:
      - - 19036
        - 1
        - 4200
      output_features_shape:
      - - 19036
        - 1
        - 4200
    - step_index: 2
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 3030912.093639374
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 19036
      - 4200
      output_shape:
      - 19036
      - 4200
      input_features_shape:
      - - 19036
        - 1
        - 4200
      output_features_shape:
      - - 19036
        - 1
        - 4200
    - step_index: 3
      operator_type: operator
      operator_class: PCA
      operator_config:
        class: sklearn.decomposition._pca.PCA
        params:
          n_components: 0.99
          whiten: true
          random_state: 42
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_033cb7$dfc251e3a6b4:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_033cb7$dfc251e3a6b4:all
        by_source:
          0:
          - 0001_SOTA_033cb7$dfc251e3a6b4:all
        by_chain:
          s3.PCA[src=0,sub=0]: 0001_SOTA_033cb7$dfc251e3a6b4:all
        metadata:
          class_name: PCA
          name: PCA_1
      branch_path: []
      branch_name: ''
      duration_ms: 6159.1479778289795
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.PCA[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 19036
      - 4200
      output_shape:
      - 19036
      - 12
      input_features_shape:
      - - 19036
        - 1
        - 4200
      output_features_shape:
      - - 19036
        - 1
        - 12
    - step_index: 4
      operator_type: model
      operator_class: TabPFNRegressor
      operator_config:
        model:
          class: tabpfn.regressor.TabPFNRegressor
          params:
            n_estimators: 16
            model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
            device: cpu
            ignore_pretraining_limits: true
            random_state: 42
        name: TabPFN-real
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_033cb7$9d98c9f5abc5:0
        - 0001_SOTA_033cb7$9d98c9f5abc5:1
        - 0001_SOTA_033cb7$9d98c9f5abc5:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0001_SOTA_033cb7$9d98c9f5abc5:0
          1: 0001_SOTA_033cb7$9d98c9f5abc5:1
          2: 0001_SOTA_033cb7$9d98c9f5abc5:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_033cb7$9d98c9f5abc5:0
            - 0001_SOTA_033cb7$9d98c9f5abc5:1
            - 0001_SOTA_033cb7$9d98c9f5abc5:2
        by_source: {}
        by_chain:
          s4.TabPFNRegressor[sub=0]: 0001_SOTA_033cb7$9d98c9f5abc5:2
        metadata:
          class_name: TabPFNRegressor
          custom_name: TabPFN-real
      branch_path: []
      branch_name: ''
      duration_ms: 6746822.12638855
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s4.TabPFNRegressor[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 19036
      - 12
      output_shape:
      - 19036
      - 12
      input_features_shape:
      - - 19036
        - 1
        - 12
      output_features_shape:
      - - 19036
        - 1
        - 12
    model_step_index: 4
    fold_weights: null
    preprocessing_chain: ASLSBaseline>PCA
    metadata:
      dataset: lucas_soc_all_26650_nocitaks
      config_name: SOTA_033cb7
      n_steps: 4
      n_artifacts: 5
