uid: 4d49575d-5f7b-4b6a-8542-3cb4c3555187
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: grapevine_chloride_556_ks
created_at: '2025-12-12T07:49:28.360622+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:11348165aae025ca2d539126682657429d57f7d05b66ba9ea0b12f1ee241a8b2
  name: ASLSBaseline_1
  path: ASLSBaseline_113481.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T07:49:28.527619+00:00'
  step: 1
- hash: sha256:b15522f704ef61928d37064523fe821099b3db09704c9e6efebf0eec1e0a646d
  name: y_StandardScaler
  path: StandardScaler_b15522.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 448
  saved_at: '2025-12-12T07:49:29.003049+00:00'
  step: 4
- hash: sha256:1d3b7c7378cac8e12ef30571affd5cc57759eed97afb5b63e224a0fdec83d271
  name: StandardScaler_1
  path: StandardScaler_1d3b7c.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 22641
  saved_at: '2025-12-12T07:49:29.021521+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T07:49:29.066310+00:00'
  step: 6
- hash: sha256:f8441def957839702f472304855d3fcf537157ed81f57e116caf99c39e0a7201
  name: PCA_1
  path: PCA_f8441d.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 76602
  saved_at: '2025-12-12T07:49:29.118659+00:00'
  step: 7
- hash: sha256:8c4e2f5c30b337d977565b73fe7b9831b517a3e47ce20295779a0669e9e208fe
  name: StandardScaler_1
  path: StandardScaler_8c4e2f.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 806
  saved_at: '2025-12-12T07:49:29.156739+00:00'
  step: 8
- hash: sha256:dc1c3cf8572b48762c8ca9810971cd29bd0a97611840cf7c39c1afe40f5e36dc
  name: PowerTransformer_1
  path: PowerTransformer_dc1c3c.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1100
  saved_at: '2025-12-12T07:49:29.209463+00:00'
  step: 9
- hash: sha256:a5d0a18f21e496d89d977dec811648abad2d508cfb31e8db92e14ce4081c58a9
  name: AutoGluon_1.pkl
  path: TabularPredictor_a5d0a1.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 16647
  saved_at: '2025-12-12T07:49:44.098551+00:00'
  step: 10
- hash: sha256:3860e67a3a843738e17e1d1289441c68bdb3b21888146c982a3c17a54d4b54a9
  name: AutoGluon_2.pkl
  path: TabularPredictor_3860e6.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 16656
  saved_at: '2025-12-12T07:49:44.099059+00:00'
  step: 10
- hash: sha256:149314392e15ab66bd405faf2b5f53e1e82a0c947995f7813f013aae73368cf9
  name: AutoGluon_3.pkl
  path: TabularPredictor_149314.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 16647
  saved_at: '2025-12-12T07:49:44.099600+00:00'
  step: 10
- hash: sha256:89d98931c147e8d70b1a8b72660e5200e5b3a60499fa4dd88072dea1ba3d4159
  name: TabPFN_1.pkl
  path: TabPFNRegressor_89d989.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42054347
  saved_at: '2025-12-12T07:50:11.694439+00:00'
  step: 11
- hash: sha256:ef6cc51a1c4ab00d126f3c7d9e3476dce7f1cf97f891d9de87b930731deaee15
  name: TabPFN_2.pkl
  path: TabPFNRegressor_ef6cc5.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42058447
  saved_at: '2025-12-12T07:50:11.742037+00:00'
  step: 11
- hash: sha256:e414455ce11740c753bc43e9c249dd71ac3c24855dd2f1885a276219bd5d4647
  name: TabPFN_3.pkl
  path: TabPFNRegressor_e41445.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42058443
  saved_at: '2025-12-12T07:50:11.789777+00:00'
  step: 11
- hash: sha256:e641c91301913ba76c864de35577e5b659f594f1da2b4975903f98b9db849eb0
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_e641c9.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42054386
  saved_at: '2025-12-12T07:51:09.192000+00:00'
  step: 12
- hash: sha256:a8e1376e4e094487314bae9945d40f5d0029315b6fe3b3a31b2eabe9a8fc449e
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_a8e137.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42058482
  saved_at: '2025-12-12T07:51:09.240231+00:00'
  step: 12
- hash: sha256:0573e2d4e6335a38ef1f1e6fa70d2cc40a78ed47443842aa3634cded7af8e88f
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_0573e2.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42058480
  saved_at: '2025-12-12T07:51:09.287593+00:00'
  step: 12
predictions: []
