uid: cd29813c-b68a-4389-b93a-9a32c43a0f08
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: diesel_d_263_b_a
created_at: '2025-12-12T13:03:13.461573+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T13:03:13.502210+00:00'
  step: 1
- hash: sha256:575bd9d6196332a26ce356c2e56f5133c286d963a0380762bc07ccc3a88edf2c
  name: y_StandardScaler
  path: StandardScaler_575bd9.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 446
  saved_at: '2025-12-12T13:03:13.634711+00:00'
  step: 4
- hash: sha256:8dc24555a00c796ebd1e5a5ef9d47da87af9ccba8bdc1e3be8e0f54cbc5e0565
  name: StandardScaler_1
  path: StandardScaler_8dc245.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9280
  saved_at: '2025-12-12T13:03:13.642533+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T13:03:13.661385+00:00'
  step: 6
- hash: sha256:e60ad2108f8e13fbc7571af44a24259f4b5e48e421a269d173ed68dea1fe45c5
  name: PCA_1
  path: PCA_e60ad2.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9235
  saved_at: '2025-12-12T13:03:13.710096+00:00'
  step: 7
- hash: sha256:0db7960513b04e2eacb6bf62bbbf4c229fc36403f9d79ba71c62d018fb6b58cb
  name: StandardScaler_1
  path: StandardScaler_0db796.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 538
  saved_at: '2025-12-12T13:03:13.740297+00:00'
  step: 8
- hash: sha256:d4619951575aeb35018d7b79a77cfae686157159d3bf0ed5b1d5b21713145c06
  name: PowerTransformer_1
  path: PowerTransformer_d46199.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 694
  saved_at: '2025-12-12T13:03:13.765037+00:00'
  step: 9
- hash: sha256:40dc26af462425f7d5510e2bb236035161ae4326590bf8d0ed7cd2b6ae5a378e
  name: AutoGluon_1.pkl
  path: TabularPredictor_40dc26.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11616
  saved_at: '2025-12-12T13:03:24.139721+00:00'
  step: 10
- hash: sha256:784c55792b2168424e910f2fc60f8e0514c0a2115c0abd559764778f77a2ccc8
  name: AutoGluon_2.pkl
  path: TabularPredictor_784c55.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11598
  saved_at: '2025-12-12T13:03:24.139985+00:00'
  step: 10
- hash: sha256:34ce207d75dffb80b630cdba7372faf12d66715c9a0bf063f0ce5d82d9eabd44
  name: AutoGluon_3.pkl
  path: TabularPredictor_34ce20.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11607
  saved_at: '2025-12-12T13:03:24.140226+00:00'
  step: 10
- hash: sha256:54dd3535d3f024efe39870dd0badeb80779770fe182d1ae692138f4f8e90a23b
  name: TabPFN_1.pkl
  path: TabPFNRegressor_54dd35.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41048768
  saved_at: '2025-12-12T13:03:32.058445+00:00'
  step: 11
- hash: sha256:8155048d030e35f15c237f464f54b6735178f2730b5b80198657d520943e83b9
  name: TabPFN_2.pkl
  path: TabPFNRegressor_815504.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41049984
  saved_at: '2025-12-12T13:03:32.112503+00:00'
  step: 11
- hash: sha256:8016d082837ee6d0d9549c66e3c3713d9ed3d798296bef892515a503a9c728d1
  name: TabPFN_3.pkl
  path: TabPFNRegressor_8016d0.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41049984
  saved_at: '2025-12-12T13:03:32.166002+00:00'
  step: 11
- hash: sha256:cdc7221095672919ef04537dd6eadf7c2e46836e7bc1b4f0f192166b3c79e607
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_cdc722.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41048805
  saved_at: '2025-12-12T13:03:47.493391+00:00'
  step: 12
- hash: sha256:bdc5d7b67519981c0dc719e6817b06d269d99a7208332f1d3748cb304ff42baf
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_bdc5d7.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41050021
  saved_at: '2025-12-12T13:03:47.548220+00:00'
  step: 12
- hash: sha256:81f51f65a9580c312a0731076f8587e80b2424e335bbe3b691b1d7e46ab1add8
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_81f51f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41050021
  saved_at: '2025-12-12T13:03:47.602292+00:00'
  step: 12
predictions: []
