schema_version: '2.0'
uid: b08e0a46-07b5-479a-b73c-411da4b3d3d1
pipeline_id: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2
name: PLS_PP_SELECTION_NO_SAVE_e4c9b2
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:48:57.115959+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: null
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - nirs4all.operators.transforms.signal.Detrend
    - class: nirs4all.operators.transforms.signal.Gaussian
      params:
        order: 1
        sigma: 2
    - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
      params:
        window_length: 15
        deriv: 2
    - null
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      error_score: .nan
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: null
- _cartesian_:
  - nirs4all.operators.transforms.signal.Detrend
  - class: nirs4all.operators.transforms.signal.Gaussian
    params:
      order: 1
      sigma: 2
  - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
    params:
      window_length: 15
      deriv: 2
  - null
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:48:57.143053+00:00'
    params: {}
    version: 3
  - artifact_id: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$51eb708c8a1f:all
    content_hash: sha256:11ce246bc67c631c59d4827a162f06b45fa0f87770f7d8325a0c50c7f6d72fcf
    path: transformer_Detrend_11ce246bc67c.joblib
    chain_path: s5.Detrend[src=0,sub=0]
    source_index: 0
    pipeline_id: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: Detrend
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 90
    created_at: '2026-01-08T17:48:57.157371+00:00'
    params: {}
    version: 3
  - artifact_id: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$5b4a7bbb9aae:all
    content_hash: sha256:fcef74d1464ae75c275fc2b03bb2c435a0787cd50861cdf41aedf150ab9f3eff
    path: transformer_Gaussian_fcef74d1464a.joblib
    chain_path: s5.Gaussian[src=0,sub=1]
    source_index: 0
    pipeline_id: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: Gaussian
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 103
    created_at: '2026-01-08T17:48:57.164510+00:00'
    params: {}
    version: 3
  - artifact_id: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$296923040127:all
    content_hash: sha256:5c353b1441d52f528075c64bd2477db6d0df3f619817bfa27a68d32928e99953
    path: transformer_SavitzkyGolay_5c353b1441d5.joblib
    chain_path: s5.SavitzkyGolay[src=0,sub=2]
    source_index: 0
    pipeline_id: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2
    branch_path: []
    step_index: 5
    substep_index: 2
    fold_id: null
    artifact_type: transformer
    class_name: SavitzkyGolay
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 137
    created_at: '2026-01-08T17:48:57.173607+00:00'
    params: {}
    version: 3
  - artifact_id: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$9f79d59455ab:0
    content_hash: sha256:b4b587a2441383561136633866768baebee93826b5106240caa859ae753067ac
    path: model_PLSRegression_b4b587a24413.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 157054
    created_at: '2026-01-08T17:48:57.776235+00:00'
    params: {}
    version: 3
  - artifact_id: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$9f79d59455ab:1
    content_hash: sha256:1d97bd6ee5bc3fbd012682e01c464336ad2538557f01046ec97d07224f4c4898
    path: model_PLSRegression_1d97bd6ee5bc.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 157401
    created_at: '2026-01-08T17:48:57.781977+00:00'
    params: {}
    version: 3
  - artifact_id: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$9f79d59455ab:2
    content_hash: sha256:1d25e5b90728954bd924836a96ee242892d8651a708dac695d95f08170ed1f1c
    path: model_PLSRegression_1d25e5b90728.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 157376
    created_at: '2026-01-08T17:48:57.785816+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  f92dff8f-001:
    trace_id: f92dff8f-001
    pipeline_uid: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2
    created_at: '2026-01-08T17:48:57.117164+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 2.130746841430664
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 1.871347427368164
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 26.30329132080078
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 5.896329879760742
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: Detrend, Gaussian, SavitzkyGolay (+1)
      operator_config:
        feature_augmentation:
        - nirs4all.operators.transforms.signal.Detrend
        - class: nirs4all.operators.transforms.signal.Gaussian
          params:
            order: 1
            sigma: 2
        - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
          params:
            window_length: 15
            deriv: 2
        - null
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$51eb708c8a1f:all
        - 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$5b4a7bbb9aae:all
        - 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$296923040127:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$51eb708c8a1f:all
            - 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$5b4a7bbb9aae:all
            - 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$296923040127:all
        by_source:
          0:
          - 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$51eb708c8a1f:all
          - 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$5b4a7bbb9aae:all
          - 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$296923040127:all
        by_chain:
          s5.Detrend[src=0,sub=0]: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$51eb708c8a1f:all
          s5.Gaussian[src=0,sub=1]: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$5b4a7bbb9aae:all
          s5.SavitzkyGolay[src=0,sub=2]: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$296923040127:all
        metadata:
          class_name: SavitzkyGolay
          name: SavitzkyGolay_3
      branch_path: []
      branch_name: ''
      duration_ms: 52.75130271911621
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.Detrend[src=0,sub=0]
      - s5.Gaussian[src=0,sub=1]
      - s5.SavitzkyGolay[src=0,sub=2]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 2304
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 4
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          error_score: .nan
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$9f79d59455ab:0
        - 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$9f79d59455ab:1
        - 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$9f79d59455ab:0
          1: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$9f79d59455ab:1
          2: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$9f79d59455ab:0
            - 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$9f79d59455ab:1
            - 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0431_PLS_PP_SELECTION_NO_SAVE_e4c9b2$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 606.966495513916
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 2304
      output_shape:
      - 60
      - 2304
      input_features_shape:
      - - 60
        - 4
        - 576
      output_features_shape:
      - - 60
        - 4
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: raw|Detr|Gauss|SG
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_e4c9b2
      n_steps: 6
      n_artifacts: 7
