schema_version: '2.0'
uid: b738652f-065b-4e64-9589-cacaa376e2f6
pipeline_id: 0001_SOTA_137acf
name: SOTA_137acf
dataset: poultry_manure_om_ks
created_at: '2026-01-09T14:29:28.830308+00:00'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 4
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0001_SOTA_137acf$bb12ee38a89c:all
    content_hash: sha256:125d94dee500492a3bdb8dd8b9fa106b8b2b34e5f42944e4b15d55960ffb73d1
    path: transformer_ASLSBaseline_125d94dee500.joblib
    chain_path: s1.ASLSBaseline[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 1
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: ASLSBaseline
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 216
    created_at: '2026-01-09T14:29:28.877841+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$2865afbbfc1d:all
    content_hash: sha256:d9085eb1080e2b3b31452ce8078642f68ef05b827e9f3c533af6a2c0c858fcc6
    path: encoder_StandardScaler_d9085eb1080e.joblib
    chain_path: s2.y_StandardScaler[sub=1]
    source_index: null
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 2
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: StandardScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 439
    created_at: '2026-01-09T14:29:28.916444+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$b3c264a83f45:all
    content_hash: sha256:b81dc395d1dd80940342c9d3237f852b94dbd4704afba86f452dc9b2bf4d63c4
    path: transformer_StandardScaler_b81dc395d1dd.joblib
    chain_path: s3.StandardScaler[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 3
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: StandardScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 21264
    created_at: '2026-01-09T14:29:28.928181+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$900033a82811:all
    content_hash: sha256:6f23e136a8ce5f96ba80df352cb0b412ddeae789536a00979df98d0c404ac4e5
    path: transformer_PCA_6f23e136a8ce.joblib
    chain_path: s5.PCA[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: PCA
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 190775
    created_at: '2026-01-09T14:29:28.996201+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$c5f06284fcbc:0
    content_hash: sha256:0826c21254497b43540685d0d6061f8aea61a3edd72fd5688a566f6b5ef7c836
    path: model_TabPFNRegressor_0826c2125449.pkl
    chain_path: s6.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 41109744
    created_at: '2026-01-09T14:29:33.903696+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$c5f06284fcbc:1
    content_hash: sha256:b152a1ecfdfcf44a933bea9adcf566d0647c3c9e2cc9246c462aae898d3e1e01
    path: model_TabPFNRegressor_b152a1ecfdfc.pkl
    chain_path: s6.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 41112304
    created_at: '2026-01-09T14:29:33.959746+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$c5f06284fcbc:2
    content_hash: sha256:03474a42f23eacf50cfb6fa2ac2db63296a1ff40a835c013215e89cfc87e97f3
    path: model_TabPFNRegressor_03474a42f23e.pkl
    chain_path: s6.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 41112304
    created_at: '2026-01-09T14:29:34.014126+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  8b2f0f0f-fbc:
    trace_id: 8b2f0f0f-fbc
    pipeline_uid: 0001_SOTA_137acf
    created_at: '2026-01-09T14:29:28.831745+00:00'
    steps:
    - step_index: 1
      operator_type: transform
      operator_class: ASLSBaseline
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$bb12ee38a89c:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$bb12ee38a89c:all
        by_source:
          0:
          - 0001_SOTA_137acf$bb12ee38a89c:all
        by_chain:
          s1.ASLSBaseline[src=0,sub=0]: 0001_SOTA_137acf$bb12ee38a89c:all
        metadata:
          class_name: ASLSBaseline
          name: ASLSBaseline_1
      branch_path: []
      branch_name: ''
      duration_ms: 50.86517333984375
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s1.ASLSBaseline[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 144
      - 1003
      output_shape:
      - 144
      - 1003
      input_features_shape:
      - - 144
        - 1
        - 1003
      output_features_shape:
      - - 144
        - 1
        - 1003
    - step_index: 2
      operator_type: y_processing
      operator_class: StandardScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.StandardScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$2865afbbfc1d:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$2865afbbfc1d:all
        by_source: {}
        by_chain:
          s2.y_StandardScaler[sub=1]: 0001_SOTA_137acf$2865afbbfc1d:all
        metadata:
          class_name: StandardScaler
          name: y_StandardScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 39.83044624328613
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s2.y_StandardScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 144
      - 1003
      output_shape:
      - 144
      - 1003
      input_features_shape:
      - - 144
        - 1
        - 1003
      output_features_shape:
      - - 144
        - 1
        - 1003
    - step_index: 3
      operator_type: transform
      operator_class: StandardScaler
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$b3c264a83f45:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$b3c264a83f45:all
        by_source:
          0:
          - 0001_SOTA_137acf$b3c264a83f45:all
        by_chain:
          s3.StandardScaler[src=0,sub=0]: 0001_SOTA_137acf$b3c264a83f45:all
        metadata:
          class_name: StandardScaler
          name: StandardScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 20.672321319580078
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.StandardScaler[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 144
      - 1003
      output_shape:
      - 144
      - 1003
      input_features_shape:
      - - 144
        - 1
        - 1003
      output_features_shape:
      - - 144
        - 1
        - 1003
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 21.826744079589844
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 144
      - 1003
      output_shape:
      - 144
      - 1003
      input_features_shape:
      - - 144
        - 1
        - 1003
      output_features_shape:
      - - 144
        - 1
        - 1003
    - step_index: 5
      operator_type: operator
      operator_class: PCA
      operator_config:
        class: sklearn.decomposition._pca.PCA
        params:
          n_components: 0.99
          whiten: true
          random_state: 42
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$900033a82811:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$900033a82811:all
        by_source:
          0:
          - 0001_SOTA_137acf$900033a82811:all
        by_chain:
          s5.PCA[src=0,sub=0]: 0001_SOTA_137acf$900033a82811:all
        metadata:
          class_name: PCA
          name: PCA_1
      branch_path: []
      branch_name: ''
      duration_ms: 70.50395011901855
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.PCA[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 144
      - 1003
      output_shape:
      - 144
      - 50
      input_features_shape:
      - - 144
        - 1
        - 1003
      output_features_shape:
      - - 144
        - 1
        - 50
    - step_index: 6
      operator_type: model
      operator_class: TabPFNRegressor
      operator_config:
        model:
          class: tabpfn.regressor.TabPFNRegressor
          params:
            n_estimators: 4
            model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
            device: cpu
            ignore_pretraining_limits: true
            random_state: 42
        name: TabPFN-real
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$c5f06284fcbc:0
        - 0001_SOTA_137acf$c5f06284fcbc:1
        - 0001_SOTA_137acf$c5f06284fcbc:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0001_SOTA_137acf$c5f06284fcbc:0
          1: 0001_SOTA_137acf$c5f06284fcbc:1
          2: 0001_SOTA_137acf$c5f06284fcbc:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$c5f06284fcbc:0
            - 0001_SOTA_137acf$c5f06284fcbc:1
            - 0001_SOTA_137acf$c5f06284fcbc:2
        by_source: {}
        by_chain:
          s6.TabPFNRegressor[sub=0]: 0001_SOTA_137acf$c5f06284fcbc:2
        metadata:
          class_name: TabPFNRegressor
          custom_name: TabPFN-real
      branch_path: []
      branch_name: ''
      duration_ms: 10224.890947341919
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.TabPFNRegressor[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 144
      - 50
      output_shape:
      - 144
      - 50
      input_features_shape:
      - - 144
        - 1
        - 50
      output_features_shape:
      - - 144
        - 1
        - 50
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: ASLSBaseline>Std>PCA
    metadata:
      dataset: poultry_manure_om_ks
      config_name: SOTA_137acf
      n_steps: 6
      n_artifacts: 7
