uid: c92ebf1c-9cf8-4441-9e4c-e1e4d5783da6
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: wood_density_402_olale
created_at: '2025-12-12T07:51:41.043578+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:c420e3c9c457cb869a0040d36665a950c74a835cc5d0f10428fe7653df5fd30e
  name: ASLSBaseline_1
  path: ASLSBaseline_c420e3.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2025-12-12T07:51:41.158692+00:00'
  step: 1
- hash: sha256:8795fd2c5508ebeb1bd85978d44945cd3497e627795fb1b607d1d27af02a10b2
  name: y_StandardScaler
  path: StandardScaler_8795fd.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 449
  saved_at: '2025-12-12T07:51:41.333082+00:00'
  step: 4
- hash: sha256:5c7b91a3b0f7550a5bfec04484480180900040ea334f2e7c596d584d2e04e109
  name: StandardScaler_1
  path: StandardScaler_5c7b91.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 22554
  saved_at: '2025-12-12T07:51:41.339943+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T07:51:41.353382+00:00'
  step: 6
- hash: sha256:5553a5e6492689bb6bb16c2c698b28f8c32fbbe33fe75207bfd1381ed6b7b5d2
  name: PCA_1
  path: PCA_5553a5.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 57825
  saved_at: '2025-12-12T07:51:41.410578+00:00'
  step: 7
- hash: sha256:91f0e8363b0bb23d78c8de11263893739ce6a12c7a47a5149639785e2484599f
  name: StandardScaler_1
  path: StandardScaler_91f0e8.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 690
  saved_at: '2025-12-12T07:51:41.437822+00:00'
  step: 8
- hash: sha256:f77e20d7f94955f5b1424ad147de142b39fabc806b8028933399929606754e97
  name: PowerTransformer_1
  path: PowerTransformer_f77e20.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 965
  saved_at: '2025-12-12T07:51:41.490210+00:00'
  step: 9
- hash: sha256:41740f06e597de4856414507b5762f2eb702f538e2467cc440682e8191981c94
  name: AutoGluon_1.pkl
  path: TabularPredictor_41740f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 14864
  saved_at: '2025-12-12T07:51:51.769299+00:00'
  step: 10
- hash: sha256:85e437690a5ed83390c4f0573e11beff6d5c2ee39b04ae0260ce665d50091076
  name: AutoGluon_2.pkl
  path: TabularPredictor_85e437.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 14873
  saved_at: '2025-12-12T07:51:51.769596+00:00'
  step: 10
- hash: sha256:9c6ad1deb7221f6de9f7b798c20fb508b0ca148587e784176268d8f1addbf7dd
  name: AutoGluon_3.pkl
  path: TabularPredictor_9c6ad1.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 14864
  saved_at: '2025-12-12T07:51:51.769850+00:00'
  step: 10
- hash: sha256:ab8995cfac9720a0d302659a7f626310e893ba8893d812340ae9e79c9a07f2db
  name: TabPFN_1.pkl
  path: TabPFNRegressor_ab8995.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41414706
  saved_at: '2025-12-12T07:52:07.589255+00:00'
  step: 11
- hash: sha256:ea4a0b9eb1a81ad3c6acd009b1313931b235742010eadcb23902e9f79e95dc66
  name: TabPFN_2.pkl
  path: TabPFNRegressor_ea4a0b.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41414714
  saved_at: '2025-12-12T07:52:07.636118+00:00'
  step: 11
- hash: sha256:07e7e774f7bf47363337640bcd129c56ec3b1e03e026a7a0096bc9948a2bc6d3
  name: TabPFN_3.pkl
  path: TabPFNRegressor_07e7e7.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41414714
  saved_at: '2025-12-12T07:52:07.682774+00:00'
  step: 11
- hash: sha256:c76b71d5449a53b7c1c37139219e0858bcf1700830b6f7b996d75640518d56b4
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_c76b71.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41414747
  saved_at: '2025-12-12T07:52:38.888557+00:00'
  step: 12
- hash: sha256:d09292e2d422dd52c397da8ba0ae2886dbdac852eb51bcd1110c156559cc0958
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_d09292.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41414751
  saved_at: '2025-12-12T07:52:38.936450+00:00'
  step: 12
- hash: sha256:059267b4635ca720c8563d4767fdb99b7fde3d4b303a7f504fe5fb41a865d998
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_059267.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41414751
  saved_at: '2025-12-12T07:52:38.984315+00:00'
  step: 12
predictions: []
