schema_version: '2.0'
uid: 36e58f59-8e6c-4a19-9647-6bdf0c80e184
pipeline_id: 0001_SOTA_033cb7
name: SOTA_033cb7
dataset: alpine_n_552_ks
created_at: '2026-01-07T17:13:15.970896+00:00'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0001_SOTA_033cb7$bb12ee38a89c:all
    content_hash: sha256:6fad93a0e497c69beabeda8f5151735441edf9b93933632b811f33b2a2f357f5
    path: transformer_ASLSBaseline_6fad93a0e497.joblib
    chain_path: s1.ASLSBaseline[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 1
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: ASLSBaseline
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 215
    created_at: '2026-01-07T17:13:16.268774+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_033cb7$dfc251e3a6b4:all
    content_hash: sha256:fb549432453d1863282837c8e17ef0374f591cc4798658a7a0dcd9c3038a13b8
    path: transformer_PCA_fb549432453d.joblib
    chain_path: s3.PCA[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 3
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: PCA
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 146086
    created_at: '2026-01-07T17:13:16.735287+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_033cb7$9d98c9f5abc5:0
    content_hash: sha256:d092e090174f059d6644dc10c530d84e01c4abcf72552ca85449d33d063b189d
    path: model_TabPFNRegressor_d092e090174f.pkl
    chain_path: s4.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 4
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 42157180
    created_at: '2026-01-07T17:13:44.674635+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_033cb7$9d98c9f5abc5:1
    content_hash: sha256:6dd79b4286102e067ee6c03bb146818852a06b68e2d09488e5614039eb400276
    path: model_TabPFNRegressor_6dd79b428610.pkl
    chain_path: s4.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 4
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 42160908
    created_at: '2026-01-07T17:13:44.722883+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_033cb7$9d98c9f5abc5:2
    content_hash: sha256:993c454e30d4da4bc2cbe6f86f6dbd5f06e8141168412e1dbd2e891d70581fc4
    path: model_TabPFNRegressor_993c454e30d4.pkl
    chain_path: s4.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 4
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 42160918
    created_at: '2026-01-07T17:13:44.827329+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  0ac6790d-73c:
    trace_id: 0ac6790d-73c
    pipeline_uid: 0001_SOTA_033cb7
    created_at: '2026-01-07T17:13:15.971626+00:00'
    steps:
    - step_index: 1
      operator_type: transform
      operator_class: ASLSBaseline
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_033cb7$bb12ee38a89c:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_033cb7$bb12ee38a89c:all
        by_source:
          0:
          - 0001_SOTA_033cb7$bb12ee38a89c:all
        by_chain:
          s1.ASLSBaseline[src=0,sub=0]: 0001_SOTA_033cb7$bb12ee38a89c:all
        metadata:
          class_name: ASLSBaseline
          name: ASLSBaseline_1
      branch_path: []
      branch_name: ''
      duration_ms: 307.65771865844727
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s1.ASLSBaseline[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 552
      - 2151
      output_shape:
      - 552
      - 2151
      input_features_shape:
      - - 552
        - 1
        - 2151
      output_features_shape:
      - - 552
        - 1
        - 2151
    - step_index: 2
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 345.74437141418457
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 552
      - 2151
      output_shape:
      - 552
      - 2151
      input_features_shape:
      - - 552
        - 1
        - 2151
      output_features_shape:
      - - 552
        - 1
        - 2151
    - step_index: 3
      operator_type: operator
      operator_class: PCA
      operator_config:
        class: sklearn.decomposition._pca.PCA
        params:
          n_components: 0.99
          whiten: true
          random_state: 42
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_033cb7$dfc251e3a6b4:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_033cb7$dfc251e3a6b4:all
        by_source:
          0:
          - 0001_SOTA_033cb7$dfc251e3a6b4:all
        by_chain:
          s3.PCA[src=0,sub=0]: 0001_SOTA_033cb7$dfc251e3a6b4:all
        metadata:
          class_name: PCA
          name: PCA_1
      branch_path: []
      branch_name: ''
      duration_ms: 139.65249061584473
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.PCA[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 552
      - 2151
      output_shape:
      - 552
      - 17
      input_features_shape:
      - - 552
        - 1
        - 2151
      output_features_shape:
      - - 552
        - 1
        - 17
    - step_index: 4
      operator_type: model
      operator_class: TabPFNRegressor
      operator_config:
        model:
          class: tabpfn.regressor.TabPFNRegressor
          params:
            n_estimators: 16
            model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
            device: cpu
            ignore_pretraining_limits: true
            random_state: 42
        name: TabPFN-real
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_033cb7$9d98c9f5abc5:0
        - 0001_SOTA_033cb7$9d98c9f5abc5:1
        - 0001_SOTA_033cb7$9d98c9f5abc5:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0001_SOTA_033cb7$9d98c9f5abc5:0
          1: 0001_SOTA_033cb7$9d98c9f5abc5:1
          2: 0001_SOTA_033cb7$9d98c9f5abc5:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_033cb7$9d98c9f5abc5:0
            - 0001_SOTA_033cb7$9d98c9f5abc5:1
            - 0001_SOTA_033cb7$9d98c9f5abc5:2
        by_source: {}
        by_chain:
          s4.TabPFNRegressor[sub=0]: 0001_SOTA_033cb7$9d98c9f5abc5:2
        metadata:
          class_name: TabPFNRegressor
          custom_name: TabPFN-real
      branch_path: []
      branch_name: ''
      duration_ms: 62177.4480342865
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s4.TabPFNRegressor[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 552
      - 17
      output_shape:
      - 552
      - 17
      input_features_shape:
      - - 552
        - 1
        - 17
      output_features_shape:
      - - 552
        - 1
        - 17
    model_step_index: 4
    fold_weights: null
    preprocessing_chain: ASLSBaseline>PCA
    metadata:
      dataset: alpine_n_552_ks
      config_name: SOTA_033cb7
      n_steps: 4
      n_artifacts: 5
