schema_version: '2.0'
uid: d3b63eaa-90ed-4686-a4db-aa4ca54d2937
pipeline_id: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd
name: PLS_PP_SELECTION_NO_SAVE_9b95fd
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:46:19.988361+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: null
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - nirs4all.operators.transforms.scalers.StandardNormalVariate
    - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
      params:
        window_length: 15
    - null
    - nirs4all.operators.transforms.nirs.Haar
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      error_score: .nan
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: null
- _cartesian_:
  - nirs4all.operators.transforms.scalers.StandardNormalVariate
  - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
    params:
      window_length: 15
  - null
  - nirs4all.operators.transforms.nirs.Haar
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:46:20.011835+00:00'
    params: {}
    version: 3
  - artifact_id: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$6e21be876a4d:all
    content_hash: sha256:f1b0d49d100fdce0b1f766631a2fc34c1b2477ed43ee4a120b8aedc3581c1d26
    path: transformer_StandardNormalVariate_f1b0d49d100f.joblib
    chain_path: s5.StandardNormalVariate[src=0,sub=0]
    source_index: 0
    pipeline_id: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: StandardNormalVariate
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 132
    created_at: '2026-01-08T17:46:20.025517+00:00'
    params: {}
    version: 3
  - artifact_id: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$eeb09d32a26b:all
    content_hash: sha256:c90a6e998d89e802fdc8ae5af3e9cd7288130360151139484ffc6499b3403f5a
    path: transformer_SavitzkyGolay_c90a6e998d89.joblib
    chain_path: s5.SavitzkyGolay[src=0,sub=1]
    source_index: 0
    pipeline_id: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: SavitzkyGolay
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 137
    created_at: '2026-01-08T17:46:20.027369+00:00'
    params: {}
    version: 3
  - artifact_id: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$f395c82b4d90:all
    content_hash: sha256:2237293e62d5640680cb91d003382cdd194cbcc1496aee2fd76192fa547a78be
    path: transformer_Haar_2237293e62d5.joblib
    chain_path: s5.Haar[src=0,sub=2]
    source_index: 0
    pipeline_id: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd
    branch_path: []
    step_index: 5
    substep_index: 2
    fold_id: null
    artifact_type: transformer
    class_name: Haar
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 112
    created_at: '2026-01-08T17:46:20.029642+00:00'
    params: {}
    version: 3
  - artifact_id: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$9f79d59455ab:0
    content_hash: sha256:a80f40ea911481df9eabbfb5c8891a22e8813789419b0d763f98541fb9ee4d3d
    path: model_PLSRegression_a80f40ea9114.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 156802
    created_at: '2026-01-08T17:46:20.593709+00:00'
    params: {}
    version: 3
  - artifact_id: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$9f79d59455ab:1
    content_hash: sha256:65483e9372c30cd89dfade13e41dcbc6c8be39187789ac402a6cfba826a51470
    path: model_PLSRegression_65483e9372c3.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 157209
    created_at: '2026-01-08T17:46:20.599683+00:00'
    params: {}
    version: 3
  - artifact_id: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$9f79d59455ab:2
    content_hash: sha256:4378643f370a711d128a9893142fe57c81bf7c583fb9f9c6b9d3e38f993e0ae1
    path: model_PLSRegression_4378643f370a.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 157166
    created_at: '2026-01-08T17:46:20.605716+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  111d4ce6-aff:
    trace_id: 111d4ce6-aff
    pipeline_uid: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd
    created_at: '2026-01-08T17:46:19.989436+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 2.1965503692626953
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 1.7232894897460938
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 24.06787872314453
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 5.302906036376953
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: StandardNormalVariate, SavitzkyGolay, None (+1)
      operator_config:
        feature_augmentation:
        - nirs4all.operators.transforms.scalers.StandardNormalVariate
        - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
          params:
            window_length: 15
        - null
        - nirs4all.operators.transforms.nirs.Haar
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$6e21be876a4d:all
        - 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$eeb09d32a26b:all
        - 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$f395c82b4d90:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$6e21be876a4d:all
            - 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$eeb09d32a26b:all
            - 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$f395c82b4d90:all
        by_source:
          0:
          - 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$6e21be876a4d:all
          - 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$eeb09d32a26b:all
          - 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$f395c82b4d90:all
        by_chain:
          s5.StandardNormalVariate[src=0,sub=0]: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$6e21be876a4d:all
          s5.SavitzkyGolay[src=0,sub=1]: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$eeb09d32a26b:all
          s5.Haar[src=0,sub=2]: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$f395c82b4d90:all
        metadata:
          class_name: Haar
          name: Haar_3
      branch_path: []
      branch_name: ''
      duration_ms: 17.182111740112305
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.StandardNormalVariate[src=0,sub=0]
      - s5.SavitzkyGolay[src=0,sub=1]
      - s5.Haar[src=0,sub=2]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 2304
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 4
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          error_score: .nan
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$9f79d59455ab:0
        - 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$9f79d59455ab:1
        - 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$9f79d59455ab:0
          1: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$9f79d59455ab:1
          2: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$9f79d59455ab:0
            - 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$9f79d59455ab:1
            - 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0287_PLS_PP_SELECTION_NO_SAVE_9b95fd$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 595.7436561584473
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 2304
      output_shape:
      - 60
      - 2304
      input_features_shape:
      - - 60
        - 4
        - 576
      output_features_shape:
      - - 60
        - 4
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: raw|SNV|SG|Haar
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_9b95fd
      n_steps: 6
      n_artifacts: 7
