#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Adaptive diverse selection via graph pruning (with visualizations and Markdown report).

What this script does
---------------------
1) Builds per-(model, preprocessing) performance profiles across datasets (normalized RRMSE).
2) Tests pairwise profile correlation with a one-sided Spearman permutation test (H1: rho > 0).
   Applies BH-FDR across all tested pairs to identify significant positive-correlation edges.
3) Iterates candidates in order of increasing median normalized RRMSE (best-first).
   For each candidate j and the current kept set S:
     * Identify neighbors k in S significantly (FDR) positively correlated with j.
     * For those k, run an exact one-sided sign test on Δ = R_j - R_k with H1: median(Δ) > 0
       (candidate strictly worse). Apply BH-FDR within the comparisons of the same j.
     * If any k yields a significant result after FDR (i.e., j is worse than at least one correlated k),
       prune j; otherwise keep j.
4) Produces CSVs + figures:
   * decisions CSV (kept/pruned + reasons)
   * Spearman rho matrix CSV
   * FDR-adjusted p-values (correlation) CSV
   * Heatmap of significant positive correlations (PNG)
   * Network graph (PNG) with nodes colored by decision
   * Markdown report summarizing pruning relations with rho and q-values

Author: Generated by ChatGPT (comments in English).
"""

from __future__ import annotations

import os
import re
import argparse
from typing import List, Tuple, Optional, Dict
import numpy as np
import pandas as pd

# Use a non-interactive backend for batch usage
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

# Network visualization (usually available)
try:
    import networkx as nx
    NETWORKX_AVAILABLE = True
except Exception:
    NETWORKX_AVAILABLE = False

# ---------------- I/O and discovery defaults ----------------

DEFAULT_ROOT = "Results/assoc_pp_model"
FILENAME_PREFIX = "results_"
# Exclude result CSV filenames that contain any of these substrings
FILENAME_EXCLUDE_SUBSTR = ["NICON", "CNN", "Ridge", "LGBM", "PLS"]

MODEL_COL = "Model"
EXCLUDE_PREPS = {"PCA"}   # preprocessings to drop globally (optional)

# ---------------- Stats / selection hyperparameters ----------------

ALPHA = 0.05                     # target FDR level
N_PERM = 1                   # permutations for Spearman one-sided test (H1: rho > 0)
RANDOM_SEED = 42                 # reproducibility
MIN_OVERLAP = 3                  # min datasets overlap to test correlation or performance
NORMALIZE_PER_DATASET = True     # normalize RRMSE per dataset by the best value (min)
REPORT_DIR = "Results/assoc_pp_model/All_datasets/Pipeline_graph"
REPORT_PREFIX = "adaptive_diverse_selection"

# ---------------- Utilities ----------------

def discover_dataset_csvs(root: str) -> List[Tuple[str, str]]:
    """Find (dataset_name, csv_path) where csv file starts with FILENAME_PREFIX and ends with .csv,
    and does NOT contain any excluded substring.
    """
    pairs: List[Tuple[str, str]] = []
    if not os.path.isdir(root):
        print(f"[WARN] Root not found: {root}")
        return pairs
    for ds in sorted(os.listdir(root)):
        ds_dir = os.path.join(root, ds)
        if not os.path.isdir(ds_dir):
            continue
        cands = [f for f in os.listdir(ds_dir)
                 if f.startswith(FILENAME_PREFIX) and f.lower().endswith(".csv")]
        cands = [f for f in cands if not any(excl in f for excl in FILENAME_EXCLUDE_SUBSTR)]
        if not cands:
            continue
        cands.sort()
        pairs.append((ds, os.path.join(ds_dir, cands[0])))
    return pairs


def benjamini_hochberg(pvals: List[Optional[float]]) -> List[Optional[float]]:
    """BH-FDR adjustment. None values are preserved."""
    n = len(pvals)
    idx_p = [(i, p) for i, p in enumerate(pvals) if p is not None and np.isfinite(p)]
    m = len(idx_p)
    if m == 0:
        return [None] * n
    # sort ascending
    idx_p.sort(key=lambda t: t[1])
    qs_sorted = [min(1.0, p * m / (rank + 1)) for rank, (_, p) in enumerate(idx_p)]
    # enforce monotonicity (non-increasing when traversed reversed)
    for k in range(m - 2, -1, -1):
        qs_sorted[k] = min(qs_sorted[k], qs_sorted[k + 1])
    qvals = [None] * n
    for (pos, (i, _)) in enumerate(idx_p):
        qvals[i] = qs_sorted[pos]
    return qvals


def exact_sign_test_one_sided_greater(diffs: np.ndarray) -> Tuple[Optional[float], int, int]:
    """Exact one-sided sign test for H1: median(diffs) > 0.
    Removes ties (diff == 0). Returns (p_value, n_eff, n_pos).
    p-value = P[Binom(n_eff, 0.5) >= n_pos]
    """
    y = diffs[np.isfinite(diffs)]
    y = y[y != 0.0]
    n_eff = y.size
    if n_eff == 0:
        return None, 0, 0
    n_pos = int(np.sum(y > 0))
    # exact binomial tail
    from math import comb
    p = sum(comb(n_eff, k) * (0.5 ** n_eff) for k in range(n_pos, n_eff + 1))
    return float(p), n_eff, n_pos


def spearman_rho_one_sided_test(x: np.ndarray, y: np.ndarray, n_perm: int, rng: np.random.Generator) -> Tuple[float, float, int]:
    """
    Hybrid one-sided Spearman correlation test (H1: rho > 0).

    - If n < 30 → performs a permutation test with n_perm iterations (Monte Carlo exact test).
    - If n >= 30 → uses the asymptotic p-value from scipy.stats.spearmanr (one-sided).
    Returns (rho_obs, p_value, n_used).
    """
    from scipy.stats import spearmanr

    mask = np.isfinite(x) & np.isfinite(y)
    x0, y0 = x[mask], y[mask]
    n_used = x0.size
    if n_used < MIN_OVERLAP:
        return np.nan, np.nan, n_used

    rho_obs, p_two_sided = spearmanr(x0, y0)
    if not np.isfinite(rho_obs):
        return np.nan, np.nan, n_used

    # Case 1: small sample -> permutation test
    if n_used < 30:
        cnt = 0
        for _ in range(n_perm):
            y_perm = rng.permutation(y0)
            rho_perm, _ = spearmanr(x0, y_perm)
            if np.isfinite(rho_perm) and rho_perm >= rho_obs:
                cnt += 1
        p_one = (cnt + 1.0) / (n_perm + 1.0)
        return float(rho_obs), float(p_one), n_used

    # Case 2: large sample -> asymptotic Spearman (convert to one-sided)
    # scipy.stats.spearmanr returns a two-sided p-value
    p_one = p_two_sided / 2 if rho_obs > 0 else 1 - (p_two_sided / 2)
    return float(rho_obs), float(p_one), n_used


# ---------------- Data assembly ----------------

def load_long_table(csv_path: str) -> pd.DataFrame:
    """Load a result CSV where rows are models and columns are preprocessings.
    Returns a long df with columns: [model, prep, rrmse].
    """
    wide = pd.read_csv(csv_path)
    if MODEL_COL not in wide.columns:
        raise ValueError(f"Missing '{MODEL_COL}' in {csv_path}")
    long = wide.melt(id_vars=[MODEL_COL], var_name="prep", value_name="rrmse").rename(columns={MODEL_COL: "model"})
    long["rrmse"] = pd.to_numeric(long["rrmse"], errors="coerce")
    long = long.dropna(subset=["rrmse"])
    # Drop globally excluded preprocessings
    if EXCLUDE_PREPS:
        long = long[~long["prep"].isin(EXCLUDE_PREPS)]
    return long


def build_profiles(root: str) -> pd.DataFrame:
    """Construct a matrix with rows=(model, prep), columns=datasets, values=normalized RRMSE."""
    ds_csvs = discover_dataset_csvs(root)
    rows = []
    for ds, path in ds_csvs:
        try:
            df = load_long_table(path)
        except Exception as e:
            print(f"[WARN] Skipping {path}: {e}")
            continue
        # Normalize per dataset by global best (min RRMSE over all (model,prep) for this dataset)
        best = df["rrmse"].min()
        if best is None or not np.isfinite(best) or best <= 0:
            df["rrmse_norm"] = df["rrmse"]
        else:
            df["rrmse_norm"] = df["rrmse"] / best

        # Pivot: index=(model,prep), single value column
        piv = df.pivot_table(index=["model", "prep"], values="rrmse_norm", aggfunc="mean")

        # Iterate properly over rows of the pivot
        for (m, p), row in piv.iterrows():
            rows.append({"model": m, "prep": p, "dataset": ds, "value": float(row["rrmse_norm"])})

    tidy = pd.DataFrame(rows)
    if tidy.empty:
        return pd.DataFrame()
    profiles = tidy.pivot_table(index=["model", "prep"], columns="dataset", values="value", aggfunc="mean")
    return profiles


# ---------------- Pruning algorithm ----------------

def adaptive_pruning(profiles: pd.DataFrame,
                     alpha: float = ALPHA,
                     n_perm: int = N_PERM,
                     seed: int = RANDOM_SEED) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Perform adaptive pruning:
    - Compute one-sided Spearman permutation p-values for all pairs (i<j); BH-FDR across all.
    - Iterate candidates sorted by median profile (ascending). Keep j unless:
        exists k in kept such that:
          (i) corr_sig(j,k) True after FDR  AND
          (ii) sign-test (H1: median Δ > 0) significant after BH-FDR within j.
    Returns:
      decisions_df: per (model,prep) keep/prune + reasons and culprit (if pruned),
      rho_df: Spearman rho matrix,
      q_df: BH-FDR adjusted p-value matrix for correlation (upper triangle mirrored).
    """
    rng = np.random.default_rng(seed)
    items = list(profiles.index)
    n = len(items)

    # 1) Pairwise correlation tests (one-sided, rho > 0)
    rho_mat = np.full((n, n), np.nan, dtype=float)
    p_mat = np.full((n, n), np.nan, dtype=float)
    for i in range(n):
        xi = profiles.iloc[i].to_numpy(dtype=float)
        for j in range(i + 1, n):
            yj = profiles.iloc[j].to_numpy(dtype=float)
            rho, p, n_used = spearman_rho_one_sided_test(xi, yj, n_perm, rng)
            rho_mat[i, j] = rho
            p_mat[i, j] = p

    # BH-FDR across all tested pairs
    p_list = [p_mat[i, j] for i in range(n) for j in range(i + 1, n)]
    q_list = benjamini_hochberg(p_list)
    q_iter = iter(q_list)
    q_mat = np.full((n, n), np.nan, dtype=float)
    for i in range(n):
        for j in range(i + 1, n):
            q_mat[i, j] = next(q_iter)

    # Symmetrize rho and q
    for i in range(n):
        for j in range(i + 1, n):
            rho_mat[j, i] = rho_mat[i, j]
            q_mat[j, i] = q_mat[i, j]

    rho_df = pd.DataFrame(rho_mat, index=items, columns=items)
    q_df = pd.DataFrame(q_mat, index=items, columns=items)

    # 2) Order candidates by median performance (ascending)
    med = profiles.median(axis=1)
    order = med.sort_values(ascending=True).index.tolist()

    kept: List[Tuple[str, str]] = []
    decisions = []

    for j in order:
        j_idx = items.index(j)
        # correlated neighbors already kept (FDR significant positive correlation)
        neighbors = []
        for k in kept:
            k_idx = items.index(k)
            qjk = q_df.iloc[j_idx, k_idx]
            rhojk = rho_df.iloc[j_idx, k_idx]
            if np.isfinite(qjk) and qjk < alpha and np.isfinite(rhojk) and rhojk > 0:
                neighbors.append(k)

        if not neighbors:
            kept.append(j)
            decisions.append({"model": j[0], "prep": j[1], "status": "kept",
                              "reason": "no_significant_positive_correlation_to_kept",
                              "culprit_model": None, "culprit_prep": None, "culprit_q": None,
                              "median_profile": float(med.loc[j]),
                              "n_neighbors_corrpos": 0})
            continue

        # For those neighbors, run exact sign tests H1: median(Δ) > 0 (candidate worse)
        pvals = []
        details = []
        xj = profiles.loc[j].to_numpy(dtype=float)
        for k in neighbors:
            xk = profiles.loc[k].to_numpy(dtype=float)
            mask = np.isfinite(xj) & np.isfinite(xk)
            if np.sum(mask) < MIN_OVERLAP:
                pvals.append(None)
                details.append((k, None, int(np.sum(mask))))
                continue
            diffs = xj[mask] - xk[mask]
            p, n_eff, n_pos = exact_sign_test_one_sided_greater(diffs)
            pvals.append(p)
            details.append((k, p, n_eff))

        # BH-FDR within the comparisons of the same j
        qvals = benjamini_hochberg(pvals)

        # If any neighbor yields q < alpha, prune j
        prune = False
        culprit = (None, None, None)
        for (k, p, n_eff), q in zip(details, qvals):
            if q is not None and q < alpha:
                prune = True
                culprit = (k[0], k[1], q)
                break

        if prune:
            decisions.append({
                "model": j[0], "prep": j[1], "status": "pruned",
                "reason": f"worse_than_correlated_kept:{culprit[0]}|{culprit[1]}",
                "culprit_model": culprit[0], "culprit_prep": culprit[1], "culprit_q": culprit[2],
                "median_profile": float(med.loc[j]),
                "n_neighbors_corrpos": int(len(neighbors))
            })
        else:
            kept.append(j)
            decisions.append({
                "model": j[0], "prep": j[1], "status": "kept",
                "reason": "not_significantly_worse_than_correlated_kept",
                "culprit_model": None, "culprit_prep": None, "culprit_q": None,
                "median_profile": float(med.loc[j]),
                "n_neighbors_corrpos": int(len(neighbors))
            })

    decisions_df = pd.DataFrame(decisions).sort_values(
        ["status", "median_profile", "model", "prep"]
    ).reset_index(drop=True)
    return decisions_df, rho_df, q_df


# ---------------- Visualizations & report ----------------

def plot_significant_corr_heatmap(rho_df: pd.DataFrame, q_df: pd.DataFrame,
                                  alpha: float, out_path: str):
    """Plot a heatmap of rho where q < alpha, NaN otherwise."""
    mask = ~(q_df < alpha)
    rho_sig = rho_df.mask(mask)  # keep only significant entries
    plt.figure(figsize=(max(8, 0.25 * rho_sig.shape[1]), max(6, 0.25 * rho_sig.shape[0])))
    sns.heatmap(rho_sig, cmap="viridis", vmin=0, vmax=1, linewidths=0.3, linecolor="white")
    plt.title(f"Significant positive Spearman correlations (q < {alpha})")
    plt.tight_layout()
    plt.savefig(out_path)
    plt.close()


def plot_network(rho_df: pd.DataFrame, q_df: pd.DataFrame,
                 decisions_df: pd.DataFrame, alpha: float, out_path: str, seed: int = 42):
    """Plot a network graph with nodes colored by keep/prune and edges for significant positive correlations."""
    if not NETWORKX_AVAILABLE:
        print("[WARN] networkx not available; skipping network plot.")
        return

    G = nx.Graph()
    # Node attributes from decisions
    status_map = {}
    for _, row in decisions_df.iterrows():
        node = (row["model"], row["prep"])
        G.add_node(node)
        status_map[node] = row["status"]

    # Edges for significant positive correlations
    items = list(rho_df.index)
    for i in range(len(items)):
        for j in range(i + 1, len(items)):
            rho = rho_df.iloc[i, j]
            q = q_df.iloc[i, j]
            if np.isfinite(rho) and np.isfinite(q) and rho > 0 and q < alpha:
                G.add_edge(items[i], items[j], weight=rho, q=q)

    # Colors
    colors = []
    for node in G.nodes():
        status = status_map.get(node, "kept")
        colors.append("#2ca02c" if status == "kept" else "#d62728")

    # Layout
    np.random.seed(seed)
    pos = nx.spring_layout(G, seed=seed, k=None)

    plt.figure(figsize=(12, 10))
    # Edge widths scaled by rho
    widths = [1 + 3 * G[u][v]["weight"] for u, v in G.edges()]
    nx.draw_networkx_edges(G, pos, width=widths, alpha=0.5, edge_color="#1f77b4")
    nx.draw_networkx_nodes(G, pos, node_color=colors, node_size=500, alpha=0.9)
    # Labels
    labels = {n: f"{n[0]}|{n[1]}" for n in G.nodes()}
    nx.draw_networkx_labels(G, pos, labels=labels, font_size=8)
    plt.title(f"Correlation network (edges: rho>0 & q<{alpha})\nGreen=kept, Red=pruned")
    plt.axis("off")
    plt.tight_layout()
    plt.savefig(out_path, dpi=200)
    plt.close()


def write_markdown_report(decisions_df: pd.DataFrame, rho_df: pd.DataFrame, q_df: pd.DataFrame,
                          alpha: float, out_path: str):
    """Write a Markdown report summarizing kept/pruned items and pruning culprits with stats."""
    kept = decisions_df[decisions_df["status"] == "kept"][["model", "prep", "median_profile"]]
    pruned = decisions_df[decisions_df["status"] == "pruned"][["model", "prep", "reason", "culprit_model", "culprit_prep", "culprit_q"]]

    # Significant edges table
    edges = []
    items = list(rho_df.index)
    for i in range(len(items)):
        for j in range(i + 1, len(items)):
            rho = rho_df.iloc[i, j]
            q = q_df.iloc[i, j]
            if np.isfinite(rho) and np.isfinite(q) and rho > 0 and q < alpha:
                edges.append({
                    "model_i": items[i][0], "prep_i": items[i][1],
                    "model_j": items[j][0], "prep_j": items[j][1],
                    "rho": float(rho), "q": float(q)
                })
    edges_df = pd.DataFrame(edges)
    if not edges_df.empty:
        edges_df = edges_df.sort_values(["q", "rho"], ascending=[True, False])


    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# Adaptive diverse selection — pruning report\n\n")
        f.write(f"- FDR level (alpha): **{alpha}**\n")
        f.write(f"- Items total: **{len(decisions_df)}** | Kept: **{(decisions_df['status']=='kept').sum()}** | Pruned: **{(decisions_df['status']=='pruned').sum()}**\n\n")

        f.write("## Kept items\n\n")
        if kept.empty:
            f.write("_None_\n\n")
        else:
            f.write("| Model | Preprocessing | Median profile |\n|---|---|---|\n")
            for _, r in kept.sort_values("median_profile").iterrows():
                f.write(f"| {r['model']} | {r['prep']} | {r['median_profile']:.4f} |\n")
            f.write("\n")

        f.write("## Pruned items (with culprit)\n\n")
        if pruned.empty:
            f.write("_None_\n\n")
        else:
            f.write("| Model | Preprocessing | Culprit (model|prep) | Culprit q (FDR) | Reason |\n|---|---|---|---|---|\n")
            for _, r in pruned.iterrows():
                cul = f"{r['culprit_model']}|{r['culprit_prep']}" if pd.notna(r['culprit_model']) else "-"
                qv = f"{r['culprit_q']:.3g}" if pd.notna(r['culprit_q']) else "-"
                f.write(f"| {r['model']} | {r['prep']} | {cul} | {qv} | {r['reason']} |\n")
            f.write("\n")

        f.write("## Significant positive-correlation edges (q < alpha)\n\n")
        if edges_df.empty:
            f.write("_None_\n")
        else:
            f.write("| i:model | i:prep | j:model | j:prep | rho | q |\n|---|---|---|---|---:|---:|\n")
            for _, r in edges_df.iterrows():
                f.write(f"| {r['model_i']} | {r['prep_i']} | {r['model_j']} | {r['prep_j']} | {r['rho']:.3f} | {r['q']:.3g} |\n")


# ---------------- Main ----------------

parser = argparse.ArgumentParser(description="Adaptive diverse selection with correlation pruning, figures, and report.")
parser.add_argument("--root", type=str, default=DEFAULT_ROOT, help="Root folder with dataset subfolders.")
parser.add_argument("--alpha", type=float, default=ALPHA, help="FDR / test level.")
parser.add_argument("--permutations", type=int, default=N_PERM, help="Number of permutations for correlation tests.")
parser.add_argument("--min_overlap", type=int, default=MIN_OVERLAP, help="Min datasets overlap to test.")
parser.add_argument("--seed", type=int, default=RANDOM_SEED, help="Random seed.")
parser.add_argument("--report_dir", type=str, default=REPORT_DIR, help="Output directory for reports.")
parser.add_argument("--report_prefix", type=str, default=REPORT_PREFIX, help="Filename prefix for outputs.")
args = parser.parse_args()

ALPHA = args.alpha
N_PERM = args.permutations
MIN_OVERLAP = args.min_overlap

os.makedirs(args.report_dir, exist_ok=True)

profiles = build_profiles(args.root)
if profiles.empty:
    print("[ERROR] No profiles could be built. Check input structure.")

decisions_df, rho_df, q_df = adaptive_pruning(profiles, alpha=args.alpha, n_perm=args.permutations, seed=args.seed)

# Save reports
dec_path = os.path.join(args.report_dir, f"{args.report_prefix}_decisions.csv")
rho_path = os.path.join(args.report_dir, f"{args.report_prefix}_rho.csv")
q_path   = os.path.join(args.report_dir, f"{args.report_prefix}_rho_q.csv")

decisions_df.to_csv(dec_path, index=False)
rho_df.to_csv(rho_path)
q_df.to_csv(q_path)

print(f"[INFO] Decisions saved to: {dec_path}")
print(f"[INFO] Spearman rho matrix saved to: {rho_path}")
print(f"[INFO] FDR-adjusted p-values (correlation) saved to: {q_path}")

# Visualizations
heatmap_path = os.path.join(args.report_dir, f"{args.report_prefix}_rho_sig_heatmap.png")
plot_significant_corr_heatmap(rho_df, q_df, args.alpha, heatmap_path)
print(f"[INFO] Significant-correlation heatmap saved to: {heatmap_path}")

net_path = os.path.join(args.report_dir, f"{args.report_prefix}_network.png")
plot_network(rho_df, q_df, decisions_df, args.alpha, net_path, seed=args.seed)
if os.path.exists(net_path):
    print(f"[INFO] Network graph saved to: {net_path}")

# Markdown report
md_path = os.path.join(args.report_dir, f"{args.report_prefix}_report.md")
write_markdown_report(decisions_df, rho_df, q_df, args.alpha, md_path)
print(f"[INFO] Markdown report saved to: {md_path}")