uid: 4ae182f2-b007-4551-ab5c-c87f51f242cf
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: diesel_v_252_hlb_a
created_at: '2026-01-07T11:16:46.555555+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2026-01-07T11:16:46.597614+00:00'
  step: 1
- hash: sha256:2db77112585c2dceb8be65702870dae8059164e2f51821a9bbbca178facffc88
  name: PCA_1
  path: PCA_2db771.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 6667
  saved_at: '2026-01-07T11:16:46.644599+00:00'
  step: 4
- hash: sha256:5b5cd3e0b02853ccbe91f8e0467b77495855e377f2fcf4598a08696b56244b25
  name: AutoGluon_1.pkl
  path: TabularPredictor_5b5cd3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 10842
  saved_at: '2026-01-07T11:16:58.377888+00:00'
  step: 5
- hash: sha256:272ab8ff973ec055c1ad0a4f904fe874750973d77cb9ff221ac5999876b98aad
  name: AutoGluon_2.pkl
  path: TabularPredictor_272ab8.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 10908
  saved_at: '2026-01-07T11:16:58.378166+00:00'
  step: 5
- hash: sha256:46e8327fcdd6ec01265fa5d531582d36a9347ce64ec3ed543fae6aac7354a1e2
  name: AutoGluon_3.pkl
  path: TabularPredictor_46e832.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 10832
  saved_at: '2026-01-07T11:16:58.378404+00:00'
  step: 5
- hash: sha256:89a74ad5611935bea7ee53534f2f7dad6a129f7bbab5746c923ed452fa4812ee
  name: TabPFN_1.pkl
  path: TabPFNRegressor_89a74a.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41023788
  saved_at: '2026-01-07T11:17:05.018179+00:00'
  step: 6
- hash: sha256:a522dbe24cbe4ad8f16413a9513d27df99370e0c4d566fbf9ecf4a99acea8a16
  name: TabPFN_2.pkl
  path: TabPFNRegressor_a522db.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41024620
  saved_at: '2026-01-07T11:17:05.080668+00:00'
  step: 6
- hash: sha256:6778de70b235673f3e66cde3626906f90b46a041e6bb64d25c9966eaf2a0cb0b
  name: TabPFN_3.pkl
  path: TabPFNRegressor_6778de.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41024620
  saved_at: '2026-01-07T11:17:05.141961+00:00'
  step: 6
- hash: sha256:5d43fd1b380c08993ce1fb3036df6265553e84f6edd704fad6cda288d9f9e8b2
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_5d43fd.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41023825
  saved_at: '2026-01-07T11:17:17.660863+00:00'
  step: 7
- hash: sha256:6836c00f3ee83eec697fab0daad2839fcab1634db5890fd9a9d16f0430bc878c
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_6836c0.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41024657
  saved_at: '2026-01-07T11:17:17.719522+00:00'
  step: 7
- hash: sha256:33816827c082753b6ef2bc27d1f68324bf89f340323bb83f7a48e1853e66c494
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_338168.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41024657
  saved_at: '2026-01-07T11:17:17.777854+00:00'
  step: 7
predictions: []
