uid: d266c1ec-3048-48f2-b7e1-9cdef5641a6a
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: cattle_manure_k2o_ks
created_at: '2026-01-07T09:24:09.460198+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:125d94dee500492a3bdb8dd8b9fa106b8b2b34e5f42944e4b15d55960ffb73d1
  name: ASLSBaseline_1
  path: ASLSBaseline_125d94.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2026-01-07T09:24:09.570883+00:00'
  step: 1
- hash: sha256:f3dbb1ab0948767bb8b88ae5f4acb9b37976f01b62b7152e644b9cd0bc31abc8
  name: PCA_1
  path: PCA_f3dbb1.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 19713
  saved_at: '2026-01-07T09:24:09.652897+00:00'
  step: 4
- hash: sha256:5bb913a6d3d904c076ba8adb62c1605f93467a7c8f4e28bcfeb20fba70515252
  name: AutoGluon_1.pkl
  path: TabularPredictor_5bb913.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11262
  saved_at: '2026-01-07T09:24:21.179303+00:00'
  step: 5
- hash: sha256:998d53432498f2e147fe1cb5d110a8cdbbbe0ed8f69ac9eb9f57e17d9d2fdb5f
  name: AutoGluon_2.pkl
  path: TabularPredictor_998d53.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11262
  saved_at: '2026-01-07T09:24:21.180145+00:00'
  step: 5
- hash: sha256:af48a03f3ab6b899ae2069645692e98bfe49074e831acd47117214a925c26bd8
  name: AutoGluon_3.pkl
  path: TabularPredictor_af48a0.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11262
  saved_at: '2026-01-07T09:24:21.180822+00:00'
  step: 5
- hash: sha256:27c95db2ff6f7fdff97192059e41fa3e3bf79c04614ab86df64271038e72cd71
  name: TabPFN_1.pkl
  path: TabPFNRegressor_27c95d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41082399
  saved_at: '2026-01-07T09:24:29.687983+00:00'
  step: 6
- hash: sha256:c47d8f297925cc9ffcff36e4fc8adc16551aa3bb19c59b2f68cf533c29e73086
  name: TabPFN_2.pkl
  path: TabPFNRegressor_c47d8f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41083423
  saved_at: '2026-01-07T09:24:29.751804+00:00'
  step: 6
- hash: sha256:53a11d0f3ac403eb575e305ed2371e3cd81be6821270ed4cb470d21362098c5a
  name: TabPFN_3.pkl
  path: TabPFNRegressor_53a11d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41083423
  saved_at: '2026-01-07T09:24:29.816351+00:00'
  step: 6
- hash: sha256:07d690e5cce3492cc9b98f6ba46e8dfa8d74032c1fd6f1aa24531d7a4c616e59
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_07d690.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41082436
  saved_at: '2026-01-07T09:24:43.443644+00:00'
  step: 7
- hash: sha256:ee3fda7fcd8643c4a60916bf43c7c3dbbd6ef234d90bbacf5406a5bb56934e05
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_ee3fda.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41083460
  saved_at: '2026-01-07T09:24:43.506626+00:00'
  step: 7
- hash: sha256:3a83b92500a27f5865915a0523c42ca077066aa44b5fa94eb5367d30e61d0cb0
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_3a83b9.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41083460
  saved_at: '2026-01-07T09:24:43.567331+00:00'
  step: 7
predictions: []
