uid: 67ec9c7e-c71c-4019-afa4-bb6d273b6cb6
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: lucas_soc_all_26650_nocitaks
created_at: '2025-12-12T11:08:24.449189+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:4b8c179b0caedba3ee8a4a4945ad287c925324d79180bc4f973c334322e0dd6a
  name: ASLSBaseline_1
  path: ASLSBaseline_4b8c17.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2025-12-12T11:08:49.542243+00:00'
  step: 1
- hash: sha256:d9794e783bb13e178228c993afcc234c8cefe95e984f8661a26b94274e71412f
  name: y_StandardScaler
  path: StandardScaler_d9794e.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 446
  saved_at: '2025-12-12T12:21:11.499902+00:00'
  step: 4
- hash: sha256:7e432f3ce8f8f32b81218a50694a58030740ec38e472b8e5e648e75360e67616
  name: StandardScaler_1
  path: StandardScaler_7e432f.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 95202
  saved_at: '2025-12-12T12:21:12.079860+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T12:21:12.774876+00:00'
  step: 6
- hash: sha256:fee1e5da6e2b37f1850308bc1c30d4590738d62abab523220e94f2c98ae5877b
  name: PCA_1
  path: PCA_fee1e5.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 516503
  saved_at: '2025-12-12T12:21:18.543420+00:00'
  step: 7
- hash: sha256:f7cb759b0569430b766c383e6fe9ac0972df0bbc6d778f8c9449f9561860447a
  name: StandardScaler_1
  path: StandardScaler_f7cb75.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1085
  saved_at: '2025-12-12T12:21:18.705480+00:00'
  step: 8
- hash: sha256:e18c8448cee67690744c32d570e292a6287fba91a25edd0d02c5dc53cdfc4045
  name: PowerTransformer_1
  path: PowerTransformer_e18c84.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1445
  saved_at: '2025-12-12T12:21:19.208361+00:00'
  step: 9
- hash: sha256:ca26bc60fee6f17042c6ce3d5480def3bf3956b3b4fb66ae738214a2c7f33968
  name: AutoGluon_1.pkl
  path: TabularPredictor_ca26bc.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 21322
  saved_at: '2025-12-12T12:25:29.191282+00:00'
  step: 10
- hash: sha256:a03ea7f18ea41736b1977dcceadef830b3d3f4e1731a813a34f23d12240f98e4
  name: AutoGluon_2.pkl
  path: TabularPredictor_a03ea7.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 21313
  saved_at: '2025-12-12T12:25:29.191715+00:00'
  step: 10
- hash: sha256:cc65643552d27a85b905615db862c35a0700a229322329fad127585ee8878da2
  name: AutoGluon_3.pkl
  path: TabularPredictor_cc6564.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 21295
  saved_at: '2025-12-12T12:25:29.192033+00:00'
  step: 10
predictions: []
