uid: c85f4be8-b3a8-4a16-8249-81a19938cf98
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: tablet_escitalopramt_310_zhao
created_at: '2025-12-12T10:52:40.888624+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:04273264a7feca0eed66b16f31cca2f85cc667a695da0b837ec42fc508ec65e5
  name: ASLSBaseline_1
  path: ASLSBaseline_042732.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T10:52:40.938973+00:00'
  step: 1
- hash: sha256:f1aebd72e217ec8157715fcce618a96f2ecc30cd92b143313e7e3cd06b427325
  name: y_StandardScaler
  path: StandardScaler_f1aebd.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 440
  saved_at: '2025-12-12T10:52:41.092892+00:00'
  step: 4
- hash: sha256:08c57278cd2daa52e0a3f7c3b48780523c687f16bcf4cab68c77bc1ce261dcc6
  name: StandardScaler_1
  path: StandardScaler_08c572.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9420
  saved_at: '2025-12-12T10:52:41.098561+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T10:52:41.112205+00:00'
  step: 6
- hash: sha256:6ae77385977756fafdbb84b7170e260fc6d598983734cf6aceed5417732e4f73
  name: PCA_1
  path: PCA_6ae773.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 8092
  saved_at: '2025-12-12T10:52:41.152959+00:00'
  step: 7
- hash: sha256:e1047d9a00c585985825dde65eb300df8f65971ada31960fdcb3294290a98d00
  name: StandardScaler_1
  path: StandardScaler_e1047d.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 520
  saved_at: '2025-12-12T10:52:41.185471+00:00'
  step: 8
- hash: sha256:79bf2e2df646d71dbea8ff5e2bc1768bc2757972d438b0a97e0d996b1d02e0bf
  name: PowerTransformer_1
  path: PowerTransformer_79bf2e.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 658
  saved_at: '2025-12-12T10:52:41.203654+00:00'
  step: 9
- hash: sha256:1590f9c688768305ac95888a0d82f7cc266a332848118a1ee3ef7af6d904d847
  name: AutoGluon_1.pkl
  path: TabularPredictor_1590f9.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2025-12-12T10:52:55.665685+00:00'
  step: 10
- hash: sha256:1e433c1a68127517072a212d326020ca6b6d7d1704112b6b065213c17caf3f3f
  name: AutoGluon_2.pkl
  path: TabularPredictor_1e433c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11262
  saved_at: '2025-12-12T10:52:55.666176+00:00'
  step: 10
- hash: sha256:4e603ecc3ab41d9226b639071fd1c55482944c9ed1931e88803e838a116d70ef
  name: AutoGluon_3.pkl
  path: TabularPredictor_4e603e.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2025-12-12T10:52:55.666428+00:00'
  step: 10
- hash: sha256:fe785aa9716b4f17f92c0153b088771466ee4c3334c31e7583bbb72939a1f3c1
  name: TabPFN_1.pkl
  path: TabPFNRegressor_fe785a.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41092701
  saved_at: '2025-12-12T10:53:03.740274+00:00'
  step: 11
- hash: sha256:500232d45763dab31c8c9f4bfd0d1b442f72a2a431c083eb849921a8c8821474
  name: TabPFN_2.pkl
  path: TabPFNRegressor_500232.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41092699
  saved_at: '2025-12-12T10:53:03.796145+00:00'
  step: 11
- hash: sha256:978d85c0b50df7d5d87b0f5c3925765378e535d9e5dfe1f116f0971b6087103e
  name: TabPFN_3.pkl
  path: TabPFNRegressor_978d85.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41092699
  saved_at: '2025-12-12T10:53:03.852097+00:00'
  step: 11
- hash: sha256:0590caf3fdad99673fd7ecb9f036b7a958b5892a627360e569f6496baa82a2ae
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_0590ca.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41092736
  saved_at: '2025-12-12T10:53:18.266783+00:00'
  step: 12
- hash: sha256:c035bbf28c93b08064f4a43b3a0784f67b80d619e26874144d04dffa305ee019
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_c035bb.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41092738
  saved_at: '2025-12-12T10:53:18.322972+00:00'
  step: 12
- hash: sha256:b0a75d797c77730a701e160604ccf3f2381496b60a38751b5e5bc7fb9b3ba843
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_b0a75d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41092736
  saved_at: '2025-12-12T10:53:18.378912+00:00'
  step: 12
predictions: []
