uid: 0fdc86a7-4128-49ab-9b26-6fc5d532d86b
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: grapevine_chloride_260_ks
created_at: '2026-01-07T09:03:11.715229+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:93ef260d2405d5ac66e8b358702b9c07f33a201ec8e7f9a1442d209371db2625
  name: ASLSBaseline_1
  path: ASLSBaseline_93ef26.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2026-01-07T09:03:12.677104+00:00'
  step: 1
- hash: sha256:a77386f37012cce2cb89c2d3f950604c3bf35ad9c5120d36e0930c64094b3ecc
  name: PCA_1
  path: PCA_a77386.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 4162
  saved_at: '2026-01-07T09:03:12.743743+00:00'
  step: 4
- hash: sha256:45dba9f000d013667e2d977c9d37824b9b98e0e796108e1560a646e83691a316
  name: AutoGluon_1.pkl
  path: TabularPredictor_45dba9.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 10851
  saved_at: '2026-01-07T09:03:22.778771+00:00'
  step: 5
- hash: sha256:8dfc49a3c6449e862d0c706ff9cc1602c16727e00e072c6ea33d3233f4d6d840
  name: AutoGluon_2.pkl
  path: TabularPredictor_8dfc49.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 10842
  saved_at: '2026-01-07T09:03:22.779066+00:00'
  step: 5
- hash: sha256:0359611f9cbbcd424ae496c76238ba5b3d7648bc4fc42c817205c472fdceeb04
  name: AutoGluon_3.pkl
  path: TabularPredictor_035961.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 10842
  saved_at: '2026-01-07T09:03:22.779310+00:00'
  step: 5
- hash: sha256:612af9f64906949a5ac4ad9165014e4397cf83c226958da71c37adf6cd4086d9
  name: TabPFN_1.pkl
  path: TabPFNRegressor_612af9.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41049525
  saved_at: '2026-01-07T09:03:29.677338+00:00'
  step: 6
- hash: sha256:87f65748b6622f3297b30138c614c0f5f979743314c9feadea2976bc1a98a190
  name: TabPFN_2.pkl
  path: TabPFNRegressor_87f657.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41050357
  saved_at: '2026-01-07T09:03:29.732334+00:00'
  step: 6
- hash: sha256:7f412493de072b36956b5f9e56841cb9dd4529c63a867d55651ddd956fbec7cf
  name: TabPFN_3.pkl
  path: TabPFNRegressor_7f4124.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41050357
  saved_at: '2026-01-07T09:03:29.787105+00:00'
  step: 6
- hash: sha256:b468defed58d3ec60c6af7fe940d8ec1433398dd6334a47cb985e90f784a8f03
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_b468de.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41049562
  saved_at: '2026-01-07T09:03:42.668856+00:00'
  step: 7
- hash: sha256:690ec9104797017803d51a0d1ebf6f21878cf5d8e3baee058a48f13803cb8617
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_690ec9.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41050394
  saved_at: '2026-01-07T09:03:42.723812+00:00'
  step: 7
- hash: sha256:2b1635824c2e9ea5c8efb99e7d635216b93e1e30b4f0a4a2b4d25f693c21ea7f
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_2b1635.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41050390
  saved_at: '2026-01-07T09:03:42.777917+00:00'
  step: 7
predictions: []
