uid: 17b9eee5-a4b3-4c26-bcbc-f65911912ac4
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: diesel_f_251_hlb_a
created_at: '2025-12-12T08:31:19.686807+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T08:31:19.727633+00:00'
  step: 1
- hash: sha256:8211ac2d04ba8f54bc9dbfb2509d09e1b77550908926bbb10cdad9b6c7731945
  name: y_StandardScaler
  path: StandardScaler_8211ac.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 443
  saved_at: '2025-12-12T08:31:19.962897+00:00'
  step: 4
- hash: sha256:fd64baccb0646773400471be7d3f6fe4e94ebdd3c53ea77fbafdf0e39e88b0e9
  name: StandardScaler_1
  path: StandardScaler_fd64ba.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9310
  saved_at: '2025-12-12T08:31:19.972072+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T08:31:19.996172+00:00'
  step: 6
- hash: sha256:b4857819a1f449243dcce11f2cae3929d411adecf0278950b02f148b11bc00d6
  name: PCA_1
  path: PCA_b48578.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 7753
  saved_at: '2025-12-12T08:31:20.033345+00:00'
  step: 7
- hash: sha256:93bc9c0ce828d897d72950721222c2c9cb6ac1d5b73d70e24f6ce9db4fec791f
  name: StandardScaler_1
  path: StandardScaler_93bc9c.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 521
  saved_at: '2025-12-12T08:31:20.055988+00:00'
  step: 8
- hash: sha256:88dbb6234d9a6426a7b269d4038c3253af012df45d8214c560ee2ac4de17fa1a
  name: PowerTransformer_1
  path: PowerTransformer_88dbb6.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 667
  saved_at: '2025-12-12T08:31:20.075094+00:00'
  step: 9
- hash: sha256:6584b9b568116e7f520d98c6335bf8d795af79a015cd2c398fb43ed8329eecff
  name: AutoGluon_1.pkl
  path: TabularPredictor_6584b9.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11262
  saved_at: '2025-12-12T08:31:30.481337+00:00'
  step: 10
- hash: sha256:dbaf788368ca81cb3c0af211985191315b44006e987d41407087dbd39bf228f0
  name: AutoGluon_2.pkl
  path: TabularPredictor_dbaf78.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11262
  saved_at: '2025-12-12T08:31:30.481621+00:00'
  step: 10
- hash: sha256:6d1d0f50ee04ca1967c917ce2ff4e3c1c585f4c7b68e3268c0301e2ecbee15e1
  name: AutoGluon_3.pkl
  path: TabularPredictor_6d1d0f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2025-12-12T08:31:30.481872+00:00'
  step: 10
- hash: sha256:66abe9a49b33924885103c18ffcf74bc8b15f74f9181581cbc36daa8d2278dc8
  name: TabPFN_1.pkl
  path: TabPFNRegressor_66abe9.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41042258
  saved_at: '2025-12-12T08:31:38.323573+00:00'
  step: 11
- hash: sha256:c9fd5dac24e6fdf4caab62b8c4ae66632704c9e56d67732d0d98c96b4cf5e70f
  name: TabPFN_2.pkl
  path: TabPFNRegressor_c9fd5d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41042258
  saved_at: '2025-12-12T08:31:38.379234+00:00'
  step: 11
- hash: sha256:ee5c6ebe87ff7b4ed2dd1484d7d4d5928825ced1a21600db87916b477f1f6840
  name: TabPFN_3.pkl
  path: TabPFNRegressor_ee5c6e.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41042258
  saved_at: '2025-12-12T08:31:38.434639+00:00'
  step: 11
- hash: sha256:4785dcc31eb7ea39f808d6d07e3275c52df037d0dd2bc79d22973c99467779b2
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_4785dc.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41042295
  saved_at: '2025-12-12T08:31:52.105800+00:00'
  step: 12
- hash: sha256:998f694f2704e3be76792f109b46485fc5106b79f3ede6c68486880063bee1cf
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_998f69.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41042295
  saved_at: '2025-12-12T08:31:52.161765+00:00'
  step: 12
- hash: sha256:a9f871485642a6413b122bdd977e9c779a46feebc0c734c7bf4b60c5500c9924
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_a9f871.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41042295
  saved_at: '2025-12-12T08:31:52.217104+00:00'
  step: 12
predictions: []
