uid: f5343f0a-8c96-4824-ad6d-bc9056e5997b
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: rice_ph
created_at: '2026-01-07T10:03:41.919871+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:b4db648a2547c1dc21ee2878cc4522bcc8f758afcdc997e89b71292698331f0a
  name: ASLSBaseline_1
  path: ASLSBaseline_b4db64.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2026-01-07T10:03:42.393396+00:00'
  step: 1
- hash: sha256:c10c90696c82ca701f9688de1f9cfe7c5b771e77fd5c930f03ecc6386c83423a
  name: PCA_1
  path: PCA_c10c90.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 7479
  saved_at: '2026-01-07T10:04:19.937904+00:00'
  step: 4
- hash: sha256:b612fb3751ed8c2825e3de2bf39676167732448d53eb0b8e4b1e8ba4585b965f
  name: AutoGluon_1.pkl
  path: TabularPredictor_b612fb.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11984
  saved_at: '2026-01-07T10:08:49.074583+00:00'
  step: 5
- hash: sha256:80aa5edb9933a632237a74bc9ca35b329ec8beeb818e8a287ced8d1f75bef700
  name: AutoGluon_2.pkl
  path: TabularPredictor_80aa5e.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12056
  saved_at: '2026-01-07T10:08:49.074923+00:00'
  step: 5
- hash: sha256:a594d107f806183e953e25f73a6ec6e4cd77a015faa74beb0e10d3ef7784fa02
  name: AutoGluon_3.pkl
  path: TabularPredictor_a594d1.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12056
  saved_at: '2026-01-07T10:08:49.075220+00:00'
  step: 5
- hash: sha256:69ac1faecd0f16258df79ad662c68fa83185048acd83690e9305532fcb99f9e2
  name: TabPFN_1.pkl
  path: TabPFNRegressor_69ac1f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 43631067
  saved_at: '2026-01-07T10:11:22.368732+00:00'
  step: 6
- hash: sha256:649ddfca458e4acb67f971c769701cab419248e3976486c75edfc118394574a3
  name: TabPFN_2.pkl
  path: TabPFNRegressor_649ddf.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 43631065
  saved_at: '2026-01-07T10:11:22.435159+00:00'
  step: 6
- hash: sha256:ba3ff3a9cda8661a46165b8981b40a13114944ca663f61d3c694a023a1acc7ca
  name: TabPFN_3.pkl
  path: TabPFNRegressor_ba3ff3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 43631067
  saved_at: '2026-01-07T10:11:22.501057+00:00'
  step: 6
- hash: sha256:10ce2cf1e28c8d11f6f442c9cb9a92270801bdddb623cb9519223bb9d3946495
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_10ce2c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 43631102
  saved_at: '2026-01-07T10:17:09.406450+00:00'
  step: 7
- hash: sha256:ab2f3f0a5329758f3651ce95fdb6b1f37f43f8221cf5a89abf17dbdb5b5032bd
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_ab2f3f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 43631104
  saved_at: '2026-01-07T10:17:09.471206+00:00'
  step: 7
- hash: sha256:cd596fdc14e0d6115f220f92d82ba0130dc061efa067e02b65bcb6df36b3ebc2
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_cd596f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 43631104
  saved_at: '2026-01-07T10:17:09.535390+00:00'
  step: 7
predictions: []
