uid: 2f68af64-6be0-44a5-add6-39bc8a8498e8
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: diesel_freeze_395_zhengybase
created_at: '2026-01-07T11:11:21.496387+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2026-01-07T11:11:21.558205+00:00'
  step: 1
- hash: sha256:d7280f799ccfc512c2daa1f2acd350129674f7389ff0e1bff2020fe4b99900e8
  name: PCA_1
  path: PCA_d7280f.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 8365
  saved_at: '2026-01-07T11:11:21.711944+00:00'
  step: 4
- hash: sha256:cca555aacc8b755bda69fc74b1d576a3dddf4630a0c80530722fb6736310c2fb
  name: AutoGluon_1.pkl
  path: TabularPredictor_cca555.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11186
  saved_at: '2026-01-07T11:11:33.849713+00:00'
  step: 5
- hash: sha256:0e1da3fd226aa60c4e648f648ee0b3e97ab5beb6f01d3c87b2e8d54a4cfdcbd5
  name: AutoGluon_2.pkl
  path: TabularPredictor_0e1da3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2026-01-07T11:11:33.850011+00:00'
  step: 5
- hash: sha256:242f99b74d42f119bfb47223cb8c38593e8446f9666f0591641d184b9daaf0cd
  name: AutoGluon_3.pkl
  path: TabularPredictor_242f99.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2026-01-07T11:11:33.850394+00:00'
  step: 5
- hash: sha256:83344aa43d8cad0624e569614b6e39d9eee3555bbe6a5c74b2aec1208d888f42
  name: TabPFN_1.pkl
  path: TabPFNRegressor_83344a.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41169256
  saved_at: '2026-01-07T11:11:42.584955+00:00'
  step: 6
- hash: sha256:a205a588509de106527ca2034af1de58282169bb6fba8a4b523f71495644d79d
  name: TabPFN_2.pkl
  path: TabPFNRegressor_a205a5.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41170280
  saved_at: '2026-01-07T11:11:42.634377+00:00'
  step: 6
- hash: sha256:cea6eb149d2203377fe16e834437ea7301065070615dd9790d7c9365790f6b0e
  name: TabPFN_3.pkl
  path: TabPFNRegressor_cea6eb.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41170280
  saved_at: '2026-01-07T11:11:42.683242+00:00'
  step: 6
- hash: sha256:12de1d612dfcf41df53064056906b24665d8cf62d1b0272225877241cfe9a2a0
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_12de1d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41169293
  saved_at: '2026-01-07T11:12:02.347231+00:00'
  step: 7
- hash: sha256:a0ee355f4fd936ed41604d0f0a12d0f7e5acdfef9e00092bc7edc89383c4ed25
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_a0ee35.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41170317
  saved_at: '2026-01-07T11:12:02.396863+00:00'
  step: 7
- hash: sha256:fd8d2605ade4b643952450dce7cfde7445d86b03b72e7f583619e56eea020442
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_fd8d26.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41170317
  saved_at: '2026-01-07T11:12:02.446526+00:00'
  step: 7
predictions: []
