uid: 64f70214-3304-411a-846f-7747abe37612
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: grapevine_chloride_556_ks
created_at: '2026-01-07T09:13:15.229917+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:11348165aae025ca2d539126682657429d57f7d05b66ba9ea0b12f1ee241a8b2
  name: ASLSBaseline_1
  path: ASLSBaseline_113481.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2026-01-07T09:13:15.406318+00:00'
  step: 1
- hash: sha256:fc28fe7a4cf8b9c51b1a5f57532b4e39b1080f383d5a4a41743d78da15f687ea
  name: PCA_1
  path: PCA_fc28fe.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 93022
  saved_at: '2026-01-07T09:13:15.699733+00:00'
  step: 4
- hash: sha256:b24019cb1b32fac9687c8ec4048a9ecefe453a0c0ac8047c703a1dc1d83da1e4
  name: AutoGluon_1.pkl
  path: TabularPredictor_b24019.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 18089
  saved_at: '2026-01-07T09:13:33.975877+00:00'
  step: 5
- hash: sha256:cd072f3a7cf255ca82f5fc9468bf8ad465459a47288db060ca53b19f4f37987d
  name: AutoGluon_2.pkl
  path: TabularPredictor_cd072f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 18089
  saved_at: '2026-01-07T09:13:33.976399+00:00'
  step: 5
- hash: sha256:2245a6f804d6a10714db1a397b5be43481a4743cdf75cc06cca005ba58ef6dd3
  name: AutoGluon_3.pkl
  path: TabularPredictor_2245a6.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 18089
  saved_at: '2026-01-07T09:13:33.976900+00:00'
  step: 5
- hash: sha256:20a1b1b8883eb4dc264600b19f719c822a3bcd68ca6cf70aaf83f0d30f5bcd72
  name: TabPFN_1.pkl
  path: TabPFNRegressor_20a1b1.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42281509
  saved_at: '2026-01-07T09:14:05.763128+00:00'
  step: 6
- hash: sha256:1b12d865ebb35dc23f103bf934edcccff607e161685a9bab093db329c5d42028
  name: TabPFN_2.pkl
  path: TabPFNRegressor_1b12d8.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42286439
  saved_at: '2026-01-07T09:14:05.823446+00:00'
  step: 6
- hash: sha256:2b5ded54b647deb0006421253450f02be48b3f323f79b40ceaba887ffec57b94
  name: TabPFN_3.pkl
  path: TabPFNRegressor_2b5ded.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42286439
  saved_at: '2026-01-07T09:14:05.886446+00:00'
  step: 6
- hash: sha256:b54fe7e82e9e1023d2614e1477bf5fcde2f093bd2b41d1abb3ee0c968f06c28f
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_b54fe7.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42281548
  saved_at: '2026-01-07T09:15:15.052720+00:00'
  step: 7
- hash: sha256:eb2b8f3433ebbe0e217536c4ecf1356f9fafdb2bfba6b2834ead8603d483e773
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_eb2b8f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42286476
  saved_at: '2026-01-07T09:15:15.112970+00:00'
  step: 7
- hash: sha256:37387ceb5695f3d644ccfd16e75f2a237a7601f57f3f530e9631ebdc098b0497
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_37387c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42286476
  saved_at: '2026-01-07T09:15:15.172556+00:00'
  step: 7
predictions: []
