uid: 6c563891-5aff-4735-98f0-08dbb758902c
pipeline_id: 0001_SOTA_d0c7aa
name: SOTA_d0c7aa
dataset: sorghom_digest
created_at: '2025-12-11T16:25:14.167702+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:5fb86667892bba4894bd89751a7de3818e857670f4b382a951e8007787318d91
  name: ASLSBaseline_1
  path: ASLSBaseline_5fb866.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-11T16:25:14.694673+00:00'
  step: 1
- hash: sha256:db3b658cd0f3254c2196fe6f8fbab9769a6d1a26db850c4bf02957276d73d659
  name: y_StandardScaler
  path: StandardScaler_db3b65.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 442
  saved_at: '2025-12-11T16:25:22.580924+00:00'
  step: 4
- hash: sha256:dd74308cd73d5c80ede1af0460c23d0cfe8a61bc833d0a3d06da902789e0670d
  name: StandardScaler_1
  path: StandardScaler_dd7430.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 20831
  saved_at: '2025-12-11T16:25:22.604441+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-11T16:25:22.637352+00:00'
  step: 6
- hash: sha256:86319218ee63fac78461cf8996dfdc85dfe21c99ed9641823995750403a7a979
  name: PCA_1
  path: PCA_863192.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 64330
  saved_at: '2025-12-11T16:25:25.279923+00:00'
  step: 7
- hash: sha256:37d528937ea3ddf56a6611f4a3f0d84d3979c6d03f4e65fcb499ea0034d896fd
  name: StandardScaler_1
  path: StandardScaler_37d528.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 775
  saved_at: '2025-12-11T16:25:25.343250+00:00'
  step: 8
- hash: sha256:0d17926760f4fc949c5beba36191739090a7748dcd7184556f7df4ed500bfa96
  name: PowerTransformer_1
  path: PowerTransformer_0d1792.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1047
  saved_at: '2025-12-11T16:25:25.386781+00:00'
  step: 9
- hash: sha256:a3e23819069cbb7eceb9475e93b6aadb45c9117e74b8567a0cb6351eec8332b3
  name: AutoGluon_1.pkl
  path: TabularPredictor_a3e238.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 15955
  saved_at: '2025-12-11T16:28:08.223350+00:00'
  step: 10
- hash: sha256:1ddb7ceba1be986f53de8080d414091f6f78c1c341a72d1a48986b4223719a0a
  name: AutoGluon_2.pkl
  path: TabularPredictor_1ddb7c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 15955
  saved_at: '2025-12-11T16:28:08.223674+00:00'
  step: 10
- hash: sha256:525118ee1216a5f7abb7679f26c4b14578af22eac1b35a89a52846e741ba6f55
  name: AutoGluon_3.pkl
  path: TabularPredictor_525118.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 15964
  saved_at: '2025-12-11T16:28:08.223952+00:00'
  step: 10
predictions: []
