schema_version: '2.0'
uid: e1c68fc4-52c0-4e60-9042-f65c2d6aa91b
pipeline_id: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78
name: PLS_PP_SELECTION_NO_SAVE_b8cf78
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:46:15.416858+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: null
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - nirs4all.operators.transforms.scalers.StandardNormalVariate
    - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
    - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
      params:
        window_length: 15
        deriv: 2
    - nirs4all.operators.transforms.nirs.Haar
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      error_score: .nan
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: null
- _cartesian_:
  - nirs4all.operators.transforms.scalers.StandardNormalVariate
  - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
  - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
    params:
      window_length: 15
      deriv: 2
  - nirs4all.operators.transforms.nirs.Haar
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:46:15.435455+00:00'
    params: {}
    version: 3
  - artifact_id: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$6e21be876a4d:all
    content_hash: sha256:f1b0d49d100fdce0b1f766631a2fc34c1b2477ed43ee4a120b8aedc3581c1d26
    path: transformer_StandardNormalVariate_f1b0d49d100f.joblib
    chain_path: s5.StandardNormalVariate[src=0,sub=0]
    source_index: 0
    pipeline_id: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: StandardNormalVariate
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 132
    created_at: '2026-01-08T17:46:15.445298+00:00'
    params: {}
    version: 3
  - artifact_id: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$43cfdb4b8dc0:all
    content_hash: sha256:691364ebf5c9cf5f03e16c3b48e170cf0041f7b9fd02c8c40dcdafece2312e1d
    path: transformer_ExtendedMultiplicativeScatterCorrection_691364ebf5c9.joblib
    chain_path: s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=1]
    source_index: 0
    pipeline_id: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: ExtendedMultiplicativeScatterCorrection
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 5683
    created_at: '2026-01-08T17:46:15.448459+00:00'
    params: {}
    version: 3
  - artifact_id: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$296923040127:all
    content_hash: sha256:5c353b1441d52f528075c64bd2477db6d0df3f619817bfa27a68d32928e99953
    path: transformer_SavitzkyGolay_5c353b1441d5.joblib
    chain_path: s5.SavitzkyGolay[src=0,sub=2]
    source_index: 0
    pipeline_id: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78
    branch_path: []
    step_index: 5
    substep_index: 2
    fold_id: null
    artifact_type: transformer
    class_name: SavitzkyGolay
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 137
    created_at: '2026-01-08T17:46:15.450146+00:00'
    params: {}
    version: 3
  - artifact_id: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$32bd0e890598:all
    content_hash: sha256:2237293e62d5640680cb91d003382cdd194cbcc1496aee2fd76192fa547a78be
    path: transformer_Haar_2237293e62d5.joblib
    chain_path: s5.Haar[src=0,sub=3]
    source_index: 0
    pipeline_id: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78
    branch_path: []
    step_index: 5
    substep_index: 3
    fold_id: null
    artifact_type: transformer
    class_name: Haar
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 112
    created_at: '2026-01-08T17:46:15.451693+00:00'
    params: {}
    version: 3
  - artifact_id: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$9f79d59455ab:0
    content_hash: sha256:610b7e3f3e6c23442ef12bcfae122b89bda2657c25ad682fc352edd0d1cb7351
    path: model_PLSRegression_610b7e3f3e6c.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 196599
    created_at: '2026-01-08T17:46:16.050336+00:00'
    params: {}
    version: 3
  - artifact_id: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$9f79d59455ab:1
    content_hash: sha256:db3a899c4484736b3eff24a877bbd8a372dfc655abfc67cd82bb290175e3202d
    path: model_PLSRegression_db3a899c4484.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 197053
    created_at: '2026-01-08T17:46:16.054428+00:00'
    params: {}
    version: 3
  - artifact_id: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$9f79d59455ab:2
    content_hash: sha256:37e360c076e9a9f44cca9c778c399a58f04db4f8abe9e3f4b48db6cea664d451
    path: model_PLSRegression_37e360c076e9.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 197043
    created_at: '2026-01-08T17:46:16.058523+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  366515ff-aa7:
    trace_id: 366515ff-aa7
    pipeline_uid: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78
    created_at: '2026-01-08T17:46:15.417967+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 2.600431442260742
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 1.7559528350830078
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 16.603469848632812
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 4.264354705810547
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: StandardNormalVariate, ExtendedMultiplicativeScatterCorrection,
        SavitzkyGolay (+1)
      operator_config:
        feature_augmentation:
        - nirs4all.operators.transforms.scalers.StandardNormalVariate
        - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
        - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
          params:
            window_length: 15
            deriv: 2
        - nirs4all.operators.transforms.nirs.Haar
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$6e21be876a4d:all
        - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$43cfdb4b8dc0:all
        - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$296923040127:all
        - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$32bd0e890598:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$6e21be876a4d:all
            - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$43cfdb4b8dc0:all
            - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$296923040127:all
            - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$32bd0e890598:all
        by_source:
          0:
          - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$6e21be876a4d:all
          - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$43cfdb4b8dc0:all
          - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$296923040127:all
          - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$32bd0e890598:all
        by_chain:
          s5.StandardNormalVariate[src=0,sub=0]: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$6e21be876a4d:all
          s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=1]: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$43cfdb4b8dc0:all
          s5.SavitzkyGolay[src=0,sub=2]: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$296923040127:all
          s5.Haar[src=0,sub=3]: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$32bd0e890598:all
        metadata:
          class_name: Haar
          name: Haar_4
      branch_path: []
      branch_name: ''
      duration_ms: 13.90528678894043
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.StandardNormalVariate[src=0,sub=0]
      - s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=1]
      - s5.SavitzkyGolay[src=0,sub=2]
      - s5.Haar[src=0,sub=3]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 2880
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 5
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          error_score: .nan
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$9f79d59455ab:0
        - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$9f79d59455ab:1
        - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$9f79d59455ab:0
          1: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$9f79d59455ab:1
          2: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$9f79d59455ab:0
            - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$9f79d59455ab:1
            - 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0282_PLS_PP_SELECTION_NO_SAVE_b8cf78$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 628.8042068481445
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 2880
      output_shape:
      - 60
      - 2880
      input_features_shape:
      - - 60
        - 5
        - 576
      output_features_shape:
      - - 60
        - 5
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: raw|SNV|ExtendedMSC|SG|Haar
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_b8cf78
      n_steps: 6
      n_artifacts: 8
