schema_version: '2.0'
uid: 9da33f8a-8e62-4d73-93f3-48944577920e
pipeline_id: 0001_SOTA_fad74e
name: SOTA_fad74e
dataset: grapevine_chloride_260_ks
created_at: '2026-01-09T14:13:14.344358+00:00'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 4
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0001_SOTA_fad74e$bb12ee38a89c:all
    content_hash: sha256:93ef260d2405d5ac66e8b358702b9c07f33a201ec8e7f9a1442d209371db2625
    path: transformer_ASLSBaseline_93ef260d2405.joblib
    chain_path: s1.ASLSBaseline[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_fad74e
    branch_path: []
    step_index: 1
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: ASLSBaseline
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 215
    created_at: '2026-01-09T14:13:14.421583+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_fad74e$2865afbbfc1d:all
    content_hash: sha256:5b58fc17365266a374f07707a5f7721295a29387a4b7467203ad925feb3203ae
    path: encoder_StandardScaler_5b58fc173652.joblib
    chain_path: s2.y_StandardScaler[sub=1]
    source_index: null
    pipeline_id: 0001_SOTA_fad74e
    branch_path: []
    step_index: 2
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: StandardScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 445
    created_at: '2026-01-09T14:13:14.529047+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_fad74e$b3c264a83f45:all
    content_hash: sha256:6b03acd5e2c3d63a3d81afea0473babad2706d8d351b2804a6d4e6a8f5051c4e
    path: transformer_StandardScaler_6b03acd5e2c3.joblib
    chain_path: s3.StandardScaler[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_fad74e
    branch_path: []
    step_index: 3
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: StandardScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 5553
    created_at: '2026-01-09T14:13:14.537110+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_fad74e$900033a82811:all
    content_hash: sha256:1431fc8d2f682a908ece8596b7d22890efd3e43c9551bb4816b491bb9e5f443a
    path: transformer_PCA_1431fc8d2f68.joblib
    chain_path: s5.PCA[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_fad74e
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: PCA
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 7508
    created_at: '2026-01-09T14:13:14.604757+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_fad74e$c5f06284fcbc:0
    content_hash: sha256:0ae0d79b458221d86cc8b486b9d2d2b9cdda5b14789a36fb9affb514dfaeaa67
    path: model_TabPFNRegressor_0ae0d79b4582.pkl
    chain_path: s6.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_fad74e
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 40969783
    created_at: '2026-01-09T14:13:17.675963+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_fad74e$c5f06284fcbc:1
    content_hash: sha256:655a73a05047af8dc9fb539221eb5da0c3bba6e5e92ea267b4e9ef3c5d908e6b
    path: model_TabPFNRegressor_655a73a05047.pkl
    chain_path: s6.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_fad74e
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 40970183
    created_at: '2026-01-09T14:13:17.726648+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_fad74e$c5f06284fcbc:2
    content_hash: sha256:3c14946995cf00f842cad11b1c55e6c04ca0312eaa06dfdd7db4338a2ade3661
    path: model_TabPFNRegressor_3c14946995cf.pkl
    chain_path: s6.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_fad74e
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 40970183
    created_at: '2026-01-09T14:13:17.777565+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  bc026dc2-c10:
    trace_id: bc026dc2-c10
    pipeline_uid: 0001_SOTA_fad74e
    created_at: '2026-01-09T14:13:14.345217+00:00'
    steps:
    - step_index: 1
      operator_type: transform
      operator_class: ASLSBaseline
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_fad74e$bb12ee38a89c:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_fad74e$bb12ee38a89c:all
        by_source:
          0:
          - 0001_SOTA_fad74e$bb12ee38a89c:all
        by_chain:
          s1.ASLSBaseline[src=0,sub=0]: 0001_SOTA_fad74e$bb12ee38a89c:all
        metadata:
          class_name: ASLSBaseline
          name: ASLSBaseline_1
      branch_path: []
      branch_name: ''
      duration_ms: 82.5338363647461
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s1.ASLSBaseline[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 259
      - 228
      output_shape:
      - 259
      - 228
      input_features_shape:
      - - 259
        - 1
        - 228
      output_features_shape:
      - - 259
        - 1
        - 228
    - step_index: 2
      operator_type: y_processing
      operator_class: StandardScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.StandardScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_fad74e$2865afbbfc1d:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_fad74e$2865afbbfc1d:all
        by_source: {}
        by_chain:
          s2.y_StandardScaler[sub=1]: 0001_SOTA_fad74e$2865afbbfc1d:all
        metadata:
          class_name: StandardScaler
          name: y_StandardScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 105.81111907958984
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s2.y_StandardScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 259
      - 228
      output_shape:
      - 259
      - 228
      input_features_shape:
      - - 259
        - 1
        - 228
      output_features_shape:
      - - 259
        - 1
        - 228
    - step_index: 3
      operator_type: transform
      operator_class: StandardScaler
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_fad74e$b3c264a83f45:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_fad74e$b3c264a83f45:all
        by_source:
          0:
          - 0001_SOTA_fad74e$b3c264a83f45:all
        by_chain:
          s3.StandardScaler[src=0,sub=0]: 0001_SOTA_fad74e$b3c264a83f45:all
        metadata:
          class_name: StandardScaler
          name: StandardScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 21.12746238708496
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.StandardScaler[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 259
      - 228
      output_shape:
      - 259
      - 228
      input_features_shape:
      - - 259
        - 1
        - 228
      output_features_shape:
      - - 259
        - 1
        - 228
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 43.615102767944336
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 259
      - 228
      output_shape:
      - 259
      - 228
      input_features_shape:
      - - 259
        - 1
        - 228
      output_features_shape:
      - - 259
        - 1
        - 228
    - step_index: 5
      operator_type: operator
      operator_class: PCA
      operator_config:
        class: sklearn.decomposition._pca.PCA
        params:
          n_components: 0.99
          whiten: true
          random_state: 42
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_fad74e$900033a82811:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_fad74e$900033a82811:all
        by_source:
          0:
          - 0001_SOTA_fad74e$900033a82811:all
        by_chain:
          s5.PCA[src=0,sub=0]: 0001_SOTA_fad74e$900033a82811:all
        metadata:
          class_name: PCA
          name: PCA_1
      branch_path: []
      branch_name: ''
      duration_ms: 25.452136993408203
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.PCA[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 259
      - 228
      output_shape:
      - 259
      - 7
      input_features_shape:
      - - 259
        - 1
        - 228
      output_features_shape:
      - - 259
        - 1
        - 7
    - step_index: 6
      operator_type: model
      operator_class: TabPFNRegressor
      operator_config:
        model:
          class: tabpfn.regressor.TabPFNRegressor
          params:
            n_estimators: 4
            model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
            device: cpu
            random_state: 42
        name: TabPFN-real
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_fad74e$c5f06284fcbc:0
        - 0001_SOTA_fad74e$c5f06284fcbc:1
        - 0001_SOTA_fad74e$c5f06284fcbc:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0001_SOTA_fad74e$c5f06284fcbc:0
          1: 0001_SOTA_fad74e$c5f06284fcbc:1
          2: 0001_SOTA_fad74e$c5f06284fcbc:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_fad74e$c5f06284fcbc:0
            - 0001_SOTA_fad74e$c5f06284fcbc:1
            - 0001_SOTA_fad74e$c5f06284fcbc:2
        by_source: {}
        by_chain:
          s6.TabPFNRegressor[sub=0]: 0001_SOTA_fad74e$c5f06284fcbc:2
        metadata:
          class_name: TabPFNRegressor
          custom_name: TabPFN-real
      branch_path: []
      branch_name: ''
      duration_ms: 5741.65678024292
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.TabPFNRegressor[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 259
      - 7
      output_shape:
      - 259
      - 7
      input_features_shape:
      - - 259
        - 1
        - 7
      output_features_shape:
      - - 259
        - 1
        - 7
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: ASLSBaseline>Std>PCA
    metadata:
      dataset: grapevine_chloride_260_ks
      config_name: SOTA_fad74e
      n_steps: 6
      n_artifacts: 7
