schema_version: '2.0'
uid: d961d0a9-8619-4c8e-ac98-54ad716a40c4
pipeline_id: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee
name: PLS_PP_SELECTION_NO_SAVE_5231ee
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:49:06.755671+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: sklearn.preprocessing._data.StandardScaler
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - null
    - null
    - null
    - nirs4all.operators.transforms.signal.Detrend
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      error_score: .nan
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: sklearn.preprocessing._data.StandardScaler
- _cartesian_:
  - null
  - null
  - null
  - nirs4all.operators.transforms.signal.Detrend
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$e8256e270180:all
    content_hash: sha256:62fbca7e67132ee4c3eac6fcd60d6652d6e5c748d596fbba7aa83af04e3a52fc
    path: transformer_StandardScaler_62fbca7e6713.joblib
    chain_path: s2.StandardScaler[src=0,sub=0]
    source_index: 0
    pipeline_id: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee
    branch_path: []
    step_index: 2
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: StandardScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 12015
    created_at: '2026-01-08T17:49:06.761534+00:00'
    params: {}
    version: 3
  - artifact_id: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:49:06.791524+00:00'
    params: {}
    version: 3
  - artifact_id: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$51eb708c8a1f:all
    content_hash: sha256:11ce246bc67c631c59d4827a162f06b45fa0f87770f7d8325a0c50c7f6d72fcf
    path: transformer_Detrend_11ce246bc67c.joblib
    chain_path: s5.Detrend[src=0,sub=0]
    source_index: 0
    pipeline_id: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: Detrend
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 90
    created_at: '2026-01-08T17:49:06.811606+00:00'
    params: {}
    version: 3
  - artifact_id: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$9f79d59455ab:0
    content_hash: sha256:dfb2a19d39f447975b1ff9ff14a4874e9427f8aeb458cab1c146e3cce972bcca
    path: model_PLSRegression_dfb2a19d39f4.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 79897
    created_at: '2026-01-08T17:49:07.605136+00:00'
    params: {}
    version: 3
  - artifact_id: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$9f79d59455ab:1
    content_hash: sha256:68a6e71ec49e7f67f0b0b26db9098e4e134999c1894018aea0b7a3ebeca07568
    path: model_PLSRegression_68a6e71ec49e.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 80166
    created_at: '2026-01-08T17:49:07.610794+00:00'
    params: {}
    version: 3
  - artifact_id: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$9f79d59455ab:2
    content_hash: sha256:62e39a6d1c66370dd9b2745ecc899562e246cdbfae5e72d0988ce7981decf8c1
    path: model_PLSRegression_62e39a6d1c66.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 80147
    created_at: '2026-01-08T17:49:07.614936+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  b1604cf0-7bc:
    trace_id: b1604cf0-7bc
    pipeline_uid: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee
    created_at: '2026-01-08T17:49:06.756656+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 2.0630359649658203
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: StandardScaler
      operator_config:
        feature_augmentation: sklearn.preprocessing._data.StandardScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$e8256e270180:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$e8256e270180:all
        by_source:
          0:
          - 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$e8256e270180:all
        by_chain:
          s2.StandardScaler[src=0,sub=0]: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$e8256e270180:all
        metadata:
          class_name: StandardScaler
          name: StandardScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 6.825685501098633
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s2.StandardScaler[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 31.281709671020508
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 8.843183517456055
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: None, None, None (+1)
      operator_config:
        feature_augmentation:
        - null
        - null
        - null
        - nirs4all.operators.transforms.signal.Detrend
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$51eb708c8a1f:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$51eb708c8a1f:all
        by_source:
          0:
          - 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$51eb708c8a1f:all
        by_chain:
          s5.Detrend[src=0,sub=0]: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$51eb708c8a1f:all
        metadata:
          class_name: Detrend
          name: Detrend_1
      branch_path: []
      branch_name: ''
      duration_ms: 32.605648040771484
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.Detrend[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 1152
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 2
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          error_score: .nan
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$9f79d59455ab:0
        - 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$9f79d59455ab:1
        - 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$9f79d59455ab:0
          1: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$9f79d59455ab:1
          2: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$9f79d59455ab:0
            - 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$9f79d59455ab:1
            - 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0438_PLS_PP_SELECTION_NO_SAVE_5231ee$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 811.6941452026367
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 1152
      output_shape:
      - 60
      - 1152
      input_features_shape:
      - - 60
        - 2
        - 576
      output_features_shape:
      - - 60
        - 2
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: Std|Std>Detr
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_5231ee
      n_steps: 6
      n_artifacts: 6
