schema_version: '2.0'
uid: e0b32aee-d137-46ec-91f4-af279852ebd2
pipeline_id: 0001_SOTA_137acf
name: SOTA_137acf
dataset: cassava_tcc_4930_davrieuxrobustness2014
created_at: '2026-01-09T14:30:44.145175+00:00'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 4
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0001_SOTA_137acf$bb12ee38a89c:all
    content_hash: sha256:e3981c22fe01bf6ba48b414ed19291553d7fa375224b447ff7d90a870e91f7c3
    path: transformer_ASLSBaseline_e3981c22fe01.joblib
    chain_path: s1.ASLSBaseline[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 1
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: ASLSBaseline
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 215
    created_at: '2026-01-09T14:30:45.524906+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$2865afbbfc1d:all
    content_hash: sha256:be7697bbf46694a8a4fbe3b04b8e33bd573c3170f766072d13a9e343f166983d
    path: encoder_StandardScaler_be7697bbf466.joblib
    chain_path: s2.y_StandardScaler[sub=1]
    source_index: null
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 2
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: StandardScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 441
    created_at: '2026-01-09T14:30:49.633071+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$b3c264a83f45:all
    content_hash: sha256:11ae92ee3c7f0cc536eb57841b9e6b33ecc89a24b71a6754cf20604f42a1461e
    path: transformer_StandardScaler_11ae92ee3c7f.joblib
    chain_path: s3.StandardScaler[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 3
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: StandardScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 24207
    created_at: '2026-01-09T14:30:49.705605+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$900033a82811:all
    content_hash: sha256:4be5fc02cab5639f5a8f40e951a2636995f0d107ef4134c709174637c426d82a
    path: transformer_PCA_4be5fc02cab5.joblib
    chain_path: s5.PCA[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: PCA
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 44053
    created_at: '2026-01-09T14:32:49.713875+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$c5f06284fcbc:0
    content_hash: sha256:757f2ea12ae7c3c346b14bb054afc5cdb261b5c6cc9ee80509f425d9bdec8043
    path: model_TabPFNRegressor_757f2ea12ae7.pkl
    chain_path: s6.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 42641296
    created_at: '2026-01-09T14:34:36.206104+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$c5f06284fcbc:1
    content_hash: sha256:0172ad4d330a50f4f9db1c262c3bf094034e775695e4c460625f57eeee5c0045
    path: model_TabPFNRegressor_0172ad4d330a.pkl
    chain_path: s6.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 42641856
    created_at: '2026-01-09T14:34:36.252105+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$c5f06284fcbc:2
    content_hash: sha256:ef406cc9ffc4aec3a96f2df5cf03247211c0bd72caac98b9753c43b3bd433254
    path: model_TabPFNRegressor_ef406cc9ffc4.pkl
    chain_path: s6.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 42641856
    created_at: '2026-01-09T14:34:36.297295+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  8667e87c-7b1:
    trace_id: 8667e87c-7b1
    pipeline_uid: 0001_SOTA_137acf
    created_at: '2026-01-09T14:30:44.145991+00:00'
    steps:
    - step_index: 1
      operator_type: transform
      operator_class: ASLSBaseline
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$bb12ee38a89c:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$bb12ee38a89c:all
        by_source:
          0:
          - 0001_SOTA_137acf$bb12ee38a89c:all
        by_chain:
          s1.ASLSBaseline[src=0,sub=0]: 0001_SOTA_137acf$bb12ee38a89c:all
        metadata:
          class_name: ASLSBaseline
          name: ASLSBaseline_1
      branch_path: []
      branch_name: ''
      duration_ms: 1428.6487102508545
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s1.ASLSBaseline[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 4930
      - 1050
      output_shape:
      - 4930
      - 1050
      input_features_shape:
      - - 4930
        - 1
        - 1050
      output_features_shape:
      - - 4930
        - 1
        - 1050
    - step_index: 2
      operator_type: y_processing
      operator_class: StandardScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.StandardScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$2865afbbfc1d:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$2865afbbfc1d:all
        by_source: {}
        by_chain:
          s2.y_StandardScaler[sub=1]: 0001_SOTA_137acf$2865afbbfc1d:all
        metadata:
          class_name: StandardScaler
          name: y_StandardScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 4077.091932296753
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s2.y_StandardScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 4930
      - 1050
      output_shape:
      - 4930
      - 1050
      input_features_shape:
      - - 4930
        - 1
        - 1050
      output_features_shape:
      - - 4930
        - 1
        - 1050
    - step_index: 3
      operator_type: transform
      operator_class: StandardScaler
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$b3c264a83f45:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$b3c264a83f45:all
        by_source:
          0:
          - 0001_SOTA_137acf$b3c264a83f45:all
        by_chain:
          s3.StandardScaler[src=0,sub=0]: 0001_SOTA_137acf$b3c264a83f45:all
        metadata:
          class_name: StandardScaler
          name: StandardScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 116.67203903198242
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.StandardScaler[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 4930
      - 1050
      output_shape:
      - 4930
      - 1050
      input_features_shape:
      - - 4930
        - 1
        - 1050
      output_features_shape:
      - - 4930
        - 1
        - 1050
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 119735.72087287903
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 4930
      - 1050
      output_shape:
      - 4930
      - 1050
      input_features_shape:
      - - 4930
        - 1
        - 1050
      output_features_shape:
      - - 4930
        - 1
        - 1050
    - step_index: 5
      operator_type: operator
      operator_class: PCA
      operator_config:
        class: sklearn.decomposition._pca.PCA
        params:
          n_components: 0.99
          whiten: true
          random_state: 42
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$900033a82811:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$900033a82811:all
        by_source:
          0:
          - 0001_SOTA_137acf$900033a82811:all
        by_chain:
          s5.PCA[src=0,sub=0]: 0001_SOTA_137acf$900033a82811:all
        metadata:
          class_name: PCA
          name: PCA_1
      branch_path: []
      branch_name: ''
      duration_ms: 292.0866012573242
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.PCA[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 4930
      - 1050
      output_shape:
      - 4930
      - 10
      input_features_shape:
      - - 4930
        - 1
        - 1050
      output_features_shape:
      - - 4930
        - 1
        - 10
    - step_index: 6
      operator_type: model
      operator_class: TabPFNRegressor
      operator_config:
        model:
          class: tabpfn.regressor.TabPFNRegressor
          params:
            n_estimators: 4
            model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
            device: cpu
            ignore_pretraining_limits: true
            random_state: 42
        name: TabPFN-real
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$c5f06284fcbc:0
        - 0001_SOTA_137acf$c5f06284fcbc:1
        - 0001_SOTA_137acf$c5f06284fcbc:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0001_SOTA_137acf$c5f06284fcbc:0
          1: 0001_SOTA_137acf$c5f06284fcbc:1
          2: 0001_SOTA_137acf$c5f06284fcbc:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$c5f06284fcbc:0
            - 0001_SOTA_137acf$c5f06284fcbc:1
            - 0001_SOTA_137acf$c5f06284fcbc:2
        by_source: {}
        by_chain:
          s6.TabPFNRegressor[sub=0]: 0001_SOTA_137acf$c5f06284fcbc:2
        metadata:
          class_name: TabPFNRegressor
          custom_name: TabPFN-real
      branch_path: []
      branch_name: ''
      duration_ms: 253314.35132026672
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.TabPFNRegressor[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 4930
      - 10
      output_shape:
      - 4930
      - 10
      input_features_shape:
      - - 4930
        - 1
        - 10
      output_features_shape:
      - - 4930
        - 1
        - 10
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: ASLSBaseline>Std>PCA
    metadata:
      dataset: cassava_tcc_4930_davrieuxrobustness2014
      config_name: SOTA_137acf
      n_steps: 6
      n_artifacts: 7
