uid: a18f3c55-b52d-4295-95fa-5097ccc9f736
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: diesel_visc_395_zhengybase
created_at: '2026-01-07T11:15:46.813362+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2026-01-07T11:15:46.875005+00:00'
  step: 1
- hash: sha256:0c6a986f7047881d4caff658470461447346c87f33a4e5831526f223b4e4e178
  name: PCA_1
  path: PCA_0c6a98.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 8373
  saved_at: '2026-01-07T11:15:47.037873+00:00'
  step: 4
- hash: sha256:7a9bb83cd9c42b33aa295b2491ba6b999c5354cb2efa6d62944dc430ed260818
  name: AutoGluon_1.pkl
  path: TabularPredictor_7a9bb8.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11262
  saved_at: '2026-01-07T11:16:05.006476+00:00'
  step: 5
- hash: sha256:dbc64d3f28341b55b68498dd51ae1ec1babbf61b036154535f7613c0db46d5f9
  name: AutoGluon_2.pkl
  path: TabularPredictor_dbc64d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2026-01-07T11:16:05.006942+00:00'
  step: 5
- hash: sha256:0b943fa168b645cc69a3d908eda9f89c93d173d20b4a2173a9f74c72eddb3dca
  name: AutoGluon_3.pkl
  path: TabularPredictor_0b943f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2026-01-07T11:16:05.007350+00:00'
  step: 5
- hash: sha256:3a6172ce761159a13476c01dac483ecb3cb768fc5faefce6211539ae924df54c
  name: TabPFN_1.pkl
  path: TabPFNRegressor_3a6172.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41169256
  saved_at: '2026-01-07T11:16:15.391360+00:00'
  step: 6
- hash: sha256:ca1d37ab9b426bfc02871e40bc719a3bb0ea63c358c0e3f3169881a3d5777bcc
  name: TabPFN_2.pkl
  path: TabPFNRegressor_ca1d37.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41170280
  saved_at: '2026-01-07T11:16:15.450019+00:00'
  step: 6
- hash: sha256:049dfd036113647f1be1e6d9861177f88aff59c2a7fa815732d47b82821c3f7f
  name: TabPFN_3.pkl
  path: TabPFNRegressor_049dfd.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41170280
  saved_at: '2026-01-07T11:16:15.508365+00:00'
  step: 6
- hash: sha256:5a1bc058623d3be1d236f9dc1b70a941feee403d2636c97af674fd2433ff7d59
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_5a1bc0.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41169293
  saved_at: '2026-01-07T11:16:35.305976+00:00'
  step: 7
- hash: sha256:4ea82936e8b4efb33ffa18b3364454c7475cfedb19b6b13a8342ad96319ebbd2
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_4ea829.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41170317
  saved_at: '2026-01-07T11:16:35.366044+00:00'
  step: 7
- hash: sha256:e44cc8fa35f9e3d8cc333b2694312756d9159d5300f2d8f5539ae314d8a40708
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_e44cc8.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41170317
  saved_at: '2026-01-07T11:16:35.425602+00:00'
  step: 7
predictions: []
