uid: c0b50332-12af-412d-a5f1-602ebc4f14e2
pipeline_id: 0001_SOTA_d0c7aa
name: SOTA_d0c7aa
dataset: cattle_manure_cao_ks
created_at: '2025-12-11T16:22:57.137666+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:125d94dee500492a3bdb8dd8b9fa106b8b2b34e5f42944e4b15d55960ffb73d1
  name: ASLSBaseline_1
  path: ASLSBaseline_125d94.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-11T16:22:57.220829+00:00'
  step: 1
- hash: sha256:143420965827cfd3120b1f3784ea94b1942e65b45398134ad2c95157367e217e
  name: y_StandardScaler
  path: StandardScaler_143420.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 440
  saved_at: '2025-12-11T16:22:57.368660+00:00'
  step: 4
- hash: sha256:df0e6280c238a24e3ec44b22bc9fcddcc1b0841f6575f06d1895df2a2a9f9e68
  name: StandardScaler_1
  path: StandardScaler_df0e62.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 21800
  saved_at: '2025-12-11T16:22:57.375005+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-11T16:22:57.384104+00:00'
  step: 6
- hash: sha256:1db9f9a5c127ba70f1a3c850c51f8c31351d192ca9288bef332a16093bc131d5
  name: PCA_1
  path: PCA_1db9f9.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 157683
  saved_at: '2025-12-11T16:22:57.454614+00:00'
  step: 7
- hash: sha256:aa283d53aea94e1aeb1f92ca04c3f881e60fecf4e1a17dbd5969fc572e87762a
  name: StandardScaler_1
  path: StandardScaler_aa283d.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1208
  saved_at: '2025-12-11T16:22:57.487603+00:00'
  step: 8
- hash: sha256:240cec9e317bfdf6b756d83c6eb6f5bc6c227fbaa0b8266ef8b6256547d93ed2
  name: PowerTransformer_1
  path: PowerTransformer_240cec.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1679
  saved_at: '2025-12-11T16:22:57.543143+00:00'
  step: 9
- hash: sha256:fa7d1f78d292aed78109c8ef4e99c283d8f6f32a97ba433eff7e32aa23549574
  name: AutoGluon_1.pkl
  path: TabularPredictor_fa7d1f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 24494
  saved_at: '2025-12-11T16:23:10.728719+00:00'
  step: 10
- hash: sha256:0be0eba86e2b6684ada3963fb434ac1bd8f79a2ad36731a0c0be5f7933bf3725
  name: AutoGluon_2.pkl
  path: TabularPredictor_0be0eb.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 24476
  saved_at: '2025-12-11T16:23:10.729053+00:00'
  step: 10
- hash: sha256:5ed406cdb457303208fd829e24c4109aa28513c6a4de5c82eace6a629deaf4b7
  name: AutoGluon_3.pkl
  path: TabularPredictor_5ed406.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 24467
  saved_at: '2025-12-11T16:23:10.729373+00:00'
  step: 10
- hash: sha256:17957111011cb19d13b66cbb2e9d19d11a2bcba86589db879fcc724f841922c8
  name: TabPFN_1.pkl
  path: TabPFNRegressor_179571.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42152951
  saved_at: '2025-12-11T16:23:39.033906+00:00'
  step: 11
- hash: sha256:a3ce115da1c72e31e3001a35828ac743c3504c69ce2cc7861d3c98e2928f8529
  name: TabPFN_2.pkl
  path: TabPFNRegressor_a3ce11.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42161655
  saved_at: '2025-12-11T16:23:39.074649+00:00'
  step: 11
- hash: sha256:013a5e385cf137315104931210f2c4cafe85e50176b65292910a82bdde616cf6
  name: TabPFN_3.pkl
  path: TabPFNRegressor_013a5e.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42161679
  saved_at: '2025-12-11T16:23:39.115208+00:00'
  step: 11
- hash: sha256:e0e1e3d36d6a6e80a8a8cf4c28e851e0c8ded8a7a031fff368842426ad16f143
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_e0e1e3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42152990
  saved_at: '2025-12-11T16:24:40.259549+00:00'
  step: 12
- hash: sha256:4bf43fa59e942b427e67e29720d8c67a4203ea4ef156979ff9702748908da883
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_4bf43f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42161704
  saved_at: '2025-12-11T16:24:40.306118+00:00'
  step: 12
- hash: sha256:ffd1ab7a0d9b1b8f374258330454bfb680496dc10b628191c5d3ac97474e0c51
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_ffd1ab.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42161698
  saved_at: '2025-12-11T16:24:40.350223+00:00'
  step: 12
predictions: []
