schema_version: '2.0'
uid: 24229bae-893c-4a77-87d6-bb4a00f78365
pipeline_id: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe
name: PLS_PP_SELECTION_NO_SAVE_2821fe
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:53:12.133373+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: sklearn.preprocessing._data.StandardScaler
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
    - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
      params:
        window_length: 15
    - null
    - nirs4all.operators.transforms.nirs.AreaNormalization
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      error_score: .nan
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: sklearn.preprocessing._data.StandardScaler
- _cartesian_:
  - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
  - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
    params:
      window_length: 15
  - null
  - nirs4all.operators.transforms.nirs.AreaNormalization
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$e8256e270180:all
    content_hash: sha256:62fbca7e67132ee4c3eac6fcd60d6652d6e5c748d596fbba7aa83af04e3a52fc
    path: transformer_StandardScaler_62fbca7e6713.joblib
    chain_path: s2.StandardScaler[src=0,sub=0]
    source_index: 0
    pipeline_id: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe
    branch_path: []
    step_index: 2
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: StandardScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 12015
    created_at: '2026-01-08T17:53:12.139745+00:00'
    params: {}
    version: 3
  - artifact_id: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:53:12.178606+00:00'
    params: {}
    version: 3
  - artifact_id: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$33af94b1bf58:all
    content_hash: sha256:0721098a9e95cc2ee2f5245b14331db5bda396203e6f9c2dc951c1d3611e0a2f
    path: transformer_ExtendedMultiplicativeScatterCorrection_0721098a9e95.joblib
    chain_path: s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=0]
    source_index: 0
    pipeline_id: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: ExtendedMultiplicativeScatterCorrection
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 4485
    created_at: '2026-01-08T17:53:12.207835+00:00'
    params: {}
    version: 3
  - artifact_id: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$eeb09d32a26b:all
    content_hash: sha256:c90a6e998d89e802fdc8ae5af3e9cd7288130360151139484ffc6499b3403f5a
    path: transformer_SavitzkyGolay_c90a6e998d89.joblib
    chain_path: s5.SavitzkyGolay[src=0,sub=1]
    source_index: 0
    pipeline_id: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: SavitzkyGolay
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 137
    created_at: '2026-01-08T17:53:12.215123+00:00'
    params: {}
    version: 3
  - artifact_id: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$ac71c0f61352:all
    content_hash: sha256:3381c200ece0f7e7ac9f3c9a70feb2bc950b0271d9a3c4d8bfc727bd6a3bfbb5
    path: transformer_AreaNormalization_3381c200ece0.joblib
    chain_path: s5.AreaNormalization[src=0,sub=2]
    source_index: 0
    pipeline_id: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe
    branch_path: []
    step_index: 5
    substep_index: 2
    fold_id: null
    artifact_type: transformer
    class_name: AreaNormalization
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 103
    created_at: '2026-01-08T17:53:12.221715+00:00'
    params: {}
    version: 3
  - artifact_id: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$9f79d59455ab:0
    content_hash: sha256:dc7e249a50fdee6100d4c17c283cf39491184d54dd93a5fe66f96281f52f57a3
    path: model_PLSRegression_dc7e249a50fd.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 158074
    created_at: '2026-01-08T17:53:12.892809+00:00'
    params: {}
    version: 3
  - artifact_id: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$9f79d59455ab:1
    content_hash: sha256:0c1858b8eb352e03fb3daf5a587e4799d8eff4627fe8e5d0d11047db572f28de
    path: model_PLSRegression_0c1858b8eb35.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 158488
    created_at: '2026-01-08T17:53:12.904103+00:00'
    params: {}
    version: 3
  - artifact_id: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$9f79d59455ab:2
    content_hash: sha256:5f4004bb8a68003fb693633da41723a7151544da5b4aa670f0222d7e2f1b48b7
    path: model_PLSRegression_5f4004bb8a68.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 158436
    created_at: '2026-01-08T17:53:12.911003+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  e0b1b982-6ca:
    trace_id: e0b1b982-6ca
    pipeline_uid: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe
    created_at: '2026-01-08T17:53:12.134475+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 2.544403076171875
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: StandardScaler
      operator_config:
        feature_augmentation: sklearn.preprocessing._data.StandardScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$e8256e270180:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$e8256e270180:all
        by_source:
          0:
          - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$e8256e270180:all
        by_chain:
          s2.StandardScaler[src=0,sub=0]: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$e8256e270180:all
        metadata:
          class_name: StandardScaler
          name: StandardScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 9.55653190612793
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s2.StandardScaler[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 38.17009925842285
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 8.735179901123047
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: ExtendedMultiplicativeScatterCorrection, SavitzkyGolay, None
        (+1)
      operator_config:
        feature_augmentation:
        - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
        - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
          params:
            window_length: 15
        - null
        - nirs4all.operators.transforms.nirs.AreaNormalization
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$33af94b1bf58:all
        - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$eeb09d32a26b:all
        - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$ac71c0f61352:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$33af94b1bf58:all
            - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$eeb09d32a26b:all
            - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$ac71c0f61352:all
        by_source:
          0:
          - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$33af94b1bf58:all
          - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$eeb09d32a26b:all
          - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$ac71c0f61352:all
        by_chain:
          s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=0]: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$33af94b1bf58:all
          s5.SavitzkyGolay[src=0,sub=1]: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$eeb09d32a26b:all
          s5.AreaNormalization[src=0,sub=2]: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$ac71c0f61352:all
        metadata:
          class_name: AreaNormalization
          name: AreaNormalization_3
      branch_path: []
      branch_name: ''
      duration_ms: 56.63800239562988
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=0]
      - s5.SavitzkyGolay[src=0,sub=1]
      - s5.AreaNormalization[src=0,sub=2]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 2304
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 4
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          error_score: .nan
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$9f79d59455ab:0
        - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$9f79d59455ab:1
        - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$9f79d59455ab:0
          1: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$9f79d59455ab:1
          2: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$9f79d59455ab:0
            - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$9f79d59455ab:1
            - 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0589_PLS_PP_SELECTION_NO_SAVE_2821fe$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 688.1849765777588
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 2304
      output_shape:
      - 60
      - 2304
      input_features_shape:
      - - 60
        - 4
        - 576
      output_features_shape:
      - - 60
        - 4
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: Std|Std>ExtendedMSC|Std>SG|Std>AreaNormalization
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_2821fe
      n_steps: 6
      n_artifacts: 8
