schema_version: '2.0'
uid: f8379257-a6d1-487a-868d-0130ab3fa930
pipeline_id: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3
name: PLS_PP_SELECTION_NO_SAVE_35bfa3
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:49:01.159560+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: null
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - nirs4all.operators.transforms.signal.Detrend
    - class: nirs4all.operators.transforms.signal.Gaussian
      params:
        order: 1
        sigma: 2
    - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
      params:
        window_length: 15
        deriv: 2
    - nirs4all.operators.transforms.nirs.AreaNormalization
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      error_score: .nan
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: null
- _cartesian_:
  - nirs4all.operators.transforms.signal.Detrend
  - class: nirs4all.operators.transforms.signal.Gaussian
    params:
      order: 1
      sigma: 2
  - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
    params:
      window_length: 15
      deriv: 2
  - nirs4all.operators.transforms.nirs.AreaNormalization
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:49:01.179627+00:00'
    params: {}
    version: 3
  - artifact_id: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$51eb708c8a1f:all
    content_hash: sha256:11ce246bc67c631c59d4827a162f06b45fa0f87770f7d8325a0c50c7f6d72fcf
    path: transformer_Detrend_11ce246bc67c.joblib
    chain_path: s5.Detrend[src=0,sub=0]
    source_index: 0
    pipeline_id: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: Detrend
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 90
    created_at: '2026-01-08T17:49:01.191258+00:00'
    params: {}
    version: 3
  - artifact_id: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$5b4a7bbb9aae:all
    content_hash: sha256:fcef74d1464ae75c275fc2b03bb2c435a0787cd50861cdf41aedf150ab9f3eff
    path: transformer_Gaussian_fcef74d1464a.joblib
    chain_path: s5.Gaussian[src=0,sub=1]
    source_index: 0
    pipeline_id: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: Gaussian
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 103
    created_at: '2026-01-08T17:49:01.197117+00:00'
    params: {}
    version: 3
  - artifact_id: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$296923040127:all
    content_hash: sha256:5c353b1441d52f528075c64bd2477db6d0df3f619817bfa27a68d32928e99953
    path: transformer_SavitzkyGolay_5c353b1441d5.joblib
    chain_path: s5.SavitzkyGolay[src=0,sub=2]
    source_index: 0
    pipeline_id: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3
    branch_path: []
    step_index: 5
    substep_index: 2
    fold_id: null
    artifact_type: transformer
    class_name: SavitzkyGolay
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 137
    created_at: '2026-01-08T17:49:01.202794+00:00'
    params: {}
    version: 3
  - artifact_id: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$077c9e0a6ccf:all
    content_hash: sha256:3381c200ece0f7e7ac9f3c9a70feb2bc950b0271d9a3c4d8bfc727bd6a3bfbb5
    path: transformer_AreaNormalization_3381c200ece0.joblib
    chain_path: s5.AreaNormalization[src=0,sub=3]
    source_index: 0
    pipeline_id: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3
    branch_path: []
    step_index: 5
    substep_index: 3
    fold_id: null
    artifact_type: transformer
    class_name: AreaNormalization
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 103
    created_at: '2026-01-08T17:49:01.207414+00:00'
    params: {}
    version: 3
  - artifact_id: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$9f79d59455ab:0
    content_hash: sha256:802e18dc659ec72d663808f95a2bf19fa95e7ca63edf355ff9b04f278ea3ccee
    path: model_PLSRegression_802e18dc659e.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 195482
    created_at: '2026-01-08T17:49:01.720690+00:00'
    params: {}
    version: 3
  - artifact_id: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$9f79d59455ab:1
    content_hash: sha256:7e1b6e229f137574d3e3188982a70ee413e3f6b5eab7693341f83aa73f2b0f4f
    path: model_PLSRegression_7e1b6e229f13.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 195887
    created_at: '2026-01-08T17:49:01.725294+00:00'
    params: {}
    version: 3
  - artifact_id: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$9f79d59455ab:2
    content_hash: sha256:58344b06f3c1e8dde81ba2ea44c500c1d0a261471b0c4f47bb0b2c9e19beee41
    path: model_PLSRegression_58344b06f3c1.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 195857
    created_at: '2026-01-08T17:49:01.729739+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  e21f33b4-458:
    trace_id: e21f33b4-458
    pipeline_uid: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3
    created_at: '2026-01-08T17:49:01.160764+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 2.373933792114258
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 1.6703605651855469
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 18.63861083984375
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 5.211114883422852
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: Detrend, Gaussian, SavitzkyGolay (+1)
      operator_config:
        feature_augmentation:
        - nirs4all.operators.transforms.signal.Detrend
        - class: nirs4all.operators.transforms.signal.Gaussian
          params:
            order: 1
            sigma: 2
        - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
          params:
            window_length: 15
            deriv: 2
        - nirs4all.operators.transforms.nirs.AreaNormalization
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$51eb708c8a1f:all
        - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$5b4a7bbb9aae:all
        - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$296923040127:all
        - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$077c9e0a6ccf:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$51eb708c8a1f:all
            - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$5b4a7bbb9aae:all
            - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$296923040127:all
            - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$077c9e0a6ccf:all
        by_source:
          0:
          - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$51eb708c8a1f:all
          - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$5b4a7bbb9aae:all
          - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$296923040127:all
          - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$077c9e0a6ccf:all
        by_chain:
          s5.Detrend[src=0,sub=0]: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$51eb708c8a1f:all
          s5.Gaussian[src=0,sub=1]: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$5b4a7bbb9aae:all
          s5.SavitzkyGolay[src=0,sub=2]: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$296923040127:all
          s5.AreaNormalization[src=0,sub=3]: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$077c9e0a6ccf:all
        metadata:
          class_name: AreaNormalization
          name: AreaNormalization_4
      branch_path: []
      branch_name: ''
      duration_ms: 32.953500747680664
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.Detrend[src=0,sub=0]
      - s5.Gaussian[src=0,sub=1]
      - s5.SavitzkyGolay[src=0,sub=2]
      - s5.AreaNormalization[src=0,sub=3]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 2880
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 5
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          error_score: .nan
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$9f79d59455ab:0
        - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$9f79d59455ab:1
        - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$9f79d59455ab:0
          1: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$9f79d59455ab:1
          2: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$9f79d59455ab:0
            - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$9f79d59455ab:1
            - 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0434_PLS_PP_SELECTION_NO_SAVE_35bfa3$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 536.5235805511475
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 2880
      output_shape:
      - 60
      - 2880
      input_features_shape:
      - - 60
        - 5
        - 576
      output_features_shape:
      - - 60
        - 5
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: raw|Detr|Gauss|SG|AreaNormalization
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_35bfa3
      n_steps: 6
      n_artifacts: 8
