schema_version: '2.0'
uid: 926669f9-8443-4132-a72f-f2715be3a065
pipeline_id: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9
name: PLS_PP_SELECTION_NO_SAVE_0fe6a9
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:48:55.847962+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: null
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - nirs4all.operators.transforms.signal.Detrend
    - class: nirs4all.operators.transforms.signal.Gaussian
      params:
        order: 1
        sigma: 2
    - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
      params:
        window_length: 15
        deriv: 1
    - class: nirs4all.operators.transforms.nirs.Wavelet
      params:
        wavelet: coif3
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      error_score: .nan
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: null
- _cartesian_:
  - nirs4all.operators.transforms.signal.Detrend
  - class: nirs4all.operators.transforms.signal.Gaussian
    params:
      order: 1
      sigma: 2
  - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
    params:
      window_length: 15
      deriv: 1
  - class: nirs4all.operators.transforms.nirs.Wavelet
    params:
      wavelet: coif3
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:48:55.869299+00:00'
    params: {}
    version: 3
  - artifact_id: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$51eb708c8a1f:all
    content_hash: sha256:11ce246bc67c631c59d4827a162f06b45fa0f87770f7d8325a0c50c7f6d72fcf
    path: transformer_Detrend_11ce246bc67c.joblib
    chain_path: s5.Detrend[src=0,sub=0]
    source_index: 0
    pipeline_id: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: Detrend
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 90
    created_at: '2026-01-08T17:48:55.882404+00:00'
    params: {}
    version: 3
  - artifact_id: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$5b4a7bbb9aae:all
    content_hash: sha256:fcef74d1464ae75c275fc2b03bb2c435a0787cd50861cdf41aedf150ab9f3eff
    path: transformer_Gaussian_fcef74d1464a.joblib
    chain_path: s5.Gaussian[src=0,sub=1]
    source_index: 0
    pipeline_id: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: Gaussian
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 103
    created_at: '2026-01-08T17:48:55.885217+00:00'
    params: {}
    version: 3
  - artifact_id: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$296923040127:all
    content_hash: sha256:d663934f32b4b5e8dba18585ed74e0c4e66ed1008ee606d100f374d3224f9c49
    path: transformer_SavitzkyGolay_d663934f32b4.joblib
    chain_path: s5.SavitzkyGolay[src=0,sub=2]
    source_index: 0
    pipeline_id: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9
    branch_path: []
    step_index: 5
    substep_index: 2
    fold_id: null
    artifact_type: transformer
    class_name: SavitzkyGolay
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 137
    created_at: '2026-01-08T17:48:55.890321+00:00'
    params: {}
    version: 3
  - artifact_id: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$3569153fa566:all
    content_hash: sha256:f2c1d06f4298f812e17b88a6602355856be25df4ed5fa680286d202bd476cb07
    path: transformer_Wavelet_f2c1d06f4298.joblib
    chain_path: s5.Wavelet[src=0,sub=3]
    source_index: 0
    pipeline_id: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9
    branch_path: []
    step_index: 5
    substep_index: 3
    fold_id: null
    artifact_type: transformer
    class_name: Wavelet
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 114
    created_at: '2026-01-08T17:48:55.893800+00:00'
    params: {}
    version: 3
  - artifact_id: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$9f79d59455ab:0
    content_hash: sha256:1125bbe474d95d4aa4488f6f8763088c21572441c4254ccf4e5d9555ea392af5
    path: model_PLSRegression_1125bbe474d9.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 195648
    created_at: '2026-01-08T17:48:56.445803+00:00'
    params: {}
    version: 3
  - artifact_id: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$9f79d59455ab:1
    content_hash: sha256:579bb69d3a293c4fe23247f4b0508bea88df13bcd304ff01bd7790531c0c0a25
    path: model_PLSRegression_579bb69d3a29.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 195954
    created_at: '2026-01-08T17:48:56.450375+00:00'
    params: {}
    version: 3
  - artifact_id: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$9f79d59455ab:2
    content_hash: sha256:9aa86b4e21de710a30be987e8fc4b135e014d2ef9e81f042159790f54f20a826
    path: model_PLSRegression_9aa86b4e21de.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 195951
    created_at: '2026-01-08T17:48:56.454828+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  f082db88-fb8:
    trace_id: f082db88-fb8
    pipeline_uid: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9
    created_at: '2026-01-08T17:48:55.849184+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 2.8085708618164062
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 1.8284320831298828
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 19.38152313232422
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 6.91533088684082
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: Detrend, Gaussian, SavitzkyGolay (+1)
      operator_config:
        feature_augmentation:
        - nirs4all.operators.transforms.signal.Detrend
        - class: nirs4all.operators.transforms.signal.Gaussian
          params:
            order: 1
            sigma: 2
        - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
          params:
            window_length: 15
            deriv: 1
        - class: nirs4all.operators.transforms.nirs.Wavelet
          params:
            wavelet: coif3
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$51eb708c8a1f:all
        - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$5b4a7bbb9aae:all
        - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$296923040127:all
        - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$3569153fa566:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$51eb708c8a1f:all
            - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$5b4a7bbb9aae:all
            - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$296923040127:all
            - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$3569153fa566:all
        by_source:
          0:
          - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$51eb708c8a1f:all
          - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$5b4a7bbb9aae:all
          - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$296923040127:all
          - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$3569153fa566:all
        by_chain:
          s5.Detrend[src=0,sub=0]: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$51eb708c8a1f:all
          s5.Gaussian[src=0,sub=1]: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$5b4a7bbb9aae:all
          s5.SavitzkyGolay[src=0,sub=2]: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$296923040127:all
          s5.Wavelet[src=0,sub=3]: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$3569153fa566:all
        metadata:
          class_name: Wavelet
          name: Wavelet_4
      branch_path: []
      branch_name: ''
      duration_ms: 28.75494956970215
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.Detrend[src=0,sub=0]
      - s5.Gaussian[src=0,sub=1]
      - s5.SavitzkyGolay[src=0,sub=2]
      - s5.Wavelet[src=0,sub=3]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 2880
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 5
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          error_score: .nan
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$9f79d59455ab:0
        - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$9f79d59455ab:1
        - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$9f79d59455ab:0
          1: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$9f79d59455ab:1
          2: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$9f79d59455ab:0
            - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$9f79d59455ab:1
            - 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0430_PLS_PP_SELECTION_NO_SAVE_0fe6a9$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 573.5538005828857
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 2880
      output_shape:
      - 60
      - 2880
      input_features_shape:
      - - 60
        - 5
        - 576
      output_features_shape:
      - - 60
        - 5
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: raw|Detr|Gauss|SG|Wavelet
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_0fe6a9
      n_steps: 6
      n_artifacts: 8
