schema_version: '2.0'
uid: f6eae3bc-a041-459c-b021-5dad5ac2a86f
pipeline_id: 0568_PLS_PP_SELECTION_NO_SAVE_da1404
name: PLS_PP_SELECTION_NO_SAVE_da1404
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:52:32.147674+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: sklearn.preprocessing._data.StandardScaler
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
    - null
    - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
      params:
        window_length: 15
        deriv: 2
    - nirs4all.operators.transforms.signal.Detrend
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      error_score: .nan
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: sklearn.preprocessing._data.StandardScaler
- _cartesian_:
  - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
  - null
  - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
    params:
      window_length: 15
      deriv: 2
  - nirs4all.operators.transforms.signal.Detrend
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0568_PLS_PP_SELECTION_NO_SAVE_da1404$e8256e270180:all
    content_hash: sha256:62fbca7e67132ee4c3eac6fcd60d6652d6e5c748d596fbba7aa83af04e3a52fc
    path: transformer_StandardScaler_62fbca7e6713.joblib
    chain_path: s2.StandardScaler[src=0,sub=0]
    source_index: 0
    pipeline_id: 0568_PLS_PP_SELECTION_NO_SAVE_da1404
    branch_path: []
    step_index: 2
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: StandardScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 12015
    created_at: '2026-01-08T17:52:32.155172+00:00'
    params: {}
    version: 3
  - artifact_id: 0568_PLS_PP_SELECTION_NO_SAVE_da1404$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0568_PLS_PP_SELECTION_NO_SAVE_da1404
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:52:32.204875+00:00'
    params: {}
    version: 3
  - artifact_id: 0568_PLS_PP_SELECTION_NO_SAVE_da1404$33af94b1bf58:all
    content_hash: sha256:0721098a9e95cc2ee2f5245b14331db5bda396203e6f9c2dc951c1d3611e0a2f
    path: transformer_ExtendedMultiplicativeScatterCorrection_0721098a9e95.joblib
    chain_path: s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=0]
    source_index: 0
    pipeline_id: 0568_PLS_PP_SELECTION_NO_SAVE_da1404
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: ExtendedMultiplicativeScatterCorrection
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 4485
    created_at: '2026-01-08T17:52:32.227225+00:00'
    params: {}
    version: 3
  - artifact_id: 0568_PLS_PP_SELECTION_NO_SAVE_da1404$eeb09d32a26b:all
    content_hash: sha256:5c353b1441d52f528075c64bd2477db6d0df3f619817bfa27a68d32928e99953
    path: transformer_SavitzkyGolay_5c353b1441d5.joblib
    chain_path: s5.SavitzkyGolay[src=0,sub=1]
    source_index: 0
    pipeline_id: 0568_PLS_PP_SELECTION_NO_SAVE_da1404
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: SavitzkyGolay
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 137
    created_at: '2026-01-08T17:52:32.230951+00:00'
    params: {}
    version: 3
  - artifact_id: 0568_PLS_PP_SELECTION_NO_SAVE_da1404$5500093c92e4:all
    content_hash: sha256:11ce246bc67c631c59d4827a162f06b45fa0f87770f7d8325a0c50c7f6d72fcf
    path: transformer_Detrend_11ce246bc67c.joblib
    chain_path: s5.Detrend[src=0,sub=2]
    source_index: 0
    pipeline_id: 0568_PLS_PP_SELECTION_NO_SAVE_da1404
    branch_path: []
    step_index: 5
    substep_index: 2
    fold_id: null
    artifact_type: transformer
    class_name: Detrend
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 90
    created_at: '2026-01-08T17:52:32.234624+00:00'
    params: {}
    version: 3
  - artifact_id: 0568_PLS_PP_SELECTION_NO_SAVE_da1404$9f79d59455ab:0
    content_hash: sha256:6243d265510d1516a33456daa1ef12c0b93766b098a63483bc7bbab112fdf00e
    path: model_PLSRegression_6243d265510d.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0568_PLS_PP_SELECTION_NO_SAVE_da1404
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 157971
    created_at: '2026-01-08T17:52:32.806391+00:00'
    params: {}
    version: 3
  - artifact_id: 0568_PLS_PP_SELECTION_NO_SAVE_da1404$9f79d59455ab:1
    content_hash: sha256:57e954dee2baf23e057163247fbcf4ad37e5f4580595df46580eb12237d4cdd7
    path: model_PLSRegression_57e954dee2ba.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0568_PLS_PP_SELECTION_NO_SAVE_da1404
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 158385
    created_at: '2026-01-08T17:52:32.809571+00:00'
    params: {}
    version: 3
  - artifact_id: 0568_PLS_PP_SELECTION_NO_SAVE_da1404$9f79d59455ab:2
    content_hash: sha256:2533a0c41aa305e5c5dca7c9bc3547ffe4b599dc07dedbcc45e3f81de34ca79f
    path: model_PLSRegression_2533a0c41aa3.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0568_PLS_PP_SELECTION_NO_SAVE_da1404
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 158438
    created_at: '2026-01-08T17:52:32.812710+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  ad73f041-266:
    trace_id: ad73f041-266
    pipeline_uid: 0568_PLS_PP_SELECTION_NO_SAVE_da1404
    created_at: '2026-01-08T17:52:32.148787+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 3.0450820922851562
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: StandardScaler
      operator_config:
        feature_augmentation: sklearn.preprocessing._data.StandardScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$e8256e270180:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$e8256e270180:all
        by_source:
          0:
          - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$e8256e270180:all
        by_chain:
          s2.StandardScaler[src=0,sub=0]: 0568_PLS_PP_SELECTION_NO_SAVE_da1404$e8256e270180:all
        metadata:
          class_name: StandardScaler
          name: StandardScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 8.591651916503906
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s2.StandardScaler[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0568_PLS_PP_SELECTION_NO_SAVE_da1404$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 53.63154411315918
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 6.001472473144531
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: ExtendedMultiplicativeScatterCorrection, None, SavitzkyGolay
        (+1)
      operator_config:
        feature_augmentation:
        - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
        - null
        - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
          params:
            window_length: 15
            deriv: 2
        - nirs4all.operators.transforms.signal.Detrend
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$33af94b1bf58:all
        - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$eeb09d32a26b:all
        - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$5500093c92e4:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$33af94b1bf58:all
            - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$eeb09d32a26b:all
            - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$5500093c92e4:all
        by_source:
          0:
          - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$33af94b1bf58:all
          - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$eeb09d32a26b:all
          - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$5500093c92e4:all
        by_chain:
          s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=0]: 0568_PLS_PP_SELECTION_NO_SAVE_da1404$33af94b1bf58:all
          s5.SavitzkyGolay[src=0,sub=1]: 0568_PLS_PP_SELECTION_NO_SAVE_da1404$eeb09d32a26b:all
          s5.Detrend[src=0,sub=2]: 0568_PLS_PP_SELECTION_NO_SAVE_da1404$5500093c92e4:all
        metadata:
          class_name: Detrend
          name: Detrend_3
      branch_path: []
      branch_name: ''
      duration_ms: 44.93355751037598
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=0]
      - s5.SavitzkyGolay[src=0,sub=1]
      - s5.Detrend[src=0,sub=2]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 2304
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 4
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          error_score: .nan
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$9f79d59455ab:0
        - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$9f79d59455ab:1
        - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0568_PLS_PP_SELECTION_NO_SAVE_da1404$9f79d59455ab:0
          1: 0568_PLS_PP_SELECTION_NO_SAVE_da1404$9f79d59455ab:1
          2: 0568_PLS_PP_SELECTION_NO_SAVE_da1404$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$9f79d59455ab:0
            - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$9f79d59455ab:1
            - 0568_PLS_PP_SELECTION_NO_SAVE_da1404$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0568_PLS_PP_SELECTION_NO_SAVE_da1404$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 575.270414352417
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 2304
      output_shape:
      - 60
      - 2304
      input_features_shape:
      - - 60
        - 4
        - 576
      output_features_shape:
      - - 60
        - 4
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: Std|Std>ExtendedMSC|Std>SG|Std>Detr
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_da1404
      n_steps: 6
      n_artifacts: 8
