uid: 7f89da62-6527-4ae6-9abb-4fa1d5d1a358
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: cattle_manure_total_n_ks
created_at: '2025-12-12T07:58:58.935606+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:125d94dee500492a3bdb8dd8b9fa106b8b2b34e5f42944e4b15d55960ffb73d1
  name: ASLSBaseline_1
  path: ASLSBaseline_125d94.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T07:58:59.019192+00:00'
  step: 1
- hash: sha256:35a03f66a5ce175432536f868773ebce44b892b2836dcc3f21264678814c9581
  name: y_StandardScaler
  path: StandardScaler_35a03f.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 442
  saved_at: '2025-12-12T07:58:59.150339+00:00'
  step: 4
- hash: sha256:df0e6280c238a24e3ec44b22bc9fcddcc1b0841f6575f06d1895df2a2a9f9e68
  name: StandardScaler_1
  path: StandardScaler_df0e62.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 21800
  saved_at: '2025-12-12T07:58:59.158583+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T07:58:59.172422+00:00'
  step: 6
- hash: sha256:1db9f9a5c127ba70f1a3c850c51f8c31351d192ca9288bef332a16093bc131d5
  name: PCA_1
  path: PCA_1db9f9.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 157683
  saved_at: '2025-12-12T07:58:59.255588+00:00'
  step: 7
- hash: sha256:aa283d53aea94e1aeb1f92ca04c3f881e60fecf4e1a17dbd5969fc572e87762a
  name: StandardScaler_1
  path: StandardScaler_aa283d.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1208
  saved_at: '2025-12-12T07:58:59.299173+00:00'
  step: 8
- hash: sha256:240cec9e317bfdf6b756d83c6eb6f5bc6c227fbaa0b8266ef8b6256547d93ed2
  name: PowerTransformer_1
  path: PowerTransformer_240cec.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1679
  saved_at: '2025-12-12T07:58:59.362254+00:00'
  step: 9
- hash: sha256:41a616b66a08b9079a5541dd124119d44f59ad82fb524fa891e289fb6acc473d
  name: AutoGluon_1.pkl
  path: TabularPredictor_41a616.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 24476
  saved_at: '2025-12-12T07:59:16.453458+00:00'
  step: 10
- hash: sha256:b5e96cc0455608d518385d5270fe95cf7cd6663a6175aa2ed7738410f57ffa70
  name: AutoGluon_2.pkl
  path: TabularPredictor_b5e96c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 24476
  saved_at: '2025-12-12T07:59:16.453998+00:00'
  step: 10
- hash: sha256:a1d8e4bd86d351f6e7033d5b2a606ab43d0bc33c064977c4f69b658946af70f5
  name: AutoGluon_3.pkl
  path: TabularPredictor_a1d8e4.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 24485
  saved_at: '2025-12-12T07:59:16.454543+00:00'
  step: 10
- hash: sha256:eb583a03c2e6a9a913bf60d44f9e0f90bc846b501afb35ae8883c8d0f5a4bcc2
  name: TabPFN_1.pkl
  path: TabPFNRegressor_eb583a.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42153197
  saved_at: '2025-12-12T07:59:45.214533+00:00'
  step: 11
- hash: sha256:0def1c5a6cd0152f1278d2fc8fe9b70cb9dc16920e2c6494f56c68d1652e1378
  name: TabPFN_2.pkl
  path: TabPFNRegressor_0def1c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42161911
  saved_at: '2025-12-12T07:59:45.261646+00:00'
  step: 11
- hash: sha256:382460114ee77e5cdc85688fe3a53965c7b1c4f597e2871f90a466c5c6424cac
  name: TabPFN_3.pkl
  path: TabPFNRegressor_382460.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42161907
  saved_at: '2025-12-12T07:59:45.307450+00:00'
  step: 11
- hash: sha256:2ad20d502a53bd76317740cb86b0ca956ebc90eb8be7b60058343be6f71a713e
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_2ad20d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42153240
  saved_at: '2025-12-12T08:00:45.216045+00:00'
  step: 12
- hash: sha256:517cafd5313a125fb8bd0b1cff0d5a99ee7accbdf3e1ed901ff6b8aac7ef43e1
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_517caf.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42161944
  saved_at: '2025-12-12T08:00:45.264830+00:00'
  step: 12
- hash: sha256:0afb423d1a882cbc451451552ac445795f596d1a661728424807a5408c73fa59
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_0afb42.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42161948
  saved_at: '2025-12-12T08:00:45.312652+00:00'
  step: 12
predictions: []
