schema_version: '2.0'
uid: 7935dca7-7dc4-46d1-b536-face2f87ecb5
pipeline_id: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3
name: PLS_PP_SELECTION_NO_SAVE_4715e3
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:47:17.606600+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: null
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
    - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
      params:
        window_length: 15
    - null
    - null
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      error_score: .nan
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: null
- _cartesian_:
  - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
  - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
    params:
      window_length: 15
  - null
  - null
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:47:17.627047+00:00'
    params: {}
    version: 3
  - artifact_id: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$33af94b1bf58:all
    content_hash: sha256:691364ebf5c9cf5f03e16c3b48e170cf0041f7b9fd02c8c40dcdafece2312e1d
    path: transformer_ExtendedMultiplicativeScatterCorrection_691364ebf5c9.joblib
    chain_path: s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=0]
    source_index: 0
    pipeline_id: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: ExtendedMultiplicativeScatterCorrection
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 5683
    created_at: '2026-01-08T17:47:17.644192+00:00'
    params: {}
    version: 3
  - artifact_id: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$eeb09d32a26b:all
    content_hash: sha256:c90a6e998d89e802fdc8ae5af3e9cd7288130360151139484ffc6499b3403f5a
    path: transformer_SavitzkyGolay_c90a6e998d89.joblib
    chain_path: s5.SavitzkyGolay[src=0,sub=1]
    source_index: 0
    pipeline_id: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: SavitzkyGolay
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 137
    created_at: '2026-01-08T17:47:17.646473+00:00'
    params: {}
    version: 3
  - artifact_id: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$9f79d59455ab:0
    content_hash: sha256:66ccabe9e9666ea4ddf0c1bc9a7a5961c44476ccb9f62e24bf28646f793196c2
    path: model_PLSRegression_66ccabe9e966.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 118912
    created_at: '2026-01-08T17:47:18.149032+00:00'
    params: {}
    version: 3
  - artifact_id: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$9f79d59455ab:1
    content_hash: sha256:53ef1e33b60db96a9d11a64e5ba86ca7ab6dfc703497201d468eabb9328e5443
    path: model_PLSRegression_53ef1e33b60d.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 119160
    created_at: '2026-01-08T17:47:18.151806+00:00'
    params: {}
    version: 3
  - artifact_id: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$9f79d59455ab:2
    content_hash: sha256:926780c732afe9105f9a969e2a475d6362b00e7041fa1fa96c7cc77b0a10bf21
    path: model_PLSRegression_926780c732af.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 119117
    created_at: '2026-01-08T17:47:18.154543+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  9b26738c-8c2:
    trace_id: 9b26738c-8c2
    pipeline_uid: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3
    created_at: '2026-01-08T17:47:17.607650+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 2.4518966674804688
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 2.306699752807617
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 19.9277400970459
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 6.858587265014648
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: ExtendedMultiplicativeScatterCorrection, SavitzkyGolay, None
        (+1)
      operator_config:
        feature_augmentation:
        - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
        - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
          params:
            window_length: 15
        - null
        - null
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$33af94b1bf58:all
        - 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$eeb09d32a26b:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$33af94b1bf58:all
            - 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$eeb09d32a26b:all
        by_source:
          0:
          - 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$33af94b1bf58:all
          - 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$eeb09d32a26b:all
        by_chain:
          s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=0]: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$33af94b1bf58:all
          s5.SavitzkyGolay[src=0,sub=1]: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$eeb09d32a26b:all
        metadata:
          class_name: SavitzkyGolay
          name: SavitzkyGolay_2
      branch_path: []
      branch_name: ''
      duration_ms: 15.438556671142578
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=0]
      - s5.SavitzkyGolay[src=0,sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 1728
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 3
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          error_score: .nan
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$9f79d59455ab:0
        - 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$9f79d59455ab:1
        - 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$9f79d59455ab:0
          1: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$9f79d59455ab:1
          2: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$9f79d59455ab:0
            - 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$9f79d59455ab:1
            - 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0346_PLS_PP_SELECTION_NO_SAVE_4715e3$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 530.6177139282227
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 1728
      output_shape:
      - 60
      - 1728
      input_features_shape:
      - - 60
        - 3
        - 576
      output_features_shape:
      - - 60
        - 3
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: raw|ExtendedMSC|SG
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_4715e3
      n_steps: 6
      n_artifacts: 6
