uid: fdc49ca0-84bb-4e28-8b0d-9e0deb10229b
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: cassava_tcc_4468_davrieuxrobustness2013
created_at: '2025-12-12T10:29:22.978069+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:e3981c22fe01bf6ba48b414ed19291553d7fa375224b447ff7d90a870e91f7c3
  name: ASLSBaseline_1
  path: ASLSBaseline_e3981c.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2025-12-12T10:29:24.261548+00:00'
  step: 1
- hash: sha256:eb4af3c13c0b850206dd728281f7ce0b3aebfc2b55eaa3e44ab2e2129fb3e857
  name: y_StandardScaler
  path: StandardScaler_eb4af3.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 444
  saved_at: '2025-12-12T10:30:37.119818+00:00'
  step: 4
- hash: sha256:0363b357788a3800d1526a76c88bfb10c0ced355bfec4ae175bf288876ff2fc0
  name: StandardScaler_1
  path: StandardScaler_0363b3.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 23833
  saved_at: '2025-12-12T10:30:37.161794+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T10:30:37.285544+00:00'
  step: 6
- hash: sha256:83966030bea7be4a7ce9d2914787d6f1925d1136efd8d8682110fc92bdaa1ab5
  name: PCA_1
  path: PCA_839660.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 44050
  saved_at: '2025-12-12T10:30:37.515063+00:00'
  step: 7
- hash: sha256:2d1fa24dee20bb73341bc03a192bf87a007fbd5d197e40d636ea933c83b8f7fb
  name: StandardScaler_1
  path: StandardScaler_2d1fa2.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 644
  saved_at: '2025-12-12T10:30:37.571925+00:00'
  step: 8
- hash: sha256:0738ac6e05c9cdcec66276b8e3ea57a9c0ba3c64a5b3e056ccf770a177d3006b
  name: PowerTransformer_1
  path: PowerTransformer_0738ac.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 849
  saved_at: '2025-12-12T10:30:37.649270+00:00'
  step: 9
- hash: sha256:40ffea14502835c9c0c84cb0320eeaa2711543234ab047fa0b439530fc56f79e
  name: AutoGluon_1.pkl
  path: TabularPredictor_40ffea.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 13481
  saved_at: '2025-12-12T10:31:06.299620+00:00'
  step: 10
- hash: sha256:44e32c1fed19294907b870e72b21ece6d319dc1a21e3376af6eb8518030bbb1d
  name: AutoGluon_2.pkl
  path: TabularPredictor_44e32c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 13463
  saved_at: '2025-12-12T10:31:06.299962+00:00'
  step: 10
- hash: sha256:067a82f22ff5834fa024fa0f645cc3d1399b28a9f761bc58940ef16c1bfaa0dd
  name: AutoGluon_3.pkl
  path: TabularPredictor_067a82.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 13481
  saved_at: '2025-12-12T10:31:06.300233+00:00'
  step: 10
- hash: sha256:77de552fcf29ec9dcc5a0d9b3b4e236d0ef1e7b70f95be72bfa73a584ef4aeac
  name: TabPFN_1.pkl
  path: TabPFNRegressor_77de55.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 46140306
  saved_at: '2025-12-12T10:35:44.245094+00:00'
  step: 11
- hash: sha256:d09a38e1cab167cb8f995d7e22bc28606a8795718e620fbf55154d7b685bdd78
  name: TabPFN_2.pkl
  path: TabPFNRegressor_d09a38.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 46140306
  saved_at: '2025-12-12T10:35:44.309599+00:00'
  step: 11
- hash: sha256:4bb84c3d96d257db57cc9c87baa5c8f2745e5885d3023508af3d4e1db35ffc1c
  name: TabPFN_3.pkl
  path: TabPFNRegressor_4bb84c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 46142548
  saved_at: '2025-12-12T10:35:44.369636+00:00'
  step: 11
- hash: sha256:895455e59dc8220ae1889d907fde00f76f1529446c8a6c2d595ed536c19e7082
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_895455.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 46140343
  saved_at: '2025-12-12T10:46:33.632040+00:00'
  step: 12
- hash: sha256:422d4e83eef9c789370a7861da4ee26819ace59348a6a8920f8149216e98c306
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_422d4e.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 46140343
  saved_at: '2025-12-12T10:46:33.692505+00:00'
  step: 12
- hash: sha256:40a61110d3a16d400af90b7e4d1722cb8c29a00e658003eb5818d5603986623f
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_40a611.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 46142583
  saved_at: '2025-12-12T10:46:33.753442+00:00'
  step: 12
predictions: []
