uid: cdbc5518-a57f-4bb3-aa9f-a0abc8ae6b07
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: rice_ph
created_at: '2025-12-12T09:30:57.484016+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:b4db648a2547c1dc21ee2878cc4522bcc8f758afcdc997e89b71292698331f0a
  name: ASLSBaseline_1
  path: ASLSBaseline_b4db64.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2025-12-12T09:30:57.953924+00:00'
  step: 1
- hash: sha256:c5a5e26c310901976c3c8311d60088f801eeaede81d977ff63e4ca51d0ec2862
  name: y_StandardScaler
  path: StandardScaler_c5a5e2.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 446
  saved_at: '2025-12-12T09:31:36.381654+00:00'
  step: 4
- hash: sha256:55c9b6c11dc8177f4481694813c0fd06d9246da22a422abb204816d33b634e2e
  name: StandardScaler_1
  path: StandardScaler_55c9b6.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 6357
  saved_at: '2025-12-12T09:31:36.400740+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T09:31:36.458309+00:00'
  step: 6
- hash: sha256:1829e3f71e85336ccc87a7ab9941e6e0f8a637dacf3265c5025b84eb27e5d7f9
  name: PCA_1
  path: PCA_1829e3.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9482
  saved_at: '2025-12-12T09:31:36.516542+00:00'
  step: 7
- hash: sha256:db228c06fa09a9a6cc8d175c6bfb6e2c1aee73871a5b074cf016fd3d6976058e
  name: StandardScaler_1
  path: StandardScaler_db228c.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 601
  saved_at: '2025-12-12T09:31:36.578643+00:00'
  step: 8
- hash: sha256:7630bd08d817e041e9de4972b99fd4cd0dfc1d34e221267e994c56d13b45ba53
  name: PowerTransformer_1
  path: PowerTransformer_7630bd.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 783
  saved_at: '2025-12-12T09:31:36.650087+00:00'
  step: 9
- hash: sha256:bd506f5868678bf1028845bbc780c91adc2c23faf73961087ae4cb1b43607edb
  name: AutoGluon_1.pkl
  path: TabularPredictor_bd506f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12755
  saved_at: '2025-12-12T09:35:20.379757+00:00'
  step: 10
- hash: sha256:653f3bfe08411b5d47eafd8b25df047fdef9cc8275cc94d1fc4c805638985d80
  name: AutoGluon_2.pkl
  path: TabularPredictor_653f3b.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12764
  saved_at: '2025-12-12T09:35:20.387422+00:00'
  step: 10
- hash: sha256:3459d874e1eaff8d666b5c6baaa29b5e7684dd79b020171d33ecf56bc32cb938
  name: AutoGluon_3.pkl
  path: TabularPredictor_3459d8.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12764
  saved_at: '2025-12-12T09:35:20.387741+00:00'
  step: 10
- hash: sha256:b72b39bf0e766633315967fed481e1d63805ed84ffc3b64d4ba56f0fab44d299
  name: TabPFN_1.pkl
  path: TabPFNRegressor_b72b39.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44484030
  saved_at: '2025-12-12T09:38:20.716690+00:00'
  step: 11
- hash: sha256:df86bd452852100a6921a22c4dd2a10f25f5f9ab16b686268980f29f2895d3ab
  name: TabPFN_2.pkl
  path: TabPFNRegressor_df86bd.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44484030
  saved_at: '2025-12-12T09:38:20.764719+00:00'
  step: 11
- hash: sha256:1277c905119b9ab6d7c08d195627031cd25a2f867929e92a00db8a5e8095abdc
  name: TabPFN_3.pkl
  path: TabPFNRegressor_1277c9.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44484030
  saved_at: '2025-12-12T09:38:20.812432+00:00'
  step: 11
- hash: sha256:53dd16a937402683fc645b196b74edc80e29a5e84e010d46ed590f80fd697b4c
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_53dd16.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44484067
  saved_at: '2025-12-12T09:45:10.715355+00:00'
  step: 12
- hash: sha256:b3a3344fae45bad96f1c78bb3ef2fa07dea7cfe468b5723858cf16919bedeeb3
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_b3a334.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44484067
  saved_at: '2025-12-12T09:45:10.764157+00:00'
  step: 12
- hash: sha256:246dde33aa89c4faae98c92201aac97fe04202b4c2b2b87ead22fcca74901e5d
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_246dde.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44484067
  saved_at: '2025-12-12T09:45:10.812773+00:00'
  step: 12
predictions: []
