schema_version: '2.0'
uid: 1ced1eca-0695-4cb0-8397-6d6fb598da43
pipeline_id: 0001_SOTA_137acf
name: SOTA_137acf
dataset: corn_oil_80_zhengchenpelegybasesplit
created_at: '2026-01-09T16:47:21.798582+00:00'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 4
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0001_SOTA_137acf$bb12ee38a89c:all
    content_hash: sha256:26b2ddd51689b4d62afd0d8120bf3701bb34aecf8f7c42b134bb6c3d9b5f3096
    path: transformer_ASLSBaseline_26b2ddd51689.joblib
    chain_path: s1.ASLSBaseline[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 1
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: ASLSBaseline
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 216
    created_at: '2026-01-09T16:47:21.821636+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$2865afbbfc1d:all
    content_hash: sha256:81ab3f90bdaf39b4d6be66976524af71d918d9691f774ba2cb394b991a5366f2
    path: encoder_StandardScaler_81ab3f90bdaf.joblib
    chain_path: s2.y_StandardScaler[sub=1]
    source_index: null
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 2
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: StandardScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 443
    created_at: '2026-01-09T16:47:21.855955+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$b3c264a83f45:all
    content_hash: sha256:cb7c5375cc9f73ec350bb0aad744952751c618d680c82fa7a81e0f1282b192a6
    path: transformer_StandardScaler_cb7c5375cc9f.joblib
    chain_path: s3.StandardScaler[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 3
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: StandardScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 14537
    created_at: '2026-01-09T16:47:21.870045+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$900033a82811:all
    content_hash: sha256:8ec25142e9a5b8349d564c95fded66ec65252c94000eb0e74b61cd4b9aae2ee4
    path: transformer_PCA_8ec25142e9a5.joblib
    chain_path: s5.PCA[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: PCA
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 20508
    created_at: '2026-01-09T16:47:21.921084+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$c5f06284fcbc:0
    content_hash: sha256:be43f42d61bad3504691836fa31e6509edbc23e8a8985371cb9bb7b78d4507ee
    path: model_TabPFNRegressor_be43f42d61ba.pkl
    chain_path: s6.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 40937561
    created_at: '2026-01-09T16:47:23.736947+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$c5f06284fcbc:1
    content_hash: sha256:c13293e175938ab678441d785c242ba22ea82655db4b1d08384828f65bde7966
    path: model_TabPFNRegressor_c13293e17593.pkl
    chain_path: s6.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 40937965
    created_at: '2026-01-09T16:47:23.783679+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$c5f06284fcbc:2
    content_hash: sha256:419d8ef233c5f2ec9a3b210f8a610312560820f83fdcb519800e1f0e16c5892a
    path: model_TabPFNRegressor_419d8ef233c5.pkl
    chain_path: s6.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 40937963
    created_at: '2026-01-09T16:47:23.830334+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  d0bc4dbb-585:
    trace_id: d0bc4dbb-585
    pipeline_uid: 0001_SOTA_137acf
    created_at: '2026-01-09T16:47:21.799945+00:00'
    steps:
    - step_index: 1
      operator_type: transform
      operator_class: ASLSBaseline
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$bb12ee38a89c:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$bb12ee38a89c:all
        by_source:
          0:
          - 0001_SOTA_137acf$bb12ee38a89c:all
        by_chain:
          s1.ASLSBaseline[src=0,sub=0]: 0001_SOTA_137acf$bb12ee38a89c:all
        metadata:
          class_name: ASLSBaseline
          name: ASLSBaseline_1
      branch_path: []
      branch_name: ''
      duration_ms: 25.62737464904785
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s1.ASLSBaseline[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 80
      - 700
      output_shape:
      - 80
      - 700
      input_features_shape:
      - - 80
        - 1
        - 700
      output_features_shape:
      - - 80
        - 1
        - 700
    - step_index: 2
      operator_type: y_processing
      operator_class: StandardScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.StandardScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$2865afbbfc1d:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$2865afbbfc1d:all
        by_source: {}
        by_chain:
          s2.y_StandardScaler[sub=1]: 0001_SOTA_137acf$2865afbbfc1d:all
        metadata:
          class_name: StandardScaler
          name: y_StandardScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 38.37132453918457
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s2.y_StandardScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 80
      - 700
      output_shape:
      - 80
      - 700
      input_features_shape:
      - - 80
        - 1
        - 700
      output_features_shape:
      - - 80
        - 1
        - 700
    - step_index: 3
      operator_type: transform
      operator_class: StandardScaler
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$b3c264a83f45:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$b3c264a83f45:all
        by_source:
          0:
          - 0001_SOTA_137acf$b3c264a83f45:all
        by_chain:
          s3.StandardScaler[src=0,sub=0]: 0001_SOTA_137acf$b3c264a83f45:all
        metadata:
          class_name: StandardScaler
          name: StandardScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 21.599531173706055
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.StandardScaler[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 80
      - 700
      output_shape:
      - 80
      - 700
      input_features_shape:
      - - 80
        - 1
        - 700
      output_features_shape:
      - - 80
        - 1
        - 700
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 15.091419219970703
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 80
      - 700
      output_shape:
      - 80
      - 700
      input_features_shape:
      - - 80
        - 1
        - 700
      output_features_shape:
      - - 80
        - 1
        - 700
    - step_index: 5
      operator_type: operator
      operator_class: PCA
      operator_config:
        class: sklearn.decomposition._pca.PCA
        params:
          n_components: 0.99
          whiten: true
          random_state: 42
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$900033a82811:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$900033a82811:all
        by_source:
          0:
          - 0001_SOTA_137acf$900033a82811:all
        by_chain:
          s5.PCA[src=0,sub=0]: 0001_SOTA_137acf$900033a82811:all
        metadata:
          class_name: PCA
          name: PCA_1
      branch_path: []
      branch_name: ''
      duration_ms: 80.59096336364746
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.PCA[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 80
      - 700
      output_shape:
      - 80
      - 7
      input_features_shape:
      - - 80
        - 1
        - 700
      output_features_shape:
      - - 80
        - 1
        - 7
    - step_index: 6
      operator_type: model
      operator_class: TabPFNRegressor
      operator_config:
        model:
          class: tabpfn.regressor.TabPFNRegressor
          params:
            n_estimators: 4
            model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
            device: cpu
            ignore_pretraining_limits: true
            random_state: 42
        name: TabPFN-real
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$c5f06284fcbc:0
        - 0001_SOTA_137acf$c5f06284fcbc:1
        - 0001_SOTA_137acf$c5f06284fcbc:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0001_SOTA_137acf$c5f06284fcbc:0
          1: 0001_SOTA_137acf$c5f06284fcbc:1
          2: 0001_SOTA_137acf$c5f06284fcbc:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$c5f06284fcbc:0
            - 0001_SOTA_137acf$c5f06284fcbc:1
            - 0001_SOTA_137acf$c5f06284fcbc:2
        by_source: {}
        by_chain:
          s6.TabPFNRegressor[sub=0]: 0001_SOTA_137acf$c5f06284fcbc:2
        metadata:
          class_name: TabPFNRegressor
          custom_name: TabPFN-real
      branch_path: []
      branch_name: ''
      duration_ms: 3569.1099166870117
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.TabPFNRegressor[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 80
      - 7
      output_shape:
      - 80
      - 7
      input_features_shape:
      - - 80
        - 1
        - 7
      output_features_shape:
      - - 80
        - 1
        - 7
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: ASLSBaseline>Std>PCA
    metadata:
      dataset: corn_oil_80_zhengchenpelegybasesplit
      config_name: SOTA_137acf
      n_steps: 6
      n_artifacts: 7
