schema_version: '2.0'
uid: 1f351788-24c2-43e0-9b1a-4f32fb705d56
pipeline_id: 0001_SOTA_033cb7
name: SOTA_033cb7
dataset: sorghom_digest
created_at: '2026-01-07T16:38:03.170259+00:00'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0001_SOTA_033cb7$bb12ee38a89c:all
    content_hash: sha256:5fb86667892bba4894bd89751a7de3818e857670f4b382a951e8007787318d91
    path: transformer_ASLSBaseline_5fb86667892b.joblib
    chain_path: s1.ASLSBaseline[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 1
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: ASLSBaseline
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 216
    created_at: '2026-01-07T16:38:03.686658+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_033cb7$dfc251e3a6b4:all
    content_hash: sha256:fa7b5d3e60fbdb75295d12438d79d16530c5454bece57d4a85951d7540c2e01a
    path: transformer_PCA_fa7b5d3e60fb.joblib
    chain_path: s3.PCA[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 3
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: PCA
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 25659
    created_at: '2026-01-07T16:38:09.141422+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_033cb7$9d98c9f5abc5:0
    content_hash: sha256:8c4fdbb38b7392b4bde515c466f146477e6b70d351305080ba90a254cddbc73b
    path: model_TabPFNRegressor_8c4fdbb38b73.pkl
    chain_path: s4.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 4
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 42404829
    created_at: '2026-01-07T16:39:06.590790+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_033cb7$9d98c9f5abc5:1
    content_hash: sha256:a26d7396bacd168c65eb3686bc3556ad573f0d6e89e0eee0a0d670ac96dac674
    path: model_TabPFNRegressor_a26d7396bacd.pkl
    chain_path: s4.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 4
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 42406227
    created_at: '2026-01-07T16:39:06.639895+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_033cb7$9d98c9f5abc5:2
    content_hash: sha256:f725a1d60c97c62c7bb6b5ab67929b0b2976b4352452316584b93a82feadf626
    path: model_TabPFNRegressor_f725a1d60c97.pkl
    chain_path: s4.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 4
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 42406235
    created_at: '2026-01-07T16:39:06.688125+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  9bfd94f0-6eb:
    trace_id: 9bfd94f0-6eb
    pipeline_uid: 0001_SOTA_033cb7
    created_at: '2026-01-07T16:38:03.171021+00:00'
    steps:
    - step_index: 1
      operator_type: transform
      operator_class: ASLSBaseline
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_033cb7$bb12ee38a89c:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_033cb7$bb12ee38a89c:all
        by_source:
          0:
          - 0001_SOTA_033cb7$bb12ee38a89c:all
        by_chain:
          s1.ASLSBaseline[src=0,sub=0]: 0001_SOTA_033cb7$bb12ee38a89c:all
        metadata:
          class_name: ASLSBaseline
          name: ASLSBaseline_1
      branch_path: []
      branch_name: ''
      duration_ms: 534.3689918518066
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s1.ASLSBaseline[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 1876
      - 949
      output_shape:
      - 1876
      - 949
      input_features_shape:
      - - 1876
        - 1
        - 949
      output_features_shape:
      - - 1876
        - 1
        - 949
    - step_index: 2
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 5338.473081588745
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 1876
      - 949
      output_shape:
      - 1876
      - 949
      input_features_shape:
      - - 1876
        - 1
        - 949
      output_features_shape:
      - - 1876
        - 1
        - 949
    - step_index: 3
      operator_type: operator
      operator_class: PCA
      operator_config:
        class: sklearn.decomposition._pca.PCA
        params:
          n_components: 0.99
          whiten: true
          random_state: 42
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_033cb7$dfc251e3a6b4:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_033cb7$dfc251e3a6b4:all
        by_source:
          0:
          - 0001_SOTA_033cb7$dfc251e3a6b4:all
        by_chain:
          s3.PCA[src=0,sub=0]: 0001_SOTA_033cb7$dfc251e3a6b4:all
        metadata:
          class_name: PCA
          name: PCA_1
      branch_path: []
      branch_name: ''
      duration_ms: 154.45876121520996
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.PCA[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 1876
      - 949
      output_shape:
      - 1876
      - 6
      input_features_shape:
      - - 1876
        - 1
        - 949
      output_features_shape:
      - - 1876
        - 1
        - 6
    - step_index: 4
      operator_type: model
      operator_class: TabPFNRegressor
      operator_config:
        model:
          class: tabpfn.regressor.TabPFNRegressor
          params:
            n_estimators: 16
            model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
            device: cpu
            ignore_pretraining_limits: true
            random_state: 42
        name: TabPFN-real
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_033cb7$9d98c9f5abc5:0
        - 0001_SOTA_033cb7$9d98c9f5abc5:1
        - 0001_SOTA_033cb7$9d98c9f5abc5:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0001_SOTA_033cb7$9d98c9f5abc5:0
          1: 0001_SOTA_033cb7$9d98c9f5abc5:1
          2: 0001_SOTA_033cb7$9d98c9f5abc5:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_033cb7$9d98c9f5abc5:0
            - 0001_SOTA_033cb7$9d98c9f5abc5:1
            - 0001_SOTA_033cb7$9d98c9f5abc5:2
        by_source: {}
        by_chain:
          s4.TabPFNRegressor[sub=0]: 0001_SOTA_033cb7$9d98c9f5abc5:2
        metadata:
          class_name: TabPFNRegressor
          custom_name: TabPFN-real
      branch_path: []
      branch_name: ''
      duration_ms: 133782.0806503296
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s4.TabPFNRegressor[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 1876
      - 6
      output_shape:
      - 1876
      - 6
      input_features_shape:
      - - 1876
        - 1
        - 6
      output_features_shape:
      - - 1876
        - 1
        - 6
    model_step_index: 4
    fold_weights: null
    preprocessing_chain: ASLSBaseline>PCA
    metadata:
      dataset: sorghom_digest
      config_name: SOTA_033cb7
      n_steps: 4
      n_artifacts: 5
