uid: 7ad1fd32-2d1a-47b9-be66-7beda050dcff
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: corn_oil_80_zhengchenpelegybasesplit
created_at: '2025-12-12T12:43:10.669425+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:26b2ddd51689b4d62afd0d8120bf3701bb34aecf8f7c42b134bb6c3d9b5f3096
  name: ASLSBaseline_1
  path: ASLSBaseline_26b2dd.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T12:43:10.689711+00:00'
  step: 1
- hash: sha256:81ab3f90bdaf39b4d6be66976524af71d918d9691f774ba2cb394b991a5366f2
  name: y_StandardScaler
  path: StandardScaler_81ab3f.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 443
  saved_at: '2025-12-12T12:43:10.743882+00:00'
  step: 4
- hash: sha256:cb7c5375cc9f73ec350bb0aad744952751c618d680c82fa7a81e0f1282b192a6
  name: StandardScaler_1
  path: StandardScaler_cb7c53.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 14537
  saved_at: '2025-12-12T12:43:10.753217+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T12:43:10.769814+00:00'
  step: 6
- hash: sha256:bf82cc4fe4b94920fa37eead61c799194614ec56db23d19932b98428813be9e9
  name: PCA_1
  path: PCA_bf82cc.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 20477
  saved_at: '2025-12-12T12:43:10.811167+00:00'
  step: 7
- hash: sha256:aac00acfb904e26a9e0c731c4ac7aa650ef302ebec8e85b2283fe085b98ee588
  name: StandardScaler_1
  path: StandardScaler_aac00a.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 553
  saved_at: '2025-12-12T12:43:10.850727+00:00'
  step: 8
- hash: sha256:ecbeaebd682ba6b3d6083272096ee46a4445db2209bf5ed0e2427aa4c19fb243
  name: PowerTransformer_1
  path: PowerTransformer_ecbeae.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 746
  saved_at: '2025-12-12T12:43:10.888684+00:00'
  step: 9
- hash: sha256:a5b95968d24b2f4d147bd575d1c88e59580c301e97985ed940a0a904223f591f
  name: AutoGluon_1.pkl
  path: TabularPredictor_a5b959.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12306
  saved_at: '2025-12-12T12:43:22.387414+00:00'
  step: 10
- hash: sha256:67636eb462257fc41327bc26f0fb3626add50536288169b89e27f006515bd95b
  name: AutoGluon_2.pkl
  path: TabularPredictor_67636e.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12378
  saved_at: '2025-12-12T12:43:22.387888+00:00'
  step: 10
- hash: sha256:157a5c451cdc0c56018357ba8053e499400fe5ecdc1868686f19645e42ba1617
  name: AutoGluon_3.pkl
  path: TabularPredictor_157a5c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12306
  saved_at: '2025-12-12T12:43:22.388467+00:00'
  step: 10
- hash: sha256:0ddfef5cb6097b32e41305c7faa56617aa23413b21fcd71df19ac0f00b25f5fe
  name: TabPFN_1.pkl
  path: TabPFNRegressor_0ddfef.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41019403
  saved_at: '2025-12-12T12:43:29.174121+00:00'
  step: 11
- hash: sha256:dffb36a6ce716d0c9650a0bf6fec81e7818d3922a8bb5a647ca7a94caf3e1205
  name: TabPFN_2.pkl
  path: TabPFNRegressor_dffb36.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41021003
  saved_at: '2025-12-12T12:43:29.228235+00:00'
  step: 11
- hash: sha256:f0aacf60ba9237ca012bfba2ceb592a0aea58d6e75553bd08de702f7a9f8377e
  name: TabPFN_3.pkl
  path: TabPFNRegressor_f0aacf.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41021003
  saved_at: '2025-12-12T12:43:29.283379+00:00'
  step: 11
- hash: sha256:e9770f4666aefb214e805bd436d201facb2f5f24c5ddb73d96c89943038d9053
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_e9770f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41019440
  saved_at: '2025-12-12T12:43:42.562131+00:00'
  step: 12
- hash: sha256:27be748f69a524514a5d82a16afd99e74c5881ec9c4f6a31531f5704829bc00e
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_27be74.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41021040
  saved_at: '2025-12-12T12:43:42.615163+00:00'
  step: 12
- hash: sha256:a38a291e688b906f08dd6a604ec3e656a0a71ccc8cf098981179268426f45492
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_a38a29.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41021040
  saved_at: '2025-12-12T12:43:42.668007+00:00'
  step: 12
predictions: []
