uid: 2663d2a5-d126-472e-bfb4-a4f7ea581649
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: diesel_cn_245_hlb_a
created_at: '2026-01-07T09:35:00.916742+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2026-01-07T09:35:00.957629+00:00'
  step: 1
- hash: sha256:8311df119a700949a439768b2d941dcf25dddad3d92fb79fb2a4574e83e98c26
  name: PCA_1
  path: PCA_8311df.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 8200
  saved_at: '2026-01-07T09:35:01.021223+00:00'
  step: 4
- hash: sha256:a59495810dd020b2f8fd8abaf4a5f40dfc4ce856b76f9281e1f20d0e2f3b9779
  name: AutoGluon_1.pkl
  path: TabularPredictor_a59495.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11262
  saved_at: '2026-01-07T09:35:13.330371+00:00'
  step: 5
- hash: sha256:4e5cd28dba983dd59d419e93743d2026eaa126776a425bcd2997c12535834200
  name: AutoGluon_2.pkl
  path: TabularPredictor_4e5cd2.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2026-01-07T09:35:13.330684+00:00'
  step: 5
- hash: sha256:dac30e60f2aaed177bb9e3d0dcef917ef839b8a626d476a374894db191dfd63b
  name: AutoGluon_3.pkl
  path: TabularPredictor_dac30e.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11196
  saved_at: '2026-01-07T09:35:13.330953+00:00'
  step: 5
- hash: sha256:7c1f933e5b012882b0010da3a9996e368d40ec3d6282d9a64ad95e84bccfb5c6
  name: TabPFN_1.pkl
  path: TabPFNRegressor_7c1f93.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41040150
  saved_at: '2026-01-07T09:35:20.102779+00:00'
  step: 6
- hash: sha256:73162cdba95683c7ae281a3b418f0f39610b4aa7e242023ca0562e50163a78c8
  name: TabPFN_2.pkl
  path: TabPFNRegressor_73162c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41040150
  saved_at: '2026-01-07T09:35:20.147354+00:00'
  step: 6
- hash: sha256:af1bca292a75588c64188773f1c194bb7c65d5cddb82213c6eb135d6a7a4c029
  name: TabPFN_3.pkl
  path: TabPFNRegressor_af1bca.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41040150
  saved_at: '2026-01-07T09:35:20.189810+00:00'
  step: 6
- hash: sha256:51a9452d5e304455b4a1607fa3c4192e002de0e5265783ce87d0ff79c055b135
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_51a945.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41040185
  saved_at: '2026-01-07T09:35:33.856858+00:00'
  step: 7
- hash: sha256:bc63563cfe53fcf928f9387aea1c31976ddf0cf89b7edb85d7a91a89b6b4c965
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_bc6356.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41040187
  saved_at: '2026-01-07T09:35:33.902571+00:00'
  step: 7
- hash: sha256:f0973568f7cce7b8ea276b103a0408eef6a956ca5731db7a7f5d40e03bc8dfdc
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_f09735.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41040187
  saved_at: '2026-01-07T09:35:33.948376+00:00'
  step: 7
predictions: []
