schema_version: '2.0'
uid: ad405678-3bec-4576-8e1c-8b55e719b87c
pipeline_id: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2
name: PLS_PP_SELECTION_NO_SAVE_2e38f2
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:47:32.674952+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: null
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
    - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
      params:
        window_length: 15
    - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
      params:
        window_length: 15
        deriv: 2
    - class: nirs4all.operators.transforms.nirs.Wavelet
      params:
        wavelet: coif3
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      error_score: .nan
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: null
- _cartesian_:
  - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
  - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
    params:
      window_length: 15
  - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
    params:
      window_length: 15
      deriv: 2
  - class: nirs4all.operators.transforms.nirs.Wavelet
    params:
      wavelet: coif3
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:47:32.701019+00:00'
    params: {}
    version: 3
  - artifact_id: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$33af94b1bf58:all
    content_hash: sha256:691364ebf5c9cf5f03e16c3b48e170cf0041f7b9fd02c8c40dcdafece2312e1d
    path: transformer_ExtendedMultiplicativeScatterCorrection_691364ebf5c9.joblib
    chain_path: s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=0]
    source_index: 0
    pipeline_id: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: ExtendedMultiplicativeScatterCorrection
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 5683
    created_at: '2026-01-08T17:47:32.714441+00:00'
    params: {}
    version: 3
  - artifact_id: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$eeb09d32a26b:all
    content_hash: sha256:c90a6e998d89e802fdc8ae5af3e9cd7288130360151139484ffc6499b3403f5a
    path: transformer_SavitzkyGolay_c90a6e998d89.joblib
    chain_path: s5.SavitzkyGolay[src=0,sub=1]
    source_index: 0
    pipeline_id: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: SavitzkyGolay
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 137
    created_at: '2026-01-08T17:47:32.716933+00:00'
    params: {}
    version: 3
  - artifact_id: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$296923040127:all
    content_hash: sha256:5c353b1441d52f528075c64bd2477db6d0df3f619817bfa27a68d32928e99953
    path: transformer_SavitzkyGolay_5c353b1441d5.joblib
    chain_path: s5.SavitzkyGolay[src=0,sub=2]
    source_index: 0
    pipeline_id: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2
    branch_path: []
    step_index: 5
    substep_index: 2
    fold_id: null
    artifact_type: transformer
    class_name: SavitzkyGolay
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 137
    created_at: '2026-01-08T17:47:32.719393+00:00'
    params: {}
    version: 3
  - artifact_id: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$3569153fa566:all
    content_hash: sha256:f2c1d06f4298f812e17b88a6602355856be25df4ed5fa680286d202bd476cb07
    path: transformer_Wavelet_f2c1d06f4298.joblib
    chain_path: s5.Wavelet[src=0,sub=3]
    source_index: 0
    pipeline_id: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2
    branch_path: []
    step_index: 5
    substep_index: 3
    fold_id: null
    artifact_type: transformer
    class_name: Wavelet
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 114
    created_at: '2026-01-08T17:47:32.722715+00:00'
    params: {}
    version: 3
  - artifact_id: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$9f79d59455ab:0
    content_hash: sha256:b152ad9ea2cd6b1a6c7e9ad83c65e6000a62bd1a12beda10ef3bf1466ad25365
    path: model_PLSRegression_b152ad9ea2cd.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 196607
    created_at: '2026-01-08T17:47:33.319533+00:00'
    params: {}
    version: 3
  - artifact_id: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$9f79d59455ab:1
    content_hash: sha256:14881beadada0f38845c62bcc8c587611e277e9fa60c50f506bd0da2688d5ed1
    path: model_PLSRegression_14881beadada.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 196900
    created_at: '2026-01-08T17:47:33.326621+00:00'
    params: {}
    version: 3
  - artifact_id: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$9f79d59455ab:2
    content_hash: sha256:97274efc9122163ba884cc541f28a1f50c92d60b729c137a75b93cb30b56c61a
    path: model_PLSRegression_97274efc9122.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 196931
    created_at: '2026-01-08T17:47:33.331237+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  df370713-4b4:
    trace_id: df370713-4b4
    pipeline_uid: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2
    created_at: '2026-01-08T17:47:32.676158+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 2.315521240234375
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 1.6562938690185547
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 24.814605712890625
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 4.096508026123047
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: ExtendedMultiplicativeScatterCorrection, SavitzkyGolay, SavitzkyGolay
        (+1)
      operator_config:
        feature_augmentation:
        - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
        - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
          params:
            window_length: 15
        - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
          params:
            window_length: 15
            deriv: 2
        - class: nirs4all.operators.transforms.nirs.Wavelet
          params:
            wavelet: coif3
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$33af94b1bf58:all
        - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$eeb09d32a26b:all
        - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$296923040127:all
        - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$3569153fa566:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$33af94b1bf58:all
            - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$eeb09d32a26b:all
            - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$296923040127:all
            - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$3569153fa566:all
        by_source:
          0:
          - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$33af94b1bf58:all
          - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$eeb09d32a26b:all
          - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$296923040127:all
          - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$3569153fa566:all
        by_chain:
          s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=0]: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$33af94b1bf58:all
          s5.SavitzkyGolay[src=0,sub=1]: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$eeb09d32a26b:all
          s5.SavitzkyGolay[src=0,sub=2]: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$296923040127:all
          s5.Wavelet[src=0,sub=3]: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$3569153fa566:all
        metadata:
          class_name: Wavelet
          name: Wavelet_4
      branch_path: []
      branch_name: ''
      duration_ms: 33.25223922729492
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=0]
      - s5.SavitzkyGolay[src=0,sub=1]
      - s5.SavitzkyGolay[src=0,sub=2]
      - s5.Wavelet[src=0,sub=3]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 2880
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 5
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          error_score: .nan
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$9f79d59455ab:0
        - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$9f79d59455ab:1
        - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$9f79d59455ab:0
          1: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$9f79d59455ab:1
          2: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$9f79d59455ab:0
            - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$9f79d59455ab:1
            - 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0360_PLS_PP_SELECTION_NO_SAVE_2e38f2$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 623.3959197998047
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 2880
      output_shape:
      - 60
      - 2880
      input_features_shape:
      - - 60
        - 5
        - 576
      output_features_shape:
      - - 60
        - 5
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: raw|ExtendedMSC|SG|SG|Wavelet
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_2e38f2
      n_steps: 6
      n_artifacts: 8
