uid: ac12f606-d915-4b9b-b778-ad56e9e57a0d
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: wood_sustainability_511_davrieux_rmse0_092
created_at: '2025-12-12T08:25:10.012161+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:e3981c22fe01bf6ba48b414ed19291553d7fa375224b447ff7d90a870e91f7c3
  name: ASLSBaseline_1
  path: ASLSBaseline_e3981c.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2025-12-12T08:25:10.177051+00:00'
  step: 1
- hash: sha256:25bf86ac950190adaed9c16a3a433eda66db00b57e98f4800eb6ec3361341490
  name: y_StandardScaler
  path: StandardScaler_25bf86.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 443
  saved_at: '2025-12-12T08:25:10.572282+00:00'
  step: 4
- hash: sha256:07556f0f7132fd8221de1453646d91f32ed4fd193558b20d26372c99646e7ea5
  name: StandardScaler_1
  path: StandardScaler_07556f.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 23269
  saved_at: '2025-12-12T08:25:10.582114+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T08:25:10.607601+00:00'
  step: 6
- hash: sha256:4b301844e446855f89f28fe7f4e761392c2da8cac5ccce17813ff97f0da637c8
  name: PCA_1
  path: PCA_4b3018.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 50881
  saved_at: '2025-12-12T08:25:10.696793+00:00'
  step: 7
- hash: sha256:cf0f98400bdc25fbab3444e1830534f94563f5f952b87ed0be37c8c1a91467c3
  name: StandardScaler_1
  path: StandardScaler_cf0f98.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 681
  saved_at: '2025-12-12T08:25:10.740367+00:00'
  step: 8
- hash: sha256:6ff4cc2bf2777db4e98e3a36d411a97c526150584302ec7f67bc5e4e9586f081
  name: PowerTransformer_1
  path: PowerTransformer_6ff4cc.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 909
  saved_at: '2025-12-12T08:25:10.776760+00:00'
  step: 9
- hash: sha256:f182fa7d5741eeae25ac1825a38544c6ca200375c192f9789e719c53b637123c
  name: AutoGluon_1.pkl
  path: TabularPredictor_f182fa.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 14179
  saved_at: '2025-12-12T08:25:25.086487+00:00'
  step: 10
- hash: sha256:17a02c4ef567f6ca96ac71fdbcb0b6b910a6cbc9c974a6fe6254c9adc7bc7719
  name: AutoGluon_2.pkl
  path: TabularPredictor_17a02c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 14143
  saved_at: '2025-12-12T08:25:25.086976+00:00'
  step: 10
- hash: sha256:87ccde6876d14c25c148cf0c891cfbcb40230fa8810e9993c3d473f4f3ddc752
  name: AutoGluon_3.pkl
  path: TabularPredictor_87ccde.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 14161
  saved_at: '2025-12-12T08:25:25.087476+00:00'
  step: 10
- hash: sha256:124f14ff22acba4230c60c027a3b44bd31521e36907c2f6992891232a734a06d
  name: TabPFN_1.pkl
  path: TabPFNRegressor_124f14.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41615531
  saved_at: '2025-12-12T08:25:45.232749+00:00'
  step: 11
- hash: sha256:1dc825f6944413cb4ea9e3063f0f2f4c950e520584bc2e5a9b052435c4488bcb
  name: TabPFN_2.pkl
  path: TabPFNRegressor_1dc825.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41615531
  saved_at: '2025-12-12T08:25:45.286299+00:00'
  step: 11
- hash: sha256:b2094229a7ec18ed0b53d6cda1fd475ddc43746216cc56d3281b600d06724698
  name: TabPFN_3.pkl
  path: TabPFNRegressor_b20942.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41615531
  saved_at: '2025-12-12T08:25:45.338938+00:00'
  step: 11
- hash: sha256:f9eff339e73d2c6da167cf1d1bb38616493165607c5079f581751757023dc1c4
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_f9eff3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41615568
  saved_at: '2025-12-12T08:26:27.629847+00:00'
  step: 12
- hash: sha256:d0e19b93fe4414a0ef1b1a2c2e1f09252f49466db6f7e82258d5fe5571132448
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_d0e19b.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41615568
  saved_at: '2025-12-12T08:26:27.688125+00:00'
  step: 12
- hash: sha256:cf4cab6501e6a541c373e6c868b4d1c9e8059b4970f0690d8fc9acdc817ab9c6
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_cf4cab.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41615568
  saved_at: '2025-12-12T08:26:27.746475+00:00'
  step: 12
predictions: []
