uid: 2883fafa-16e8-414d-9447-55289b4f72da
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: poultry_manure_mgo_ks
created_at: '2025-12-12T07:52:55.290245+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:125d94dee500492a3bdb8dd8b9fa106b8b2b34e5f42944e4b15d55960ffb73d1
  name: ASLSBaseline_1
  path: ASLSBaseline_125d94.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T07:52:55.337203+00:00'
  step: 1
- hash: sha256:a17010cb94be9fcc9a6a31bcadb96b783a787112f27caa2146f9543169cd58f7
  name: y_StandardScaler
  path: StandardScaler_a17010.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 441
  saved_at: '2025-12-12T07:52:55.395915+00:00'
  step: 4
- hash: sha256:b81dc395d1dd80940342c9d3237f852b94dbd4704afba86f452dc9b2bf4d63c4
  name: StandardScaler_1
  path: StandardScaler_b81dc3.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 21264
  saved_at: '2025-12-12T07:52:55.402371+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T07:52:55.414076+00:00'
  step: 6
- hash: sha256:5862dbfd9bfbdf7f0cbfc1c544cd73bf5e8f61dea119f9b4783de94b26d16912
  name: PCA_1
  path: PCA_5862db.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 111761
  saved_at: '2025-12-12T07:52:55.476135+00:00'
  step: 7
- hash: sha256:839f98ae517f3aa6a02b3903217ecb1645dff11963b361a4c3c6a436ae95334c
  name: StandardScaler_1
  path: StandardScaler_839f98.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 944
  saved_at: '2025-12-12T07:52:55.513141+00:00'
  step: 8
- hash: sha256:d84f5cbd3f747a7ec3dc5ab2623a45bce39a0502f058affcadd8ac7b3caed0b7
  name: PowerTransformer_1
  path: PowerTransformer_d84f5c.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1339
  saved_at: '2025-12-12T07:52:55.546611+00:00'
  step: 9
- hash: sha256:18eb89a44e38387e1abebc9b869460557ecda2648761e6d9d1de001bf1806b7a
  name: AutoGluon_1.pkl
  path: TabularPredictor_18eb89.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 20195
  saved_at: '2025-12-12T07:53:09.704833+00:00'
  step: 10
- hash: sha256:f02eda2f260ff04f598fd4bbe9d08bf4be42c9ada1aafbff38cf0804517ae892
  name: AutoGluon_2.pkl
  path: TabularPredictor_f02eda.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 20222
  saved_at: '2025-12-12T07:53:09.705174+00:00'
  step: 10
- hash: sha256:9891128ae363ac6423569eae94dcfb4eab6350f482df4f331a180caf4c4420c9
  name: AutoGluon_3.pkl
  path: TabularPredictor_989112.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 20195
  saved_at: '2025-12-12T07:53:09.705510+00:00'
  step: 10
- hash: sha256:30925c0856d2768fb9ec0230923aab165e2c483ab9213bcfc98c9a171cd330f0
  name: TabPFN_1.pkl
  path: TabPFNRegressor_30925c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41403996
  saved_at: '2025-12-12T07:53:23.285790+00:00'
  step: 11
- hash: sha256:7b1c4becc8e400d1a0d449c6885160cc59ee1eb0e029341e0353185581f16f16
  name: TabPFN_2.pkl
  path: TabPFNRegressor_7b1c4b.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41410208
  saved_at: '2025-12-12T07:53:23.331749+00:00'
  step: 11
- hash: sha256:8a101c28bffd1a5906c332e9f33c7d8feb386b0c72b3cb97d2669508f5881f3a
  name: TabPFN_3.pkl
  path: TabPFNRegressor_8a101c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41410216
  saved_at: '2025-12-12T07:53:23.377790+00:00'
  step: 11
- hash: sha256:4305f2ec46be081bad4aa57ded4989047c3da6b8f830501ad0f3b2330a03ad77
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_4305f2.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41404041
  saved_at: '2025-12-12T07:53:50.895082+00:00'
  step: 12
- hash: sha256:133c3b5c69a789a038b18d3c7aff1c652e595d3f47f950af4714bd321ffea9f8
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_133c3b.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41410243
  saved_at: '2025-12-12T07:53:50.942008+00:00'
  step: 12
- hash: sha256:c131c3100853e4bd0bf4a20519b4370a604dc44081d335c8d956d0cdee3f0477
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_c131c3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41410249
  saved_at: '2025-12-12T07:53:50.989142+00:00'
  step: 12
predictions: []
