uid: 7f57dabc-1913-4adc-8abb-a028a3f226da
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: diesel_cn_381_pengks
created_at: '2026-01-07T09:21:55.684574+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2026-01-07T09:21:55.745208+00:00'
  step: 1
- hash: sha256:33c09bea115496e3a5abc11565814ad3956fde1ca69e03da32483d4a8bc6108c
  name: PCA_1
  path: PCA_33c09b.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 8366
  saved_at: '2026-01-07T09:21:55.856850+00:00'
  step: 4
- hash: sha256:8e9ec8dcacce6e326d4fe19843b1150eda723c700167d0a617bc09c589dae451
  name: AutoGluon_1.pkl
  path: TabularPredictor_8e9ec8.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2026-01-07T09:22:07.992526+00:00'
  step: 5
- hash: sha256:57c4b2585fbceaf89c3cb03aa6db122d2d14e9daddc6a2251814e0366979e068
  name: AutoGluon_2.pkl
  path: TabularPredictor_57c4b2.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2026-01-07T09:22:07.992936+00:00'
  step: 5
- hash: sha256:355ed1fee4f8318da765772eaf628ed5b354d4647488abd1e343e44e23c95de7
  name: AutoGluon_3.pkl
  path: TabularPredictor_355ed1.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11271
  saved_at: '2026-01-07T09:22:07.993329+00:00'
  step: 5
- hash: sha256:126f986fb4eac7d1958cfdd7f08fa4f7a2b77afe95a782767a81359eea53fe1b
  name: TabPFN_1.pkl
  path: TabPFNRegressor_126f98.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41135199
  saved_at: '2026-01-07T09:22:18.631270+00:00'
  step: 6
- hash: sha256:118b4d2fbe8a747a4ef2c5b584b3b28d5abe02e9da8a95f56f0924e34f92d0dc
  name: TabPFN_2.pkl
  path: TabPFNRegressor_118b4d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41135195
  saved_at: '2026-01-07T09:22:18.695056+00:00'
  step: 6
- hash: sha256:3ac19552d04fbb67248dc658258b002003629f073186bf2606660b861333db09
  name: TabPFN_3.pkl
  path: TabPFNRegressor_3ac195.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41135199
  saved_at: '2026-01-07T09:22:18.756402+00:00'
  step: 6
- hash: sha256:7172d0e370f6a50d733b68fa823e4f2915c6481f75b804c2db912d3111a2ebb9
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_7172d0.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41135236
  saved_at: '2026-01-07T09:22:35.268685+00:00'
  step: 7
- hash: sha256:4687e95399627d8cff4f3c823e3d1b97aafe7d2d8d5d4ee96d4e1642a4a10934
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_4687e9.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41135236
  saved_at: '2026-01-07T09:22:35.330201+00:00'
  step: 7
- hash: sha256:ef780479508321d889eb0adea310b67d62be3e1343e093ae60ca3cc6c514b698
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_ef7804.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41135234
  saved_at: '2026-01-07T09:22:35.394446+00:00'
  step: 7
predictions: []
