schema_version: '2.0'
uid: 5f1f264d-e6a2-41b9-8556-2a7bc2df82af
pipeline_id: 0427_PLS_PP_SELECTION_NO_SAVE_d72302
name: PLS_PP_SELECTION_NO_SAVE_d72302
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:48:51.941801+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: null
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - nirs4all.operators.transforms.signal.Detrend
    - class: nirs4all.operators.transforms.signal.Gaussian
      params:
        order: 1
        sigma: 2
    - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
      params:
        window_length: 15
        deriv: 1
    - nirs4all.operators.transforms.nirs.Haar
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      error_score: .nan
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: null
- _cartesian_:
  - nirs4all.operators.transforms.signal.Detrend
  - class: nirs4all.operators.transforms.signal.Gaussian
    params:
      order: 1
      sigma: 2
  - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
    params:
      window_length: 15
      deriv: 1
  - nirs4all.operators.transforms.nirs.Haar
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0427_PLS_PP_SELECTION_NO_SAVE_d72302$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0427_PLS_PP_SELECTION_NO_SAVE_d72302
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:48:51.968111+00:00'
    params: {}
    version: 3
  - artifact_id: 0427_PLS_PP_SELECTION_NO_SAVE_d72302$51eb708c8a1f:all
    content_hash: sha256:11ce246bc67c631c59d4827a162f06b45fa0f87770f7d8325a0c50c7f6d72fcf
    path: transformer_Detrend_11ce246bc67c.joblib
    chain_path: s5.Detrend[src=0,sub=0]
    source_index: 0
    pipeline_id: 0427_PLS_PP_SELECTION_NO_SAVE_d72302
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: Detrend
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 90
    created_at: '2026-01-08T17:48:51.986180+00:00'
    params: {}
    version: 3
  - artifact_id: 0427_PLS_PP_SELECTION_NO_SAVE_d72302$5b4a7bbb9aae:all
    content_hash: sha256:fcef74d1464ae75c275fc2b03bb2c435a0787cd50861cdf41aedf150ab9f3eff
    path: transformer_Gaussian_fcef74d1464a.joblib
    chain_path: s5.Gaussian[src=0,sub=1]
    source_index: 0
    pipeline_id: 0427_PLS_PP_SELECTION_NO_SAVE_d72302
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: Gaussian
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 103
    created_at: '2026-01-08T17:48:51.996498+00:00'
    params: {}
    version: 3
  - artifact_id: 0427_PLS_PP_SELECTION_NO_SAVE_d72302$296923040127:all
    content_hash: sha256:d663934f32b4b5e8dba18585ed74e0c4e66ed1008ee606d100f374d3224f9c49
    path: transformer_SavitzkyGolay_d663934f32b4.joblib
    chain_path: s5.SavitzkyGolay[src=0,sub=2]
    source_index: 0
    pipeline_id: 0427_PLS_PP_SELECTION_NO_SAVE_d72302
    branch_path: []
    step_index: 5
    substep_index: 2
    fold_id: null
    artifact_type: transformer
    class_name: SavitzkyGolay
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 137
    created_at: '2026-01-08T17:48:52.008229+00:00'
    params: {}
    version: 3
  - artifact_id: 0427_PLS_PP_SELECTION_NO_SAVE_d72302$32bd0e890598:all
    content_hash: sha256:2237293e62d5640680cb91d003382cdd194cbcc1496aee2fd76192fa547a78be
    path: transformer_Haar_2237293e62d5.joblib
    chain_path: s5.Haar[src=0,sub=3]
    source_index: 0
    pipeline_id: 0427_PLS_PP_SELECTION_NO_SAVE_d72302
    branch_path: []
    step_index: 5
    substep_index: 3
    fold_id: null
    artifact_type: transformer
    class_name: Haar
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 112
    created_at: '2026-01-08T17:48:52.018463+00:00'
    params: {}
    version: 3
  - artifact_id: 0427_PLS_PP_SELECTION_NO_SAVE_d72302$9f79d59455ab:0
    content_hash: sha256:b67478834ec1bb981bb72e251fafaaf9131f45679309dda22af647f3612c02aa
    path: model_PLSRegression_b67478834ec1.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0427_PLS_PP_SELECTION_NO_SAVE_d72302
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 195570
    created_at: '2026-01-08T17:48:52.558330+00:00'
    params: {}
    version: 3
  - artifact_id: 0427_PLS_PP_SELECTION_NO_SAVE_d72302$9f79d59455ab:1
    content_hash: sha256:3c0ad4eec30020a4bca9665c4d8d5c5fc5c4ebaa4db8465f6d4bdbcd8b65505e
    path: model_PLSRegression_3c0ad4eec300.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0427_PLS_PP_SELECTION_NO_SAVE_d72302
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 195892
    created_at: '2026-01-08T17:48:52.562846+00:00'
    params: {}
    version: 3
  - artifact_id: 0427_PLS_PP_SELECTION_NO_SAVE_d72302$9f79d59455ab:2
    content_hash: sha256:3c3ab200634b18077eca2cfe01dbdbdf38abd1472479ad2e0ff113de3097fcb8
    path: model_PLSRegression_3c3ab200634b.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0427_PLS_PP_SELECTION_NO_SAVE_d72302
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 195885
    created_at: '2026-01-08T17:48:52.567291+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  de0fa0b9-17b:
    trace_id: de0fa0b9-17b
    pipeline_uid: 0427_PLS_PP_SELECTION_NO_SAVE_d72302
    created_at: '2026-01-08T17:48:51.942963+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 2.5043487548828125
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 1.7108917236328125
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0427_PLS_PP_SELECTION_NO_SAVE_d72302$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 24.934053421020508
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 9.525060653686523
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: Detrend, Gaussian, SavitzkyGolay (+1)
      operator_config:
        feature_augmentation:
        - nirs4all.operators.transforms.signal.Detrend
        - class: nirs4all.operators.transforms.signal.Gaussian
          params:
            order: 1
            sigma: 2
        - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
          params:
            window_length: 15
            deriv: 1
        - nirs4all.operators.transforms.nirs.Haar
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$51eb708c8a1f:all
        - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$5b4a7bbb9aae:all
        - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$296923040127:all
        - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$32bd0e890598:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$51eb708c8a1f:all
            - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$5b4a7bbb9aae:all
            - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$296923040127:all
            - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$32bd0e890598:all
        by_source:
          0:
          - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$51eb708c8a1f:all
          - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$5b4a7bbb9aae:all
          - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$296923040127:all
          - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$32bd0e890598:all
        by_chain:
          s5.Detrend[src=0,sub=0]: 0427_PLS_PP_SELECTION_NO_SAVE_d72302$51eb708c8a1f:all
          s5.Gaussian[src=0,sub=1]: 0427_PLS_PP_SELECTION_NO_SAVE_d72302$5b4a7bbb9aae:all
          s5.SavitzkyGolay[src=0,sub=2]: 0427_PLS_PP_SELECTION_NO_SAVE_d72302$296923040127:all
          s5.Haar[src=0,sub=3]: 0427_PLS_PP_SELECTION_NO_SAVE_d72302$32bd0e890598:all
        metadata:
          class_name: Haar
          name: Haar_4
      branch_path: []
      branch_name: ''
      duration_ms: 65.56200981140137
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.Detrend[src=0,sub=0]
      - s5.Gaussian[src=0,sub=1]
      - s5.SavitzkyGolay[src=0,sub=2]
      - s5.Haar[src=0,sub=3]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 2880
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 5
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          error_score: .nan
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$9f79d59455ab:0
        - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$9f79d59455ab:1
        - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0427_PLS_PP_SELECTION_NO_SAVE_d72302$9f79d59455ab:0
          1: 0427_PLS_PP_SELECTION_NO_SAVE_d72302$9f79d59455ab:1
          2: 0427_PLS_PP_SELECTION_NO_SAVE_d72302$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$9f79d59455ab:0
            - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$9f79d59455ab:1
            - 0427_PLS_PP_SELECTION_NO_SAVE_d72302$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0427_PLS_PP_SELECTION_NO_SAVE_d72302$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 550.4653453826904
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 2880
      output_shape:
      - 60
      - 2880
      input_features_shape:
      - - 60
        - 5
        - 576
      output_features_shape:
      - - 60
        - 5
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: raw|Detr|Gauss|SG|Haar
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_d72302
      n_steps: 6
      n_artifacts: 8
