#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Non-inferiority tests for model + preprocessing pairs using per-dataset CSVs.
This script:
  - Walks /Results/asso_pp_model/<dataset_name>/ for CSV files named "results_*.csv"
    that do NOT contain certain excluded substrings.
  - Automatically detects TASK TYPE per dataset CSV:
      * regression if any model name ends with "_reg"  (metric assumed to be RRMSE; smaller is better)
      * classification if any model ends with "_classif" (metric assumed to be Accuracy; larger is better)
    If both suffixes are present in a CSV, the dataset is skipped as ambiguous.
  - Builds Δ values per (candidate model, preprocessing, dataset):
      * regression: Δ = RRMSE(candidate) - RRMSE(reference)                (smaller is better)
      * classification: Δ = Accuracy(reference) - Accuracy(candidate)      (larger is better)
    => In BOTH tasks, Δ < δ supports non-inferiority of the candidate.
  - Applies THREE procedures MODEL-BY-MODEL (i.e., within each candidate model, across preprocessings):
      a) Exact sign test (binomial) on Y = Δ - δ (ties removed), one-sided "less"
      b) Wilcoxon signed-rank on Y = Δ - δ (one-sided "less"), ties handled as zero
      c) Bootstrap percentile CI for the median(Δ); non-inferiority if UpperCI < δ
  - Controls multiplicity with Benjamini-Hochberg (FDR) **within each (task, candidate model)**
    separately for sign test and Wilcoxon.
  - Outputs TWO CSV reports (one per task) and companion *_diffs.csv files.
  - Generates visualization figures per task: 4 subplots per figure (2x2),
    one subplot per candidate model, showing a "mini-forest" of median Δ with bootstrap CI
    across preprocessings for that model.

Author: Generated by ChatGPT. All code comments are in English.
"""

from __future__ import annotations

import os
import re
import math
import json
import argparse
from typing import List, Tuple, Optional, Dict

import numpy as np
import pandas as pd

# SciPy is recommended for exact binomial CDF and Wilcoxon.
# The script degrades gracefully if SciPy is missing (Wilcoxon becomes None; binomial computed manually).
try:
    from scipy.stats import wilcoxon, binom
    SCIPY_AVAILABLE = True
except Exception:
    SCIPY_AVAILABLE = False

import matplotlib
matplotlib.use("Agg")  # ensure non-interactive backend for batch usage
import matplotlib.pyplot as plt


# ------------------------- Configuration (defaults; can be overridden by CLI) -------------------------

DEFAULT_RESULTS_ROOT = "Results/assoc_pp_model/per_dataset"
MODEL_COL = "Model"

FILENAME_PREFIX = "results_"
FILENAME_EXCLUDE_SUBSTRINGS = ["NICON", "CNN", "Ridge", "LGBM", "PLS"]  # case-sensitive

DEFAULT_REFERENCE_MODE = "per_dataset_best"    # "fixed_model" or "per_dataset_best"
DEFAULT_REFERENCE_MODEL_REG = "PLS_reg"   # used only if reference_mode == fixed_model
DEFAULT_REFERENCE_MODEL_CLASSIF = "PLS_classif"

DEFAULT_DELTA_MARGIN = 0.1
DEFAULT_ALPHA = 0.05
DEFAULT_BOOTSTRAP_B = 2000
DEFAULT_CI_LEVEL = 0.95
DEFAULT_RANDOM_SEED = 42

DEFAULT_OUTPUT_PREFIX = "noninferiority"  # will produce <prefix>_reg.csv / <prefix>_classif.csv

# Optional restrictions
PREP_CASE_SENSITIVE = True

# Preprocessings to exclude globally (independent of RESTRICT_TO_PREPS)
EXCLUDE_PREPS = {"PCA"}



# ------------------------- Utilities -------------------------

def discover_dataset_csvs(root: str) -> List[Tuple[str, str]]:
    """Discover (dataset_name, csv_path) pairs under root.
    The FIRST CSV (sorted) in each dataset dir that matches the rules is selected.
    """
    pairs: List[Tuple[str, str]] = []
    if not os.path.isdir(root):
        print(f"[WARN] Root directory not found: {root}")
        return pairs

    for ds in sorted(os.listdir(root)):
        ds_dir = os.path.join(root, ds)
        if not os.path.isdir(ds_dir):
            continue
        candidates = [f for f in os.listdir(ds_dir)
                      if f.startswith(FILENAME_PREFIX) and f.lower().endswith(".csv")]
        candidates = [f for f in candidates
                      if not any(excl in f for excl in FILENAME_EXCLUDE_SUBSTRINGS)]
        if not candidates:
            continue
        candidates.sort()
        csv_path = os.path.join(ds_dir, candidates[0])
        pairs.append((ds, csv_path))
    return pairs


def detect_task_from_models(models: List[str]) -> str:
    """Detect task type from model names within a CSV.
    Returns "regression", "classification", or "ambiguous"/"unknown".
    - regression if any model endswith "_reg" and no model endswith "_classif"
    - classification if any endswith "_classif" and no endswith "_reg"
    - ambiguous if both are present
    - unknown if none matches
    """
    has_reg = any(isinstance(m, str) and m.endswith("_reg") for m in models)
    has_clf = any(isinstance(m, str) and m.endswith("_classif") for m in models)
    if has_reg and not has_clf:
        return "regression"
    if has_clf and not has_reg:
        return "classification"
    if has_reg and has_clf:
        return "ambiguous"
    return "unknown"


def benjamini_hochberg(pvals: List[Optional[float]]) -> List[Optional[float]]:
    """Benjamini–Hochberg FDR adjustment. None p-values are preserved as None."""
    n = len(pvals)
    with_idx = [(i, p) for i, p in enumerate(pvals) if p is not None]
    m = len(with_idx)
    if m == 0:
        return [None] * n
    # Sort by p ascending
    with_idx.sort(key=lambda t: t[1])
    # Compute q values with monotonicity
    qs = [None] * n
    prev_q = 1.0
    for rank, (i, p) in enumerate(reversed(with_idx), start=1):
        q = min(prev_q, p * m / (m - rank + 1))
        qs[i] = q
        prev_q = q
    return qs


def exact_sign_test_pvalue(diffs: np.ndarray, delta: float) -> Tuple[Optional[float], int]:
    """Exact one-sided sign test for non-inferiority on Y = diffs - delta.
    H0: median(Y) >= 0  vs  H1: median(Y) < 0
    Ties Y == 0 are removed.
    Returns (p_value, n_effective).
    """
    y = diffs - delta
    eff = y[np.abs(y) > 0]
    n_eff = eff.size
    if n_eff == 0:
        return None, 0
    s = int(np.sum(eff < 0))
    if SCIPY_AVAILABLE:
        p = float(binom.cdf(s, n_eff, 0.5))
    else:
        # Exact binomial CDF without SciPy
        from math import comb
        p = sum(comb(n_eff, k) * (0.5 ** n_eff) for k in range(0, s + 1))
    return p, n_eff


def wilcoxon_less_pvalue(diffs: np.ndarray, delta: float) -> Tuple[Optional[float], int]:
    """One-sided Wilcoxon signed-rank on Y = diffs - delta ('less').
    Returns (p_value, n_effective = count of non-zero pairs)."""
    y = diffs - delta
    n_eff = int(np.sum(np.abs(y) > 0))
    if n_eff == 0 or not SCIPY_AVAILABLE:
        return None, n_eff
    try:
        stat, p = wilcoxon(y, alternative="less", zero_method="wilcox", correction=False, mode="auto")
        return float(p), n_eff if isinstance(p, float) else (None, n_eff)
    except Exception:
        return None, n_eff


def bootstrap_ci_median(diffs: np.ndarray, ci: float, B: int, seed: int) -> Tuple[float, float]:
    """Bootstrap percentile CI for the median of diffs. Returns (lower, upper)."""
    rng = np.random.default_rng(seed)
    n = len(diffs)
    if n == 0:
        return (float("nan"), float("nan"))
    meds = np.empty(B, dtype=float)
    for b in range(B):
        idx = rng.integers(0, n, n)
        meds[b] = np.median(diffs[idx])
    alpha = 1 - ci
    lo = float(np.quantile(meds, alpha / 2))
    hi = float(np.quantile(meds, 1 - alpha / 2))
    return lo, hi


# ------------------------- Core data assembly -------------------------

def harmonize_model_name(model: str) -> str:
    """Unify NICON and CNN into the same model family."""
    if not isinstance(model, str):
        return model
    if model.endswith("_reg"):
        if "NICON" in model or "CNN" in model:
            return "CNN_reg"
    if model.endswith("_classif"):
        if "NICON" in model or "CNN" in model:
            return "CNN_classif"
    return model

def collect_diffs_split_by_task(dataset_csvs: List[Tuple[str, str]],
                                reference_mode: str,
                                ref_model_reg: Optional[str],
                                ref_model_classif: Optional[str],
                                restrict_models: Optional[set],
                                restrict_preps: Optional[set],
                                prep_case_sensitive: bool) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Collect Δ across datasets and split into two tidy DataFrames (regression, classification).

    Returns:
      diffs_reg: columns [dataset, candidate_model, prep, delta_value]
      diffs_clf: columns [dataset, candidate_model, prep, delta_value]
    """
    reg_rows = []
    clf_rows = []

    for ds_name, csv_path in dataset_csvs:
        try:
            wide = pd.read_csv(csv_path)
        except Exception as e:
            print(f"[WARN] Failed to read CSV '{csv_path}': {e}")
            continue

        if MODEL_COL not in wide.columns:
            print(f"[WARN] Missing '{MODEL_COL}' in {csv_path}, skipping dataset.")
            continue

        models = [str(x) for x in wide[MODEL_COL].dropna().tolist()]
        task = detect_task_from_models(models)
        if task in ("ambiguous", "unknown"):
            print(f"[WARN] Dataset '{ds_name}' task is {task}; skipping.")
            continue

        # Long format
        df = wide.melt(id_vars=[MODEL_COL], var_name="prep", value_name="metric").rename(columns={MODEL_COL: "model"})
        df["model"] = df["model"].apply(harmonize_model_name)

        # Exclude unwanted preprocessings globally
        if EXCLUDE_PREPS:
            df = df[~df["prep"].isin(EXCLUDE_PREPS)]

        df["metric"] = pd.to_numeric(df["metric"], errors="coerce")
        df = df.dropna(subset=["metric"])


        # Restrictions
        if restrict_models is not None:
            df = df[df["model"].isin(restrict_models)]
        if restrict_preps is not None:
            if prep_case_sensitive:
                df = df[df["prep"].isin(restrict_preps)]
            else:
                df = df[df["prep"].str.lower().isin({p.lower() for p in restrict_preps})]

        if df.empty:
            continue

        pivot = df.pivot_table(index="model", columns="prep", values="metric", aggfunc="mean")

        if reference_mode == "fixed_model":
            ref_model = ref_model_reg if task == "regression" else ref_model_classif
            if ref_model not in pivot.index:
                # Can't compute diffs for this dataset
                continue
            ref_row = pivot.loc[ref_model]
            for cand in pivot.index:
                if cand == ref_model:
                    continue
                for prep in pivot.columns:
                    c_val = pivot.loc[cand, prep]
                    r_val = ref_row[prep]
                    if pd.isna(c_val) or pd.isna(r_val):
                        continue
                    if task == "regression":    # smaller is better
                        delta_val = float(c_val - r_val)
                        reg_rows.append((ds_name, cand, str(prep), delta_val))
                    else:                       # classification: larger is better
                        delta_val = float(r_val - c_val)
                        clf_rows.append((ds_name, cand, str(prep), delta_val))

        elif reference_mode == "per_dataset_best":
            for prep in pivot.columns:
                col = pivot[prep].dropna()
                if col.empty:
                    continue
                if task == "regression":   # best = min
                    best_model = col.idxmin()
                    best_val = float(col.min())
                else:                      # best = max
                    best_model = col.idxmax()
                    best_val = float(col.max())
                for cand in pivot.index:
                    if cand == best_model or pd.isna(pivot.loc[cand, prep]):
                        continue
                    if task == "regression":
                        delta_val = float(pivot.loc[cand, prep] - best_val)
                        reg_rows.append((ds_name, cand, str(prep), delta_val))
                    else:
                        delta_val = float(best_val - pivot.loc[cand, prep])
                        clf_rows.append((ds_name, cand, str(prep), delta_val))
        else:
            raise ValueError(f"Unknown reference_mode: {reference_mode}")

    diffs_reg = pd.DataFrame(reg_rows, columns=["dataset", "candidate_model", "prep", "delta_value"])
    diffs_clf = pd.DataFrame(clf_rows, columns=["dataset", "candidate_model", "prep", "delta_value"])
    return diffs_reg, diffs_clf


# ------------------------- Statistical tests (model-by-model) -------------------------

def run_tests_model_by_model(diffs_df: pd.DataFrame,
                             delta_margin: float,
                             alpha: float,
                             ci_level: float,
                             bootstrap_B: int,
                             seed: int,
                             apply_fdr: bool = False) -> pd.DataFrame:
    """Run sign test, Wilcoxon, and bootstrap CI **within each candidate model** across preprocessings.
    Grouping key is (candidate_model, prep). FDR is computed **within candidate model**.
    """
    if diffs_df.empty:
        return pd.DataFrame(columns=[
            "candidate_model","prep","n_datasets","n_pairs",
            "median_diff","mean_diff",
            "sign_p","sign_q","sign_n_eff","noninferior_sign","noninferior_sign_fdr",
            "wilcoxon_p","wilcoxon_q","wilcoxon_n_eff","noninferior_wilcoxon","noninferior_wilcoxon_fdr",
            "boot_ci_low","boot_ci_high","noninferior_bootstrap"
        ])

    rows = []
    grouped = diffs_df.groupby(["candidate_model", "prep"], sort=False)
    for (cand, prep), g in grouped:
        diffs = g["delta_value"].to_numpy(dtype=float)
        diffs = diffs[np.isfinite(diffs)]
        if diffs.size == 0:
            continue

        sign_p, sign_n = exact_sign_test_pvalue(diffs, delta_margin)
        wil_p, wil_n = wilcoxon_less_pvalue(diffs, delta_margin)
        ci_lo, ci_hi = bootstrap_ci_median(diffs, ci=ci_level, B=bootstrap_B, seed=seed)
        median_diff = float(np.median(diffs))
        mean_diff = float(np.mean(diffs))

        rows.append({
            "candidate_model": cand,
            "prep": prep,
            "n_datasets": int(g["dataset"].nunique()),
            "n_pairs": int(diffs.size),
            "median_diff": median_diff,
            "mean_diff": mean_diff,
            "sign_p": sign_p,
            "sign_n_eff": sign_n,
            "wilcoxon_p": wil_p,
            "wilcoxon_n_eff": wil_n,
            "boot_ci_low": ci_lo,
            "boot_ci_high": ci_hi,
        })

    out = pd.DataFrame(rows)

    # Compute FDR within each candidate model (over its preprocessings)
    if not out.empty:
        out = out.sort_values(["candidate_model", "prep"]).reset_index(drop=True)

        if apply_fdr:
            out["sign_q"] = np.nan
            out["wilcoxon_q"] = np.nan
            for cand, sub in out.groupby("candidate_model", sort=False):
                idx = sub.index
                out.loc[idx, "sign_q"] = benjamini_hochberg([out.loc[i, "sign_p"] for i in idx])
                out.loc[idx, "wilcoxon_q"] = benjamini_hochberg([out.loc[i, "wilcoxon_p"] for i in idx])

            out["noninferior_sign_fdr"] = out.apply(lambda r: (not pd.isna(r["sign_q"])) and (r["sign_q"] < alpha), axis=1)
            out["noninferior_wilcoxon_fdr"] = out.apply(lambda r: (not pd.isna(r["wilcoxon_q"])) and (r["wilcoxon_q"] < alpha), axis=1)
        else:
            out["sign_q"] = np.nan
            out["wilcoxon_q"] = np.nan
            out["noninferior_sign_fdr"] = np.nan
            out["noninferior_wilcoxon_fdr"] = np.nan

        out["noninferior_sign"] = out["sign_p"].apply(lambda p: (p is not None) and (p < alpha))
        out["noninferior_wilcoxon"] = out["wilcoxon_p"].apply(lambda p: (p is not None) and (p < alpha))
        out["noninferior_bootstrap"] = out["boot_ci_high"] < delta_margin

    return out



# ------------------------- Visualization -------------------------

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import os

def make_visualizations_by_task_and_model(summary: pd.DataFrame, 
                                          delta_margin: float, 
                                          alpha: float, 
                                          output_dir: str, 
                                          task_label: str):
    """Generate volcano + forest plots per model, 
    and one global heatmap for all models within the task."""

    if summary.empty:
        print(f"[WARN] No summary to visualize for {task_label}.")
        return

    os.makedirs(output_dir, exist_ok=True)

    # ---------------- Per-model volcano + forest ----------------
    for cand_model, sub in summary.groupby("candidate_model"):
        sub = sub[~sub["prep"].isin(EXCLUDE_PREPS)]
        if sub.empty:
            continue

        model_safe = cand_model.replace("/", "_").replace(" ", "_")
        prefix = os.path.join(output_dir, f"{task_label}_{model_safe}")

        # Volcano
        plt.figure(figsize=(8,6))
        x = sub["median_diff"]
        y = -np.log10(sub["wilcoxon_p"].fillna(1.0))
        colors = []
        for md, p in zip(sub["median_diff"], sub["wilcoxon_p"]):
            if p is None or np.isnan(p):
                colors.append("gray")
            elif (p < alpha) and (md < delta_margin):
                colors.append("green")
            elif (p < alpha) and (md >= delta_margin):
                colors.append("red")
            else:
                colors.append("orange")
        plt.scatter(x, y, c=colors, alpha=0.7)
        plt.axvline(delta_margin, color="black", linestyle="--", label=f"delta={delta_margin}")
        plt.xlabel("Median Δ (candidate - reference)")
        plt.ylabel("-log10 p-value (Wilcoxon)")
        plt.title(f"Volcano plot - {cand_model} ({task_label})")
        plt.legend()
        plt.tight_layout()
        plt.savefig(f"{prefix}_volcano.png")
        plt.close()

        # Forest
        fig_height = max(6, 0.5*len(sub))
        fig, ax = plt.subplots(figsize=(10, fig_height))
        sorted_sub = sub.sort_values("median_diff")
        y_positions = range(len(sorted_sub))
        ax.errorbar(x=sorted_sub["median_diff"], y=y_positions,
                    xerr=[sorted_sub["median_diff"]-sorted_sub["boot_ci_low"],
                          sorted_sub["boot_ci_high"]-sorted_sub["median_diff"]],
                    fmt='o', ecolor="gray", capsize=3)
        ax.axvline(delta_margin, color="red", linestyle="--", label=f"delta={delta_margin}")
        ax.set_yticks(y_positions)
        labels = [f"{p}" for p in sorted_sub["prep"]]
        ax.set_yticklabels(labels, fontsize=9)
        ax.set_xlabel("Median Δ with bootstrap CI", fontsize=11)
        ax.set_title(f"Forest plot - {cand_model} ({task_label})", fontsize=12)
        ax.legend()
        plt.tight_layout()
        plt.savefig(f"{prefix}_forest.png")
        plt.close()

    # ---------------- Global heatmap for all models ----------------
    summary_no_pca = summary[~summary["prep"].isin(EXCLUDE_PREPS)]
    if summary_no_pca.empty:
        return

    decision_matrix = summary_no_pca.pivot(index="candidate_model", columns="prep",
                                           values="noninferior_wilcoxon")
    cmap = {True:1, False:0, None:np.nan}
    mat = decision_matrix.applymap(lambda v: cmap.get(v, np.nan))

    n_preps = len(mat.columns)
    n_models = len(mat.index)
    fig_width = max(12, 0.6*n_preps)
    fig_height = max(6, 0.5*n_models)

    plt.figure(figsize=(fig_width, fig_height))
    sns.heatmap(mat, cmap=sns.color_palette(["red","green"]),
                cbar=False, linewidths=0.5, linecolor="gray",
                annot=True, fmt="", xticklabels=True, yticklabels=True)

    plt.xticks(fontsize=8, rotation=45, ha="right")
    plt.yticks(fontsize=9, rotation=0)
    plt.title(f"Global Heatmap of non-inferiority (Wilcoxon) - {task_label}", fontsize=12)
    plt.xlabel("Preprocessing", fontsize=11)
    plt.ylabel("Model", fontsize=11)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, f"{task_label}_heatmap_global.png"))
    plt.close()

    print(f"[INFO] Global heatmap saved for {task_label} in {output_dir}")


# ------------------------- Main -------------------------

def main():
    parser = argparse.ArgumentParser(description="Non-inferiority tests split by task, model-by-model.")
    parser.add_argument("--root", type=str, default=DEFAULT_RESULTS_ROOT, help="Root directory with dataset subfolders.")
    parser.add_argument("--reference_mode", type=str, choices=["fixed_model", "per_dataset_best"],
                        default=DEFAULT_REFERENCE_MODE, help="Reference choice.")
    parser.add_argument("--reference_model_reg", type=str, default=DEFAULT_REFERENCE_MODEL_REG,
                        help="Reference model name when task=regression and reference_mode=fixed_model.")
    parser.add_argument("--reference_model_classif", type=str, default=DEFAULT_REFERENCE_MODEL_CLASSIF,
                        help="Reference model name when task=classification and reference_mode=fixed_model.")
    parser.add_argument("--delta", type=float, default=DEFAULT_DELTA_MARGIN, help="Non-inferiority margin δ.")
    parser.add_argument("--alpha", type=float, default=DEFAULT_ALPHA, help="Significance level (one-sided).")
    parser.add_argument("--bootstrap", type=int, default=DEFAULT_BOOTSTRAP_B, help="Bootstrap resamples for CI.")
    parser.add_argument("--ci", type=float, default=DEFAULT_CI_LEVEL, help="Confidence level for bootstrap CI.")
    parser.add_argument("--restrict_models", type=str, default=None,
                        help="JSON array of model names to include (or None).")
    parser.add_argument("--restrict_preps", type=str, default=None,
                        help="JSON array of preprocessing names to include (or None).")
    parser.add_argument("--output_prefix", type=str, default=DEFAULT_OUTPUT_PREFIX,
                        help="Prefix for output files. Will create <prefix>_reg.csv and <prefix>_classif.csv.")
    parser.add_argument("--fig_dir", type=str, default="Figures/assoc_pp_model/All_datasets",
                        help="Directory where figures will be saved (subfolders per task).")
    parser.add_argument("--fdr", action="store_true", default=False,
                    help="Apply Benjamini-Hochberg FDR correction (default: False).")
    args = parser.parse_args()

    # Parse restrictions
    restrict_models = set(json.loads(args.restrict_models)) if args.restrict_models else None
    restrict_preps = set(json.loads(args.restrict_preps)) if args.restrict_preps else None

    # Discover CSVs
    dataset_csvs = discover_dataset_csvs(args.root)
    if not dataset_csvs:
        print(f"[WARN] No dataset CSVs discovered under {args.root}.")
        return

    # Collect Δ split by task
    diffs_reg, diffs_clf = collect_diffs_split_by_task(
        dataset_csvs=dataset_csvs,
        reference_mode=args.reference_mode,
        ref_model_reg=args.reference_model_reg,
        ref_model_classif=args.reference_model_classif,
        restrict_models=restrict_models,
        restrict_preps=restrict_preps,
        prep_case_sensitive=PREP_CASE_SENSITIVE
    )

    # Run tests per task (model-by-model within task)
    summary_reg = run_tests_model_by_model(diffs_reg, args.delta, args.alpha, args.ci, args.bootstrap, DEFAULT_RANDOM_SEED, apply_fdr=args.fdr)
    summary_clf = run_tests_model_by_model(diffs_clf, args.delta, args.alpha, args.ci, args.bootstrap, DEFAULT_RANDOM_SEED, apply_fdr=args.fdr)

    # Save reports and raw diffs
    out_reg = f"Results/assoc_pp_model/All_datasets/Global_tests/{args.output_prefix}_reg.csv"
    out_clf = f"Results/assoc_pp_model/All_datasets/Global_tests/{args.output_prefix}_classif.csv"
    summary_reg.to_csv(out_reg, index=False)
    summary_clf.to_csv(out_clf, index=False)
    diffs_reg.to_csv(f"Results/assoc_pp_model/All_datasets/Global_tests/{args.output_prefix}_reg_diffs.csv", index=False)
    diffs_clf.to_csv(f"Results/assoc_pp_model/All_datasets/Global_tests/{args.output_prefix}_classif_diffs.csv", index=False)
    print(f"[INFO] Saved regression report: {out_reg} (and *_reg_diffs.csv)")
    print(f"[INFO] Saved classification report: {out_clf} (and *_classif_diffs.csv)")

    # Figures per task (per model)
    if not summary_reg.empty:
        make_visualizations_by_task_and_model(summary_reg, args.delta, args.alpha, 
                                              os.path.join(args.fig_dir, "regression"), "regression")

    if not summary_clf.empty:
        make_visualizations_by_task_and_model(summary_clf, args.delta, args.alpha, 
                                              os.path.join(args.fig_dir, "classification"), "classification")

    print(f"[INFO] Figures saved under '{args.fig_dir}/regression' and '{args.fig_dir}/classification' (if any).")


if __name__ == "__main__":
    main()