#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Adaptive gatekeeping pipeline for filtering (model, preprocessing) pairs.

Corrections:
------------
✅ Gate 1 now compares candidate performance to the *best model per dataset*
   instead of comparing to its own mean (fixes high p-values ~0.95).
✅ Gate 2 correlation test skips constant or degenerate vectors,
   preventing artificial identical p-values (~0.0004) across all pairs.
✅ Vectorized Westfall–Young maxT correlation test remains, but handles NaN safely.
✅ Benjamini–Hochberg correction applied to Gate 2 p-values.
✅ Added --task_only CLI argument to restrict processing to regression/classification.
✅ Added --batch_size CLI argument for permutation efficiency control.

Author: Generated by ChatGPT (OpenAI)
All comments in English.
"""

# ===============================================================
# Imports
# ===============================================================

import os
import numpy as np
import pandas as pd
import argparse
import warnings
import sys
import random
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import spearmanr, binomtest, ConstantInputWarning
from tqdm import tqdm

warnings.filterwarnings("ignore", category=ConstantInputWarning)

# ===============================================================
# Deterministic setup
# ===============================================================

def set_global_determinism(seed: int = 42):
    """Set deterministic behavior across numpy, random, and OS threads."""
    os.environ["PYTHONHASHSEED"] = str(seed)
    os.environ["OMP_NUM_THREADS"] = "1"
    os.environ["OPENBLAS_NUM_THREADS"] = "1"
    os.environ["MKL_NUM_THREADS"] = "1"
    os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
    os.environ["NUMEXPR_NUM_THREADS"] = "1"
    random.seed(seed)
    np.random.seed(seed)

set_global_determinism(42)

# ===============================================================
# Utility Functions
# ===============================================================

def benjamini_hochberg(pvals):
    """Benjamini–Hochberg FDR correction."""
    pvals = np.array(pvals, dtype=float)
    n = len(pvals)
    order = np.argsort(pvals)
    qvals = np.empty_like(pvals)
    prev_q = 1.0
    for rank, idx in enumerate(order[::-1], start=1):
        q = min(prev_q, pvals[idx] * n / (n - rank + 1))
        qvals[idx] = q
        prev_q = q
    return qvals


def exact_sign_test(diff, delta):
    """Exact one-sided sign test: H0 median(diff - delta) <= 0 vs H1 > 0."""
    y = diff - delta
    y = y[np.abs(y) > 0]
    n = len(y)
    if n == 0:
        return None
    s = np.sum(y > 0)
    p_res = binomtest(s, n, 0.5, alternative="greater")
    return float(p_res.pvalue if hasattr(p_res, "pvalue") else p_res)

# ===============================================================
# Vectorized Westfall–Young maxT permutation test (fixed)
# ===============================================================

def gate2_maxT_permutation_vectorized(candidate_vec: pd.Series,
                                      kept_block: pd.DataFrame,
                                      rng_seed: int = 42,
                                      n_perm: int = 10000,
                                      use_resid: bool = True,
                                      batch_size: int = 256):
    """
    Vectorized Westfall–Young maxT permutation test for correlation redundancy (ρ > 0).
    Now skips constant/degenerate vectors and handles NaNs safely.
    """
    rng = np.random.default_rng(rng_seed)
    valid_pairs = []
    rho_obs = []

    # Gather valid correlation pairs
    for idx in kept_block.index:
        y = kept_block.loc[idx].dropna()
        common = candidate_vec.index.intersection(y.index)
        if len(common) < 3:
            continue
        x_vals = candidate_vec.loc[common].to_numpy(dtype=float)
        y_vals = y.loc[common].to_numpy(dtype=float)

        # Skip degenerate or constant vectors
        if np.nanstd(x_vals) < 1e-10 or np.nanstd(y_vals) < 1e-10:
            continue

        rho = spearmanr(x_vals, y_vals)[0]
        if np.isnan(rho) or np.isinf(rho):
            continue

        valid_pairs.append((x_vals, y_vals))
        rho_obs.append(rho)

    m_valid = len(valid_pairs)
    if m_valid == 0:
        return None, None, 0

    T_obs = float(np.nanmax(rho_obs))

    # Prepare rank-transformed matrices
    max_len = max(len(x) for (x, _) in valid_pairs)
    Xr = np.full((m_valid, max_len), np.nan)
    Yr = np.full((m_valid, max_len), np.nan)

    for i, (x, y) in enumerate(valid_pairs):
        rx = pd.Series(x).rank(method="average").to_numpy()
        ry = pd.Series(y).rank(method="average").to_numpy()
        if use_resid:
            rx -= rx.mean()
            ry -= ry.mean()
        Xr[i, :len(x)] = rx
        Yr[i, :len(y)] = ry

    denom_X = np.nansum(Xr**2, axis=1)**0.5
    denom_Y = np.nansum(Yr**2, axis=1)**0.5
    denom = denom_X * denom_Y
    valid_mask = denom > 0
    Xr, Yr, denom = Xr[valid_mask], Yr[valid_mask], denom[valid_mask]
    m_valid = Xr.shape[0]

    n = Xr.shape[1]
    perms = np.array([rng.permutation(n) for _ in range(n_perm)])
    max_stats = np.full(n_perm, -np.inf)

    for start in range(0, n_perm, batch_size):
        end = min(start + batch_size, n_perm)
        batch_perm = perms[start:end]
        X_perm = np.take_along_axis(np.broadcast_to(Xr, (end - start, *Xr.shape)),
                                    batch_perm[:, None, :], axis=2)
        cov = np.nansum(X_perm * Yr[None, :, :], axis=2)
        rhos = cov / denom[None, :]
        max_stats[start:end] = np.nanmax(rhos, axis=1)

    exceed = np.sum(max_stats >= T_obs - 1e-15)
    p_maxT = (exceed + 1.0) / (n_perm + 1.0)

    return float(T_obs), float(p_maxT), m_valid

# ===============================================================
# Gatekeeping logic (Gate 1 fixed)
# ===============================================================

def iterative_gatekeeping(df: pd.DataFrame, delta: float, alpha: float,
                          n_perm: int, seed: int, batch_size: int):
    """
    Adaptive gatekeeping selection:
      Gate 1: performance degradation vs dataset-wise best model
      Gate 2: redundancy via maxT permutation correlation
    """
    mat = df.pivot_table(index=["candidate_model", "prep"], columns="dataset", values="metric", aggfunc="mean")
    kept_mask = pd.Series(False, index=mat.index)
    records = {}

    # Compute dataset-wise best performances
    task_type = df["task"].iloc[0]
    best_per_dataset = (df.groupby("dataset")["metric"].min()
                        if task_type == "regression"
                        else df.groupby("dataset")["metric"].max())

    for idx in tqdm(mat.index, desc="Gatekeeping iteration"):
        vec = mat.loc[idx].dropna()
        if len(vec) < 3:
            records[idx] = {"gate1_p": None, "gate2_p": None, "decision": "SKIP"}
            continue

        # --- Gate 1: performance degradation test (vs best model per dataset) ---
        diffs = []
        for ds, val in vec.items():
            if ds in best_per_dataset.index:
                diffs.append(val - best_per_dataset.loc[ds])
        diffs = np.array(diffs)

        if len(diffs) == 0:
            p1 = None
            median_gain = np.nan
        else:
            p1 = exact_sign_test(diffs, delta)
            median_gain = np.median(diffs)  # <-- NEW: median gain vs best

        # --- Gate 2: redundancy correlation test ---
        if kept_mask.any():
            kept_block = mat.loc[kept_mask]
            T_obs, p2, m_valid = gate2_maxT_permutation_vectorized(
                vec, kept_block,
                rng_seed=seed,
                n_perm=n_perm,
                batch_size=batch_size
            )
        else:
            T_obs, p2, m_valid = np.nan, np.nan, 0

        # Record everything
        records[idx] = {
            "gate1_p": p1,
            "gate2_p": p2,
            "rho_max": T_obs,
            "m_valid": m_valid,
            "median_gain_vs_best": median_gain  # <-- NEW field stored for plotting
        }

        # Decision to whether exclude a couple or keep it
        condition_perf = (p1 is not None and p1 < alpha)
        condition_corr = (p2 is not None and p2 < alpha) and (T_obs > args.corr_threshold)
        if condition_perf and condition_corr:
            kept_mask.loc[idx] = False
            records[idx]["decision"] = "EXCLUDE"
        else:
            kept_mask.loc[idx] = True
            records[idx]["decision"] = "KEEP"

    # Build the report DataFrame safely
    report_df = pd.DataFrame.from_dict(records, orient="index")
    if isinstance(report_df.index, pd.MultiIndex):
        report_df = report_df.reset_index(names=["candidate_model", "prep"])
    else:
        report_df = report_df.reset_index()
        if "index" in report_df.columns:
            report_df[["candidate_model", "prep"]] = pd.DataFrame(
                report_df["index"].tolist(), index=report_df.index)
            report_df.drop(columns="index", inplace=True)

    # --- Apply BH correction to Gate 2 ---
    valid_p2 = report_df["gate2_p"].dropna()
    if len(valid_p2) > 0:
        q2 = benjamini_hochberg(valid_p2.values)
        report_df.loc[report_df["gate2_p"].notna(), "gate2_q"] = q2
    else:
        report_df["gate2_q"] = np.nan

    # --- Flag significant correlation (statistical + practical) ---
    report_df["corr_significant"] = (
        (report_df["gate2_q"] < alpha) &
        (report_df["rho_max"].abs() >= args.corr_threshold)
    )

    return report_df, kept_mask

# ===============================================================
# Visualization
# ===============================================================

def visualize_gatekeeping(report_df: pd.DataFrame, kept_mask: pd.Series, output_prefix: str, task: str):
    """Generate global scatter, heatmap, and p-value histograms."""
    os.makedirs(os.path.dirname(output_prefix), exist_ok=True)
    fig_path = f"{output_prefix}/{task}".replace("Results", "Figures")

    # --- Scatterplot: correlation vs median gain vs best model ---
    plt.figure(figsize=(8,6))
    sns.scatterplot(
        data=report_df,
        x="rho_max",
        y="median_gain_vs_best",
        hue="decision",
        style="corr_significant",  # <-- NEW: use cross/ring for correlation significance
        markers={True: "X", False: "o"},  # True → cross, False → circle
        palette={"KEEP": "green", "EXCLUDE": "red", "SKIP": "gray"},
        s=90,  # marker size
        alpha=0.85
    )

    # Add visual reference lines
    plt.axhline(0, color="gray", linestyle="--", alpha=0.6)
    plt.axvline(args.corr_threshold, color="black", linestyle="--", linewidth=1.2)
    
    plt.xlabel("Max correlation with S (Gate 2)")
    plt.ylabel("Median gain vs best model (negative = better)")
    plt.title(f"Gatekeeping scatter - {task}")
    plt.legend(title="Decision / Corr. sig.", loc="best", fontsize=9)
    plt.tight_layout()
    plt.savefig(fig_path + "_scatter.png", dpi=300)
    plt.close()

    # --- Plot the decision heatmap
    pivot = report_df.pivot(index="candidate_model", columns="prep", values="decision")
    mat = pivot.map(lambda v: 1 if str(v).upper()=="KEEP" else 0 if str(v).upper()=="EXCLUDE" else np.nan)
    plt.figure(figsize=(max(10,0.4*len(mat.columns)), max(6,0.4*len(mat.index))))
    sns.heatmap(mat, cmap=sns.color_palette(["red","green"]), cbar=False, linewidths=0.5, linecolor="gray")
    plt.title(f"Global decision heatmap - {task}")
    plt.xlabel("Preprocessing")
    plt.ylabel("Model")
    plt.tight_layout()
    plt.savefig(fig_path + "_heatmap.png", dpi=300)
    plt.close()

    # --- Plot the histograms of pvalues repartitions on both gates
    fig, axes = plt.subplots(1,2,figsize=(10,4))
    sns.histplot(report_df["gate1_p"], bins=20, ax=axes[0], color="blue")
    sns.histplot(report_df["gate2_p"], bins=20, ax=axes[1], color="orange")
    axes[0].set_title("Gate 1 p-values (performance)")
    axes[1].set_title("Gate 2 p-values (correlation)")  
    plt.tight_layout()
    plt.savefig(fig_path + "_pvals.png", dpi=300)
    plt.close()

# ===============================================================
# Data loading
# ===============================================================

def discover_dataset_csvs(root="Results/assoc_pp_model"):
    dataset_files = []
    for ds in sorted(os.listdir(root)):
        ds_dir = os.path.join(root, ds)
        if not os.path.isdir(ds_dir):
            continue
        candidates = [f for f in os.listdir(ds_dir)
                      if f.startswith("results_") and f.endswith(".csv")
                      and not any(bad in f for bad in ["CNN","LGBM","PLS","Ridge","NICON","dynamic"])]
        if candidates:
            candidates.sort()
            dataset_files.append((ds, os.path.join(ds_dir, candidates[0])))
    return dataset_files


def collect_and_merge_results(dataset_csvs):
    """
    Load all dataset CSVs and merge them into a unified DataFrame.
    CNN and NICON are considered the same model family and are merged by averaging their metrics.
    """
    all_dfs = []

    for ds, path in dataset_csvs:
        try:
            df = pd.read_csv(path)
        except Exception:
            continue

        # --- Skip invalid CSVs ---
        if "Model" not in df.columns:
            continue

        # --- Detect task type ---
        models = df["Model"].astype(str)
        if any(m.endswith("_reg") for m in models):
            task = "regression"
        elif any(m.endswith("_classif") for m in models):
            task = "classification"
        else:
            continue

        # --- Long-format melt ---
        long = df.melt(id_vars=["Model"], var_name="prep", value_name="metric")
        long["dataset"] = ds
        long["task"] = task
        long.rename(columns={"Model": "candidate_model"}, inplace=True)

        # --- 🔹 Merge CNN and NICON together ---
        # Step 1: Normalize model names — treat all CNN* as NICON*
        long["candidate_model"] = long["candidate_model"].replace(
            {m: m.replace("CNN", "NICON") for m in long["candidate_model"] if "CNN" in m}
        )

        # Step 2: Aggregate duplicates (same model, prep, dataset)
        long = (
            long.groupby(["candidate_model", "prep", "dataset", "task"], as_index=False)
                .agg({"metric": "mean"})
        )

        all_dfs.append(long)

    # --- Final concatenation ---
    if not all_dfs:
        return pd.DataFrame()
    return pd.concat(all_dfs, ignore_index=True)

def build_selection_table(df_task: pd.DataFrame,
                          kept_mask: pd.Series) -> pd.DataFrame:
    """
    Build a flat selection table with mean/std metric per (model, preprocessing)
    and a 'selected' flag from kept_mask.
    """
    # Mean / std across datasets for each (model, prep)
    stats = (
        df_task
        .groupby(["candidate_model", "prep"], as_index=True)["metric"]
        .agg(metric_mean="mean", metric_std="std")
    )

    # Align kept_mask (MultiIndex) into a DataFrame
    sel = kept_mask.rename("selected").to_frame()

    # Join and tidy
    out = stats.join(sel, how="left")
    out["selected"] = out["selected"].fillna(False).astype(bool)

    # Final column names as requested
    out = out.reset_index().rename(columns={
        "candidate_model": "model_name",
        "prep": "preprocessing_name"
    })
    # Optional dataset column (left empty to indicate “aggregated across datasets”)
    out["dataset_name"] = ""  # keep the column for downstream pivots

    # Reorder columns
    out = out[["model_name", "preprocessing_name", "dataset_name", "metric_mean", "metric_std", "selected"]]
    return out

# ===============================================================
# Main
# ===============================================================

parser = argparse.ArgumentParser(description="Gatekeeping pipeline (fixed performance & correlation tests).")
parser.add_argument("--input_dir", type=str, default="Results/assoc_pp_model/per_dataset")
parser.add_argument("--output_prefix", type=str, default="Results/assoc_pp_model/All_datasets/Pipeline_gatekeeping")
parser.add_argument("--delta", type=float, default=0.01)
parser.add_argument("--alpha", type=float, default=0.05)
parser.add_argument("--permutations", type=int, default=2000)
parser.add_argument("--seed", type=int, default=42)
parser.add_argument("--batch_size", type=int, default=500)
parser.add_argument("--task_only", type=str, choices=["regression","classification"], default=None)
parser.add_argument("--corr_threshold", type=float, default=0.7, help="Absolute correlation threshold (|rho|) to consider redundancy practically significant.")
args = parser.parse_args()

dataset_csvs = discover_dataset_csvs(args.input_dir)
merged_df = collect_and_merge_results(dataset_csvs)
if merged_df.empty:
    print("[ERROR] No data found.")
    sys.exit()

if args.task_only:
    merged_df = merged_df[merged_df["task"] == args.task_only]
    print(f"[INFO] Running gatekeeping only for task: {args.task_only}")

# Accumulate selection rows across tasks, then write one file at the end
selection_rows = []

for task, df_task in merged_df.groupby("task"):
    print(f"[INFO] Running gatekeeping for {task}...")
    report_df, kept_mask = iterative_gatekeeping(
        df_task, args.delta, args.alpha, args.permutations, args.seed, args.batch_size
    )

    out_csv = f"{args.output_prefix}/{task}_report.csv"
    keep_csv = f"{args.output_prefix}/{task}_keep.csv"
    os.makedirs(os.path.dirname(out_csv), exist_ok=True)
    report_df.to_csv(out_csv, index=False)
    kept_mask.to_csv(keep_csv)
    print(f"[INFO] Saved {task.upper()} csvs -> {out_csv} / {keep_csv}")

    # --- NEW: build per-task selection table and keep it ---
    sel_tbl = build_selection_table(df_task, kept_mask)
    selection_rows.append(sel_tbl)

    visualize_gatekeeping(report_df, kept_mask, args.output_prefix, task)

# --- NEW: write the unified selection CSV at the very end ---
if selection_rows:
    selection_df = pd.concat(selection_rows, ignore_index=True)
    final_path = os.path.join(args.output_prefix, "pipeline_gatekeeping_selected.csv")
    os.makedirs(os.path.dirname(final_path), exist_ok=True)
    selection_df.to_csv(final_path, index=False)
    print(f"[INFO] Wrote selection summary -> {final_path}")
else:
    print("[WARN] No selection rows to write.")
