#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Adaptive selection of (model, preprocessing) pairs based on:
  - coverage of weaknesses of the current ensemble (non-inferiority on "hard" datasets)
  - conditional correlation significance (redundancy detection via Spearman + permutation + FDR)

Additionally:
  - Generates global visualizations per task (regression/classification)
  - Tracks and plots selection progression (number of kept pairs vs iteration)

Author: Generated by ChatGPT
All comments in English.
"""

import os
import argparse
import numpy as np
import pandas as pd
import warnings
import random
from scipy.stats import ConstantInputWarning
warnings.filterwarnings("ignore", category=ConstantInputWarning)
from scipy.stats import spearmanr, binomtest
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm

# ----------------------- Parameters -----------------------

DEFAULT_OUTPUT_PREFIX = "Results/assoc_pp_model/All_datasets/Pipeline_weakness_coverage/weakness_coverage"

DEFAULT_DELTA_MARGIN = 0.01
DEFAULT_ALPHA = 0.05
DEFAULT_PERMUTATIONS = 100
DEFAULT_FDR = True
DEFAULT_RANDOM_SEED = 42


# ----------------------- Utilities -----------------------

def normalize_within_dataset(df: pd.DataFrame, metric_col: str = "delta_value") -> pd.DataFrame:
    """Normalize performance per dataset so that the best = 1 (for regression) or max = 1 (classification)."""
    df = df.copy()
    if "task" not in df.columns:
        raise ValueError("Missing 'task' column to distinguish regression/classification.")

    df["norm_perf"] = np.nan
    for dset, sub in df.groupby("dataset"):
        task = sub["task"].iloc[0]
        if task == "regression":  # smaller is better
            best = sub[metric_col].min()
            df.loc[sub.index, "norm_perf"] = sub[metric_col] / best if best != 0 else sub[metric_col]
        else:  # classification: larger is better
            best = sub[metric_col].max()
            df.loc[sub.index, "norm_perf"] = best / sub[metric_col]
    return df



# ----------------------- Determinism setup -----------------------

def set_global_determinism(seed: int = 42):
    """Set full deterministic behavior across all libraries."""
    import os
    import numpy as np
    import random

    # Environment variables to limit parallelism
    os.environ["PYTHONHASHSEED"] = str(seed)
    os.environ["OMP_NUM_THREADS"] = "1"
    os.environ["OPENBLAS_NUM_THREADS"] = "1"
    os.environ["MKL_NUM_THREADS"] = "1"
    os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
    os.environ["NUMEXPR_NUM_THREADS"] = "1"
    os.environ["BLIS_NUM_THREADS"] = "1"

    # Python and numpy random seeds
    random.seed(seed)
    np.random.seed(seed)

    # Ensure deterministic hash ordering
    import sys
    if hasattr(sys, "set_int_max_str_digits"):
        sys.set_int_max_str_digits(1000000)

# Call determinism setup early
set_global_determinism(DEFAULT_RANDOM_SEED)



# ----------------------- Statistical functions -----------------------

def permutation_test_corr(x, y, n_perm=5000, alternative="two-sided", seed=42, use_resid=True):
    """
    Deterministic permutation test for Spearman correlation.

    Parameters
    ----------
    x, y : array-like
        Input vectors of equal length.
    n_perm : int, default=5000
        Number of permutations.
    alternative : {'two-sided', 'greater', 'less'}, default='two-sided'
        Direction of the test.
    seed : int, default=42
        Random seed for reproducibility.
    use_resid : bool, default=True
        Whether to mean-center data before computing correlation.

    Returns
    -------
    rho_obs : float
        Observed Spearman correlation.
    p_val : float
        Exact Monte Carlo p-value (Phipson–Smyth corrected).
    """
    # Convert to numpy arrays
    x = np.asarray(x)
    y = np.asarray(y)
    assert x.shape == y.shape, "x and y must have the same length"
    n = len(x)
    if n < 3:
        return np.nan, np.nan

    rng = np.random.default_rng(seed)

    # Optionally mean-center the data (residualization)
    if use_resid:
        x = x - np.mean(x)
        y = y - np.mean(y)

    # Observed Spearman correlation
    rho_obs, _ = spearmanr(x, y)
    if np.isnan(rho_obs):
        return np.nan, np.nan

    # Vectorized permutation test
    perm_indices = np.array([rng.permutation(n) for _ in range(n_perm)])
    x_perm = x[perm_indices]  # shape: (n_perm, n)

    # Rank-transform for Spearman correlation
    rx = np.argsort(np.argsort(x))
    ry = np.argsort(np.argsort(y))
    ry_centered = ry - ry.mean()
    x_perm_rank = np.argsort(np.argsort(x_perm, axis=1), axis=1)
    x_perm_rank_centered = x_perm_rank - x_perm_rank.mean(axis=1, keepdims=True)

    # Compute all permuted correlations at once
    cov = np.sum(x_perm_rank_centered * ry_centered, axis=1)
    denom = np.sqrt(np.sum(x_perm_rank_centered**2, axis=1) * np.sum(ry_centered**2))
    rho_perm = cov / denom

    # Compute permutation p-value according to test direction
    if alternative == "greater":
        exceed = np.sum(rho_perm >= rho_obs)
    elif alternative == "less":
        exceed = np.sum(rho_perm <= rho_obs)
    else:  # two-sided
        exceed = np.sum(np.abs(rho_perm) >= abs(rho_obs))

    # Phipson–Smyth correction (avoids zero p-values)
    p_val = (exceed + 1) / (n_perm + 1)
    return float(rho_obs), float(p_val)


def maxT_corr_pvalue(vec_j, selected, pivot, permutations=2000, seed=42, use_resid=True):
    """
    Vectorized Westfall-Young maxT correlation test for redundancy detection.

    Parameters
    ----------
    vec_j : pd.Series
        Candidate performance vector.
    selected : list of tuples
        Already selected (model, prep) pairs.
    pivot : pd.DataFrame
        Performance matrix (pairs x datasets).
    permutations : int, default=2000
        Number of random permutations for null distribution.
    seed : int, default=42
        Random seed for reproducibility.
    use_resid : bool, default=True
        Whether to center vectors before computing correlation.

    Returns
    -------
    T_obs : float
        Observed maximum Spearman correlation with selected set.
    p_maxT : float
        Westfall-Young p-value controlling FWER.
    ok : bool
        Whether computation was successful.
    """
    rng = np.random.default_rng(seed)
    pairs = []

    # --- Gather all valid correlations between candidate and selected pairs ---
    for s in selected:
        vec_s = pivot.loc[s].dropna()
        common_idx = vec_j.index.intersection(vec_s.index)
        if len(common_idx) >= 3:
            x = vec_j.loc[common_idx].to_numpy()
            y = vec_s.loc[common_idx].to_numpy()
            if use_resid:
                x = x - x.mean()
                y = y - y.mean()
            rho, _ = spearmanr(x, y)
            pairs.append((x, y, rho))

    if not pairs:
        return np.nan, np.nan, False

    rho_obs_list = [r for (_, _, r) in pairs if not np.isnan(r)]
    if len(rho_obs_list) == 0:
        return np.nan, np.nan, False
    T_obs = np.nanmax(rho_obs_list)

    # --- Handle the single-correlation case via standard permutation test ---
    if len(pairs) == 1:
        x, y, rho = pairs[0]
        p = permutation_test_corr(x, y, n_perm=permutations, alternative="greater", seed=seed)[1]
        return rho, p, True

    # --- Vectorized permutation computation ---
    # Each pair has its own number of overlapping datasets, so we handle them separately
    max_T_perm = np.empty(permutations)
    max_T_perm.fill(-np.inf)

    for (x, y, _) in pairs:
        n = len(x)
        if n < 3:
            continue

        # Generate all permutations at once (matrix shape = [permutations, n])
        perm_indices = np.array([rng.permutation(n) for _ in range(permutations)])

        # Rank-transform for Spearman (faster and equivalent)
        rx = np.argsort(np.argsort(x))
        ry = np.argsort(np.argsort(y))

        # Compute correlation for all permutations using vectorized operations
        x_perm_rank = rx[perm_indices]  # shape: [permutations, n]
        x_perm_rank_centered = x_perm_rank - x_perm_rank.mean(axis=1, keepdims=True)
        ry_centered = ry - ry.mean()

        # Compute Pearson correlation on ranks = Spearman correlation
        cov = np.sum(x_perm_rank_centered * ry_centered, axis=1)
        denom = np.sqrt(np.sum(x_perm_rank_centered**2, axis=1) * np.sum(ry_centered**2))
        rhos_perm = cov / denom

        # Update the running maximum across all selected correlations
        max_T_perm = np.maximum(max_T_perm, rhos_perm)

    # --- Compute permutation-based p-value ---
    exceed = np.sum(max_T_perm >= T_obs)
    p_maxT = (exceed + 1) / (permutations + 1)
    return T_obs, p_maxT, True


def benjamini_hochberg(pvals):
    """Benjamini-Hochberg FDR correction."""
    pvals = np.array(pvals)
    n = len(pvals)
    order = np.argsort(pvals)
    ranked = np.empty_like(order, dtype=float)
    prev_q = 1.0
    for i, idx in enumerate(order[::-1]):
        rank = n - i
        q = min(prev_q, pvals[idx] * n / rank)
        ranked[idx] = q
        prev_q = q
    return ranked


def exact_sign_test(diff, delta):
    """Exact one-sided sign test for median(diff - delta) < 0 (returns a float p-value)."""
    y = diff - delta
    y = y[np.abs(y) > 0]
    n = len(y)
    if n == 0:
        return None
    s = np.sum(y < 0)
    p_res = binomtest(s, n, 0.5, alternative="less")
    # Ensure backward and forward compatibility with SciPy versions >=1.11
    if hasattr(p_res, "pvalue"):
        return float(p_res.pvalue)
    return float(p_res)



# ----------------------- Core adaptive method -----------------------

def adaptive_diverse_selection(df: pd.DataFrame,
                               delta_margin: float,
                               alpha: float,
                               permutations: int,
                               fdr: bool,
                               seed: int):
    """
    Adaptive selection by coverage of weaknesses and conditional correlation.
    Now also computes the *median gain on hard datasets* for visualization.
    """
    rng = np.random.default_rng(seed)
    results = []
    selected = set()
    # Force a deterministic ordering of the pairs
    remaining = sorted(set(df.set_index(["candidate_model", "prep"]).index))

    progression = []  # track how the number of selected pairs evolves

    # Pivot table: each (model, prep) has a vector of normalized performances across datasets
    pivot = df.pivot_table(index=["candidate_model", "prep"],
                           columns="dataset", values="norm_perf", aggfunc="mean")

    mean_perf = pivot.mean(axis=1)  # global mean performance (for info only)

    iteration = 0
    while remaining:
        iteration += 1
        progress = False

        for pair in list(sorted(remaining)):  # ensure deterministic traversal
            vec_j = pivot.loc[pair].dropna()
            if len(vec_j) < 3:
                remaining.remove(pair)
                continue

            sig_corr = False
            max_rho = np.nan
            median_gain_hard = np.nan  # <-- NEW metric for visualization

            # ---------------------------
            # (1) Performance improvement on "hard" datasets
            # ---------------------------
            if selected:
                current_best = pivot.loc[list(selected)].min(axis=0)
                # Take top 25% hardest datasets (highest normalized error)
                k = max(1, int(np.ceil(0.25 * len(current_best))))
                hard_dsets = current_best.nlargest(k).index
                valid_hard = [d for d in hard_dsets if d in vec_j.index]
                if len(valid_hard) < 3:
                    p_perf = None
                else:
                    diff = vec_j[valid_hard] - current_best[valid_hard]
                    p_perf = exact_sign_test(diff.values, delta_margin)
                    # Compute median gain (negative = improvement)
                    median_gain_hard = float(np.median(diff.values))
            else:
                p_perf = 0.0
                median_gain_hard = 0.0  # baseline

            # ---------------------------
            # (2) Redundancy via global correlation (maxT test + effect threshold)
            # ---------------------------
            if selected:
                # Run Westfall–Young maxT global permutation test
                T_obs, p_maxT, ok = maxT_corr_pvalue(
                    vec_j, selected, pivot,
                    permutations=permutations,
                    seed=seed,
                    use_resid=True
                )

                if ok:
                    max_rho = float(T_obs)
                    # Candidate considered redundant if correlation is both statistically and practically significant
                    sig_corr = (p_maxT < alpha) and (abs(max_rho) >= args.corr_threshold)
                else:
                    sig_corr = False
                    max_rho = np.nan
            else:
                sig_corr = False
                max_rho = np.nan

            # ---------------------------
            # (3) Decision rule
            # ---------------------------
            keep = (p_perf is None or p_perf > alpha) or (not sig_corr)


            results.append({
                "iteration": iteration,
                "candidate_model": pair[0],
                "prep": pair[1],
                "mean_perf": mean_perf[pair],
                "median_gain_hard": median_gain_hard,  # <-- Added here
                "p_perf": p_perf,
                "sig_corr_FDR": sig_corr,
                "max_corr_to_S": max_rho,
                "keep": keep
            })

            if keep:
                selected.add(pair)
                remaining.remove(pair)
                progress = True

         # Always sort selected deterministically to preserve order across runs
        selected = set(sorted(selected))

        progression.append(len(selected))
        if not progress:
            break

    return pd.DataFrame(results), list(selected), progression



def discover_dataset_csvs(root_dir="Results/assoc_pp_model",
                          include_prefix="results_",
                          exclude_substrings=("CNN", "LGBM", "PLS", "Ridge", "NICON", "dynamic")):
    """
    Discover per-dataset results CSVs under the given root directory.
    Each dataset is a subfolder under root_dir.
    The first valid CSV matching inclusion/exclusion rules is returned per dataset.

    Returns:
        list of tuples (dataset_name, csv_path)
    """
    dataset_files = []

    if not os.path.isdir(root_dir):
        print(f"[WARN] Root directory not found: {root_dir}")
        return dataset_files

    for dataset_name in sorted(os.listdir(root_dir)):
        ds_path = os.path.join(root_dir, dataset_name)
        if not os.path.isdir(ds_path):
            continue

        # Find candidates starting with "results_" and ending with ".csv"
        candidates = [
            f for f in os.listdir(ds_path)
            if f.startswith(include_prefix)
            and f.lower().endswith(".csv")
            and not any(excl in f for excl in exclude_substrings)
        ]

        if not candidates:
            print(f"[WARN] No valid results CSV found for dataset: {dataset_name}")
            continue

        # Use the first valid candidate (sorted alphabetically)
        candidates.sort()
        csv_path = os.path.join(ds_path, candidates[0])
        dataset_files.append((dataset_name, csv_path))

    return dataset_files


def collect_and_merge_results(dataset_csvs):
    """
    Load all dataset CSVs, determine task type (regression/classification)
    based on model names, and return a merged DataFrame.
    """

    all_data = []

    for dataset_name, csv_path in dataset_csvs:
        try:
            df = pd.read_csv(csv_path)
        except Exception as e:
            print(f"[WARN] Failed to read {csv_path}: {e}")
            continue

        if "Model" not in df.columns:
            print(f"[WARN] No 'Model' column in {csv_path}, skipping.")
            continue

        # Determine task type
        models = df["Model"].astype(str).tolist()
        has_reg = any(m.endswith("_reg") for m in models)
        has_clf = any(m.endswith("_classif") for m in models)

        if has_reg and not has_clf:
            task = "regression"
        elif has_clf and not has_reg:
            task = "classification"
        else:
            print(f"[WARN] Ambiguous or unknown task for {dataset_name}, skipping.")
            continue

        # Melt to long format
        long_df = df.melt(id_vars=["Model"], var_name="prep", value_name="metric")
        long_df["dataset"] = dataset_name
        long_df["task"] = task
        long_df.rename(columns={"Model": "candidate_model"}, inplace=True)
        long_df.dropna(subset=["metric"], inplace=True)

        # --- Merge CNN and NICON as one logical model ---
        # Normalize names: treat CNN and NICON as the same model type
        long_df["candidate_model"] = long_df["candidate_model"].replace(
            {m: m.replace("CNN", "NICON") for m in long_df["candidate_model"] if "CNN" in m}
        )

        # If both CNN_* and NICON_* exist, aggregate their metrics (mean)
        merged_models = (
            long_df.groupby(["candidate_model", "prep", "dataset", "task"], as_index=False)
                .agg({"metric": "mean"})
        )

        all_data.append(merged_models)


    if not all_data:
        print("[ERROR] No valid dataset CSVs found after filtering.")
        return pd.DataFrame(columns=["dataset", "candidate_model", "prep", "metric", "task"])

    merged_df = pd.concat(all_data, ignore_index=True)
    return merged_df


# ----------------------- Visualization -----------------------

def visualize_global(results: pd.DataFrame, progression: list, output_prefix: str, task_label: str):
    """Global visualization of selection results + progression plot."""
    if results.empty:
        print(f"[WARN] No results for visualization ({task_label}).")
        return

    # -------------------- Scatter plot --------------------
    plt.figure(figsize=(8, 6))
    sns.scatterplot(
        data=results,
        x="max_corr_to_S",
        y="median_gain_hard",  # <-- Use median gain on hard datasets instead of mean_perf
        hue="keep",
        style="sig_corr_FDR",
        sizes=(20, 120),
        palette={True: "green", False: "red"},
        alpha=0.85
    )
    plt.xlabel("Max correlation to S (worst-case)")
    plt.ylabel("Median gain on hard datasets (negative = improvement)")
    plt.title(f"Global selection overview - {task_label}")
    plt.axhline(0, color="gray", linestyle="--", alpha=0.5)  # visual reference line
    plt.tight_layout()
    plt.savefig(f"{output_prefix}_{task_label}_scatter.png", dpi=300)
    plt.close()

    # -------------------- Heatmap --------------------
    results_sorted = results.sort_values(["candidate_model", "prep", "iteration"])
    results_unique = (
        results_sorted.groupby(["candidate_model", "prep"], as_index=False)
        .agg({"keep": "last"})
    )

    pivot_heat = results_unique.pivot(index="candidate_model", columns="prep", values="keep").fillna(False)
    cmap = {True: 1, False: 0, None: np.nan}
    mat = pivot_heat.apply(lambda col: col.map(lambda v: cmap.get(v, np.nan)))

    fig_width = max(12, 0.3 * len(mat.columns))
    fig_height = max(6, 0.5 * len(mat))
    plt.figure(figsize=(fig_width, fig_height))

    sns.heatmap(
        mat,
        cmap=sns.color_palette(["red", "green"]),
        cbar=False,
        linewidths=0.5,
        linecolor="gray"
    )
    plt.title(f"Heatmap of kept/rejected (adaptive selection) - {task_label}")
    plt.xlabel("Preprocessing")
    plt.ylabel("Model")
    plt.xticks(rotation=45, ha="right", fontsize=9)
    plt.yticks(fontsize=9)
    plt.tight_layout(rect=[0, 0.05, 1, 1])
    plt.subplots_adjust(bottom=0.2)
    plt.savefig(f"{output_prefix}_{task_label}_heatmap.png", dpi=300)
    plt.close()

    # -------------------- Progression plot --------------------
    plt.figure(figsize=(7, 5))
    plt.plot(range(1, len(progression) + 1), progression, marker='o', linewidth=2)
    plt.xlabel("Iteration")
    plt.ylabel("Number of selected pairs")
    plt.title(f"Selection progression - {task_label}")
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(f"{output_prefix}_{task_label}_progression.png", dpi=300)
    plt.close()


# ----------------------- Main -----------------------

parser = argparse.ArgumentParser(description="Adaptive selection based on coverage and correlation significance.")
parser.add_argument("--output_prefix", type=str, default=DEFAULT_OUTPUT_PREFIX, help="Output prefix.")
parser.add_argument("--delta", type=float, default=DEFAULT_DELTA_MARGIN, help="Non-inferiority margin δ.")
parser.add_argument("--alpha", type=float, default=DEFAULT_ALPHA, help="Significance level.")
parser.add_argument("--permutations", type=int, default=DEFAULT_PERMUTATIONS, help="Number of permutations.")
parser.add_argument("--seed", type=int, default=DEFAULT_RANDOM_SEED, help="Random seed.")
parser.add_argument("--no_fdr", action="store_true", help="Disable FDR correction on correlations.")
parser.add_argument( "--task_only", type=str, choices=["regression", "classification"], default=None, help="If specified, only run adaptive selection for the chosen task (regression or classification).")
parser.add_argument("--corr_threshold", type=float, default=0.7, help="Absolute correlation threshold (|rho|) to consider redundancy practically significant.")


args = parser.parse_args()

# Discover and merge results
dataset_csvs = discover_dataset_csvs("Results/assoc_pp_model/per_dataset")
merged_df = collect_and_merge_results(dataset_csvs)

if merged_df.empty:
    print("[ERROR] No data found for adaptive selection.")    

# Split by task and process separately
else:
    available_tasks = merged_df["task"].unique().tolist()
    task_filter = args.task_only

    if task_filter:
        if task_filter not in available_tasks:
            print(f"[WARN] No datasets found for task '{task_filter}'. Available: {available_tasks}")
        else:
            print(f"[INFO] Running only on task: {task_filter}")
            merged_df = merged_df[merged_df["task"] == task_filter]

    for task_label, df_task in merged_df.groupby("task"):
        df_norm = normalize_within_dataset(df_task.rename(columns={"metric": "delta_value"}))
        print(f"[INFO] Running adaptive selection for {task_label} ...")

        results, selected, progression = adaptive_diverse_selection(
            df_norm, delta_margin=args.delta, alpha=args.alpha,
            permutations=args.permutations, fdr=(not args.no_fdr), seed=args.seed
        )

        results["random_seed"] = args.seed  # trace seed used
        output_path = f"{args.output_prefix}_{task_label}.csv"
        results.to_csv(output_path, index=False)
        print(f"[INFO] Saved selection results for {task_label} to: {output_path}")
        print(f"[INFO] Number of selected pairs: {len(selected)}")
        output_fig = args.output_prefix.replace("Results", "Figures")
        visualize_global(results, progression, output_fig, task_label)

    print("[INFO] All tasks processed.")
