#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Adaptive selection of (model, preprocessing) pairs via GRAPH PRUNING based on:
  - Redundancy detection (positive Spearman correlation) with a HYBRID test:
      * n < 30  -> one-sided permutation test (H1: rho > 0)
      * n >= 30 -> one-sided asymptotic test from scipy.stats.spearmanr
    + Global BH-FDR across all tested pairwise correlations (edges)
  - Performance non-inferiority as an EXCLUSION guard:
      For candidate j vs already kept k, test Δ = r_j - r_k with H1: median(Δ) > 0
      using the exact sign test; apply BH-FDR WITHIN j (across all k ∈ S that are
      positively correlated with j at FDR level). If any comparison is significant,
      prune j; otherwise keep j.

Task separation:
  - Regression and classification are handled SEPARATELY (auto-detected by model suffix).
  - Normalization per dataset so "best" equals 1.0 (min for regression, max for classification).

Outputs:
  - CSV of decisions (kept/pruned), with reasons.
  - Spearman rho matrix CSV and matching BH-FDR q-value matrix CSV (global over edges).
  - Significant-correlation heatmap (q < alpha).
  - Correlation network (nodes= pairs, edges if rho>0 & q<alpha; green=kept, red=pruned).
  - Progression, scatter and kept/pruned heatmap.

Structure intentionally mirrors your "weakness_coverage.py" script (sections & style).
Author: Generated by ChatGPT. All comments are in English.
"""

import os
import argparse
import numpy as np
import pandas as pd
import random
import warnings
import sys
from joblib import Parallel, delayed
import gc
from tqdm import tqdm
from scipy.stats import spearmanr, binomtest, ConstantInputWarning
warnings.filterwarnings("ignore", category=ConstantInputWarning)

import matplotlib
matplotlib.use("Agg")  # safe for batch
import matplotlib.pyplot as plt
import seaborn as sns

# Optional network plot
try:
    import networkx as nx
    NETWORKX_AVAILABLE = True
except Exception:
    NETWORKX_AVAILABLE = False


# ----------------------- Parameters -----------------------

DEFAULT_INPUT_DIR = "Results/assoc_pp_model/per_dataset"
DEFAULT_OUTPUT_PREFIX = "Results/assoc_pp_model/All_datasets/Pipeline_graph/"
DEFAULT_ALPHA = 0.05
DEFAULT_PERMUTATIONS = 10000
DEFAULT_RANDOM_SEED = 42
DEFAULT_MIN_OVERLAP = 3
DEFAULT_EXCLUDE_NAME_SUBSTR = ["CNN", "LGBM", "PLS", "Ridge", "NICON"]  # filenames containing these substrings are ignored
DEFAULT_EXCLUDE_PREPS = {"PCA"}  # optional global exclusion of preprocessings


# ----------------------- Determinism -----------------------

def set_global_determinism(seed=42):
    """Ensure deterministic behavior across libs & threads."""
    os.environ["PYTHONHASHSEED"] = str(seed)
    os.environ["OMP_NUM_THREADS"] = "1"
    os.environ["OPENBLAS_NUM_THREADS"] = "1"
    os.environ["MKL_NUM_THREADS"] = "1"
    os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
    os.environ["NUMEXPR_NUM_THREADS"] = "1"
    os.environ["BLIS_NUM_THREADS"] = "1"
    random.seed(seed)
    np.random.seed(seed)

set_global_determinism(DEFAULT_RANDOM_SEED)


# ----------------------- Utilities -----------------------

def benjamini_hochberg(pvals):
    """Benjamini–Hochberg FDR correction. Keeps shape & order."""
    p = np.asarray(pvals, dtype=float)
    n = len(p)
    order = np.argsort(p)
    q = np.empty_like(p)
    prev = 1.0
    for r, idx in enumerate(order[::-1], start=1):
        qq = min(prev, p[idx] * n / r)
        q[idx] = qq
        prev = qq
    return q

def exact_sign_test_greater(diff):
    """Exact one-sided sign test for H1: median(diff) > 0. Ties (0) removed."""
    y = np.asarray(diff)
    y = y[np.abs(y) > 0]
    n = len(y)
    if n == 0:
        return None
    s = int(np.sum(y > 0))
    res = binomtest(s, n, 0.5, alternative="greater")
    return float(res.pvalue) if hasattr(res, "pvalue") else float(res)

def spearman_hybrid_pvalue(x, y, n_perm=10000, seed=42):
    """
    Hybrid one-sided Spearman test (H1: rho > 0).
    - n < 30  -> permutation p-value (exact Monte Carlo)
    - n >= 30 -> fast direct rank-correlation with asymptotic one-sided p-value
    Returns (rho, p_one_sided, n_used).
    """
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    mask = np.isfinite(x) & np.isfinite(y)
    x, y = x[mask], y[mask]
    n = len(x)
    if n < 3:
        return np.nan, np.nan, n

    # --- Guard against degenerate data ---
    if np.allclose(x, x[0]) or np.allclose(y, y[0]):
        return np.nan, np.nan, n

    # --- Case 1: small n -> permutation test ---
    if n < 30:
        rng = np.random.default_rng(seed)
        rx = np.argsort(np.argsort(x))
        ry = np.argsort(np.argsort(y))
        rho_obs = np.corrcoef(rx, ry)[0, 1]
        cnt = 0
        for _ in range(n_perm):
            rp = np.corrcoef(rx, np.random.permutation(ry))[0, 1]
            if rp >= rho_obs:
                cnt += 1
        p_one = (cnt + 1) / (n_perm + 1)
        return float(rho_obs), float(p_one), n

    # --- Case 2: n >= 30 -> fast asymptotic computation ---
    # Compute rank correlation manually (no scipy.spearmanr)
    rx = np.argsort(np.argsort(x))
    ry = np.argsort(np.argsort(y))
    rho = np.corrcoef(rx, ry)[0, 1]

    # Asymptotic p-value (one-sided)
    # Under H0, t = rho * sqrt((n-2)/(1-rho^2)) ~ Student(n-2)
    if np.isnan(rho) or abs(rho) >= 1:
        return rho, 0.0 if rho > 0 else 1.0, n
    t_stat = rho * np.sqrt((n - 2) / max(1e-12, 1 - rho**2))
    # approximate one-sided p-value via survival function of normal
    from scipy.stats import norm
    p_one = 1 - norm.cdf(t_stat)
    return float(rho), float(p_one), n


# ----------------------- Data discovery & parsing -----------------------

def discover_dataset_csvs(root_dir, include_prefix="results_", exclude_substrings=None):
    """Return [(dataset_name, csv_path), ...] for first valid CSV per dataset folder."""
    exclude_substrings = exclude_substrings or []
    out = []
    if not os.path.isdir(root_dir):
        return out
    for ds in sorted(os.listdir(root_dir)):
        ds_dir = os.path.join(root_dir, ds)
        if not os.path.isdir(ds_dir):
            continue
        cands = [f for f in os.listdir(ds_dir)
                 if f.startswith(include_prefix) and f.lower().endswith(".csv")
                 and not any(excl in f for excl in exclude_substrings)]
        if not cands:
            continue
        cands.sort()
        out.append((ds, os.path.join(ds_dir, cands[0])))
    return out

def load_long_table(csv_path, exclude_preps=None):
    """Load per-dataset wide CSV -> long table [model, prep, metric]."""
    df = pd.read_csv(csv_path)
    if "Model" not in df.columns:
        raise ValueError("Missing 'Model' column in CSV.")
    long = df.melt(id_vars=["Model"], var_name="prep", value_name="metric")
    long.rename(columns={"Model": "candidate_model"}, inplace=True)
    # --- Merge equivalent model names ---
    def _merge_nicon_cnn(name):
        # Preserve suffix (_reg / _classif) if present
        if "CNN" in name or "NICON" in name:
            if name.endswith("_reg"):
                return "CNN_reg"
            elif name.endswith("_classif"):
                return "CNN_classif"
            else:
                return "CNN"
        return name

    long["candidate_model"] = long["candidate_model"].apply(_merge_nicon_cnn)

    long.dropna(subset=["metric"], inplace=True)
    if exclude_preps:
        long = long[~long["prep"].isin(exclude_preps)]
    return long

def detect_task(models):
    """Detect task from model suffixes."""
    s = [str(m) for m in models]
    s = ["NICON_reg" if ("CNN_reg" in x or "NICON_reg" in x) else
         "NICON_classif" if ("CNN_classif" in x or "NICON_classif" in x) else x for x in s]
    has_reg = any(m.endswith("_reg") for m in s)
    has_clf = any(m.endswith("_classif") for m in s)
    if has_reg and not has_clf:
        return "regression"
    if has_clf and not has_reg:
        return "classification"
    return "ambiguous"


def collect_and_merge(dataset_csvs, exclude_preps=None):
    """Merge all datasets into long table with task labels and normalization per dataset."""
    rows = []
    for ds, path in dataset_csvs:
        try:
            wide = pd.read_csv(path)
        except Exception as e:
            print(f"[WARN] Skipping {path}: {e}")
            continue
        if "Model" not in wide.columns:
            print(f"[WARN] Missing 'Model' in {path}, skipping dataset {ds}.")
            continue
        task = detect_task(wide["Model"])
        if task == "ambiguous":
            print(f"[WARN] Ambiguous task for dataset {ds}; skipping.")
            continue
        long = load_long_table(path, exclude_preps=exclude_preps)
        long["dataset"] = ds
        long["task"] = task
        rows.append(long)
    if not rows:
        return pd.DataFrame()
    merged = pd.concat(rows, ignore_index=True)
    return merged


# ----------------------- Normalization -----------------------

def normalize_within_dataset_task(df):
    """Normalize metric per dataset so best = 1.0 (min for regression, max for classification)."""
    df = df.copy()
    df["norm_perf"] = np.nan
    for (ds, task), sub in df.groupby(["dataset", "task"]):
        if task == "regression":
            best = sub["metric"].min()
            df.loc[sub.index, "norm_perf"] = sub["metric"] / best if best > 0 else sub["metric"]
        else:
            best = sub["metric"].max()
            df.loc[sub.index, "norm_perf"] = best / sub["metric"]
    return df


# ----------------------- Graph pruning core -----------------------

def precompute_correlations_streaming(
    pivot: pd.DataFrame,
    alpha: float,
    n_perm: int,
    seed: int,
    min_overlap: int,
    neighbor_preselect: int = 25,
    preselect_sample: int = 32,
    k_neighbors: int = 5,
    n_jobs_corr: int = 1
):
    """
    Streaming correlation computation with pre-screening, NumPy vectorization,
    and parallelized true tests.

    Parameters
    ----------
    pivot : pd.DataFrame
        Performance matrix (rows = (model, prep), columns = datasets).
    alpha : float
        Significance level (for later BH-FDR).
    n_perm : int
        Number of permutations for small-n tests.
    seed : int
        Random seed for determinism.
    min_overlap : int
        Minimum number of common datasets to compute a correlation.
    neighbor_preselect : int
        Number of top cheap correlations per i to keep for exact tests.
    preselect_sample : int
        Number of dataset columns to subsample for cheap screening.
    k_neighbors : int
        Number of final strongest neighbors per i kept.
    n_jobs_corr : int
        Number of parallel threads for true correlation tests.

    Returns
    -------
    rho_df : pd.DataFrame
        Matrix of positive Spearman correlations (NaN elsewhere).
    q_df : pd.DataFrame
        Matrix of p-values (uncorrected, NaN elsewhere).
    """

    from joblib import Parallel, delayed
    import gc

    items = list(pivot.index)
    n_items = len(items)
    n_cols = pivot.shape[1]
    print(f"[Graph] Streaming correlations on {n_items} pairs × {n_cols} datasets")

    # --- Convert pivot to NumPy for efficiency ---
    X = pivot.to_numpy(dtype=np.float64, copy=True)
    mask_valid = np.isfinite(X)
    rng = np.random.default_rng(seed)

    rho = np.full((n_items, n_items), np.nan, dtype=float)
    pmat = np.full((n_items, n_items), np.nan, dtype=float)

    # --- Main loop over i ---
    for i in tqdm(range(n_items), desc="[Graph] Streaming correlations"):
        xi_full = X[i, :]
        mask_i = mask_valid[i, :]
        if np.sum(mask_i) < min_overlap:
            continue

        # 1) choose deterministic subsample of columns for cheap screening
        valid_cols_i = np.where(mask_i)[0]
        if len(valid_cols_i) > preselect_sample:
            S = rng.choice(valid_cols_i, size=preselect_sample, replace=False)
        else:
            S = valid_cols_i
        xiS = xi_full[S]
        mask_iS = np.isfinite(xiS)
        if mask_iS.sum() < min_overlap:
            continue
        xiS = xiS[mask_iS]
        xiS -= xiS.mean()
        den_iS = np.sqrt(np.sum(xiS ** 2))
        if den_iS == 0:
            continue

        # 2) cheap screening on subsample S
        candidates = []
        for j in range(i + 1, n_items):
            yjS = X[j, S][mask_iS]
            if np.sum(np.isfinite(yjS)) < min_overlap:
                continue
            yjS = yjS[np.isfinite(yjS)]
            if len(yjS) != len(xiS):
                continue
            yjS -= yjS.mean()
            den_jS = np.sqrt(np.sum(yjS ** 2))
            if den_jS == 0:
                continue
            cheap_r = float(np.dot(xiS, yjS) / (den_iS * den_jS))
            if cheap_r > 0:
                candidates.append((cheap_r, j))

        # keep top candidates
        candidates.sort(key=lambda t: t[0], reverse=True)
        candidates = [j for _, j in candidates[:neighbor_preselect]]
        if not candidates:
            continue

        # 3) true tests in parallel
        def test_one(j):
            y = X[j, :]
            mask = mask_i & mask_valid[j, :]
            if np.sum(mask) < min_overlap:
                return None
            xx, yy = xi_full[mask], y[mask]
            if np.allclose(xx, xx[0]) or np.allclose(yy, yy[0]):
                return None
            r, p, n_used = spearman_hybrid_pvalue(xx, yy, n_perm=n_perm, seed=seed + j)
            if np.isnan(r) or np.isnan(p) or r <= 0:
                return None
            return (r, p, j)

        local_corrs = Parallel(n_jobs=n_jobs_corr, prefer="threads")(
            delayed(test_one)(j) for j in candidates
        )
        local_corrs = [t for t in local_corrs if t is not None]
        if not local_corrs:
            continue

        # 4) keep only top k_neighbors per node
        local_corrs.sort(key=lambda t: t[0], reverse=True)
        for (r, p, j) in local_corrs[:k_neighbors]:
            rho[i, j] = r
            pmat[i, j] = p

        if i % 10 == 0:
            gc.collect()

    # symmetrize
    for i in range(n_items):
        for j in range(i + 1, n_items):
            rho[j, i] = rho[i, j]
            pmat[j, i] = pmat[i, j]

    # BH-FDR across all p-values
    flat_p = [pmat[i, j] for i in range(n_items) for j in range(i + 1, n_items) if not np.isnan(pmat[i, j])]
    q_df = np.full_like(pmat, np.nan)
    if flat_p:
        q_flat = benjamini_hochberg(flat_p)
        it = iter(q_flat)
        for i in range(n_items):
            for j in range(i + 1, n_items):
                if not np.isnan(pmat[i, j]):
                    q_df[i, j] = next(it)
                    q_df[j, i] = q_df[i, j]

    rho_df = pd.DataFrame(rho, index=items, columns=items)
    q_df = pd.DataFrame(q_df, index=items, columns=items)
    # Flatten tuple index for compatibility with .loc
    flat_labels = [f"{m}|{p}" for (m, p) in items]
    rho_df.index = rho_df.columns = flat_labels
    q_df.index = q_df.columns = flat_labels

    return rho_df, q_df


def adaptive_graph_pruning(df_task, alpha, n_perm, seed, min_overlap):
    """Run graph pruning for a single task (regression or classification)."""
    pivot = df_task.pivot_table(index=["candidate_model", "prep"],
                                columns="dataset", values="norm_perf", aggfunc="mean")
    rho_df, q_df = precompute_correlations_streaming(
        pivot,
        alpha=alpha,
        n_perm=n_perm,
        seed=seed,
        min_overlap=min_overlap,
        neighbor_preselect=args.neighbor_preselect,
        preselect_sample=args.preselect_sample,
        k_neighbors=args.k_neighbors,
        n_jobs_corr=args.n_jobs_corr
    )

    
    med = pivot.median(axis=1)
    order = med.sort_values(ascending=True).index.tolist()

    kept = []
    decisions = []
    progression = []
    for pair in order:
        xj = pivot.loc[pair].to_numpy(dtype=float)
        if np.sum(np.isfinite(xj)) < min_overlap:
            decisions.append({
                "candidate_model": pair[0], "prep": pair[1], "status": "skipped_insufficient_data",
                "reason": f"valid_entries<{min_overlap}", "median_profile": float(med.loc[pair]),
                "sig_corr_edge": None, "sig_worse": None
            })
            continue

        neighbors = []
        for k in kept:
            pair_key = f"{pair[0]}|{pair[1]}"
            k_key = f"{k[0]}|{k[1]}"
            q = q_df.loc[pair_key, k_key]
            r = rho_df.loc[pair_key, k_key]
            if np.isfinite(q) and q < alpha and np.isfinite(r) and r > 0:
                xk = pivot.loc[k].to_numpy(dtype=float)
                mask = np.isfinite(xj) & np.isfinite(xk)
                if np.sum(mask) >= min_overlap:
                    neighbors.append(k)

            # Compute maximum correlation with kept pairs
        valid_corrs = []
        for k in kept:
            if (pair in rho_df.index) and (k in rho_df.columns):
                r = rho_df.loc[pair, k]
                if np.isfinite(r):
                    valid_corrs.append(r)
        max_corr_to_S = float(np.max(valid_corrs)) if valid_corrs else 0.0


        if not neighbors:
            kept.append(pair)
            decisions.append({
                "candidate_model": pair[0], "prep": pair[1], "status": "kept",
                "reason": "no_significant_positive_correlation_to_kept",
                "median_profile": float(med.loc[pair]),
                "sig_corr_edge": False, "sig_worse": False,
                "max_corr_to_S": max_corr_to_S
            })
            progression.append(len(kept))
            continue

        # Performance exact sign tests H1: median Δ > 0, BH-FDR within-j
        pvals = []
        for k in neighbors:
            xk = pivot.loc[k].to_numpy(dtype=float)
            mask = np.isfinite(xj) & np.isfinite(xk)
            diff = xj[mask] - xk[mask]
            p = exact_sign_test_greater(diff)
            pvals.append(p)
        qvals = benjamini_hochberg([p if p is not None else np.nan for p in pvals]) if pvals else []
        sig_worse = any((q is not None) and np.isfinite(q) and (q < alpha) for q in qvals)

        if sig_worse:
            decisions.append({
                "candidate_model": pair[0], "prep": pair[1], "status": "pruned",
                "reason": "worse_than_correlated_kept",
                "median_profile": float(med.loc[pair]),
                "sig_corr_edge": True, "sig_worse": True,
                "max_corr_to_S": max_corr_to_S
            })
        else:
            kept.append(pair)
            decisions.append({
                "candidate_model": pair[0], "prep": pair[1], "status": "kept",
                "reason": "not_worse_than_correlated_kept",
                "median_profile": float(med.loc[pair]),
                "sig_corr_edge": True, "sig_worse": False,
                "max_corr_to_S": max_corr_to_S
            })
        progression.append(len(kept))

    dec_df = pd.DataFrame(decisions)
    return dec_df, kept, progression, rho_df, q_df, pivot


# ----------------------- Visualization -----------------------

def plot_sig_corr_heatmap(rho_df, q_df, alpha, out_path):
    """Heatmap of significant positive correlations (q < alpha)."""
    mask = ~(q_df < alpha)
    rho_sig = rho_df.mask(mask)
    plt.figure(figsize=(max(8, 0.25*rho_sig.shape[1]), max(6, 0.25*rho_sig.shape[0])))
    sns.heatmap(rho_sig, cmap="viridis", vmin=0, vmax=1, linewidths=0.3, linecolor="white")
    plt.title(f"Significant positive Spearman correlations (q < {alpha})")
    plt.tight_layout()
    plt.savefig(out_path, dpi=200)
    plt.close()

def plot_network(rho_df, q_df, dec_df, alpha, out_path, seed=42):
    """Correlation network: nodes colored by final decision (green=kept, red=pruned)."""
    if not NETWORKX_AVAILABLE:
        return
    G = nx.Graph()
    status = {}
    final = dec_df.groupby(["candidate_model", "prep"], as_index=False).tail(1)
    for _, r in final.iterrows():
        node = (r["candidate_model"], r["prep"])
        status[node] = r["status"]
        G.add_node(node)
    items = list(rho_df.index)
    for i in range(len(items)):
        for j in range(i+1, len(items)):
            if np.isfinite(rho_df.iloc[i, j]) and np.isfinite(q_df.iloc[i, j]) \
               and rho_df.iloc[i, j] > 0 and q_df.iloc[i, j] < alpha:
                G.add_edge(items[i], items[j], weight=float(rho_df.iloc[i, j]))
    colors = ["#2ca02c" if status.get(n)=="kept" else "#d62728" for n in G.nodes()]
    pos = nx.spring_layout(G, seed=seed)
    widths = [1 + 3*G[u][v]["weight"] for u, v in G.edges()]
    plt.figure(figsize=(12, 10))
    nx.draw_networkx_edges(G, pos, width=widths, alpha=0.6, edge_color="#1f77b4")
    nx.draw_networkx_nodes(G, pos, node_color=colors, node_size=500, alpha=0.9)
    nx.draw_networkx_labels(G, pos, labels={n:f"{n[0]}|{n[1]}" for n in G.nodes()}, font_size=8)
    plt.title("Correlation network (edges: rho>0 & q<alpha) — green=kept, red=pruned")
    plt.axis("off")
    plt.tight_layout()
    plt.savefig(out_path, dpi=220)
    plt.close()

def visualize_global(dec_df, pivot, out_prefix, task_label):
    """
    Visualization of adaptive graph pruning results:
      - Scatter plot: X = max correlation to kept, Y = median Δ vs best, color by status.
      - Decision heatmap: models × preprocessings.
    """
    if dec_df.empty:
        print(f"[WARN] No data for visualization ({task_label}).")
        return

    fig_prefix = out_prefix.replace("Results", "Figures")
    # Keep final decisions (one per pair)
    final = dec_df.groupby(["candidate_model", "prep"], as_index=False).tail(1)

    # --- Compute median Δ (vs best per dataset) for scatter Y-axis ---
    med_diffs = []
    for (model, prep), row in pivot.iterrows():
        vec = row.dropna()
        if len(vec) < 3:
            med_diffs.append(np.nan)
            continue
        # Compute difference to best value per dataset
        best_val = np.min(vec) if task_label == "regression" else np.max(vec)
        med_diffs.append(np.median(vec - best_val))
    pivot["median_diff_vs_best"] = med_diffs

    # Merge median_diff into final
    final = final.merge(pivot[["median_diff_vs_best"]], left_on=["candidate_model", "prep"], right_index=True, how="left")

    # --- Scatter plot ---
    plt.figure(figsize=(8, 6))
    color_map = {"kept": "green", "pruned": "red", "skipped_insufficient_data": "gray"}
    plt.scatter(final["max_corr_to_S"], final["median_diff_vs_best"],
                c=final["status"].map(color_map), alpha=0.8, s=80, edgecolor="black", linewidth=0.5)
    plt.axhline(0, color="black", linestyle="--", linewidth=1)
    plt.xlabel("Max correlation to kept pairs")
    plt.ylabel("Median Δ vs best (negative = better)")
    plt.title(f"Graph pruning decision map — {task_label}")
    plt.tight_layout()
    plt.savefig(f"{fig_prefix}{task_label}_scatter.png", dpi=300)
    plt.close()

    # --- Decision heatmap (models × preprocessings) ---
    heat_df = final.pivot(index="candidate_model", columns="prep", values="status")
    mat = heat_df.replace({"kept": 1, "pruned": 0, "skipped_insufficient_data": np.nan}).infer_objects(copy=False)
    fig_width = max(10, 0.4 * len(mat.columns))
    fig_height = max(6, 0.5 * len(mat.index))
    plt.figure(figsize=(fig_width, fig_height))
    sns.heatmap(mat, cmap=sns.color_palette(["red", "green"]), cbar=False, linewidths=0.5, linecolor="gray")
    plt.title(f"Decision heatmap — {task_label}")
    plt.xlabel("Preprocessing")
    plt.ylabel("Model")
    plt.xticks(rotation=45, ha="right", fontsize=8)
    plt.yticks(fontsize=9)
    plt.tight_layout()
    plt.savefig(f"{fig_prefix}{task_label}_heatmap.png", dpi=300)
    plt.close()

# ----------------------- Main -----------------------

parser = argparse.ArgumentParser(description="Adaptive graph pruning selection (regression & classification separated).")
parser.add_argument("--input_dir", type=str, default=DEFAULT_INPUT_DIR, help="Root folder with per-dataset result CSVs.")
parser.add_argument("--output_prefix", type=str, default=DEFAULT_OUTPUT_PREFIX, help="Prefix for outputs (CSV & figures).")
parser.add_argument("--alpha", type=float, default=DEFAULT_ALPHA, help="Significance level (for FDR and tests).")
parser.add_argument("--permutations", type=int, default=DEFAULT_PERMUTATIONS, help="Permutations (for small-n correlation tests).")
parser.add_argument("--seed", type=int, default=DEFAULT_RANDOM_SEED, help="Random seed for determinism.")
parser.add_argument("--min_overlap", type=int, default=DEFAULT_MIN_OVERLAP, help="Min dataset overlap to test.")
parser.add_argument("--task_only", type=str, choices=["regression", "classification"], default=None, help="If specified, only run adaptive selection for the chosen task (regression or classification).")
parser.add_argument("--k_neighbors", type=int, default=5,
                    help="Maximum number of true neighbors kept per node.")
parser.add_argument("--neighbor_preselect", type=int, default=25,
                    help="Number of top cheap correlations per node pre-selected for true testing.")
parser.add_argument("--preselect_sample", type=int, default=32,
                    help="Number of dataset columns subsampled for cheap screening.")
parser.add_argument("--n_jobs_corr", type=int, default=1,
                    help="Parallel jobs for correlation testing (threads).")
args = parser.parse_args()

# Discover datasets
dataset_csvs = discover_dataset_csvs(args.input_dir, exclude_substrings=DEFAULT_EXCLUDE_NAME_SUBSTR)
if not dataset_csvs:
    print(f"[ERROR] No dataset CSVs found under {args.input_dir}.")
    sys.exit()

# Merge and normalize per task
merged = collect_and_merge(dataset_csvs, exclude_preps=DEFAULT_EXCLUDE_PREPS)
if args.task_only:
    merged = merged[merged["task"] == args.task_only]

if merged.empty:
    print("[ERROR] No valid data after filtering.")
    sys.exit()
merged = normalize_within_dataset_task(merged)

# Process tasks separately
for task_label, df_task in merged.groupby("task"):
    print(f"[INFO] Running graph pruning for task: {task_label}")
    dec_df, kept, progression, rho_df, q_df, pivot = adaptive_graph_pruning(
        df_task, alpha=args.alpha, n_perm=args.permutations, seed=args.seed, min_overlap=args.min_overlap
    )

    # Prepare output paths
    base = f"{args.output_prefix}_{task_label}"
    os.makedirs(os.path.dirname(base), exist_ok=True)

    # Save decisions and matrices
    dec_df.to_csv(f"{base}_decisions.csv", index=False)
    rho_df.to_csv(f"{base}_rho.csv")
    q_df.to_csv(f"{base}_rho_q.csv")
    print(f"[INFO] Saved decisions to: {base}_decisions.csv")
    print(f"[INFO] Saved rho and q matrices to: {base}_rho.csv / {base}_rho_q.csv")

    # Visualizations: significant-corr heatmap and network
    plot_sig_corr_heatmap(rho_df, q_df, args.alpha, f"{base}_rho_sig_heatmap.png")
    print(f"[INFO] Saved significant correlation heatmap to: {base}_rho_sig_heatmap.png")
    plot_network(rho_df, q_df, dec_df, args.alpha, f"{base}_network.png", seed=args.seed)
    if NETWORKX_AVAILABLE:
        print(f"[INFO] Saved correlation network to: {base}_network.png")

    # Global summaries
    figs_prefix = base.replace("Results", "Figures")
    os.makedirs(os.path.dirname(figs_prefix), exist_ok=True)
    visualize_global(dec_df, pivot, figs_prefix, task_label)

    # --- Export unified selected summary ---
    summary_path = os.path.join(os.path.dirname(base), "pipeline_graph_pruning_selected.csv")

    # Compute mean & std performance per pair (over datasets)
    perf_stats = pivot.copy()
    perf_stats["metric_mean"] = pivot.mean(axis=1)
    perf_stats["metric_std"] = pivot.std(axis=1)
    perf_stats = perf_stats[["metric_mean", "metric_std"]].reset_index()
    perf_stats.rename(columns={"candidate_model": "model_name", "prep": "preprocessing_name"}, inplace=True)

    # Merge with decisions
    final_dec = dec_df.groupby(["candidate_model", "prep"], as_index=False).tail(1)
    final_dec["selected"] = final_dec["status"].eq("kept")
    merged_out = pd.merge(perf_stats, final_dec[["candidate_model", "prep", "selected"]],
                        left_on=["model_name", "preprocessing_name"],
                        right_on=["candidate_model", "prep"], how="left").drop(columns=["candidate_model", "prep"])

    merged_out["dataset_name"] = None  # optional placeholder for compatibility
    merged_out.to_csv(summary_path, index=False)
    print(f"[INFO] Saved unified summary CSV: {summary_path}")

print("[INFO] All tasks processed successfully.")
