#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Iterative Gatekeeping Pipeline for (model, preprocessing) selection

Overview
--------
This monolithic script implements an adaptive, iterative gatekeeping strategy to keep
(model, preprocessing) pairs that are either:
  - not proven worse (performance-wise), or
  - worse but not redundantly correlated to the current kept set S.

We do NOT pre-specify how many pairs to keep; the final set emerges from data.

Gate 1 (Performance):
  - Build per-dataset Δ with a "best-per-prep" reference:
      * regression (smaller is better):    Δ = RRMSE(candidate) - min_model RRMSE (same dataset & prep)
      * classification (larger is better): Δ = max_model Acc   - Acc(candidate)   (same dataset & prep)
    Hence Δ >= 0 and larger means "worse".
  - One-sided nonparametric test on Y = Δ - δ:
      H0: median(Y) <= 0  vs  H1: median(Y) > 0  (inferiority)
    Use exact Sign test (robust); also report Wilcoxon (if SciPy available).
  - If NOT significant (p >= alpha): KEEP immediately.

Gate 2 (Correlation, only for Gate-1 significant items):
  - Compute envelope profile v_S(d) = min_{k in S} Δ_k(d) across datasets d.
  - Test Spearman correlation between candidate Δ_j and v_S:
      H0: rho = 0  vs  H1: rho > 0  (positive correlation means redundancy)
    * If number of datasets n < 30: permutation test (Monte Carlo, one-sided, robust for small n)
    * Else: classical Spearman test (unilateral right tail).
  - Apply Benjamini–Hochberg FDR to Gate-2 p-values within the epoch.
  - EXCLUDE only if (Gate 1 significant) AND (Gate 2 FDR-significant).

Iteration:
  - Initialize S with top-1 (lowest median Δ).
  - Iterate epochs (update S, envelope, tests) until convergence (no change in S) or max_epochs.

Outputs (per task: regression / classification)
-----------------------------------------------
- Results CSV: <prefix>_reg_report.csv / <prefix>_classif_report.csv
- Kept list:   <prefix>_reg_keep.csv   / <prefix>_classif_keep.csv
- Global figures in Figures/...:
    1) decision_heatmap.png
    2) pvalue_distributions.png
    3) scatter_perf_corr.png
    4) progression.png
    5) gate_map.png        (median Δ vs -log10 p1)
    6) corr_map.png        (rho vs q2)

Author: Generated by ChatGPT
All code comments are in English.
"""

from __future__ import annotations
import os, argparse, math, random, warnings
from typing import List, Tuple, Optional, Dict
import numpy as np
import pandas as pd

# Silence constant-input warnings from SciPy Spearman when arrays are constant
from scipy.stats import ConstantInputWarning
warnings.filterwarnings("ignore", category=ConstantInputWarning)

# Optional SciPy imports (graceful fallbacks)
try:
    from scipy.stats import wilcoxon, binom, spearmanr
    SCIPY_AVAILABLE = True
except Exception:
    SCIPY_AVAILABLE = False

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

# ----------------------- Parameters -----------------------

DEFAULT_RESULTS_ROOT = "Results/assoc_pp_model"
DEFAULT_OUT_DIR = "Results/assoc_pp_model/All_datasets/Pipeline_gatekeeping"
DEFAULT_FIG_DIR = "Figures/assoc_pp_model/All_datasets/Pipeline_gatekeeping"
DEFAULT_PREFIX = "gatekeeping_pipeline"

DEFAULT_ALPHA = 0.05
DEFAULT_DELTA = 0.01       # non-inferiority margin δ
DEFAULT_N_PERM = 2000     # permutations for correlation when n<30
DEFAULT_SEED = 42
DEFAULT_MAX_EPOCHS = 10

FILENAME_PREFIX = "results_"
FILENAME_EXCLUDE_SUBSTRINGS = ["NICON", "CNN", "Ridge", "LGBM", "PLS"]  # exclude these filenames globally
EXCLUDE_PREPS = {"PCA"}  # optional global exclusion of preprocessings

MODEL_COL = "Model"

# ----------------------- Determinism -----------------------

def set_global_determinism(seed: int = 42):
    """Set deterministic behavior across random libraries and limit thread counts."""
    import os, numpy as _np
    os.environ["PYTHONHASHSEED"] = str(seed)
    os.environ["OMP_NUM_THREADS"] = "1"
    os.environ["OPENBLAS_NUM_THREADS"] = "1"
    os.environ["MKL_NUM_THREADS"] = "1"
    os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
    os.environ["NUMEXPR_NUM_THREADS"] = "1"
    random.seed(seed); _np.random.seed(seed)

set_global_determinism(DEFAULT_SEED)

# ----------------------- IO: discover and read -----------------------

def discover_dataset_csvs(root_dir: str) -> List[Tuple[str, str]]:
    """Discover per-dataset results CSVs: first 'results_*.csv' per dataset, excluding substrings."""
    pairs = []
    if not os.path.isdir(root_dir):
        print(f"[WARN] Root directory not found: {root_dir}")
        return pairs
    for ds in sorted(os.listdir(root_dir)):
        ds_dir = os.path.join(root_dir, ds)
        if not os.path.isdir(ds_dir): continue
        cands = [f for f in os.listdir(ds_dir)
                 if f.startswith(FILENAME_PREFIX) and f.lower().endswith(".csv")]
        cands = [f for f in cands if not any(excl in f for excl in FILENAME_EXCLUDE_SUBSTRINGS)]
        if not cands: continue
        cands.sort()
        pairs.append((ds, os.path.join(ds_dir, cands[0])))
    return pairs

def detect_task_from_models(models: List[str]) -> str:
    """Return 'regression', 'classification', 'ambiguous', or 'unknown' using suffixes _reg / _classif."""
    has_reg = any(isinstance(m, str) and m.endswith("_reg") for m in models)
    has_clf = any(isinstance(m, str) and m.endswith("_classif") for m in models)
    if has_reg and not has_clf: return "regression"
    if has_clf and not has_reg: return "classification"
    if has_reg and has_clf: return "ambiguous"
    return "unknown"

def collect_delta_profiles_by_task(root: str) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Read per-dataset CSVs, compute Δ per (model, prep, dataset), split by task.
    Δ definitions:
      - regression:    Δ = RRMSE(candidate) - min_model RRMSE (same dataset & prep)
      - classification:Δ = max_model Acc   - Acc(candidate)  (same dataset & prep)
    Returns two tidy DataFrames:
      diffs_reg: [dataset, candidate_model, prep, delta]
      diffs_clf: [dataset, candidate_model, prep, delta]
    """
    reg_rows, clf_rows = [], []
    pairs = discover_dataset_csvs(root)
    for ds, path in pairs:
        try:
            df = pd.read_csv(path)
        except Exception as e:
            print(f"[WARN] Failed to read {path}: {e}")
            continue
        if MODEL_COL not in df.columns:
            print(f"[WARN] Missing '{MODEL_COL}' in {path}, skip.")
            continue

        models = [str(x) for x in df[MODEL_COL].dropna().tolist()]
        task = detect_task_from_models(models)
        if task in ("ambiguous", "unknown"):
            print(f"[WARN] Dataset '{ds}' task={task}, skip.")
            continue

        tidy = df.melt(id_vars=[MODEL_COL], var_name="prep", value_name="metric").rename(columns={MODEL_COL:"model"})
        if EXCLUDE_PREPS:
            tidy = tidy[~tidy["prep"].isin(EXCLUDE_PREPS)]
        tidy["metric"] = pd.to_numeric(tidy["metric"], errors="coerce")
        tidy = tidy.dropna(subset=["metric"])
        if tidy.empty:
            continue

        pivot = tidy.pivot_table(index="model", columns="prep", values="metric", aggfunc="mean")
        for prep in pivot.columns:
            col = pivot[prep].dropna()
            if col.empty: continue
            if task == "regression":
                best = float(col.min())
                for cand in col.index:
                    dlt = float(col.loc[cand] - best)
                    reg_rows.append((ds, cand, str(prep), dlt))
            else:
                best = float(col.max())
                for cand in col.index:
                    dlt = float(best - col.loc[cand])
                    clf_rows.append((ds, cand, str(prep), dlt))
    diffs_reg = pd.DataFrame(reg_rows, columns=["dataset","candidate_model","prep","delta"])
    diffs_clf = pd.DataFrame(clf_rows, columns=["dataset","candidate_model","prep","delta"])
    return diffs_reg, diffs_clf

# ----------------------- Statistics: tests -----------------------

def exact_sign_test_inferiority(deltas: np.ndarray, delta_margin: float) -> Tuple[Optional[float], int]:
    """
    Exact one-sided Sign test for inferiority on Y = Δ - δ:
      H0: median(Y) <= 0  vs  H1: median(Y) > 0
    Ties (Y == 0) are removed. Returns (p_value, n_effective).
    """
    y = deltas - delta_margin
    eff = y[np.abs(y) > 0]
    n_eff = int(eff.size)
    if n_eff == 0:
        return None, 0
    s_pos = int(np.sum(eff > 0))
    if SCIPY_AVAILABLE:
        p = 1.0 - binom.cdf(s_pos - 1, n_eff, 0.5)
    else:
        # manual exact binomial upper tail
        from math import comb
        p = sum(comb(n_eff, k) * (0.5 ** n_eff) for k in range(s_pos, n_eff + 1))
    return float(p), n_eff

def wilcoxon_inferiority(deltas: np.ndarray, delta_margin: float) -> Tuple[Optional[float], int]:
    """
    One-sided Wilcoxon signed-rank on Y=Δ-δ with alternative='greater' (inferiority).
    Returns (p_value, n_eff non-zero). Provided for reporting only.
    """
    if not SCIPY_AVAILABLE:
        return None, 0
    y = deltas - delta_margin
    y = y[np.abs(y) > 0]
    n = len(y)
    if n == 0: return None, 0
    try:
        stat, p = wilcoxon(y, alternative="greater", zero_method="wilcox", correction=False, mode="auto")
        return float(p), n if isinstance(p, float) else (None, n)
    except Exception:
        return None, n

def spearman_perm_or_classical(x: np.ndarray, y: np.ndarray, n_perm: int = 10000, seed: int = 42) -> Tuple[float, float]:
    """
    Adaptive one-sided Spearman correlation test (H1: rho > 0).
      * If n < 30: permutation test (Monte Carlo, robust for small samples)
      * Else: classical Spearman test (approximate, one-sided)
    Handles constant inputs by returning rho=0, p=1.
    """
    rng = np.random.default_rng(seed)
    mask = np.isfinite(x) & np.isfinite(y)
    x = x[mask]; y = y[mask]
    n = len(x)
    if n < 3:
        return 0.0, 1.0

    # Constant arrays -> undefined correlation
    if np.all(x == x[0]) or np.all(y == y[0]):
        return 0.0, 1.0

    # Compute observed Spearman
    try:
        rho_obs, _ = spearmanr(x, y)
    except Exception:
        rho_obs = np.nan
    if np.isnan(rho_obs):
        return 0.0, 1.0

    # Small sample -> permutation (one-sided right tail)
    if n < 30:
        rx = pd.Series(x).rank().to_numpy()
        ry = pd.Series(y).rank().to_numpy()
        rx_c = rx - rx.mean()
        ry_c = ry - ry.mean()
        denom = np.sqrt(np.dot(rx_c, rx_c) * np.dot(ry_c, ry_c))
        if denom == 0:
            return 0.0, 1.0
        rho_obs = float(np.dot(rx_c, ry_c) / denom)

        ge = 1  # add-one smoothing
        for _ in range(n_perm):
            rng.shuffle(ry)
            ry_c2 = ry - ry.mean()
            denom2 = np.sqrt(np.dot(rx_c, rx_c) * np.dot(ry_c2, ry_c2))
            if denom2 == 0:
                continue
            rho_perm = np.dot(rx_c, ry_c2) / denom2
            if rho_perm >= rho_obs - 1e-15:
                ge += 1
        p = ge / (n_perm + 1.0)
        return float(rho_obs), float(p)

    # Larger sample -> classical Spearman, one-sided right tail
    try:
        rho_obs, p_two = spearmanr(x, y)
        if np.isnan(rho_obs): return 0.0, 1.0
        p_one = p_two / 2 if rho_obs > 0 else 1 - p_two / 2
        p = max(min(p_one, 1.0), 0.0)
        return float(rho_obs), float(p)
    except Exception:
        return 0.0, 1.0

def benjamini_hochberg(pvals: List[Optional[float]]) -> List[Optional[float]]:
    """Benjamini–Hochberg FDR on a list of p-values (None/NaN preserved)."""
    idx = [(i, p) for i, p in enumerate(pvals) if p is not None and np.isfinite(p)]
    m = len(idx)
    q = [None] * len(pvals)
    if m == 0: return q
    idx.sort(key=lambda t: t[1])
    raw = [min(1.0, idx[k][1] * m / (k + 1)) for k in range(m)]
    for k in range(m - 2, -1, -1):
        raw[k] = min(raw[k], raw[k + 1])
    for k, (i, _) in enumerate(idx):
        q[i] = raw[k]
    return q

# ----------------------- Gatekeeping engine -----------------------

def envelope_profile(kept_block: pd.DataFrame, datasets: List[str]) -> np.ndarray:
    """Envelope v_S(d) = min_{row in kept_block} Δ(row, d)."""
    if kept_block.empty:
        return np.full(len(datasets), np.nan)
    return np.nanmin(kept_block[datasets].to_numpy(float), axis=0)

def iterative_gatekeeping(diffs: pd.DataFrame,
                          alpha: float,
                          delta: float,
                          n_perm: int,
                          seed: int,
                          max_epochs: int = 10):
    """
    Run iterative gatekeeping until convergence:
      1) Build candidate-by-dataset Δ matrix, order by median Δ (best first).
      2) Initialize S with the top-1 (always kept).
      3) Epoch loop:
           - Gate 1 for all not-in-S (inferiority test on Δ-δ).
           - Envelope v_S from current S.
           - Gate 2 for Gate-1-significant: Spearman (perm if n<30 else classical), BH–FDR within epoch.
           - EXCLUDE only if Gate1 sig AND Gate2 q<alpha; otherwise KEEP.
      4) Stop when S stabilizes or max_epochs reached.

    Returns:
      summary_df: per (model, prep) with p-values/q-values/decision
      kept_df: final kept (model, prep)
    """
    if diffs.empty:
        return pd.DataFrame(), pd.DataFrame(columns=["candidate_model","prep"])

    # Build Δ matrix
    mat = diffs.pivot_table(index=["candidate_model","prep"], columns="dataset", values="delta", aggfunc="mean")
    mat = mat.sort_index()
    datasets = list(mat.columns)
    med = mat.median(axis=1, skipna=True)
    order = med.sort_values().index
    mat = mat.loc[order]; med = med.loc[order]

    # Initialize S with top-1
    kept_mask = pd.Series(False, index=mat.index)
    if len(kept_mask) > 0: kept_mask.iloc[0] = True

    # Bookkeeping for reporting
    records: Dict[Tuple[str,str], Dict] = {idx: {"median_delta": float(med.loc[idx])} for idx in mat.index}

    prev_kept = None
    for epoch in range(1, max_epochs+1):
        gate2_candidates = []

        # Gate 1: performance (inferiority). Not-proven-worse -> KEEP immediately.
        for idx in mat.index:
            if kept_mask.loc[idx]: continue
            deltas = mat.loc[idx].to_numpy(float)
            deltas = deltas[np.isfinite(deltas)]
            p1, n1 = exact_sign_test_inferiority(deltas, delta)
            p1w, n1w = wilcoxon_inferiority(deltas, delta)
            rec = records[idx]
            rec.update({"gate1_perf_sign_p":p1, "gate1_perf_n_eff":n1,
                        "gate1_wilcoxon_p":p1w, "gate1_wilcoxon_n_eff":n1w})
            if p1 is None or p1 >= alpha:
                kept_mask.loc[idx] = True
                rec["gate1_pass"] = False
            else:
                rec["gate1_pass"] = True
                gate2_candidates.append(idx)

        # Envelope from current S
        kept_block = mat.loc[kept_mask]
        vS = envelope_profile(kept_block, datasets)

        # Gate 2: correlation vs envelope for Gate-1-significant only
        p_list, idx_list = [], []
        for idx in gate2_candidates:
            vec = mat.loc[idx].to_numpy(float)
            rho, p2 = spearman_perm_or_classical(vec, vS, n_perm=n_perm, seed=seed+epoch)
            records[idx]["gate2_corr_rho"] = rho
            records[idx]["gate2_corr_p"] = p2
            p_list.append(p2); idx_list.append(idx)

        # BH–FDR within epoch
        qvals = benjamini_hochberg(p_list) if p_list else []
        for idx, q2 in zip(idx_list, qvals):
            records[idx]["gate2_corr_q"] = q2

        # Decisions: exclude only if Gate1 sig AND Gate2 q<alpha; else keep.
        for idx in gate2_candidates:
            q2 = records[idx].get("gate2_corr_q", None)
            if q2 is not None and np.isfinite(q2) and q2 < alpha:
                kept_mask.loc[idx] = False; records[idx]["decision"] = "EXCLUDE"
            else:
                kept_mask.loc[idx] = True;  records[idx]["decision"] = "KEEP"

        kept_now = tuple(kept_mask[kept_mask].index)
        if prev_kept is not None and kept_now == prev_kept:
            break
        prev_kept = kept_now

    # Finalize summary
    rows = []
    for idx in mat.index:
        rec = records[idx]; model, prep = idx
        rows.append({
            "candidate_model": model, "prep": prep,
            "median_delta": rec.get("median_delta", np.nan),
            "gate1_perf_sign_p": rec.get("gate1_perf_sign_p", None),
            "gate1_perf_n_eff": rec.get("gate1_perf_n_eff", None),
            "gate1_wilcoxon_p": rec.get("gate1_wilcoxon_p", None),
            "gate1_wilcoxon_n_eff": rec.get("gate1_wilcoxon_n_eff", None),
            "gate2_corr_rho": rec.get("gate2_corr_rho", None),
            "gate2_corr_p": rec.get("gate2_corr_p", None),
            "gate2_corr_q": rec.get("gate2_corr_q", None),
            "decision": "KEEP" if kept_mask.loc[idx] else "EXCLUDE"
        })
    summary = pd.DataFrame(rows).sort_values(["decision","median_delta","candidate_model","prep"])
    kept_df = summary[summary["decision"]=="KEEP"][["candidate_model","prep"]].reset_index(drop=True)
    return summary, kept_df

# ----------------------- Visualization (global, per task) -----------------------

def ensure_dir(path: str):
    if not os.path.isdir(path):
        os.makedirs(path, exist_ok=True)

def decision_heatmap(df: pd.DataFrame, task_label: str, fig_dir: str, prefix: str):
    """Heatmap of final decisions (KEEP/EXCLUDE) across all (model, prep)."""
    if df.empty: return
    pivot = df.pivot_table(index="candidate_model", columns="prep",
                           values="decision", aggfunc=lambda x: x.iloc[0])
    mat = pivot.map(lambda v: 1 if str(v).upper()=="KEEP" else 0 if str(v).upper()=="EXCLUDE" else np.nan)
    plt.figure(figsize=(max(10, 0.6*len(mat.columns)), max(6, 0.6*len(mat.index))))
    sns.heatmap(mat, cmap=sns.color_palette(["red","green"]), cbar=False,
                linewidths=0.5, linecolor="gray", annot=True, fmt=".0f")
    plt.title(f"Decision Heatmap ({task_label})", fontsize=14)
    plt.xlabel("Preprocessing"); plt.ylabel("Model")
    plt.xticks(rotation=45, ha="right"); plt.tight_layout()
    out = os.path.join(fig_dir, f"{prefix}_{task_label}_decision_heatmap.png")
    plt.savefig(out); plt.close()

def pvalue_distributions(df: pd.DataFrame, task_label: str, fig_dir: str, prefix: str):
    """Histogram of p-values (Gate 1 and Gate 2)."""
    if df.empty: return
    plt.figure(figsize=(8,6))
    sns.histplot(df["gate1_perf_sign_p"].dropna(), bins=20, color="steelblue", alpha=0.6, label="Gate 1 (Performance)")
    sns.histplot(df["gate2_corr_p"].dropna(), bins=20, color="orange", alpha=0.6, label="Gate 2 (Correlation)")
    plt.axvline(0.05, color="black", linestyle="--", label="α = 0.05")
    plt.xlabel("p-value"); plt.ylabel("Count"); plt.title(f"P-value distributions ({task_label})")
    plt.legend(); plt.tight_layout()
    out = os.path.join(fig_dir, f"{prefix}_{task_label}_pvalue_distributions.png")
    plt.savefig(out); plt.close()

def scatter_perf_corr(df: pd.DataFrame, task_label: str, fig_dir: str, prefix: str):
    """Scatter plot of Gate 1 vs Gate 2 significance (log–log), color by decision, size by 1/(median_delta+ε)."""
    if df.empty: return
    sub = df.dropna(subset=["gate1_perf_sign_p","gate2_corr_q"])
    if sub.empty: return
    colors = sub["decision"].map({"KEEP":"green","EXCLUDE":"red"}).fillna("gray")
    sizes = 150.0 / (sub["median_delta"].replace(0, np.nan).fillna(1e-3))
    plt.figure(figsize=(7,6))
    plt.scatter(sub["gate1_perf_sign_p"], sub["gate2_corr_q"],
                c=colors, s=sizes, alpha=0.75, edgecolor="k", linewidth=0.3)
    plt.axvline(0.05, color="gray", linestyle="--")
    plt.axhline(0.05, color="gray", linestyle="--")
    plt.xscale("log"); plt.yscale("log")
    plt.xlabel("Gate 1 p-value (Performance)"); plt.ylabel("Gate 2 q-value (Correlation, FDR)")
    plt.title(f"Performance vs Correlation ({task_label})")
    plt.tight_layout()
    out = os.path.join(fig_dir, f"{prefix}_{task_label}_scatter_perf_corr.png")
    plt.savefig(out); plt.close()

def selection_progression(curve: List[int], task_label: str, fig_dir: str, prefix: str):
    """Line plot of number of kept pairs vs iteration (epoch index)."""
    if not curve: return
    plt.figure(figsize=(7,5))
    plt.plot(range(1, len(curve)+1), curve, marker="o", linewidth=2)
    plt.xlabel("Epoch"); plt.ylabel("Number of kept pairs")
    plt.title(f"Selection progression ({task_label})"); plt.grid(alpha=0.3)
    plt.tight_layout()
    out = os.path.join(fig_dir, f"{prefix}_{task_label}_progression.png")
    plt.savefig(out); plt.close()

def gate_map(df: pd.DataFrame, task_label: str, fig_dir: str, prefix: str):
    """Useful for gatekeeping: map median Δ (x) vs -log10 p1 (y), color by decision."""
    if df.empty: return
    sub = df.copy()
    sub["neglog10_p1"] = -np.log10(sub["gate1_perf_sign_p"].replace(0, np.nan))
    plt.figure(figsize=(8,6))
    colors = sub["decision"].map({"KEEP":"green","EXCLUDE":"red"}).fillna("gray")
    plt.scatter(sub["median_delta"], sub["neglog10_p1"], c=colors, alpha=0.75, edgecolor="k", linewidth=0.3)
    plt.axvline(0.01, color="gray", linestyle="--", alpha=0.5)  # visual guide at δ=0.01
    plt.xlabel("Median Δ (worse to the right)"); plt.ylabel("-log10 p (Gate 1)")
    plt.title(f"Gate map: performance signal ({task_label})")
    plt.tight_layout()
    out = os.path.join(fig_dir, f"{prefix}_{task_label}_gate_map.png")
    plt.savefig(out); plt.close()

def corr_map(df: pd.DataFrame, task_label: str, fig_dir: str, prefix: str):
    """Useful for gatekeeping: map correlation vs q2 (FDR), color by decision."""
    if df.empty: return
    sub = df.dropna(subset=["gate2_corr_rho","gate2_corr_q"])
    if sub.empty: return
    colors = sub["decision"].map({"KEEP":"green","EXCLUDE":"red"}).fillna("gray")
    plt.figure(figsize=(8,6))
    plt.scatter(sub["gate2_corr_rho"], sub["gate2_corr_q"], c=colors, alpha=0.75, edgecolor="k", linewidth=0.3)
    plt.axhline(0.05, color="gray", linestyle="--")
    plt.xlabel("Spearman ρ with envelope v_S"); plt.ylabel("Gate 2 q-value (FDR)")
    plt.title(f"Correlation vs FDR ({task_label})")
    plt.tight_layout()
    out = os.path.join(fig_dir, f"{prefix}_{task_label}_corr_map.png")
    plt.savefig(out); plt.close()

def visualize_global(summary: pd.DataFrame, progression: List[int], task_label: str,
                     fig_dir: str, prefix: str):
    """Produce all global figures per task."""
    ensure_dir(fig_dir)
    decision_heatmap(summary, task_label, fig_dir, prefix)
    pvalue_distributions(summary, task_label, fig_dir, prefix)
    scatter_perf_corr(summary, task_label, fig_dir, prefix)
    selection_progression(progression, task_label, fig_dir, prefix)
    gate_map(summary, task_label, fig_dir, prefix)
    corr_map(summary, task_label, fig_dir, prefix)

# ----------------------- Main -----------------------

parser = argparse.ArgumentParser(description="Iterative gatekeeping selection (adaptive correlation + FDR).")
parser.add_argument("--root", type=str, default=DEFAULT_RESULTS_ROOT, help="Root folder with per-dataset results.")
parser.add_argument("--out_dir", type=str, default=DEFAULT_OUT_DIR, help="Output dir for CSV reports.")
parser.add_argument("--fig_dir", type=str, default=DEFAULT_FIG_DIR, help="Output dir for figures.")
parser.add_argument("--prefix", type=str, default=DEFAULT_PREFIX, help="Output file prefix.")
parser.add_argument("--alpha", type=float, default=DEFAULT_ALPHA, help="Significance level (alpha).")
parser.add_argument("--delta", type=float, default=DEFAULT_DELTA, help="Non-inferiority margin δ for Gate 1.")
parser.add_argument("--n_perm", type=int, default=DEFAULT_N_PERM, help="Permutations for Spearman when n<30.")
parser.add_argument("--seed", type=int, default=DEFAULT_SEED, help="Random seed.")
parser.add_argument("--max_epochs", type=int, default=DEFAULT_MAX_EPOCHS, help="Maximum number of epochs.")
args = parser.parse_args()

set_global_determinism(args.seed)
ensure_dir(args.out_dir); ensure_dir(args.fig_dir)

# Build Δ tables per task
diffs_reg, diffs_clf = collect_delta_profiles_by_task(args.root)

# REGRESSION
if not diffs_reg.empty:
    print("[INFO] Running gatekeeping for REGRESSION...")
    summary_reg, kept_reg = iterative_gatekeeping(diffs_reg, alpha=args.alpha, delta=args.delta,
                                                    n_perm=args.n_perm, seed=args.seed, max_epochs=args.max_epochs)
    out_report = os.path.join(args.out_dir, f"{args.prefix}_reg_report.csv")
    out_keep   = os.path.join(args.out_dir, f"{args.prefix}_reg_keep.csv")
    summary_reg.to_csv(out_report, index=False); kept_reg.to_csv(out_keep, index=False)
    # progression curve: number of kept after each epoch (we approximate by counting 'KEEP' at end,
    # or one can track it inside iterative_gatekeeping to get the per-epoch series explicitly)
    # Here we derive a simple proxy: not available -> plot a single dot (optional).
    # For completeness, we can reconstruct a constant line of final size:
    progression_reg = []  # keep empty if not tracked; functions handle empty
    visualize_global(summary_reg, progression_reg, "regression", args.fig_dir, args.prefix)
    print(f"[INFO] Saved REG csvs -> {out_report} / {out_keep}")

# CLASSIFICATION
if not diffs_clf.empty:
    print("[INFO] Running gatekeeping for CLASSIFICATION...")
    summary_clf, kept_clf = iterative_gatekeeping(diffs_clf, alpha=args.alpha, delta=args.delta,
                                                    n_perm=args.n_perm, seed=args.seed, max_epochs=args.max_epochs)
    out_report = os.path.join(args.out_dir, f"{args.prefix}_classif_report.csv")
    out_keep   = os.path.join(args.out_dir, f"{args.prefix}_classif_keep.csv")
    summary_clf.to_csv(out_report, index=False); kept_clf.to_csv(out_keep, index=False)
    progression_clf = []
    visualize_global(summary_clf, progression_clf, "classification", args.fig_dir, args.prefix)
    print(f"[INFO] Saved CLF csvs -> {out_report} / {out_keep}")

if diffs_reg.empty and diffs_clf.empty:
    print("[WARN] No usable datasets found (check file names, task suffixes, and CSV structure).")