#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Adaptive selection of (model, preprocessing) pairs via GRAPH PRUNING based on:
  - Redundancy detection (positive Spearman correlation) with a HYBRID test:
      * n < 30  -> one-sided permutation test (H1: rho > 0)
      * n >= 30 -> one-sided asymptotic test from scipy.stats.spearmanr
    + Global BH-FDR across all tested pairwise correlations (edges)
  - Performance non-inferiority as an EXCLUSION guard:
      For candidate j vs already kept k, test Δ = r_j - r_k with H1: median(Δ) > 0
      using the exact sign test; apply BH-FDR WITHIN j (across all k ∈ S that are
      positively correlated with j at FDR level). If any comparison is significant,
      prune j; otherwise keep j.

Task separation:
  - Regression and classification are handled SEPARATELY (auto-detected by model suffix).
  - Normalization per dataset so "best" equals 1.0 (min for regression, max for classification).

Outputs:
  - CSV of decisions (kept/pruned), with reasons.
  - Spearman rho matrix CSV and matching BH-FDR q-value matrix CSV (global over edges).
  - Significant-correlation heatmap (q < alpha).
  - Correlation network (nodes= pairs, edges if rho>0 & q<alpha; green=kept, red=pruned).
  - Progression, scatter and kept/pruned heatmap.

Structure intentionally mirrors your "weakness_coverage.py" script (sections & style).
Author: Generated by ChatGPT. All comments are in English.
"""

import os
import argparse
import numpy as np
import pandas as pd
import random
import warnings
import sys
from tqdm import tqdm
from scipy.stats import spearmanr, binomtest, ConstantInputWarning
warnings.filterwarnings("ignore", category=ConstantInputWarning)

import matplotlib
matplotlib.use("Agg")  # safe for batch
import matplotlib.pyplot as plt
import seaborn as sns

# Optional network plot
try:
    import networkx as nx
    NETWORKX_AVAILABLE = True
except Exception:
    NETWORKX_AVAILABLE = False


# ----------------------- Parameters -----------------------

DEFAULT_INPUT_DIR = "Results/assoc_pp_model/per_dataset"
DEFAULT_OUTPUT_PREFIX = "Results/assoc_pp_model/All_datasets/Pipeline_graph/adaptive_diverse_selection"
DEFAULT_ALPHA = 0.05
DEFAULT_PERMUTATIONS = 10000
DEFAULT_RANDOM_SEED = 42
DEFAULT_MIN_OVERLAP = 3
DEFAULT_EXCLUDE_NAME_SUBSTR = ["CNN", "LGBM", "PLS", "Ridge", "NICON"]  # filenames containing these substrings are ignored
DEFAULT_EXCLUDE_PREPS = {"PCA"}  # optional global exclusion of preprocessings


# ----------------------- Determinism -----------------------

def set_global_determinism(seed=42):
    """Ensure deterministic behavior across libs & threads."""
    os.environ["PYTHONHASHSEED"] = str(seed)
    os.environ["OMP_NUM_THREADS"] = "1"
    os.environ["OPENBLAS_NUM_THREADS"] = "1"
    os.environ["MKL_NUM_THREADS"] = "1"
    os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
    os.environ["NUMEXPR_NUM_THREADS"] = "1"
    os.environ["BLIS_NUM_THREADS"] = "1"
    random.seed(seed)
    np.random.seed(seed)

set_global_determinism(DEFAULT_RANDOM_SEED)


# ----------------------- Utilities -----------------------

def benjamini_hochberg(pvals):
    """Benjamini–Hochberg FDR correction. Keeps shape & order."""
    p = np.asarray(pvals, dtype=float)
    n = len(p)
    order = np.argsort(p)
    q = np.empty_like(p)
    prev = 1.0
    for r, idx in enumerate(order[::-1], start=1):
        qq = min(prev, p[idx] * n / r)
        q[idx] = qq
        prev = qq
    return q

def exact_sign_test_greater(diff):
    """Exact one-sided sign test for H1: median(diff) > 0. Ties (0) removed."""
    y = np.asarray(diff)
    y = y[np.abs(y) > 0]
    n = len(y)
    if n == 0:
        return None
    s = int(np.sum(y > 0))
    res = binomtest(s, n, 0.5, alternative="greater")
    return float(res.pvalue) if hasattr(res, "pvalue") else float(res)

def spearman_hybrid_pvalue(x, y, n_perm=10000, seed=42):
    """Hybrid one-sided Spearman test (H1: rho > 0).
       If n < 30 -> permutation p-value; else -> asymptotic one-sided p-value.
       Returns (rho, p_one_sided, n_used).
    """
    mask = np.isfinite(x) & np.isfinite(y)
    x, y = x[mask], y[mask]
    n = len(x)
    if n < 3:
        return np.nan, np.nan, n
    rho, p_two = spearmanr(x, y)
    if np.isnan(rho):
        return np.nan, np.nan, n
    if n < 30:
        rng = np.random.default_rng(seed)
        cnt = 0
        for _ in range(n_perm):
            yp = rng.permutation(y)
            rp, _ = spearmanr(x, yp)
            if np.isfinite(rp) and rp >= rho:
                cnt += 1
        p_one = (cnt + 1) / (n_perm + 1)
    else:
        p_one = p_two / 2 if rho > 0 else 1 - p_two / 2
    return float(rho), float(p_one), n


# ----------------------- Data discovery & parsing -----------------------

def discover_dataset_csvs(root_dir, include_prefix="results_", exclude_substrings=None):
    """Return [(dataset_name, csv_path), ...] for first valid CSV per dataset folder."""
    exclude_substrings = exclude_substrings or []
    out = []
    if not os.path.isdir(root_dir):
        return out
    for ds in sorted(os.listdir(root_dir)):
        ds_dir = os.path.join(root_dir, ds)
        if not os.path.isdir(ds_dir):
            continue
        cands = [f for f in os.listdir(ds_dir)
                 if f.startswith(include_prefix) and f.lower().endswith(".csv")
                 and not any(excl in f for excl in exclude_substrings)]
        if not cands:
            continue
        cands.sort()
        out.append((ds, os.path.join(ds_dir, cands[0])))
    return out

def load_long_table(csv_path, exclude_preps=None):
    """Load per-dataset wide CSV -> long table [model, prep, metric]."""
    df = pd.read_csv(csv_path)
    if "Model" not in df.columns:
        raise ValueError("Missing 'Model' column in CSV.")
    long = df.melt(id_vars=["Model"], var_name="prep", value_name="metric")
    long.rename(columns={"Model": "candidate_model"}, inplace=True)
    long.dropna(subset=["metric"], inplace=True)
    if exclude_preps:
        long = long[~long["prep"].isin(exclude_preps)]
    return long

def detect_task(models):
    """Detect task from model suffixes."""
    s = [str(m) for m in models]
    has_reg = any(m.endswith("_reg") for m in s)
    has_clf = any(m.endswith("_classif") for m in s)
    if has_reg and not has_clf:
        return "regression"
    if has_clf and not has_reg:
        return "classification"
    return "ambiguous"


def collect_and_merge(dataset_csvs, exclude_preps=None):
    """Merge all datasets into long table with task labels and normalization per dataset."""
    rows = []
    for ds, path in dataset_csvs:
        try:
            wide = pd.read_csv(path)
        except Exception as e:
            print(f"[WARN] Skipping {path}: {e}")
            continue
        if "Model" not in wide.columns:
            print(f"[WARN] Missing 'Model' in {path}, skipping dataset {ds}.")
            continue
        task = detect_task(wide["Model"])
        if task == "ambiguous":
            print(f"[WARN] Ambiguous task for dataset {ds}; skipping.")
            continue
        long = load_long_table(path, exclude_preps=exclude_preps)
        long["dataset"] = ds
        long["task"] = task
        rows.append(long)
    if not rows:
        return pd.DataFrame()
    merged = pd.concat(rows, ignore_index=True)
    return merged


# ----------------------- Normalization -----------------------

def normalize_within_dataset_task(df):
    """Normalize metric per dataset so best = 1.0 (min for regression, max for classification)."""
    df = df.copy()
    df["norm_perf"] = np.nan
    for (ds, task), sub in df.groupby(["dataset", "task"]):
        if task == "regression":
            best = sub["metric"].min()
            df.loc[sub.index, "norm_perf"] = sub["metric"] / best if best > 0 else sub["metric"]
        else:
            best = sub["metric"].max()
            df.loc[sub.index, "norm_perf"] = best / sub["metric"]
    return df


# ----------------------- Graph pruning core -----------------------

def precompute_correlations(pivot, alpha, n_perm, seed):
    """Compute Spearman hybrid tests for all pairs; return rho & q matrices (global BH-FDR)."""
    items = list(pivot.index)
    n = len(items)
    rho = np.full((n, n), np.nan, dtype=float)
    pmat = np.full((n, n), np.nan, dtype=float)

    # Upper-triangular tests
    for i in range(n):
        xi = pivot.loc[items[i]].to_numpy(dtype=float)
        for j in range(i + 1, n):
            yj = pivot.loc[items[j]].to_numpy(dtype=float)
            r, p, n_used = spearman_hybrid_pvalue(xi, yj, n_perm=n_perm, seed=seed)
            rho[i, j] = r
            pmat[i, j] = p

    # BH-FDR across all tested edges
    p_list = [pmat[i, j] for i in range(n) for j in range(i + 1, n) if not np.isnan(pmat[i, j])]
    q = np.full_like(pmat, np.nan)
    if p_list:
        q_list = benjamini_hochberg(p_list)
        it = iter(q_list)
        for i in range(n):
            for j in range(i + 1, n):
                if not np.isnan(pmat[i, j]):
                    q[i, j] = next(it)

    # symmetrize
    for i in range(n):
        for j in range(i + 1, n):
            rho[j, i] = rho[i, j]
            q[j, i] = q[i, j]

    rho_df = pd.DataFrame(rho, index=items, columns=items)
    q_df = pd.DataFrame(q, index=items, columns=items)
    return rho_df, q_df


def adaptive_graph_pruning(df_task, alpha, n_perm, seed, min_overlap):
    """Run graph pruning for a single task (regression or classification)."""
    pivot = df_task.pivot_table(index=["candidate_model", "prep"],
                                columns="dataset", values="norm_perf", aggfunc="mean")
    rho_df, q_df = precompute_correlations(pivot, alpha=alpha, n_perm=n_perm, seed=seed)

    med = pivot.median(axis=1)
    order = med.sort_values(ascending=True).index.tolist()

    kept = []
    decisions = []
    progression = []
    for pair in order:
        xj = pivot.loc[pair].to_numpy(dtype=float)
        if np.sum(np.isfinite(xj)) < min_overlap:
            decisions.append({
                "candidate_model": pair[0], "prep": pair[1], "status": "skipped_insufficient_data",
                "reason": f"valid_entries<{min_overlap}", "median_profile": float(med.loc[pair]),
                "sig_corr_edge": None, "sig_worse": None
            })
            continue

        neighbors = []
        for k in kept:
            q = q_df.loc[pair, k]
            r = rho_df.loc[pair, k]
            if np.isfinite(q) and q < alpha and np.isfinite(r) and r > 0:
                xk = pivot.loc[k].to_numpy(dtype=float)
                mask = np.isfinite(xj) & np.isfinite(xk)
                if np.sum(mask) >= min_overlap:
                    neighbors.append(k)

        if not neighbors:
            kept.append(pair)
            decisions.append({
                "candidate_model": pair[0], "prep": pair[1], "status": "kept",
                "reason": "no_significant_positive_correlation_to_kept",
                "median_profile": float(med.loc[pair]),
                "sig_corr_edge": False, "sig_worse": False
            })
            progression.append(len(kept))
            continue

        # Performance exact sign tests H1: median Δ > 0, BH-FDR within-j
        pvals = []
        for k in neighbors:
            xk = pivot.loc[k].to_numpy(dtype=float)
            mask = np.isfinite(xj) & np.isfinite(xk)
            diff = xj[mask] - xk[mask]
            p = exact_sign_test_greater(diff)
            pvals.append(p)
        qvals = benjamini_hochberg([p if p is not None else np.nan for p in pvals]) if pvals else []
        sig_worse = any((q is not None) and np.isfinite(q) and (q < alpha) for q in qvals)

        if sig_worse:
            decisions.append({
                "candidate_model": pair[0], "prep": pair[1], "status": "pruned",
                "reason": "worse_than_correlated_kept",
                "median_profile": float(med.loc[pair]),
                "sig_corr_edge": True, "sig_worse": True
            })
        else:
            kept.append(pair)
            decisions.append({
                "candidate_model": pair[0], "prep": pair[1], "status": "kept",
                "reason": "not_worse_than_correlated_kept",
                "median_profile": float(med.loc[pair]),
                "sig_corr_edge": True, "sig_worse": False
            })
        progression.append(len(kept))

    dec_df = pd.DataFrame(decisions)
    return dec_df, kept, progression, rho_df, q_df, pivot


# ----------------------- Visualization -----------------------

def plot_sig_corr_heatmap(rho_df, q_df, alpha, out_path):
    """Heatmap of significant positive correlations (q < alpha)."""
    mask = ~(q_df < alpha)
    rho_sig = rho_df.mask(mask)
    plt.figure(figsize=(max(8, 0.25*rho_sig.shape[1]), max(6, 0.25*rho_sig.shape[0])))
    sns.heatmap(rho_sig, cmap="viridis", vmin=0, vmax=1, linewidths=0.3, linecolor="white")
    plt.title(f"Significant positive Spearman correlations (q < {alpha})")
    plt.tight_layout()
    plt.savefig(out_path, dpi=200)
    plt.close()

def plot_network(rho_df, q_df, dec_df, alpha, out_path, seed=42):
    """Correlation network: nodes colored by final decision (green=kept, red=pruned)."""
    if not NETWORKX_AVAILABLE:
        return
    G = nx.Graph()
    status = {}
    final = dec_df.groupby(["candidate_model", "prep"], as_index=False).tail(1)
    for _, r in final.iterrows():
        node = (r["candidate_model"], r["prep"])
        status[node] = r["status"]
        G.add_node(node)
    items = list(rho_df.index)
    for i in range(len(items)):
        for j in range(i+1, len(items)):
            if np.isfinite(rho_df.iloc[i, j]) and np.isfinite(q_df.iloc[i, j]) \
               and rho_df.iloc[i, j] > 0 and q_df.iloc[i, j] < alpha:
                G.add_edge(items[i], items[j], weight=float(rho_df.iloc[i, j]))
    colors = ["#2ca02c" if status.get(n)=="kept" else "#d62728" for n in G.nodes()]
    pos = nx.spring_layout(G, seed=seed)
    widths = [1 + 3*G[u][v]["weight"] for u, v in G.edges()]
    plt.figure(figsize=(12, 10))
    nx.draw_networkx_edges(G, pos, width=widths, alpha=0.6, edge_color="#1f77b4")
    nx.draw_networkx_nodes(G, pos, node_color=colors, node_size=500, alpha=0.9)
    nx.draw_networkx_labels(G, pos, labels={n:f"{n[0]}|{n[1]}" for n in G.nodes()}, font_size=8)
    plt.title("Correlation network (edges: rho>0 & q<alpha) — green=kept, red=pruned")
    plt.axis("off")
    plt.tight_layout()
    plt.savefig(out_path, dpi=220)
    plt.close()

def visualize_global(dec_df, progression, out_prefix, task_label):
    """Scatter (sig_corr vs sig_worse), heatmap kept/pruned, progression plot."""
    if dec_df.empty:
        return
    final = dec_df.groupby(["candidate_model","prep"], as_index=False).tail(1)

    # Scatter
    plt.figure(figsize=(7.5,6))
    sns.scatterplot(data=final, x="sig_corr_edge", y="sig_worse", hue="status",
                    palette={"kept":"green","pruned":"red","skipped_insufficient_data":"gray"},
                    s=100, alpha=0.9)
    plt.title(f"Outcomes — {task_label}")
    plt.xlabel("Has significant positive corr to kept set")
    plt.ylabel("Significantly worse (FDR within-j)")
    plt.tight_layout()
    plt.savefig(f"{out_prefix}_{task_label}_scatter.png", dpi=300)
    plt.close()

    # Heatmap kept/pruned
    mat = final.pivot(index="candidate_model", columns="prep", values="status")
    mat = mat.replace({"kept":1, "pruned":0, "skipped_insufficient_data":np.nan})
    plt.figure(figsize=(max(12,0.4*mat.shape[1]), max(6,0.5*mat.shape[0])))
    sns.heatmap(mat, cmap=sns.color_palette(["red","green"]), cbar=False, linewidths=0.4, linecolor="gray")
    plt.title(f"Kept vs pruned — {task_label}")
    plt.tight_layout()
    plt.savefig(f"{out_prefix}_{task_label}_heatmap.png", dpi=300)
    plt.close()

    # Progression
    plt.figure(figsize=(7,5))
    plt.plot(range(1,len(progression)+1), progression, marker="o", linewidth=2)
    plt.xlabel("Iteration")
    plt.ylabel("Number of kept pairs")
    plt.title(f"Selection progression — {task_label}")
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(f"{out_prefix}_{task_label}_progression.png", dpi=300)
    plt.close()


# ----------------------- Main -----------------------

parser = argparse.ArgumentParser(description="Adaptive graph pruning selection (regression & classification separated).")
parser.add_argument("--input_dir", type=str, default=DEFAULT_INPUT_DIR, help="Root folder with per-dataset result CSVs.")
parser.add_argument("--output_prefix", type=str, default=DEFAULT_OUTPUT_PREFIX, help="Prefix for outputs (CSV & figures).")
parser.add_argument("--alpha", type=float, default=DEFAULT_ALPHA, help="Significance level (for FDR and tests).")
parser.add_argument("--permutations", type=int, default=DEFAULT_PERMUTATIONS, help="Permutations (for small-n correlation tests).")
parser.add_argument("--seed", type=int, default=DEFAULT_RANDOM_SEED, help="Random seed for determinism.")
parser.add_argument("--min_overlap", type=int, default=DEFAULT_MIN_OVERLAP, help="Min dataset overlap to test.")
parser.add_argument("--task_only", type=str, choices=["regression", "classification"], default=None, help="If specified, only run adaptive selection for the chosen task (regression or classification).")
args = parser.parse_args()

# Discover datasets
dataset_csvs = discover_dataset_csvs(args.input_dir, exclude_substrings=DEFAULT_EXCLUDE_NAME_SUBSTR)
if not dataset_csvs:
    print(f"[ERROR] No dataset CSVs found under {args.input_dir}.")
    sys.exit()

# Merge and normalize per task
merged = collect_and_merge(dataset_csvs, exclude_preps=DEFAULT_EXCLUDE_PREPS)
if args.task_only:
    merged = merged[merged["task"] == args.task_only]

if merged.empty:
    print("[ERROR] No valid data after filtering.")
    sys.exit()
merged = normalize_within_dataset_task(merged)

# Process tasks separately
for task_label, df_task in merged.groupby("task"):
    print(f"[INFO] Running graph pruning for task: {task_label}")
    dec_df, kept, progression, rho_df, q_df, pivot = adaptive_graph_pruning(
        df_task, alpha=args.alpha, n_perm=args.permutations, seed=args.seed, min_overlap=args.min_overlap
    )

    # Prepare output paths
    base = f"{args.output_prefix}_{task_label}"
    os.makedirs(os.path.dirname(base), exist_ok=True)

    # Save decisions and matrices
    dec_df.to_csv(f"{base}_decisions.csv", index=False)
    rho_df.to_csv(f"{base}_rho.csv")
    q_df.to_csv(f"{base}_rho_q.csv")
    print(f"[INFO] Saved decisions to: {base}_decisions.csv")
    print(f"[INFO] Saved rho and q matrices to: {base}_rho.csv / {base}_rho_q.csv")

    # Visualizations: significant-corr heatmap and network
    plot_sig_corr_heatmap(rho_df, q_df, args.alpha, f"{base}_rho_sig_heatmap.png")
    print(f"[INFO] Saved significant correlation heatmap to: {base}_rho_sig_heatmap.png")
    plot_network(rho_df, q_df, dec_df, args.alpha, f"{base}_network.png", seed=args.seed)
    if NETWORKX_AVAILABLE:
        print(f"[INFO] Saved correlation network to: {base}_network.png")

    # Global summaries
    figs_prefix = base.replace("Results", "Figures")
    os.makedirs(os.path.dirname(figs_prefix), exist_ok=True)
    visualize_global(dec_df, progression, figs_prefix, task_label)
    print(f"[INFO] Saved visual summaries under prefix: {figs_prefix}_*.png")

print("[INFO] All tasks processed successfully.")
