uid: 4a10a23b-6c78-43ae-a28b-e75faaef840f
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: wood_c_402_olale
created_at: '2026-01-07T09:27:58.606361+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:c420e3c9c457cb869a0040d36665a950c74a835cc5d0f10428fe7653df5fd30e
  name: ASLSBaseline_1
  path: ASLSBaseline_c420e3.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2026-01-07T09:27:58.721869+00:00'
  step: 1
- hash: sha256:59ffc9f0d1073f838ce9d9b1231a023f6b0d90ef9ef3416bed1e54dee331fbe8
  name: PCA_1
  path: PCA_59ffc9.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 39674
  saved_at: '2026-01-07T09:27:58.826660+00:00'
  step: 4
- hash: sha256:8d17d922721838bedef3458fbd4d61ae977883401b82acb0f67e25863a32f47a
  name: AutoGluon_1.pkl
  path: TabularPredictor_8d17d9.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 13095
  saved_at: '2026-01-07T09:28:09.635355+00:00'
  step: 5
- hash: sha256:e1b0173ac5c474fbe8afe304c76f3a72f2880b5f1f839d4e6ba60bc48d9aa583
  name: AutoGluon_2.pkl
  path: TabularPredictor_e1b017.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 13104
  saved_at: '2026-01-07T09:28:09.635687+00:00'
  step: 5
- hash: sha256:b261fddcf8e8bfd3d422e29993e96259714b1b121600096a46c17612bd130941
  name: AutoGluon_3.pkl
  path: TabularPredictor_b261fd.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 13086
  saved_at: '2026-01-07T09:28:09.635989+00:00'
  step: 5
- hash: sha256:8083693fdb6d270d9a3c73c597027bf4e0e5f250bad9f0395a7bc001495cddb8
  name: TabPFN_1.pkl
  path: TabPFNRegressor_808369.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41256781
  saved_at: '2026-01-07T09:28:21.985760+00:00'
  step: 6
- hash: sha256:a81908e20d594194a0ff289013cc76df6c8cb1332cf7d1e29215d1e02dc9cd93
  name: TabPFN_2.pkl
  path: TabPFNRegressor_a81908.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41256777
  saved_at: '2026-01-07T09:28:22.041306+00:00'
  step: 6
- hash: sha256:f590a69845b41e3740af9bfb0a996bb7ec80f8872465dc89cd1592b1aa3a59c9
  name: TabPFN_3.pkl
  path: TabPFNRegressor_f590a6.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41256781
  saved_at: '2026-01-07T09:28:22.108929+00:00'
  step: 6
- hash: sha256:a6da784b216db6c468b1e3d5f193fc9fd57802980969d9a21e5947155dfe40c9
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_a6da78.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41256818
  saved_at: '2026-01-07T09:28:45.935224+00:00'
  step: 7
- hash: sha256:0f50057ce51c3b1150c36a0e25e752204aab0b2083860385c2294bc56f517262
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_0f5005.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41256818
  saved_at: '2026-01-07T09:28:45.984015+00:00'
  step: 7
- hash: sha256:cb63e81ae0f490a1686923e06f6528102ee302506080aee8f15bc337ab9c2abb
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_cb63e8.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41256818
  saved_at: '2026-01-07T09:28:46.031191+00:00'
  step: 7
predictions: []
