uid: 05b6a70b-efba-4537-a3c3-57d05e7bbdce
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: diesel_f_251_b_a
created_at: '2026-01-07T09:28:58.135873+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2026-01-07T09:28:58.174055+00:00'
  step: 1
- hash: sha256:c65a8564ea5b8a0d370fcad160d29912e625237cc30e98771eb0dade50c8bb26
  name: PCA_1
  path: PCA_c65a85.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 6679
  saved_at: '2026-01-07T09:28:58.206872+00:00'
  step: 4
- hash: sha256:80cd89474ca36f0454d274b097235a496bf7c3b018ea596ddb43e2cbf153481d
  name: AutoGluon_1.pkl
  path: TabularPredictor_80cd89.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 10842
  saved_at: '2026-01-07T09:29:08.800882+00:00'
  step: 5
- hash: sha256:72ce89fa2e7a6b990616f130b3024745dcc9b7a984696bc67b58d7143d19da7e
  name: AutoGluon_2.pkl
  path: TabularPredictor_72ce89.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 10851
  saved_at: '2026-01-07T09:29:08.801160+00:00'
  step: 5
- hash: sha256:8e1199b1aded2712d593abb148c22d1af8a5dbcc7be454d7d38472e14daff14f
  name: AutoGluon_3.pkl
  path: TabularPredictor_8e1199.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 10842
  saved_at: '2026-01-07T09:29:08.801398+00:00'
  step: 5
- hash: sha256:230343c65cebd841be7f2b5516a7793a4bdd1d3d65d904b9abf5e202bf1a631b
  name: TabPFN_1.pkl
  path: TabPFNRegressor_230343.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41011626
  saved_at: '2026-01-07T09:29:14.312468+00:00'
  step: 6
- hash: sha256:c88258d9d18ca5f45fd1a80b87870b3e2e8861d72dc1c5930fce92da6f74ed76
  name: TabPFN_2.pkl
  path: TabPFNRegressor_c88258.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41012460
  saved_at: '2026-01-07T09:29:14.357243+00:00'
  step: 6
- hash: sha256:b34aa3c01e8bdc6b049ec09d5c1a9c272e72a728ffc89a31fdd89b416b7c5792
  name: TabPFN_3.pkl
  path: TabPFNRegressor_b34aa3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41012460
  saved_at: '2026-01-07T09:29:14.401928+00:00'
  step: 6
- hash: sha256:095c0ac6c8713e83858b5969ccf37da75495ecc275f8b569a8bfa63a131a29a8
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_095c0a.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41011663
  saved_at: '2026-01-07T09:29:25.756856+00:00'
  step: 7
- hash: sha256:ac71ee8a057360ef9027b038e8f06a091fa4b03f7864ebe74e8619aec2dd5d4f
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_ac71ee.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41012497
  saved_at: '2026-01-07T09:29:25.803147+00:00'
  step: 7
- hash: sha256:938c66da5ca0a2690fc97a733abf1ffebee0af136e99973170f63dcda1063109
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_938c66.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41012497
  saved_at: '2026-01-07T09:29:25.849433+00:00'
  step: 7
predictions: []
