uid: a5451051-d0d9-46fc-9026-c0fcf3a76a1a
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: corn_starch_80_zhengchenpelegybasesplit
created_at: '2026-01-07T11:18:07.190993+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:26b2ddd51689b4d62afd0d8120bf3701bb34aecf8f7c42b134bb6c3d9b5f3096
  name: ASLSBaseline_1
  path: ASLSBaseline_26b2dd.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2026-01-07T11:18:07.211378+00:00'
  step: 1
- hash: sha256:b7a00fa0eca6c6f98b9f6e9974a6f0a67613caa485169f44461b35ce2bf77a56
  name: PCA_1
  path: PCA_b7a00f.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 13840
  saved_at: '2026-01-07T11:18:07.232148+00:00'
  step: 4
- hash: sha256:16307d2454436cc7cad974e5c556b1c97a66b98cfc1223cfcd9269a456eca7a6
  name: AutoGluon_1.pkl
  path: TabularPredictor_16307d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2026-01-07T11:18:16.316691+00:00'
  step: 5
- hash: sha256:3e151877d60c7845c8846878f1ece544d5d6ad9f4a72afa35b2a65c793cbda24
  name: AutoGluon_2.pkl
  path: TabularPredictor_3e1518.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11196
  saved_at: '2026-01-07T11:18:16.318714+00:00'
  step: 5
- hash: sha256:04cdeef6d86bacf9d75ffbf3f77f672a6dfe05c620e7e82f2f6da92541270743
  name: AutoGluon_3.pkl
  path: TabularPredictor_04cdee.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2026-01-07T11:18:16.320144+00:00'
  step: 5
- hash: sha256:e93a503bfd42fa5e09cc3426c7692845eef35237f362da41417a9bb78b1a5bea
  name: TabPFN_1.pkl
  path: TabPFNRegressor_e93a50.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 40991766
  saved_at: '2026-01-07T11:18:21.951798+00:00'
  step: 6
- hash: sha256:6a6d39d2c4d22cad831b17c6ca116061696854f0683cdffbb4e08340f58093bb
  name: TabPFN_2.pkl
  path: TabPFNRegressor_6a6d39.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 40992790
  saved_at: '2026-01-07T11:18:22.008893+00:00'
  step: 6
- hash: sha256:0eb6887ae17fa668dcfaaef3c1accfddf0c202050c6e08644f338f11f7f950bb
  name: TabPFN_3.pkl
  path: TabPFNRegressor_0eb688.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 40992790
  saved_at: '2026-01-07T11:18:22.065943+00:00'
  step: 6
- hash: sha256:b31b3f4686dc558ce030a5ba37ec6d9be87b552f5befb19d2818c585a92f2963
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_b31b3f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 40991803
  saved_at: '2026-01-07T11:18:30.389862+00:00'
  step: 7
- hash: sha256:3ce1241f8d79cf8e74f86978fd4d69542446fd707cd168b9d8e409db8a378c55
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_3ce124.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 40992827
  saved_at: '2026-01-07T11:18:30.447020+00:00'
  step: 7
- hash: sha256:c500713362af86b1d056ee932d5e26b2793c133c5b4aa556be8e4077283851fd
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_c50071.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 40992827
  saved_at: '2026-01-07T11:18:30.503723+00:00'
  step: 7
predictions: []
