schema_version: '2.0'
uid: 52880a61-6e90-42ce-86b8-80929fd66308
pipeline_id: 0001_SOTA_137acf
name: SOTA_137acf
dataset: corn_protein_80_zhengchenpelegybasesplit
created_at: '2026-01-09T16:49:06.426941+00:00'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 4
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0001_SOTA_137acf$bb12ee38a89c:all
    content_hash: sha256:26b2ddd51689b4d62afd0d8120bf3701bb34aecf8f7c42b134bb6c3d9b5f3096
    path: transformer_ASLSBaseline_26b2ddd51689.joblib
    chain_path: s1.ASLSBaseline[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 1
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: ASLSBaseline
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 216
    created_at: '2026-01-09T16:49:06.448450+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$2865afbbfc1d:all
    content_hash: sha256:3b745a96567e56d7273d748fa476c0726021fd6f960cf2e39fc6e6b632bd0f82
    path: encoder_StandardScaler_3b745a96567e.joblib
    chain_path: s2.y_StandardScaler[sub=1]
    source_index: null
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 2
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: StandardScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 444
    created_at: '2026-01-09T16:49:06.481587+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$b3c264a83f45:all
    content_hash: sha256:029da016177956f939761a7f2aa0dd50292822b9bbda321c3b90d9d49a5a90bb
    path: transformer_StandardScaler_029da0161779.joblib
    chain_path: s3.StandardScaler[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 3
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: StandardScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 14519
    created_at: '2026-01-09T16:49:06.490895+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$900033a82811:all
    content_hash: sha256:b08cd905668f3eb5009a629972ac9a0ea248d174cddc425d0b804f2e6cadefc8
    path: transformer_PCA_b08cd905668f.joblib
    chain_path: s5.PCA[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: PCA
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 20774
    created_at: '2026-01-09T16:49:06.527924+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$c5f06284fcbc:0
    content_hash: sha256:4403f72775f7cb002cbe5d98c18c11dd575b8cbb0cb15ba355933077b7d070e8
    path: model_TabPFNRegressor_4403f72775f7.pkl
    chain_path: s6.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 40937563
    created_at: '2026-01-09T16:49:07.979868+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$c5f06284fcbc:1
    content_hash: sha256:3fa4cad5c253a67599cebb3cb91327efc58fd29d5cddf16efa383556751acbe7
    path: model_TabPFNRegressor_3fa4cad5c253.pkl
    chain_path: s6.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 40937959
    created_at: '2026-01-09T16:49:08.023441+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_137acf$c5f06284fcbc:2
    content_hash: sha256:532684f66242b4c121f813db5d99d3918b208175336fd1d2a2c105e9a9a631d7
    path: model_TabPFNRegressor_532684f66242.pkl
    chain_path: s6.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_137acf
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 40937963
    created_at: '2026-01-09T16:49:08.067196+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  1f0e3a2c-504:
    trace_id: 1f0e3a2c-504
    pipeline_uid: 0001_SOTA_137acf
    created_at: '2026-01-09T16:49:06.427784+00:00'
    steps:
    - step_index: 1
      operator_type: transform
      operator_class: ASLSBaseline
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$bb12ee38a89c:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$bb12ee38a89c:all
        by_source:
          0:
          - 0001_SOTA_137acf$bb12ee38a89c:all
        by_chain:
          s1.ASLSBaseline[src=0,sub=0]: 0001_SOTA_137acf$bb12ee38a89c:all
        metadata:
          class_name: ASLSBaseline
          name: ASLSBaseline_1
      branch_path: []
      branch_name: ''
      duration_ms: 24.581193923950195
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s1.ASLSBaseline[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 80
      - 700
      output_shape:
      - 80
      - 700
      input_features_shape:
      - - 80
        - 1
        - 700
      output_features_shape:
      - - 80
        - 1
        - 700
    - step_index: 2
      operator_type: y_processing
      operator_class: StandardScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.StandardScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$2865afbbfc1d:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$2865afbbfc1d:all
        by_source: {}
        by_chain:
          s2.y_StandardScaler[sub=1]: 0001_SOTA_137acf$2865afbbfc1d:all
        metadata:
          class_name: StandardScaler
          name: y_StandardScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 34.21521186828613
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s2.y_StandardScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 80
      - 700
      output_shape:
      - 80
      - 700
      input_features_shape:
      - - 80
        - 1
        - 700
      output_features_shape:
      - - 80
        - 1
        - 700
    - step_index: 3
      operator_type: transform
      operator_class: StandardScaler
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$b3c264a83f45:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$b3c264a83f45:all
        by_source:
          0:
          - 0001_SOTA_137acf$b3c264a83f45:all
        by_chain:
          s3.StandardScaler[src=0,sub=0]: 0001_SOTA_137acf$b3c264a83f45:all
        metadata:
          class_name: StandardScaler
          name: StandardScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 19.5157527923584
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.StandardScaler[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 80
      - 700
      output_shape:
      - 80
      - 700
      input_features_shape:
      - - 80
        - 1
        - 700
      output_features_shape:
      - - 80
        - 1
        - 700
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 13.042688369750977
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 80
      - 700
      output_shape:
      - 80
      - 700
      input_features_shape:
      - - 80
        - 1
        - 700
      output_features_shape:
      - - 80
        - 1
        - 700
    - step_index: 5
      operator_type: operator
      operator_class: PCA
      operator_config:
        class: sklearn.decomposition._pca.PCA
        params:
          n_components: 0.99
          whiten: true
          random_state: 42
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$900033a82811:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$900033a82811:all
        by_source:
          0:
          - 0001_SOTA_137acf$900033a82811:all
        by_chain:
          s5.PCA[src=0,sub=0]: 0001_SOTA_137acf$900033a82811:all
        metadata:
          class_name: PCA
          name: PCA_1
      branch_path: []
      branch_name: ''
      duration_ms: 36.253929138183594
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.PCA[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 80
      - 700
      output_shape:
      - 80
      - 7
      input_features_shape:
      - - 80
        - 1
        - 700
      output_features_shape:
      - - 80
        - 1
        - 7
    - step_index: 6
      operator_type: model
      operator_class: TabPFNRegressor
      operator_config:
        model:
          class: tabpfn.regressor.TabPFNRegressor
          params:
            n_estimators: 4
            model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
            device: cpu
            ignore_pretraining_limits: true
            random_state: 42
        name: TabPFN-real
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_137acf$c5f06284fcbc:0
        - 0001_SOTA_137acf$c5f06284fcbc:1
        - 0001_SOTA_137acf$c5f06284fcbc:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0001_SOTA_137acf$c5f06284fcbc:0
          1: 0001_SOTA_137acf$c5f06284fcbc:1
          2: 0001_SOTA_137acf$c5f06284fcbc:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_137acf$c5f06284fcbc:0
            - 0001_SOTA_137acf$c5f06284fcbc:1
            - 0001_SOTA_137acf$c5f06284fcbc:2
        by_source: {}
        by_chain:
          s6.TabPFNRegressor[sub=0]: 0001_SOTA_137acf$c5f06284fcbc:2
        metadata:
          class_name: TabPFNRegressor
          custom_name: TabPFN-real
      branch_path: []
      branch_name: ''
      duration_ms: 3240.31400680542
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.TabPFNRegressor[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 80
      - 7
      output_shape:
      - 80
      - 7
      input_features_shape:
      - - 80
        - 1
        - 7
      output_features_shape:
      - - 80
        - 1
        - 7
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: ASLSBaseline>Std>PCA
    metadata:
      dataset: corn_protein_80_zhengchenpelegybasesplit
      config_name: SOTA_137acf
      n_steps: 6
      n_artifacts: 7
