schema_version: '2.0'
uid: 4f7690ab-8468-4043-aa8a-6353a83b081f
pipeline_id: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77
name: PLS_PP_SELECTION_NO_SAVE_6baf77
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:48:00.679149+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: null
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - nirs4all.operators.transforms.signal.Detrend
    - null
    - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
      params:
        window_length: 15
        deriv: 1
    - class: nirs4all.operators.transforms.nirs.Wavelet
      params:
        wavelet: coif3
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      error_score: .nan
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: null
- _cartesian_:
  - nirs4all.operators.transforms.signal.Detrend
  - null
  - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
    params:
      window_length: 15
      deriv: 1
  - class: nirs4all.operators.transforms.nirs.Wavelet
    params:
      wavelet: coif3
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:48:00.774635+00:00'
    params: {}
    version: 3
  - artifact_id: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$51eb708c8a1f:all
    content_hash: sha256:11ce246bc67c631c59d4827a162f06b45fa0f87770f7d8325a0c50c7f6d72fcf
    path: transformer_Detrend_11ce246bc67c.joblib
    chain_path: s5.Detrend[src=0,sub=0]
    source_index: 0
    pipeline_id: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: Detrend
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 90
    created_at: '2026-01-08T17:48:00.828252+00:00'
    params: {}
    version: 3
  - artifact_id: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$eeb09d32a26b:all
    content_hash: sha256:d663934f32b4b5e8dba18585ed74e0c4e66ed1008ee606d100f374d3224f9c49
    path: transformer_SavitzkyGolay_d663934f32b4.joblib
    chain_path: s5.SavitzkyGolay[src=0,sub=1]
    source_index: 0
    pipeline_id: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: SavitzkyGolay
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 137
    created_at: '2026-01-08T17:48:00.839289+00:00'
    params: {}
    version: 3
  - artifact_id: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$509095d16b8c:all
    content_hash: sha256:f2c1d06f4298f812e17b88a6602355856be25df4ed5fa680286d202bd476cb07
    path: transformer_Wavelet_f2c1d06f4298.joblib
    chain_path: s5.Wavelet[src=0,sub=2]
    source_index: 0
    pipeline_id: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77
    branch_path: []
    step_index: 5
    substep_index: 2
    fold_id: null
    artifact_type: transformer
    class_name: Wavelet
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 114
    created_at: '2026-01-08T17:48:00.849861+00:00'
    params: {}
    version: 3
  - artifact_id: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$9f79d59455ab:0
    content_hash: sha256:3f59ebe5794b2aca93c039371bd41a6dc6cd6d6f7bae3314d0a6d89dd94917f6
    path: model_PLSRegression_3f59ebe5794b.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 157060
    created_at: '2026-01-08T17:48:01.359913+00:00'
    params: {}
    version: 3
  - artifact_id: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$9f79d59455ab:1
    content_hash: sha256:9103c3915c448841a0aa9fba3a9f9c34d68fb620cfccd3c20da4ac1075eacb5a
    path: model_PLSRegression_9103c3915c44.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 157325
    created_at: '2026-01-08T17:48:01.363667+00:00'
    params: {}
    version: 3
  - artifact_id: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$9f79d59455ab:2
    content_hash: sha256:b66ea8bb415b6faf2b040f4d830745135409456f6dd7a9a3f9690ec1d446fcf2
    path: model_PLSRegression_b66ea8bb415b.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 157334
    created_at: '2026-01-08T17:48:01.367341+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  a58095d3-3c7:
    trace_id: a58095d3-3c7
    pipeline_uid: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77
    created_at: '2026-01-08T17:48:00.688246+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 6.054162979125977
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 5.455255508422852
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 91.8433666229248
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 22.166013717651367
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: Detrend, None, SavitzkyGolay (+1)
      operator_config:
        feature_augmentation:
        - nirs4all.operators.transforms.signal.Detrend
        - null
        - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
          params:
            window_length: 15
            deriv: 1
        - class: nirs4all.operators.transforms.nirs.Wavelet
          params:
            wavelet: coif3
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$51eb708c8a1f:all
        - 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$eeb09d32a26b:all
        - 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$509095d16b8c:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$51eb708c8a1f:all
            - 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$eeb09d32a26b:all
            - 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$509095d16b8c:all
        by_source:
          0:
          - 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$51eb708c8a1f:all
          - 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$eeb09d32a26b:all
          - 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$509095d16b8c:all
        by_chain:
          s5.Detrend[src=0,sub=0]: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$51eb708c8a1f:all
          s5.SavitzkyGolay[src=0,sub=1]: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$eeb09d32a26b:all
          s5.Wavelet[src=0,sub=2]: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$509095d16b8c:all
        metadata:
          class_name: Wavelet
          name: Wavelet_3
      branch_path: []
      branch_name: ''
      duration_ms: 63.36355209350586
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.Detrend[src=0,sub=0]
      - s5.SavitzkyGolay[src=0,sub=1]
      - s5.Wavelet[src=0,sub=2]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 2304
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 4
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          error_score: .nan
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$9f79d59455ab:0
        - 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$9f79d59455ab:1
        - 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$9f79d59455ab:0
          1: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$9f79d59455ab:1
          2: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$9f79d59455ab:0
            - 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$9f79d59455ab:1
            - 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0385_PLS_PP_SELECTION_NO_SAVE_6baf77$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 516.6134834289551
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 2304
      output_shape:
      - 60
      - 2304
      input_features_shape:
      - - 60
        - 4
        - 576
      output_features_shape:
      - - 60
        - 4
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: raw|Detr|SG|Wavelet
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_6baf77
      n_steps: 6
      n_artifacts: 7
