uid: 37445140-7446-4afc-aede-5e1ebadcce3f
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: diesel_d4052_395_pengks
created_at: '2025-12-12T13:03:54.787311+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T13:03:54.854192+00:00'
  step: 1
- hash: sha256:f2cd2ff91afa18b0c2aba62eb0d31275bdafd2d585358c565aa68ff38f16cf65
  name: y_StandardScaler
  path: StandardScaler_f2cd2f.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 444
  saved_at: '2025-12-12T13:03:55.066897+00:00'
  step: 4
- hash: sha256:bd9a2a4557c5bfe5c8581ba4b33d0d137f704888377d915db8b226bc95732cc7
  name: StandardScaler_1
  path: StandardScaler_bd9a2a.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9263
  saved_at: '2025-12-12T13:03:55.073235+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T13:03:55.087380+00:00'
  step: 6
- hash: sha256:14277eb7b1f5b7062bd8f152a392a86d81a2bfe3c17beee9c744a39a2e844a76
  name: PCA_1
  path: PCA_14277e.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 20170
  saved_at: '2025-12-12T13:03:55.139655+00:00'
  step: 7
- hash: sha256:9d712e01e5246372efb886c41a2c85737fcd7a662fae7bb2fad1dfa78d5c0c05
  name: StandardScaler_1
  path: StandardScaler_9d712e.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 675
  saved_at: '2025-12-12T13:03:55.191569+00:00'
  step: 8
- hash: sha256:e0df57e41c735dedcdf3b9b005fb28a065cec55af2a6ba7ac5a5cad4bb760229
  name: PowerTransformer_1
  path: PowerTransformer_e0df57.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 908
  saved_at: '2025-12-12T13:03:55.227781+00:00'
  step: 9
- hash: sha256:a615b8b062dc5194baa41b6ca13aa7275a86a92f680b411f928fedd506a3832b
  name: AutoGluon_1.pkl
  path: TabularPredictor_a615b8.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 14161
  saved_at: '2025-12-12T13:04:31.505755+00:00'
  step: 10
- hash: sha256:1f140fc8216a1ff7c8e64352931f692ece904b4b714c04d3fbff83a61248b201
  name: AutoGluon_2.pkl
  path: TabularPredictor_1f140f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 14170
  saved_at: '2025-12-12T13:04:31.506064+00:00'
  step: 10
- hash: sha256:3b00b8a14c11c93811c4a7471bb00f0beb573742cfb14190d07a0c824412a43c
  name: AutoGluon_3.pkl
  path: TabularPredictor_3b00b8.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 14152
  saved_at: '2025-12-12T13:04:31.506332+00:00'
  step: 10
- hash: sha256:228502a8806506936b753e83fe23e6ca975d6aa8c9a54fc8f26bfcb8d99bac1c
  name: TabPFN_1.pkl
  path: TabPFNRegressor_228502.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41466479
  saved_at: '2025-12-12T13:04:46.784118+00:00'
  step: 11
- hash: sha256:4e825c6ddb2fb3da1ce5714d2eafa13d6fbe9d4e27f18f46d51584c2c384c542
  name: TabPFN_2.pkl
  path: TabPFNRegressor_4e825c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41466479
  saved_at: '2025-12-12T13:04:46.838845+00:00'
  step: 11
- hash: sha256:4751fc0a2fb8934266bbd35c7c3a98b406548b90dd041683805bcfe8b650fa58
  name: TabPFN_3.pkl
  path: TabPFNRegressor_4751fc.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41466479
  saved_at: '2025-12-12T13:04:46.892234+00:00'
  step: 11
- hash: sha256:e184ca5a568f9544d998dc4b62eac7d9793b079b06ecc71240193bb3e4f82c46
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_e184ca.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41466516
  saved_at: '2025-12-12T13:05:18.074769+00:00'
  step: 12
- hash: sha256:34cd4050f3427c50ca63afccf5bd32e0e6a34ec9c9ebafeb157cde007d6f453a
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_34cd40.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41466516
  saved_at: '2025-12-12T13:05:18.127324+00:00'
  step: 12
- hash: sha256:303dd37ce771c0573746ce5d647e25fe2a12db28eb7971fee72a6bfb42847707
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_303dd3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41466516
  saved_at: '2025-12-12T13:05:18.180185+00:00'
  step: 12
predictions: []
