uid: 174bb9f8-bb2b-4d4f-9518-2918f7a2da9a
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: alpine_n_552_robustnessfennoscandia
created_at: '2026-01-07T09:37:30.670829+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:6fad93a0e497c69beabeda8f5151735441edf9b93933632b811f33b2a2f357f5
  name: ASLSBaseline_1
  path: ASLSBaseline_6fad93.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2026-01-07T09:37:30.980157+00:00'
  step: 1
- hash: sha256:642f394a7766e5333f271624ec7fc92e9b013d0a2e6ee06f47acbb24d67fbe31
  name: PCA_1
  path: PCA_642f39.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 137797
  saved_at: '2026-01-07T09:37:31.150841+00:00'
  step: 4
- hash: sha256:1394a04a5da7284a782f13411eaaf1947df87c52609574a2dc09d9f8bfa83515
  name: AutoGluon_1.pkl
  path: TabularPredictor_1394a0.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 15594
  saved_at: '2026-01-07T09:37:53.994711+00:00'
  step: 5
- hash: sha256:c37a943b0126abce8c76ba17acd7c8516c10891ae3fac6ed14779629eaf572e4
  name: AutoGluon_2.pkl
  path: TabularPredictor_c37a94.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 15594
  saved_at: '2026-01-07T09:37:53.995267+00:00'
  step: 5
- hash: sha256:bdf60290fe3d71d5feda56bd5251fc8843750906792bffa2f36ea7597a674907
  name: AutoGluon_3.pkl
  path: TabularPredictor_bdf602.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 15576
  saved_at: '2026-01-07T09:37:53.995742+00:00'
  step: 5
- hash: sha256:8b51ea00b56fcdafdcdeb9a3b58cb0b137ecdb72fcb27dbdfc389e4897cf8623
  name: TabPFN_1.pkl
  path: TabPFNRegressor_8b51ea.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41506574
  saved_at: '2026-01-07T09:38:11.630546+00:00'
  step: 6
- hash: sha256:c32a8195d853a51dafc0501333cbc454dc2b1dec5e098ca8c03a79e3bfcbfa55
  name: TabPFN_2.pkl
  path: TabPFNRegressor_c32a81.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41510094
  saved_at: '2026-01-07T09:38:11.687872+00:00'
  step: 6
- hash: sha256:dd6bfbc9c6ad377b7a09908d7d0274bc706c6cd95a9d21d028aa4e5826f1b033
  name: TabPFN_3.pkl
  path: TabPFNRegressor_dd6bfb.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41510092
  saved_at: '2026-01-07T09:38:11.745588+00:00'
  step: 6
- hash: sha256:a0a5ebc54508fc25df00c3e6a609dc24ca60b4f26a715bc036418fd900dd8ee6
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_a0a5eb.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41506609
  saved_at: '2026-01-07T09:38:47.789461+00:00'
  step: 7
- hash: sha256:48983b82b977f96a4a6505508100ef1b2e8b40365864172b29202920e26f1c81
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_48983b.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41510131
  saved_at: '2026-01-07T09:38:47.848099+00:00'
  step: 7
- hash: sha256:eb9e6edc2f853a0e337634f0fb9dc59dadc40ea7afc44e43405b75416f99f873
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_eb9e6e.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41510131
  saved_at: '2026-01-07T09:38:47.906483+00:00'
  step: 7
predictions: []
