uid: b52825d9-f7f0-4160-a3d5-78fc583ffa5b
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: diesel_t_256_hlb_a
created_at: '2025-12-12T12:58:42.864365+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T12:58:42.905970+00:00'
  step: 1
- hash: sha256:20ae615bb249cab3aae11ae663b35684c6a9c11a4504b4bdcdc805cb3daf8349
  name: y_StandardScaler
  path: StandardScaler_20ae61.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 442
  saved_at: '2025-12-12T12:58:43.000055+00:00'
  step: 4
- hash: sha256:eb34356b753c4d0c559b128f6092a5428e7af480c8e454401c0df0e95f689991
  name: StandardScaler_1
  path: StandardScaler_eb3435.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9198
  saved_at: '2025-12-12T12:58:43.005158+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T12:58:43.013149+00:00'
  step: 6
- hash: sha256:b0f6b22bbcae7794dbf0d97995ca0d1d68ffaf2ef1a257246d193cd9255e5d94
  name: PCA_1
  path: PCA_b0f6b2.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 7862
  saved_at: '2025-12-12T12:58:43.040942+00:00'
  step: 7
- hash: sha256:c9c61baef3da301697155289ab087c36d2646a89e02e12d3e7d75aae07799c4d
  name: StandardScaler_1
  path: StandardScaler_c9c61b.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 519
  saved_at: '2025-12-12T12:58:43.081006+00:00'
  step: 8
- hash: sha256:518b816f775fd9e706c6642ec57f7151dc13f7365761564454902826dd861d9a
  name: PowerTransformer_1
  path: PowerTransformer_518b81.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 668
  saved_at: '2025-12-12T12:58:43.121126+00:00'
  step: 9
- hash: sha256:40f744fdefe27da2d5f8b7c09357ac3e92d98e8a2e13c761f983c61b9475c3ac
  name: AutoGluon_1.pkl
  path: TabularPredictor_40f744.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11196
  saved_at: '2025-12-12T12:59:03.090186+00:00'
  step: 10
- hash: sha256:8fb5323611f6c290a103d41e128f3ee79012d0d6ac7dd9f6532becf5f72d2e55
  name: AutoGluon_2.pkl
  path: TabularPredictor_8fb532.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2025-12-12T12:59:03.090491+00:00'
  step: 10
- hash: sha256:fd4f700c1b7d57ac60b87ab78e380255db749841aca1b1ba89f7722c9c4bbc4d
  name: AutoGluon_3.pkl
  path: TabularPredictor_fd4f70.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2025-12-12T12:59:03.090754+00:00'
  step: 10
- hash: sha256:afedb6a9d98d7ef8551280c7655c0ea7403765e874757ad93fa7b5ef4ca0cadf
  name: TabPFN_1.pkl
  path: TabPFNRegressor_afedb6.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41044566
  saved_at: '2025-12-12T12:59:10.198467+00:00'
  step: 11
- hash: sha256:6b89fe664882d4dac1b2768b2561ebc3331d021009a195737931547cd41dc24d
  name: TabPFN_2.pkl
  path: TabPFNRegressor_6b89fe.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41044566
  saved_at: '2025-12-12T12:59:10.253512+00:00'
  step: 11
- hash: sha256:9dcfc5b92f9b0cb1be6d7e4721504df0dc5476e261ef71d418c95e254682e4f0
  name: TabPFN_3.pkl
  path: TabPFNRegressor_9dcfc5.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41044566
  saved_at: '2025-12-12T12:59:10.307302+00:00'
  step: 11
- hash: sha256:1bf23bdfad9b53bf65980f5d19b57564bbb74bfbf2d59ed619bd4710a1743407
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_1bf23b.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41044603
  saved_at: '2025-12-12T12:59:23.736384+00:00'
  step: 12
- hash: sha256:651aee32c418a7eafde945898e5576fa1bb84c1045fc47a179972c0145a02c7d
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_651aee.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41044603
  saved_at: '2025-12-12T12:59:23.791224+00:00'
  step: 12
- hash: sha256:0c12a341c4efd3b16566aa2d6cd1c1803c28e41063b47c83901f4718c6efffa2
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_0c12a3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41044603
  saved_at: '2025-12-12T12:59:23.845165+00:00'
  step: 12
predictions: []
