schema_version: '2.0'
uid: f493abb2-f09c-4ba3-a918-0a5af09a93d3
pipeline_id: 0001_SOTA_033cb7
name: SOTA_033cb7
dataset: diesel_d_263_b_a
created_at: '2026-01-07T20:19:26.612441+00:00'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0001_SOTA_033cb7$bb12ee38a89c:all
    content_hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
    path: transformer_ASLSBaseline_95c7c1d7b88a.joblib
    chain_path: s1.ASLSBaseline[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 1
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: ASLSBaseline
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 216
    created_at: '2026-01-07T20:19:26.653851+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_033cb7$dfc251e3a6b4:all
    content_hash: sha256:5c6ff325e7a8a4a2bc8829ff6d45617ebdc39ad51ef885a1fc306bfcfab91d4b
    path: transformer_PCA_5c6ff325e7a8.joblib
    chain_path: s3.PCA[src=0,sub=0]
    source_index: 0
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 3
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: PCA
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 8181
    created_at: '2026-01-07T20:19:26.688953+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_033cb7$9d98c9f5abc5:0
    content_hash: sha256:90cc5f2e150c08b85ae26e9238b5496837a9f18b06831df825403366fdebb028
    path: model_TabPFNRegressor_90cc5f2e150c.pkl
    chain_path: s4.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 4
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 41031815
    created_at: '2026-01-07T20:19:33.352972+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_033cb7$9d98c9f5abc5:1
    content_hash: sha256:acd16bbf5de83c948bc963a1bf3a634546a4bfb7d27d2fa55c0ae03034cb09e2
    path: model_TabPFNRegressor_acd16bbf5de8.pkl
    chain_path: s4.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 4
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 41032855
    created_at: '2026-01-07T20:19:33.415652+00:00'
    params: {}
    version: 3
  - artifact_id: 0001_SOTA_033cb7$9d98c9f5abc5:2
    content_hash: sha256:f8b1122f3c68be0317bd82c589f15f9fe904057b53f8a72629ccdf4255428039
    path: model_TabPFNRegressor_f8b1122f3c68.pkl
    chain_path: s4.TabPFNRegressor[sub=0]
    source_index: null
    pipeline_id: 0001_SOTA_033cb7
    branch_path: []
    step_index: 4
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: TabPFNRegressor
    custom_name: TabPFN-real
    depends_on: []
    format: cloudpickle
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 41032885
    created_at: '2026-01-07T20:19:33.477856+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  7f4b27b0-fbb:
    trace_id: 7f4b27b0-fbb
    pipeline_uid: 0001_SOTA_033cb7
    created_at: '2026-01-07T20:19:26.613203+00:00'
    steps:
    - step_index: 1
      operator_type: transform
      operator_class: ASLSBaseline
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_033cb7$bb12ee38a89c:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_033cb7$bb12ee38a89c:all
        by_source:
          0:
          - 0001_SOTA_033cb7$bb12ee38a89c:all
        by_chain:
          s1.ASLSBaseline[src=0,sub=0]: 0001_SOTA_033cb7$bb12ee38a89c:all
        metadata:
          class_name: ASLSBaseline
          name: ASLSBaseline_1
      branch_path: []
      branch_name: ''
      duration_ms: 46.167850494384766
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s1.ASLSBaseline[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 243
      - 401
      output_shape:
      - 243
      - 401
      input_features_shape:
      - - 243
        - 1
        - 401
      output_features_shape:
      - - 243
        - 1
        - 401
    - step_index: 2
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 18.78523826599121
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 243
      - 401
      output_shape:
      - 243
      - 401
      input_features_shape:
      - - 243
        - 1
        - 401
      output_features_shape:
      - - 243
        - 1
        - 401
    - step_index: 3
      operator_type: operator
      operator_class: PCA
      operator_config:
        class: sklearn.decomposition._pca.PCA
        params:
          n_components: 0.99
          whiten: true
          random_state: 42
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_033cb7$dfc251e3a6b4:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_033cb7$dfc251e3a6b4:all
        by_source:
          0:
          - 0001_SOTA_033cb7$dfc251e3a6b4:all
        by_chain:
          s3.PCA[src=0,sub=0]: 0001_SOTA_033cb7$dfc251e3a6b4:all
        metadata:
          class_name: PCA
          name: PCA_1
      branch_path: []
      branch_name: ''
      duration_ms: 33.72764587402344
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.PCA[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 243
      - 401
      output_shape:
      - 243
      - 4
      input_features_shape:
      - - 243
        - 1
        - 401
      output_features_shape:
      - - 243
        - 1
        - 4
    - step_index: 4
      operator_type: model
      operator_class: TabPFNRegressor
      operator_config:
        model:
          class: tabpfn.regressor.TabPFNRegressor
          params:
            n_estimators: 16
            model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
            device: cpu
            ignore_pretraining_limits: true
            random_state: 42
        name: TabPFN-real
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0001_SOTA_033cb7$9d98c9f5abc5:0
        - 0001_SOTA_033cb7$9d98c9f5abc5:1
        - 0001_SOTA_033cb7$9d98c9f5abc5:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0001_SOTA_033cb7$9d98c9f5abc5:0
          1: 0001_SOTA_033cb7$9d98c9f5abc5:1
          2: 0001_SOTA_033cb7$9d98c9f5abc5:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0001_SOTA_033cb7$9d98c9f5abc5:0
            - 0001_SOTA_033cb7$9d98c9f5abc5:1
            - 0001_SOTA_033cb7$9d98c9f5abc5:2
        by_source: {}
        by_chain:
          s4.TabPFNRegressor[sub=0]: 0001_SOTA_033cb7$9d98c9f5abc5:2
        metadata:
          class_name: TabPFNRegressor
          custom_name: TabPFN-real
      branch_path: []
      branch_name: ''
      duration_ms: 12400.148391723633
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s4.TabPFNRegressor[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 243
      - 4
      output_shape:
      - 243
      - 4
      input_features_shape:
      - - 243
        - 1
        - 4
      output_features_shape:
      - - 243
        - 1
        - 4
    model_step_index: 4
    fold_weights: null
    preprocessing_chain: ASLSBaseline>PCA
    metadata:
      dataset: diesel_d_263_b_a
      config_name: SOTA_033cb7
      n_steps: 4
      n_artifacts: 5
