uid: b27a792c-64ea-4b25-a624-9003ef65cfa1
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: diesel_bp50_246_b_a
created_at: '2026-01-07T11:20:05.976321+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2026-01-07T11:20:06.015885+00:00'
  step: 1
- hash: sha256:dd57f29adb414fd105ca32e33a28688b90b30628abb1c0dfb5c8fda6dac6beeb
  name: PCA_1
  path: PCA_dd57f2.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 8195
  saved_at: '2026-01-07T11:20:06.061822+00:00'
  step: 4
- hash: sha256:b4f6a05f28d7e6cf756dd1fcdd84e24fb96b7f98747e86aa20360e9c54f070cd
  name: AutoGluon_1.pkl
  path: TabularPredictor_b4f6a0.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11271
  saved_at: '2026-01-07T11:20:17.097529+00:00'
  step: 5
- hash: sha256:6998c2d87948625472261ebdaea25ade1cd2b4e147081c4e042c6df0c9e2578b
  name: AutoGluon_2.pkl
  path: TabularPredictor_6998c2.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2026-01-07T11:20:17.097861+00:00'
  step: 5
- hash: sha256:3fff19ed05e3e3a89ac4efbc68ee44f896b1ada3acc80a2020d7e28983cb2b48
  name: AutoGluon_3.pkl
  path: TabularPredictor_3fff19.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11262
  saved_at: '2026-01-07T11:20:17.098183+00:00'
  step: 5
- hash: sha256:26fcb21a5b18375a424d45dd41500eb389522f365468b695a8914858dc6c49bb
  name: TabPFN_1.pkl
  path: TabPFNRegressor_26fcb2.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41026518
  saved_at: '2026-01-07T11:20:24.988351+00:00'
  step: 6
- hash: sha256:33c1377571184b91706909869305bc3be772a98916cccfa18a49510c2297ad7a
  name: TabPFN_2.pkl
  path: TabPFNRegressor_33c137.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41026518
  saved_at: '2026-01-07T11:20:25.049765+00:00'
  step: 6
- hash: sha256:52f8d3deea31aa261f34d165df17891ac397b2fb731d79628164b57abd1f4e32
  name: TabPFN_3.pkl
  path: TabPFNRegressor_52f8d3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41027542
  saved_at: '2026-01-07T11:20:25.108554+00:00'
  step: 6
- hash: sha256:b6477df25393fa143d750db2ae1306c2c1f9d0a1fec0ae38eea404df8c299af4
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_b6477d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41026555
  saved_at: '2026-01-07T11:20:37.138802+00:00'
  step: 7
- hash: sha256:c566ebd3fb0b20b9d708b91f8e4e41e0bac1126e1ed1d2b6d0629d50a2fca47b
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_c566eb.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41026555
  saved_at: '2026-01-07T11:20:37.197365+00:00'
  step: 7
- hash: sha256:b96b6156e870fff8f582a2549095f3860eeb9763c81b28727fb33bcd2d747f6e
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_b96b61.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41027579
  saved_at: '2026-01-07T11:20:37.255225+00:00'
  step: 7
predictions: []
