uid: bcfc4ffe-4039-4155-827d-f4e5e79d3fca
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: poultry_manure_p2o5_ks
created_at: '2025-12-12T08:01:17.906535+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:125d94dee500492a3bdb8dd8b9fa106b8b2b34e5f42944e4b15d55960ffb73d1
  name: ASLSBaseline_1
  path: ASLSBaseline_125d94.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T08:01:17.955491+00:00'
  step: 1
- hash: sha256:8a51d37a70c61e26935165145efa5d289179f586c1ce3a9106d1e3e16b1d5389
  name: y_StandardScaler
  path: StandardScaler_8a51d3.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 442
  saved_at: '2025-12-12T08:01:18.020882+00:00'
  step: 4
- hash: sha256:b81dc395d1dd80940342c9d3237f852b94dbd4704afba86f452dc9b2bf4d63c4
  name: StandardScaler_1
  path: StandardScaler_b81dc3.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 21264
  saved_at: '2025-12-12T08:01:18.026629+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T08:01:18.038370+00:00'
  step: 6
- hash: sha256:5862dbfd9bfbdf7f0cbfc1c544cd73bf5e8f61dea119f9b4783de94b26d16912
  name: PCA_1
  path: PCA_5862db.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 111761
  saved_at: '2025-12-12T08:01:18.141444+00:00'
  step: 7
- hash: sha256:839f98ae517f3aa6a02b3903217ecb1645dff11963b361a4c3c6a436ae95334c
  name: StandardScaler_1
  path: StandardScaler_839f98.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 944
  saved_at: '2025-12-12T08:01:18.168791+00:00'
  step: 8
- hash: sha256:d84f5cbd3f747a7ec3dc5ab2623a45bce39a0502f058affcadd8ac7b3caed0b7
  name: PowerTransformer_1
  path: PowerTransformer_d84f5c.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1339
  saved_at: '2025-12-12T08:01:18.198566+00:00'
  step: 9
- hash: sha256:4740b20cda021670ccd311e05cc8fff0b65252238703efe13f1e388d6499c019
  name: AutoGluon_1.pkl
  path: TabularPredictor_4740b2.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 20213
  saved_at: '2025-12-12T08:01:27.943866+00:00'
  step: 10
- hash: sha256:0d658a4dc5a0e218282dd9e37c8dadb3a054a55eebd9fc1ea6d394b09de53da4
  name: AutoGluon_2.pkl
  path: TabularPredictor_0d658a.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 20195
  saved_at: '2025-12-12T08:01:27.944211+00:00'
  step: 10
- hash: sha256:b04d01e31793240b0f40812207816d3f985f1628cd04d04828f7f171547257d2
  name: AutoGluon_3.pkl
  path: TabularPredictor_b04d01.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 20195
  saved_at: '2025-12-12T08:01:27.944531+00:00'
  step: 10
- hash: sha256:953340f4ee7cd4e8ad099e187ff229c577bbc231838986dfbd9a4cd4d1085ba0
  name: TabPFN_1.pkl
  path: TabPFNRegressor_953340.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41404004
  saved_at: '2025-12-12T08:01:42.439252+00:00'
  step: 11
- hash: sha256:5a5a2c482129bc4c9f9681d87451839c04e6b85c565e5970cee42fbdc6288743
  name: TabPFN_2.pkl
  path: TabPFNRegressor_5a5a2c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41410208
  saved_at: '2025-12-12T08:01:42.484371+00:00'
  step: 11
- hash: sha256:27d5a798cedf6c8155a904743910f4320015b648d338726eda3839bec9df4200
  name: TabPFN_3.pkl
  path: TabPFNRegressor_27d5a7.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41410210
  saved_at: '2025-12-12T08:01:42.529663+00:00'
  step: 11
- hash: sha256:a142f4f9a519e4cd4374f7156df240bab72c7c5cc280230020f30f4b0eef78a0
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_a142f4.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41404035
  saved_at: '2025-12-12T08:02:10.495917+00:00'
  step: 12
- hash: sha256:8f0eea541a9ace4f76ff4ef1b8cb9419856b8a9e4ffa220f44b17fa606bd2809
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_8f0eea.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41410247
  saved_at: '2025-12-12T08:02:10.544922+00:00'
  step: 12
- hash: sha256:b546545cb433a057aed5c2d42f4b2e141384c140096e17d1688ebfe70ce635d3
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_b54654.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41410249
  saved_at: '2025-12-12T08:02:10.593879+00:00'
  step: 12
predictions: []
