uid: d2b386c7-de84-4864-9612-3b13d3f4254c
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: beer_originalextract_60_ks
created_at: '2025-12-12T12:52:04.509713+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:b4553481208e6d47e63ea320aba96e6244c0562bb0ff417a85f9518d4d8b3223
  name: ASLSBaseline_1
  path: ASLSBaseline_b45534.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2025-12-12T12:52:04.523102+00:00'
  step: 1
- hash: sha256:0b527dc6afe5fe4852109a07aa65b60ae57907dad06d920e9eccc3f4c44fb5d3
  name: y_StandardScaler
  path: StandardScaler_0b527d.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 438
  saved_at: '2025-12-12T12:52:04.562572+00:00'
  step: 4
- hash: sha256:a48c44c96eb6e87f190840766e4149504ee78eb8127eb9828168c8ca86ff894e
  name: StandardScaler_1
  path: StandardScaler_a48c44.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 12079
  saved_at: '2025-12-12T12:52:04.575483+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T12:52:04.589138+00:00'
  step: 6
- hash: sha256:bb5b26cec46f5da49aee6a23229eaf3d1e9805d3f4eff8e66f3cdf212bf08a31
  name: PCA_1
  path: PCA_bb5b26.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 75545
  saved_at: '2025-12-12T12:52:04.604471+00:00'
  step: 7
- hash: sha256:4f40eaff61acb828290589be013dcc6a2f73be6e803827ede6285f625e3d81cd
  name: StandardScaler_1
  path: StandardScaler_4f40ea.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 974
  saved_at: '2025-12-12T12:52:04.640248+00:00'
  step: 8
- hash: sha256:30bb9d168e6959636b7b3a06624c05e4276032ee4e96b1d70294bf3aaaa6a819
  name: PowerTransformer_1
  path: PowerTransformer_30bb9d.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1443
  saved_at: '2025-12-12T12:52:04.698675+00:00'
  step: 9
- hash: sha256:87e1fdb3615c5985c34e2945478999ddac2368c71a0c32edfead065f7cc41683
  name: AutoGluon_1.pkl
  path: TabularPredictor_87e1fd.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 21975
  saved_at: '2025-12-12T12:53:03.647959+00:00'
  step: 10
- hash: sha256:b713d8ed3e54abe48461c4f1ffea61399e36db3636dd57e1e84ae943c74b6d8b
  name: AutoGluon_2.pkl
  path: TabularPredictor_b713d8.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 21975
  saved_at: '2025-12-12T12:53:03.648488+00:00'
  step: 10
- hash: sha256:95991b32d33a07a3c8b95e2fa9c385f821f80f1663d9cbdfe9885031441ace61
  name: AutoGluon_3.pkl
  path: TabularPredictor_95991b.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 21965
  saved_at: '2025-12-12T12:53:03.648982+00:00'
  step: 10
- hash: sha256:9beb18540e9d4ef3eb5ea4e7a001b5c714e9e71c994c25cb41e598ea9fbff70e
  name: TabPFN_1.pkl
  path: TabPFNRegressor_9beb18.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41163380
  saved_at: '2025-12-12T12:53:14.216153+00:00'
  step: 11
- hash: sha256:cb81d8a1624f6bb3126fe0bf08e431e71ed219cd929cef790fdc9ddc8d79034f
  name: TabPFN_2.pkl
  path: TabPFNRegressor_cb81d8.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41170292
  saved_at: '2025-12-12T12:53:14.269532+00:00'
  step: 11
- hash: sha256:389dc9cfc453c2fdde78c835db8dacb88d227d9a115bcda2e879641790f46dbd
  name: TabPFN_3.pkl
  path: TabPFNRegressor_389dc9.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41170292
  saved_at: '2025-12-12T12:53:14.321491+00:00'
  step: 11
- hash: sha256:0655d268fa245599d5644d416f3d9433cab221b6658bcf8428f07dd67ea04bc2
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_0655d2.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41163417
  saved_at: '2025-12-12T12:53:33.228493+00:00'
  step: 12
- hash: sha256:55b562fdf464bb714d3133af2a3b2af96caecf68d3106da1ab72c9f3a97abdd9
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_55b562.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41170329
  saved_at: '2025-12-12T12:53:33.281474+00:00'
  step: 12
- hash: sha256:567d7c27402ba8e101a7e61d6f95633ba67443b5a3198a75355a65aff1cae1c3
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_567d7c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41170329
  saved_at: '2025-12-12T12:53:33.337460+00:00'
  step: 12
predictions: []
