uid: 99d7d93a-da1a-41ee-ba9f-c189d66e7ac7
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: diesel_t_256_b_a
created_at: '2025-12-12T12:55:50.957675+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T12:55:51.010469+00:00'
  step: 1
- hash: sha256:7d4ce3de5815f210e158428283881eac59899dcedffdd0ec9008ee205e3bac76
  name: y_StandardScaler
  path: StandardScaler_7d4ce3.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 443
  saved_at: '2025-12-12T12:55:51.120877+00:00'
  step: 4
- hash: sha256:4d257d230f78341a1cf0d04f312b683d01539780ccda4af3345926dae8f65752
  name: StandardScaler_1
  path: StandardScaler_4d257d.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9151
  saved_at: '2025-12-12T12:55:51.128267+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T12:55:51.139451+00:00'
  step: 6
- hash: sha256:b7439f6f4373db4fcf0e48d7eeccf16ae97f3ef61bf4f6eadd3f3b23845535c3
  name: PCA_1
  path: PCA_b7439f.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 7848
  saved_at: '2025-12-12T12:55:51.180533+00:00'
  step: 7
- hash: sha256:6c282ae52ae338848da8bbe5873f9db5edffcc2a72a673c2158a2b64d4128e0f
  name: StandardScaler_1
  path: StandardScaler_6c282a.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 515
  saved_at: '2025-12-12T12:55:51.236853+00:00'
  step: 8
- hash: sha256:71fb18aece0a59b8eb6e6fc9b8bd15fcf5c08392c4342ef688a13348bf75c0cb
  name: PowerTransformer_1
  path: PowerTransformer_71fb18.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 665
  saved_at: '2025-12-12T12:55:51.260929+00:00'
  step: 9
- hash: sha256:000f35c5b667540b09b884cb77d8e307964040d238c6b7504f124adca53afe0d
  name: AutoGluon_1.pkl
  path: TabularPredictor_000f35.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11262
  saved_at: '2025-12-12T12:56:01.938010+00:00'
  step: 10
- hash: sha256:52391fb8a0e2fafbb7dbbd6a306ff74e9090084ca01f90a6a9f4d03c20f4690f
  name: AutoGluon_2.pkl
  path: TabularPredictor_52391f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2025-12-12T12:56:01.938285+00:00'
  step: 10
- hash: sha256:ef575fb5a7fb615736089cf645686b1540038d79f566c4db59375be27f178915
  name: AutoGluon_3.pkl
  path: TabularPredictor_ef575f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11196
  saved_at: '2025-12-12T12:56:01.938555+00:00'
  step: 10
- hash: sha256:58bdc3b6edac8df6f0780d82236295cddee7ef967b0245446510a37545167465
  name: TabPFN_1.pkl
  path: TabPFNRegressor_58bdc3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41029590
  saved_at: '2025-12-12T12:56:07.925259+00:00'
  step: 11
- hash: sha256:7baf152b53c953d044f8a1def5b8d361a594a13311213847ade13966a3ac786c
  name: TabPFN_2.pkl
  path: TabPFNRegressor_7baf15.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41030614
  saved_at: '2025-12-12T12:56:07.980817+00:00'
  step: 11
- hash: sha256:358a842cbf1f3139b7435389a53738818debdf76105a8ad7f05ab3056f8bf567
  name: TabPFN_3.pkl
  path: TabPFNRegressor_358a84.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41030614
  saved_at: '2025-12-12T12:56:08.035882+00:00'
  step: 11
- hash: sha256:009ff9df2abb4cdf78db4f44d46a34bdfa7ab74e2b52332719986eb5d7722c75
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_009ff9.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41029627
  saved_at: '2025-12-12T12:56:20.629685+00:00'
  step: 12
- hash: sha256:5987789bc97c6fe2995c4a8910beccc06c8d0bf70dc9b37ea539578ee22bbbab
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_598778.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41030651
  saved_at: '2025-12-12T12:56:20.687541+00:00'
  step: 12
- hash: sha256:77b3cdbdc03b230b24dcbc1db73731e20a6265b1319620746a4a1c73de48e87e
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_77b3cd.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41030651
  saved_at: '2025-12-12T12:56:20.746561+00:00'
  step: 12
predictions: []
