uid: 6ba86710-38be-464b-8a17-c033ab420739
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: diesel_f_251_hla_b
created_at: '2025-12-12T08:31:59.123464+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T08:31:59.165020+00:00'
  step: 1
- hash: sha256:4feedb6981b0a193fb985eec37ab005fe0d566b36bc6dee619ac09c6fb51ad9f
  name: y_StandardScaler
  path: StandardScaler_4feedb.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 444
  saved_at: '2025-12-12T08:31:59.351015+00:00'
  step: 4
- hash: sha256:023b2c0677dd7bdf636e0f362cb022226b9ff9d4547f2bb8dd831f7d7cf51e27
  name: StandardScaler_1
  path: StandardScaler_023b2c.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9012
  saved_at: '2025-12-12T08:31:59.361041+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T08:31:59.384462+00:00'
  step: 6
- hash: sha256:2bdd9fb6a3bb23509ed4a874cb30b558d458f6bebef6998610d2c912f35753e7
  name: PCA_1
  path: PCA_2bdd9f.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9303
  saved_at: '2025-12-12T08:31:59.431018+00:00'
  step: 7
- hash: sha256:9db5c3d836e1380c00acf297f626a82b01946c25dab914422eeab49671fd6126
  name: StandardScaler_1
  path: StandardScaler_9db5c3.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 530
  saved_at: '2025-12-12T08:31:59.471169+00:00'
  step: 8
- hash: sha256:a923171998dc9ed0c23c4d97046f2c0e0125f8cc7986f34005bf5a2e75f8ad44
  name: PowerTransformer_1
  path: PowerTransformer_a92317.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 691
  saved_at: '2025-12-12T08:31:59.491841+00:00'
  step: 9
- hash: sha256:d4891b05bfe1660f5678f70251cf54fa5ec4d3c1b673db1dc6ad3a6843d9b504
  name: AutoGluon_1.pkl
  path: TabularPredictor_d4891b.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11607
  saved_at: '2025-12-12T08:32:12.538533+00:00'
  step: 10
- hash: sha256:cc52e82d5dfcd48e71eded1ccdd9523cd13a6cb3c51d95cf5441ad732d552d4f
  name: AutoGluon_2.pkl
  path: TabularPredictor_cc52e8.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11616
  saved_at: '2025-12-12T08:32:12.539102+00:00'
  step: 10
- hash: sha256:0f58eb538d4cba8195f73fd4afa02157a49aaf792906365a1764badb88c6cd50
  name: AutoGluon_3.pkl
  path: TabularPredictor_0f58eb.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11688
  saved_at: '2025-12-12T08:32:12.539663+00:00'
  step: 10
- hash: sha256:95a6f0ae3be31af156a5e7458045b270dd96fa4abf76393192e8c3df655b0103
  name: TabPFN_1.pkl
  path: TabPFNRegressor_95a6f0.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41061052
  saved_at: '2025-12-12T08:32:21.983581+00:00'
  step: 11
- hash: sha256:524da28458f9a8906b3678008807e6a0698121881469198b807d512f50978e41
  name: TabPFN_2.pkl
  path: TabPFNRegressor_524da2.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41062268
  saved_at: '2025-12-12T08:32:22.026667+00:00'
  step: 11
- hash: sha256:cf088781cca11046a2a16b686da9ac401ffc5688d5ac5e095e1ca6562aac42cd
  name: TabPFN_3.pkl
  path: TabPFNRegressor_cf0887.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41062268
  saved_at: '2025-12-12T08:32:22.069474+00:00'
  step: 11
- hash: sha256:3c97f7bf0b1cc346031eac267dd02c2b18b3532590a74c80dd7366e6ed830ebe
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_3c97f7.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41061089
  saved_at: '2025-12-12T08:32:38.035939+00:00'
  step: 12
- hash: sha256:1fec0512435542f7997577f7ccf9bef79978a620ff651daa4397b3a3971d342d
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_1fec05.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41062305
  saved_at: '2025-12-12T08:32:38.079585+00:00'
  step: 12
- hash: sha256:12a67d1efbd703da0e076e9531cd5c2db78c7e079c52a9b660521ee2a637d8ce
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_12a67d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41062305
  saved_at: '2025-12-12T08:32:38.120790+00:00'
  step: 12
predictions: []
