uid: 4f8e7a70-519d-4ae8-a57f-dc41334178a7
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: alpine_p_291_robustnessfennoscandia
created_at: '2025-12-12T08:02:25.580887+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:6fad93a0e497c69beabeda8f5151735441edf9b93933632b811f33b2a2f357f5
  name: ASLSBaseline_1
  path: ASLSBaseline_6fad93.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2025-12-12T08:02:25.747226+00:00'
  step: 1
- hash: sha256:52c4d2f4a7b892a4d554a277bcb9c9547aad067c7246dc49a051a2229f8e1a17
  name: y_StandardScaler
  path: StandardScaler_52c4d2.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 446
  saved_at: '2025-12-12T08:02:25.889381+00:00'
  step: 4
- hash: sha256:e026ff771d93ebf0fa376b88beb7d42feaec0d0c5645a9b788e2b41560226e96
  name: StandardScaler_1
  path: StandardScaler_e026ff.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 46129
  saved_at: '2025-12-12T08:02:25.897950+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T08:02:25.908102+00:00'
  step: 6
- hash: sha256:e43770e72b5546759a5ffb10f4a565b74210df3c36f69a5e0f6bd81d915e91f6
  name: PCA_1
  path: PCA_e43770.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 206463
  saved_at: '2025-12-12T08:02:25.961865+00:00'
  step: 7
- hash: sha256:72b583e4ed6a6b71d98228a2e0fc883e4f8ac630e9236489d758c1124ca4a06d
  name: StandardScaler_1
  path: StandardScaler_72b583.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 926
  saved_at: '2025-12-12T08:02:26.003700+00:00'
  step: 8
- hash: sha256:684d6aaf9f6fffdb4faf4ac9daaba2eaf2d3ddc36541a0e5329cd94424813427
  name: PowerTransformer_1
  path: PowerTransformer_684d6a.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1254
  saved_at: '2025-12-12T08:02:26.044814+00:00'
  step: 9
- hash: sha256:0ef46e8bfe6a16702269939b11695f16641aff00e23cfd264c51d2491464ee99
  name: AutoGluon_1.pkl
  path: TabularPredictor_0ef46e.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 18807
  saved_at: '2025-12-12T08:02:38.713180+00:00'
  step: 10
- hash: sha256:f3ea0925b9aec50c09ef5f76366913bd14d1f49869cb2250bf566401e5b1e23a
  name: AutoGluon_2.pkl
  path: TabularPredictor_f3ea09.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 18780
  saved_at: '2025-12-12T08:02:38.713501+00:00'
  step: 10
- hash: sha256:5700176a581d350f8b36d517bdec896cb8bf1b465c229da7ff9ca517a7144e5d
  name: AutoGluon_3.pkl
  path: TabularPredictor_570017.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 18780
  saved_at: '2025-12-12T08:02:38.713782+00:00'
  step: 10
- hash: sha256:177e329aa0a0722183785948fbbf536766a6a8601d8bfff7b3b3c1fd628920c2
  name: TabPFN_1.pkl
  path: TabPFNRegressor_177e32.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41462162
  saved_at: '2025-12-12T08:02:55.336958+00:00'
  step: 11
- hash: sha256:fd9516c04647d2b45b1e5e1f218a22359b3171475f46d0cea38d7394795fc494
  name: TabPFN_2.pkl
  path: TabPFNRegressor_fd9516.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41467550
  saved_at: '2025-12-12T08:02:55.383417+00:00'
  step: 11
- hash: sha256:ebc28dca3f8ac8554d4c98d605750b5e78b6058c20672c63717a8dc3f2c4b3df
  name: TabPFN_3.pkl
  path: TabPFNRegressor_ebc28d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41467548
  saved_at: '2025-12-12T08:02:55.428464+00:00'
  step: 11
- hash: sha256:1b80f4b15597d64d6af7b66909ddaeaa0912199227670507e9de7faa67d93583
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_1b80f4.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41462207
  saved_at: '2025-12-12T08:03:30.423716+00:00'
  step: 12
- hash: sha256:5cd655c471dd8e6a64d07ae2aac284745a407fd2a1494ad71b1c155f1dd2a15b
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_5cd655.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41467577
  saved_at: '2025-12-12T08:03:30.470999+00:00'
  step: 12
- hash: sha256:0c52673ff3d18e9fe6ed65966bb19eb8ebd82e900166f1cffdd97992622fe2d5
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_0c5267.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41467585
  saved_at: '2025-12-12T08:03:30.517567+00:00'
  step: 12
predictions: []
