uid: 48645428-e34a-4c68-b354-3cf8bb984c56
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: diesel_v_252_hla_b
created_at: '2026-01-07T11:18:34.923814+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2026-01-07T11:18:34.965339+00:00'
  step: 1
- hash: sha256:b3acd08c14a1b2ef19d15950443255ebca91078ff53ffbeb84eedacba56475ca
  name: PCA_1
  path: PCA_b3acd0.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 6678
  saved_at: '2026-01-07T11:18:35.005413+00:00'
  step: 4
- hash: sha256:f6ef9d405aa269e5400e0b49ff8adfb2b98c9db32e51aff07c00f5b7193c0db6
  name: AutoGluon_1.pkl
  path: TabularPredictor_f6ef9d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 10851
  saved_at: '2026-01-07T11:18:46.243900+00:00'
  step: 5
- hash: sha256:99da20fc52d7ebaf8de404b8ca2b945c53cbe0f9eb2c122c08e9554c73ed38cf
  name: AutoGluon_2.pkl
  path: TabularPredictor_99da20.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 10917
  saved_at: '2026-01-07T11:18:46.244182+00:00'
  step: 5
- hash: sha256:2ffb86f0eb27be3221d32fd26bef5a9790189b7f852909eacfea8856b453b621
  name: AutoGluon_3.pkl
  path: TabularPredictor_2ffb86.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 10851
  saved_at: '2026-01-07T11:18:46.244438+00:00'
  step: 5
- hash: sha256:4a8b0d8627eb06a54983d1cda0f2590b37d0d957ed93b3917387d46a0268296e
  name: TabPFN_1.pkl
  path: TabPFNRegressor_4a8b0d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41023788
  saved_at: '2026-01-07T11:18:54.316380+00:00'
  step: 6
- hash: sha256:c601b2b53d19a607e5e896b9adf1a492b771c81f1b1a92f47808e9adda29d87b
  name: TabPFN_2.pkl
  path: TabPFNRegressor_c601b2.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41024620
  saved_at: '2026-01-07T11:18:54.375791+00:00'
  step: 6
- hash: sha256:c33130f544d62c90efdfd6125fac72ea4234cd12eb397c4c4d68d3312694e5d3
  name: TabPFN_3.pkl
  path: TabPFNRegressor_c33130.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41024620
  saved_at: '2026-01-07T11:18:54.434231+00:00'
  step: 6
- hash: sha256:ebfe485bf0167eb7a7b0bddb96e81d1f4b94d338efb674c20c63be67ac96a4b7
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_ebfe48.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41023825
  saved_at: '2026-01-07T11:19:07.145390+00:00'
  step: 7
- hash: sha256:e652f2e35ac3e06422b6a7d97bcd8bc0b5860eb16102951d1a9f958017e82c18
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_e652f2.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41024657
  saved_at: '2026-01-07T11:19:07.202915+00:00'
  step: 7
- hash: sha256:64eb64d94b9094ca84bfe26934f37ba97200ec59e985f798cb9296d18ddc3d25
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_64eb64.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41024657
  saved_at: '2026-01-07T11:19:07.259917+00:00'
  step: 7
predictions: []
