uid: bb917cb7-fd6c-4081-81fe-08706509912f
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: rice_redox
created_at: '2025-12-12T09:49:36.197417+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:b4db648a2547c1dc21ee2878cc4522bcc8f758afcdc997e89b71292698331f0a
  name: ASLSBaseline_1
  path: ASLSBaseline_b4db64.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2025-12-12T09:49:36.665401+00:00'
  step: 1
- hash: sha256:111fd53badada5d61bfe1dd212ba690186c13384ceaa8ae2769ea9f5d758988a
  name: y_StandardScaler
  path: StandardScaler_111fd5.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 444
  saved_at: '2025-12-12T09:50:14.544937+00:00'
  step: 4
- hash: sha256:55c9b6c11dc8177f4481694813c0fd06d9246da22a422abb204816d33b634e2e
  name: StandardScaler_1
  path: StandardScaler_55c9b6.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 6357
  saved_at: '2025-12-12T09:50:14.558522+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T09:50:14.636036+00:00'
  step: 6
- hash: sha256:1829e3f71e85336ccc87a7ab9941e6e0f8a637dacf3265c5025b84eb27e5d7f9
  name: PCA_1
  path: PCA_1829e3.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9482
  saved_at: '2025-12-12T09:50:14.981925+00:00'
  step: 7
- hash: sha256:db228c06fa09a9a6cc8d175c6bfb6e2c1aee73871a5b074cf016fd3d6976058e
  name: StandardScaler_1
  path: StandardScaler_db228c.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 601
  saved_at: '2025-12-12T09:50:15.050415+00:00'
  step: 8
- hash: sha256:7630bd08d817e041e9de4972b99fd4cd0dfc1d34e221267e994c56d13b45ba53
  name: PowerTransformer_1
  path: PowerTransformer_7630bd.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 783
  saved_at: '2025-12-12T09:50:15.117020+00:00'
  step: 9
- hash: sha256:3af368fb60f51eeee944311f962529092f151c1375086ff9cb8d59f5614a44d2
  name: AutoGluon_1.pkl
  path: TabularPredictor_3af368.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12764
  saved_at: '2025-12-12T09:53:28.497293+00:00'
  step: 10
- hash: sha256:f1b98d1936be24b16abd78debde187ef5caaded24819fe01d67e54542d1aea69
  name: AutoGluon_2.pkl
  path: TabularPredictor_f1b98d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12755
  saved_at: '2025-12-12T09:53:28.497624+00:00'
  step: 10
- hash: sha256:27426cc706c9210869a34d7cd53e66cb3b5347d85f65e17e781e28915c3b7f53
  name: AutoGluon_3.pkl
  path: TabularPredictor_27426c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12755
  saved_at: '2025-12-12T09:53:28.497888+00:00'
  step: 10
- hash: sha256:31c9c3dcb6db8d80ac247f28fbc503f573e166168370d606386ddda60f8770cb
  name: TabPFN_1.pkl
  path: TabPFNRegressor_31c9c3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44484030
  saved_at: '2025-12-12T09:56:25.739270+00:00'
  step: 11
- hash: sha256:289377707294bad437eaf35317ab6e3838a70220d066dea8dd575feaa657dff5
  name: TabPFN_2.pkl
  path: TabPFNRegressor_289377.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44484030
  saved_at: '2025-12-12T09:56:25.788530+00:00'
  step: 11
- hash: sha256:f551777c2c39e04a702e6e8b1ccf7f0ec327f46c5a23069f9b8e163fbc1cee7c
  name: TabPFN_3.pkl
  path: TabPFNRegressor_f55177.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44484030
  saved_at: '2025-12-12T09:56:25.836882+00:00'
  step: 11
- hash: sha256:c5fa857bfdfc8ec14f02c4690461a44c0f90f33426af719b70710a58fe7576eb
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_c5fa85.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44484069
  saved_at: '2025-12-12T10:03:16.934181+00:00'
  step: 12
- hash: sha256:02daea956410770c1331d0673075ec7f3911fd5f5c0ca70d165124118d154a3f
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_02daea.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44484067
  saved_at: '2025-12-12T10:03:16.983814+00:00'
  step: 12
- hash: sha256:d928ff8a58ca399f34e0834344d9339ce7fca50f515f2b2ef4ae13d5e3983b49
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_d928ff.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 44484069
  saved_at: '2025-12-12T10:03:17.035571+00:00'
  step: 12
predictions: []
