uid: 00549753-29a0-4a58-9a82-7767176c02e4
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: biscuit_sucrose_40_randomsplit
created_at: '2025-12-12T10:11:18.529116+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:26b2ddd51689b4d62afd0d8120bf3701bb34aecf8f7c42b134bb6c3d9b5f3096
  name: ASLSBaseline_1
  path: ASLSBaseline_26b2dd.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T10:11:18.547123+00:00'
  step: 1
- hash: sha256:b0bdcaf69fb9a48b0eb496d06d479b706ee52841189d0fe57235426a46823080
  name: y_StandardScaler
  path: StandardScaler_b0bdca.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 442
  saved_at: '2025-12-12T10:11:18.613808+00:00'
  step: 4
- hash: sha256:fa4d2ae956948b6752ec5fca718f59ad142b32ecfb304090fa41f55ecc187ed9
  name: StandardScaler_1
  path: StandardScaler_fa4d2a.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 14783
  saved_at: '2025-12-12T10:11:18.624098+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T10:11:18.642573+00:00'
  step: 6
- hash: sha256:cd06a905716bdccae8d88b53d1219a51662ca3bb4f0cb306a12c812023df7b90
  name: PCA_1
  path: PCA_cd06a9.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 23233
  saved_at: '2025-12-12T10:11:18.665413+00:00'
  step: 7
- hash: sha256:fb709059d22d4623ce24f3021f7f0c34dca83a91b1b82596fb50405294714a52
  name: StandardScaler_1
  path: StandardScaler_fb7090.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 574
  saved_at: '2025-12-12T10:11:18.713519+00:00'
  step: 8
- hash: sha256:158f4d6497c37c10c224ca9eaada2b81d4e3238c33a5652ae23c122cc3814dfd
  name: PowerTransformer_1
  path: PowerTransformer_158f4d.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 785
  saved_at: '2025-12-12T10:11:18.740227+00:00'
  step: 9
- hash: sha256:df103ac964d32fe14805135186da84532a0a4eef8e177f1bb52ac2c25aae59b8
  name: AutoGluon_1.pkl
  path: TabularPredictor_df103a.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12723
  saved_at: '2025-12-12T10:11:44.084749+00:00'
  step: 10
- hash: sha256:239442ce751f4be19b0f231dd7017297e9e9add674db3f848b9abea582707437
  name: AutoGluon_2.pkl
  path: TabularPredictor_239442.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12723
  saved_at: '2025-12-12T10:11:44.085070+00:00'
  step: 10
- hash: sha256:48b5110e4f9b9a9a134ca6ba72605789c8212e6c4fbbdcfae626364b64aad9a5
  name: AutoGluon_3.pkl
  path: TabularPredictor_48b511.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12723
  saved_at: '2025-12-12T10:11:44.085352+00:00'
  step: 10
- hash: sha256:3ca148dad1c9c783e4a478ea49c646f89c8b6733431af1079c1403d9163c2921
  name: TabPFN_1.pkl
  path: TabPFNRegressor_3ca148.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41001094
  saved_at: '2025-12-12T10:11:49.810805+00:00'
  step: 11
- hash: sha256:490e7598cfe89ee6452644360fa5800f24a0a791254c5e03cfa749402b3eeb4b
  name: TabPFN_2.pkl
  path: TabPFNRegressor_490e75.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41002948
  saved_at: '2025-12-12T10:11:49.856572+00:00'
  step: 11
- hash: sha256:1ce61fb9a671213c441a4046b2a64e162cef769aa8c44a006b34d5ca34eeb3fb
  name: TabPFN_3.pkl
  path: TabPFNRegressor_1ce61f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41002948
  saved_at: '2025-12-12T10:11:49.901866+00:00'
  step: 11
- hash: sha256:671f3d4152dd167a009a3ce5fdc84cdd178ed977d95178214e72aafc2cd721f7
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_671f3d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41001129
  saved_at: '2025-12-12T10:12:01.603933+00:00'
  step: 12
- hash: sha256:8ba1d8c2a03471f4f21566075b75527399477d2c15482e911692e7480a6b375f
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_8ba1d8.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41002985
  saved_at: '2025-12-12T10:12:01.651803+00:00'
  step: 12
- hash: sha256:8854de38554859e9d491e9919c72b19e733265ca968f39a7ebde35560ff4b7c5
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_8854de.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41002987
  saved_at: '2025-12-12T10:12:01.699562+00:00'
  step: 12
predictions: []
