uid: 3e654ac0-4f3e-4f41-b71a-9dc6467fc918
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: diesel_flash_395_pengks
created_at: '2026-01-07T09:18:47.134199+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2026-01-07T09:18:47.196276+00:00'
  step: 1
- hash: sha256:92331de0a6abeb376567d1f35b38a76eff3c4883e3fa9a706fba4ae38dbca73f
  name: PCA_1
  path: PCA_92331d.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 8365
  saved_at: '2026-01-07T09:18:47.317873+00:00'
  step: 4
- hash: sha256:e7772333020958eafdb1f5b2599efef3aea3e43e71d1e34dc317b09cb4ab7c47
  name: AutoGluon_1.pkl
  path: TabularPredictor_e77723.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11196
  saved_at: '2026-01-07T09:18:57.740019+00:00'
  step: 5
- hash: sha256:3c24afe3aa24c67d6e1e82cf26f110ef6424e652a05c4cf47117326717564c72
  name: AutoGluon_2.pkl
  path: TabularPredictor_3c24af.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11262
  saved_at: '2026-01-07T09:18:57.740370+00:00'
  step: 5
- hash: sha256:8c6d1f3f13e2a0c8ba088f2499d1dd4c1cdee5fd6c01c8f9938be903fde4d775
  name: AutoGluon_3.pkl
  path: TabularPredictor_8c6d1f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11253
  saved_at: '2026-01-07T09:18:57.740636+00:00'
  step: 5
- hash: sha256:cd6c7b96c74f00af04b6a35c3d3120ef8f551e6ac4242c07d4afd0f80f855a96
  name: TabPFN_1.pkl
  path: TabPFNRegressor_cd6c7b.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41141672
  saved_at: '2026-01-07T09:19:05.895176+00:00'
  step: 6
- hash: sha256:0298ef46506aa83dfcd69ac7e3f28228bf31c845e2eefd664488e54e93cd01ad
  name: TabPFN_2.pkl
  path: TabPFNRegressor_0298ef.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41141670
  saved_at: '2026-01-07T09:19:05.952966+00:00'
  step: 6
- hash: sha256:9b1a92af86b7ed40ddfb8bee0c0ee39c297fb57c866b2c85b20d4da4b172800d
  name: TabPFN_3.pkl
  path: TabPFNRegressor_9b1a92.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41141672
  saved_at: '2026-01-07T09:19:06.010212+00:00'
  step: 6
- hash: sha256:5a5b6b61de4f3cb6cb28749c0106183c6436fb223bd2fd3a540e3edd261195ea
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_5a5b6b.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41141707
  saved_at: '2026-01-07T09:19:22.820353+00:00'
  step: 7
- hash: sha256:f333f22acc1ae77abbc1ca39ada05bae2e41f5aad14e22d0ac9b3bdb139b16d3
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_f333f2.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41141709
  saved_at: '2026-01-07T09:19:22.878758+00:00'
  step: 7
- hash: sha256:97a020d4cda49d06aca24d6a3f9acbc017f28ebfc3dc652f228508287721a596
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_97a020.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41141709
  saved_at: '2026-01-07T09:19:22.936679+00:00'
  step: 7
predictions: []
