uid: e7dc94ae-7db7-4601-9501-a07e08f8a5b4
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: wood_n_402_olale
created_at: '2025-12-12T08:10:09.524236+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:c420e3c9c457cb869a0040d36665a950c74a835cc5d0f10428fe7653df5fd30e
  name: ASLSBaseline_1
  path: ASLSBaseline_c420e3.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2025-12-12T08:10:09.642784+00:00'
  step: 1
- hash: sha256:99a8725f265b768e4aceabdc9b0df053a226e7aa01b56a99f60bde6ffc713ed3
  name: y_StandardScaler
  path: StandardScaler_99a872.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 444
  saved_at: '2025-12-12T08:10:09.812160+00:00'
  step: 4
- hash: sha256:5c7b91a3b0f7550a5bfec04484480180900040ea334f2e7c596d584d2e04e109
  name: StandardScaler_1
  path: StandardScaler_5c7b91.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 22554
  saved_at: '2025-12-12T08:10:09.819433+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T08:10:09.833931+00:00'
  step: 6
- hash: sha256:5553a5e6492689bb6bb16c2c698b28f8c32fbbe33fe75207bfd1381ed6b7b5d2
  name: PCA_1
  path: PCA_5553a5.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 57825
  saved_at: '2025-12-12T08:10:09.916472+00:00'
  step: 7
- hash: sha256:91f0e8363b0bb23d78c8de11263893739ce6a12c7a47a5149639785e2484599f
  name: StandardScaler_1
  path: StandardScaler_91f0e8.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 690
  saved_at: '2025-12-12T08:10:09.948381+00:00'
  step: 8
- hash: sha256:f77e20d7f94955f5b1424ad147de142b39fabc806b8028933399929606754e97
  name: PowerTransformer_1
  path: PowerTransformer_f77e20.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 965
  saved_at: '2025-12-12T08:10:09.994803+00:00'
  step: 9
predictions: []
