schema_version: '2.0'
uid: 14528b35-362e-4265-bc02-6408bdebf598
pipeline_id: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e
name: PLS_PP_SELECTION_NO_SAVE_a7ef2e
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:50:27.631431+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: sklearn.preprocessing._data.StandardScaler
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - null
    - class: nirs4all.operators.transforms.signal.Gaussian
      params:
        order: 1
        sigma: 2
    - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
      params:
        window_length: 15
        deriv: 2
    - nirs4all.operators.transforms.nirs.AreaNormalization
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      error_score: .nan
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: sklearn.preprocessing._data.StandardScaler
- _cartesian_:
  - null
  - class: nirs4all.operators.transforms.signal.Gaussian
    params:
      order: 1
      sigma: 2
  - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
    params:
      window_length: 15
      deriv: 2
  - nirs4all.operators.transforms.nirs.AreaNormalization
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$e8256e270180:all
    content_hash: sha256:62fbca7e67132ee4c3eac6fcd60d6652d6e5c748d596fbba7aa83af04e3a52fc
    path: transformer_StandardScaler_62fbca7e6713.joblib
    chain_path: s2.StandardScaler[src=0,sub=0]
    source_index: 0
    pipeline_id: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e
    branch_path: []
    step_index: 2
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: StandardScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 12015
    created_at: '2026-01-08T17:50:27.638681+00:00'
    params: {}
    version: 3
  - artifact_id: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:50:27.696520+00:00'
    params: {}
    version: 3
  - artifact_id: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$944ddc9b0e46:all
    content_hash: sha256:fcef74d1464ae75c275fc2b03bb2c435a0787cd50861cdf41aedf150ab9f3eff
    path: transformer_Gaussian_fcef74d1464a.joblib
    chain_path: s5.Gaussian[src=0,sub=0]
    source_index: 0
    pipeline_id: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: Gaussian
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 103
    created_at: '2026-01-08T17:50:27.718577+00:00'
    params: {}
    version: 3
  - artifact_id: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$eeb09d32a26b:all
    content_hash: sha256:5c353b1441d52f528075c64bd2477db6d0df3f619817bfa27a68d32928e99953
    path: transformer_SavitzkyGolay_5c353b1441d5.joblib
    chain_path: s5.SavitzkyGolay[src=0,sub=1]
    source_index: 0
    pipeline_id: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: SavitzkyGolay
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 137
    created_at: '2026-01-08T17:50:27.722157+00:00'
    params: {}
    version: 3
  - artifact_id: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$ac71c0f61352:all
    content_hash: sha256:3381c200ece0f7e7ac9f3c9a70feb2bc950b0271d9a3c4d8bfc727bd6a3bfbb5
    path: transformer_AreaNormalization_3381c200ece0.joblib
    chain_path: s5.AreaNormalization[src=0,sub=2]
    source_index: 0
    pipeline_id: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e
    branch_path: []
    step_index: 5
    substep_index: 2
    fold_id: null
    artifact_type: transformer
    class_name: AreaNormalization
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 103
    created_at: '2026-01-08T17:50:27.726688+00:00'
    params: {}
    version: 3
  - artifact_id: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$9f79d59455ab:0
    content_hash: sha256:57e3e42afbedc6ae372fab3418532549f9fd5b0a57545397431f90172b782024
    path: model_PLSRegression_57e3e42afbed.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 157670
    created_at: '2026-01-08T17:50:28.261898+00:00'
    params: {}
    version: 3
  - artifact_id: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$9f79d59455ab:1
    content_hash: sha256:351a80ae0845d2142765735d21881cb705eaab30ea09d84fac52b0fbad9f94cc
    path: model_PLSRegression_351a80ae0845.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 158011
    created_at: '2026-01-08T17:50:28.265732+00:00'
    params: {}
    version: 3
  - artifact_id: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$9f79d59455ab:2
    content_hash: sha256:58172fc50f806ce8b63ef6a98ca5087e07cba179f7ad58eb15246583e7c739da
    path: model_PLSRegression_58172fc50f80.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 158029
    created_at: '2026-01-08T17:50:28.269647+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  09b59014-fcf:
    trace_id: 09b59014-fcf
    pipeline_uid: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e
    created_at: '2026-01-08T17:50:27.632617+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 3.3140182495117188
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: StandardScaler
      operator_config:
        feature_augmentation: sklearn.preprocessing._data.StandardScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$e8256e270180:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$e8256e270180:all
        by_source:
          0:
          - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$e8256e270180:all
        by_chain:
          s2.StandardScaler[src=0,sub=0]: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$e8256e270180:all
        metadata:
          class_name: StandardScaler
          name: StandardScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 11.191129684448242
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s2.StandardScaler[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 60.247182846069336
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 6.826162338256836
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: None, Gaussian, SavitzkyGolay (+1)
      operator_config:
        feature_augmentation:
        - null
        - class: nirs4all.operators.transforms.signal.Gaussian
          params:
            order: 1
            sigma: 2
        - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
          params:
            window_length: 15
            deriv: 2
        - nirs4all.operators.transforms.nirs.AreaNormalization
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$944ddc9b0e46:all
        - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$eeb09d32a26b:all
        - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$ac71c0f61352:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$944ddc9b0e46:all
            - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$eeb09d32a26b:all
            - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$ac71c0f61352:all
        by_source:
          0:
          - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$944ddc9b0e46:all
          - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$eeb09d32a26b:all
          - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$ac71c0f61352:all
        by_chain:
          s5.Gaussian[src=0,sub=0]: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$944ddc9b0e46:all
          s5.SavitzkyGolay[src=0,sub=1]: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$eeb09d32a26b:all
          s5.AreaNormalization[src=0,sub=2]: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$ac71c0f61352:all
        metadata:
          class_name: AreaNormalization
          name: AreaNormalization_3
      branch_path: []
      branch_name: ''
      duration_ms: 29.636859893798828
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.Gaussian[src=0,sub=0]
      - s5.SavitzkyGolay[src=0,sub=1]
      - s5.AreaNormalization[src=0,sub=2]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 2304
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 4
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          error_score: .nan
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$9f79d59455ab:0
        - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$9f79d59455ab:1
        - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$9f79d59455ab:0
          1: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$9f79d59455ab:1
          2: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$9f79d59455ab:0
            - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$9f79d59455ab:1
            - 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0494_PLS_PP_SELECTION_NO_SAVE_a7ef2e$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 554.4357299804688
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 2304
      output_shape:
      - 60
      - 2304
      input_features_shape:
      - - 60
        - 4
        - 576
      output_features_shape:
      - - 60
        - 4
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: Std|Std>Gauss|Std>SG|Std>AreaNormalization
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_a7ef2e
      n_steps: 6
      n_artifacts: 8
