uid: 5656c133-5721-4d04-b8e0-6fb9285cf1a6
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: poultry_manure_total_n_ks
created_at: '2025-12-12T08:05:07.828535+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:125d94dee500492a3bdb8dd8b9fa106b8b2b34e5f42944e4b15d55960ffb73d1
  name: ASLSBaseline_1
  path: ASLSBaseline_125d94.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T08:05:07.874674+00:00'
  step: 1
- hash: sha256:94a0899b20d8c6ab36cea6e66ce97267468df11044817a8ee754ef4040a1fccc
  name: y_StandardScaler
  path: StandardScaler_94a089.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 440
  saved_at: '2025-12-12T08:05:07.958030+00:00'
  step: 4
- hash: sha256:b81dc395d1dd80940342c9d3237f852b94dbd4704afba86f452dc9b2bf4d63c4
  name: StandardScaler_1
  path: StandardScaler_b81dc3.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 21264
  saved_at: '2025-12-12T08:05:07.970469+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T08:05:07.985163+00:00'
  step: 6
- hash: sha256:5862dbfd9bfbdf7f0cbfc1c544cd73bf5e8f61dea119f9b4783de94b26d16912
  name: PCA_1
  path: PCA_5862db.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 111761
  saved_at: '2025-12-12T08:05:08.060875+00:00'
  step: 7
- hash: sha256:839f98ae517f3aa6a02b3903217ecb1645dff11963b361a4c3c6a436ae95334c
  name: StandardScaler_1
  path: StandardScaler_839f98.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 944
  saved_at: '2025-12-12T08:05:08.094951+00:00'
  step: 8
- hash: sha256:d84f5cbd3f747a7ec3dc5ab2623a45bce39a0502f058affcadd8ac7b3caed0b7
  name: PowerTransformer_1
  path: PowerTransformer_d84f5c.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1339
  saved_at: '2025-12-12T08:05:08.165271+00:00'
  step: 9
- hash: sha256:10d2aa7d975ebc46d1bfbc682445a6e3dcf52c0ca924a7cf5f40b46f72e9bb3e
  name: AutoGluon_1.pkl
  path: TabularPredictor_10d2aa.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 20222
  saved_at: '2025-12-12T08:05:22.662235+00:00'
  step: 10
- hash: sha256:614d8cee63e986fd945201fef8b321df8f7f1c6752a33bde60885932b374f12e
  name: AutoGluon_2.pkl
  path: TabularPredictor_614d8c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 20204
  saved_at: '2025-12-12T08:05:22.663192+00:00'
  step: 10
- hash: sha256:40cf392bee8a7d5bb355733f59c2fc8d7f5a81e97f9e9e2eddf7bb0b574e9fa6
  name: AutoGluon_3.pkl
  path: TabularPredictor_40cf39.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 20213
  saved_at: '2025-12-12T08:05:22.664007+00:00'
  step: 10
- hash: sha256:3f3538749c76953aa570735e2f46a7ccc7506eda6f6a011ddb6be20e41520bef
  name: TabPFN_1.pkl
  path: TabPFNRegressor_3f3538.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41403998
  saved_at: '2025-12-12T08:05:37.985844+00:00'
  step: 11
- hash: sha256:366a3175b7c2b89ab151de056c43a1ebd8e159d63239532bba40a7bfc001acd7
  name: TabPFN_2.pkl
  path: TabPFNRegressor_366a31.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41410198
  saved_at: '2025-12-12T08:05:38.031917+00:00'
  step: 11
- hash: sha256:82d215b64ded2f6a5ee35cf4c73b9e6b0bec4472ea096f8aa3f662255b5e9987
  name: TabPFN_3.pkl
  path: TabPFNRegressor_82d215.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41410204
  saved_at: '2025-12-12T08:05:38.078159+00:00'
  step: 11
- hash: sha256:16c72f57f85acb1fb63251e61df870356de24e69e4fd5829524440b9aaf0f824
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_16c72f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41404029
  saved_at: '2025-12-12T08:06:06.782252+00:00'
  step: 12
- hash: sha256:548f8ec9b510938bdd29979fa73fb5b0def3375656f4df8f9ddcd278d450e6c8
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_548f8e.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41410243
  saved_at: '2025-12-12T08:06:06.829247+00:00'
  step: 12
- hash: sha256:6fb5651a98c1954e3dba964f215e0fa98f24e04a1ed22bc4f80a73a9b63a592a
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_6fb565.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41410243
  saved_at: '2025-12-12T08:06:06.876283+00:00'
  step: 12
predictions: []
