uid: 0f01484c-beab-4abe-97ac-cd5603ff99d3
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: diesel_cn_245_b_a
created_at: '2025-12-12T08:41:16.458887+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:95c7c1d7b88a1236418be2266cbd228dac43925cfde8d91ae47a473976519313
  name: ASLSBaseline_1
  path: ASLSBaseline_95c7c1.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T08:41:16.500571+00:00'
  step: 1
- hash: sha256:6331a52fc6d4cda43c7c42a479fd495b82374f5a22b637833a04e718b1dbc465
  name: y_StandardScaler
  path: StandardScaler_6331a5.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 445
  saved_at: '2025-12-12T08:41:16.660886+00:00'
  step: 4
- hash: sha256:973e525c44ef4b96524cb3bf34b362fe205763aef175a1304ec75f1f79cedf12
  name: StandardScaler_1
  path: StandardScaler_973e52.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 8872
  saved_at: '2025-12-12T08:41:16.668796+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T08:41:16.681862+00:00'
  step: 6
- hash: sha256:02cb731f64a866b34586c4a3f058f59b30a58f1af4cc702009e074f48bd67a43
  name: PCA_1
  path: PCA_02cb73.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 9238
  saved_at: '2025-12-12T08:41:16.723427+00:00'
  step: 7
- hash: sha256:e7c8e96ad3737e583cc22ec24368026feafb9e2b53bef7091486e5e05b058bfe
  name: StandardScaler_1
  path: StandardScaler_e7c8e9.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 523
  saved_at: '2025-12-12T08:41:16.757461+00:00'
  step: 8
- hash: sha256:be3186ea75c273143e498b17056220b396deaae3dc81e7a165dd085245c0b59f
  name: PowerTransformer_1
  path: PowerTransformer_be3186.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 690
  saved_at: '2025-12-12T08:41:16.777802+00:00'
  step: 9
- hash: sha256:cfa3919612b9d0617df63da90e1cac9969a18cf934dc65baa68406337ed4aaf7
  name: AutoGluon_1.pkl
  path: TabularPredictor_cfa391.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11616
  saved_at: '2025-12-12T08:41:26.786912+00:00'
  step: 10
- hash: sha256:3f6ae521cbd390a1e19ccd9f8dee46fcead1c434d9ebc32b11a7a666526afc38
  name: AutoGluon_2.pkl
  path: TabularPredictor_3f6ae5.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11598
  saved_at: '2025-12-12T08:41:26.787504+00:00'
  step: 10
- hash: sha256:ff7adb3c861038c151ad3090c515c009de346748a135f147519cc56a7da9e498
  name: AutoGluon_3.pkl
  path: TabularPredictor_ff7adb.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 11598
  saved_at: '2025-12-12T08:41:26.787799+00:00'
  step: 10
- hash: sha256:4ea2fc7466288803cc42bc0d3e0c81ca8a8f1b9ce12d8d9f7d4a6e5a1bbf3302
  name: TabPFN_1.pkl
  path: TabPFNRegressor_4ea2fc.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41040819
  saved_at: '2025-12-12T08:41:34.049203+00:00'
  step: 11
- hash: sha256:9ca1bf4637d3ed6e306e74f40ead79957a6ae99db541d841a3fd12533997cf2e
  name: TabPFN_2.pkl
  path: TabPFNRegressor_9ca1bf.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41042035
  saved_at: '2025-12-12T08:41:34.094640+00:00'
  step: 11
- hash: sha256:20c27719dce0a8c91a7bda4410ff133f6fd15796d737694a5b690421bdc5b2ee
  name: TabPFN_3.pkl
  path: TabPFNRegressor_20c277.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41042035
  saved_at: '2025-12-12T08:41:34.138785+00:00'
  step: 11
- hash: sha256:15d80ddc69a716942162d523dc0ec88e6706b97358e71861c70723b794d89154
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_15d80d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41040856
  saved_at: '2025-12-12T08:41:49.811733+00:00'
  step: 12
- hash: sha256:255bf6afdf16405240fe406281fb83956133210fd11f43de7c9700c1e226fd44
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_255bf6.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41042072
  saved_at: '2025-12-12T08:41:49.856006+00:00'
  step: 12
- hash: sha256:8d3e53cf31510a4ec9e4fc5b04441d4f5c079015778f3c7e3a6d32c31a1c2215
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_8d3e53.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41042072
  saved_at: '2025-12-12T08:41:49.899229+00:00'
  step: 12
predictions: []
