uid: 58d0050c-ca3b-4546-b53e-4ce55e5d610c
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: alpine_p_291_robustnessfennoscandia
created_at: '2026-01-07T09:20:49.640106+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:6fad93a0e497c69beabeda8f5151735441edf9b93933632b811f33b2a2f357f5
  name: ASLSBaseline_1
  path: ASLSBaseline_6fad93.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2026-01-07T09:20:49.803475+00:00'
  step: 1
- hash: sha256:ce32297247ab6d049b186891be2ea1ce8b76b2141d02c371fb092fa1723a3a16
  name: PCA_1
  path: PCA_ce3229.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 137832
  saved_at: '2026-01-07T09:20:49.890739+00:00'
  step: 4
- hash: sha256:b4ac15e766a3eac61e8086fdbb50378bb80af795712a37ab600e6b2c13dddee5
  name: AutoGluon_1.pkl
  path: TabularPredictor_b4ac15.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 15576
  saved_at: '2026-01-07T09:21:07.772465+00:00'
  step: 5
- hash: sha256:e247847c7140bb133328d3392748dc543ebecb3657b50fb6fdb496f02cd0bfe2
  name: AutoGluon_2.pkl
  path: TabularPredictor_e24784.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 15576
  saved_at: '2026-01-07T09:21:07.772963+00:00'
  step: 5
- hash: sha256:0995a8c879f9c0880fd5b552339e89df30281461a77e3ee632e609706dd7d0ab
  name: AutoGluon_3.pkl
  path: TabularPredictor_0995a8.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 15576
  saved_at: '2026-01-07T09:21:07.773547+00:00'
  step: 5
- hash: sha256:0c8864456a09ac38f1de252142b7ab7a4bf0f7bd01146595d01cfa39e2f090fe
  name: TabPFN_1.pkl
  path: TabPFNRegressor_0c8864.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41280700
  saved_at: '2026-01-07T09:21:18.773289+00:00'
  step: 6
- hash: sha256:70af155b8f29ddec0a3a2304756565ffea79ce989c1f488484f6ae25f98010ce
  name: TabPFN_2.pkl
  path: TabPFNRegressor_70af15.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41284216
  saved_at: '2026-01-07T09:21:18.832912+00:00'
  step: 6
- hash: sha256:ecc24d2f2e0c342f3a6ba753bc72a20a50aa6b1a4a9a572631b49fb2c331548f
  name: TabPFN_3.pkl
  path: TabPFNRegressor_ecc24d.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41284220
  saved_at: '2026-01-07T09:21:18.892922+00:00'
  step: 6
- hash: sha256:e6b3d778e5fa1ef9c1eab6b8560eed6d6158dca7199d31a72f07b2c115786828
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_e6b3d7.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41280737
  saved_at: '2026-01-07T09:21:42.633251+00:00'
  step: 7
- hash: sha256:39a9a34f9d886addfae9592b9d9fef1b2e4955ac35999f9ed30fc8eb9b5415c1
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_39a9a3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41284255
  saved_at: '2026-01-07T09:21:42.692837+00:00'
  step: 7
- hash: sha256:09e2ccbbe2d54326d6372b336a0a203a1573ba9aea2492aa8cbaf46784543a89
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_09e2cc.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 41284257
  saved_at: '2026-01-07T09:21:42.752762+00:00'
  step: 7
predictions: []
