schema_version: '2.0'
uid: dc9e51da-604c-4dc8-8524-71480e581cad
pipeline_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9
name: PLS_PP_SELECTION_NO_SAVE_32c0d9
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:53:57.567758+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: sklearn.preprocessing._data.StandardScaler
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
    - class: nirs4all.operators.transforms.signal.Gaussian
      params:
        order: 1
        sigma: 2
    - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
      params:
        window_length: 15
        deriv: 2
    - nirs4all.operators.transforms.nirs.Haar
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      error_score: .nan
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: sklearn.preprocessing._data.StandardScaler
- _cartesian_:
  - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
  - class: nirs4all.operators.transforms.signal.Gaussian
    params:
      order: 1
      sigma: 2
  - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
    params:
      window_length: 15
      deriv: 2
  - nirs4all.operators.transforms.nirs.Haar
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$e8256e270180:all
    content_hash: sha256:62fbca7e67132ee4c3eac6fcd60d6652d6e5c748d596fbba7aa83af04e3a52fc
    path: transformer_StandardScaler_62fbca7e6713.joblib
    chain_path: s2.StandardScaler[src=0,sub=0]
    source_index: 0
    pipeline_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9
    branch_path: []
    step_index: 2
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: StandardScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 12015
    created_at: '2026-01-08T17:53:57.574362+00:00'
    params: {}
    version: 3
  - artifact_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:53:57.635340+00:00'
    params: {}
    version: 3
  - artifact_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$33af94b1bf58:all
    content_hash: sha256:0721098a9e95cc2ee2f5245b14331db5bda396203e6f9c2dc951c1d3611e0a2f
    path: transformer_ExtendedMultiplicativeScatterCorrection_0721098a9e95.joblib
    chain_path: s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=0]
    source_index: 0
    pipeline_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: ExtendedMultiplicativeScatterCorrection
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 4485
    created_at: '2026-01-08T17:53:57.652850+00:00'
    params: {}
    version: 3
  - artifact_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$5b4a7bbb9aae:all
    content_hash: sha256:fcef74d1464ae75c275fc2b03bb2c435a0787cd50861cdf41aedf150ab9f3eff
    path: transformer_Gaussian_fcef74d1464a.joblib
    chain_path: s5.Gaussian[src=0,sub=1]
    source_index: 0
    pipeline_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: Gaussian
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 103
    created_at: '2026-01-08T17:53:57.655022+00:00'
    params: {}
    version: 3
  - artifact_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$296923040127:all
    content_hash: sha256:5c353b1441d52f528075c64bd2477db6d0df3f619817bfa27a68d32928e99953
    path: transformer_SavitzkyGolay_5c353b1441d5.joblib
    chain_path: s5.SavitzkyGolay[src=0,sub=2]
    source_index: 0
    pipeline_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9
    branch_path: []
    step_index: 5
    substep_index: 2
    fold_id: null
    artifact_type: transformer
    class_name: SavitzkyGolay
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 137
    created_at: '2026-01-08T17:53:57.657949+00:00'
    params: {}
    version: 3
  - artifact_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$32bd0e890598:all
    content_hash: sha256:2237293e62d5640680cb91d003382cdd194cbcc1496aee2fd76192fa547a78be
    path: transformer_Haar_2237293e62d5.joblib
    chain_path: s5.Haar[src=0,sub=3]
    source_index: 0
    pipeline_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9
    branch_path: []
    step_index: 5
    substep_index: 3
    fold_id: null
    artifact_type: transformer
    class_name: Haar
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 112
    created_at: '2026-01-08T17:53:57.661316+00:00'
    params: {}
    version: 3
  - artifact_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$9f79d59455ab:0
    content_hash: sha256:163338930120949d1196f2bf2e74123fa8e90e95c832a9f66601669cb539143d
    path: model_PLSRegression_163338930120.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 196729
    created_at: '2026-01-08T17:53:58.257515+00:00'
    params: {}
    version: 3
  - artifact_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$9f79d59455ab:1
    content_hash: sha256:e2c7337384a2ad22f162f8bc1ae8042aedec55800a5234e28a680d74cc8ee061
    path: model_PLSRegression_e2c7337384a2.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 197160
    created_at: '2026-01-08T17:53:58.270023+00:00'
    params: {}
    version: 3
  - artifact_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$9f79d59455ab:2
    content_hash: sha256:6cfcbee80eaee0e8ad6c349e8ef6579e91cac61403f3d1467df400c2c2d6cfe9
    path: model_PLSRegression_6cfcbee80eae.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 197176
    created_at: '2026-01-08T17:53:58.279235+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  c918be65-a22:
    trace_id: c918be65-a22
    pipeline_uid: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9
    created_at: '2026-01-08T17:53:57.568962+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 2.666950225830078
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: StandardScaler
      operator_config:
        feature_augmentation: sklearn.preprocessing._data.StandardScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$e8256e270180:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$e8256e270180:all
        by_source:
          0:
          - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$e8256e270180:all
        by_chain:
          s2.StandardScaler[src=0,sub=0]: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$e8256e270180:all
        metadata:
          class_name: StandardScaler
          name: StandardScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 13.004779815673828
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s2.StandardScaler[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 58.62927436828613
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 4.32896614074707
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: ExtendedMultiplicativeScatterCorrection, Gaussian, SavitzkyGolay
        (+1)
      operator_config:
        feature_augmentation:
        - nirs4all.operators.transforms.nirs.ExtendedMultiplicativeScatterCorrection
        - class: nirs4all.operators.transforms.signal.Gaussian
          params:
            order: 1
            sigma: 2
        - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
          params:
            window_length: 15
            deriv: 2
        - nirs4all.operators.transforms.nirs.Haar
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$33af94b1bf58:all
        - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$5b4a7bbb9aae:all
        - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$296923040127:all
        - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$32bd0e890598:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$33af94b1bf58:all
            - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$5b4a7bbb9aae:all
            - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$296923040127:all
            - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$32bd0e890598:all
        by_source:
          0:
          - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$33af94b1bf58:all
          - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$5b4a7bbb9aae:all
          - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$296923040127:all
          - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$32bd0e890598:all
        by_chain:
          s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=0]: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$33af94b1bf58:all
          s5.Gaussian[src=0,sub=1]: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$5b4a7bbb9aae:all
          s5.SavitzkyGolay[src=0,sub=2]: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$296923040127:all
          s5.Haar[src=0,sub=3]: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$32bd0e890598:all
        metadata:
          class_name: Haar
          name: Haar_4
      branch_path: []
      branch_name: ''
      duration_ms: 33.536434173583984
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.ExtendedMultiplicativeScatterCorrection[src=0,sub=0]
      - s5.Gaussian[src=0,sub=1]
      - s5.SavitzkyGolay[src=0,sub=2]
      - s5.Haar[src=0,sub=3]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 2880
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 5
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          error_score: .nan
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$9f79d59455ab:0
        - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$9f79d59455ab:1
        - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$9f79d59455ab:0
          1: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$9f79d59455ab:1
          2: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$9f79d59455ab:0
            - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$9f79d59455ab:1
            - 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0612_PLS_PP_SELECTION_NO_SAVE_32c0d9$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 627.5951862335205
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 2880
      output_shape:
      - 60
      - 2880
      input_features_shape:
      - - 60
        - 5
        - 576
      output_features_shape:
      - - 60
        - 5
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: Std|Std>ExtendedMSC|Std>Gauss|Std>SG|Std>Haar
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_32c0d9
      n_steps: 6
      n_artifacts: 9
