uid: 6ebdbc4c-6c23-48ec-b582-50890eced2aa
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: lucas_soc_all_26650_nocitaks
created_at: '2026-01-07T11:21:07.697882+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:4b8c179b0caedba3ee8a4a4945ad287c925324d79180bc4f973c334322e0dd6a
  name: ASLSBaseline_1
  path: ASLSBaseline_4b8c17.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 215
  saved_at: '2026-01-07T11:21:32.768447+00:00'
  step: 1
- hash: sha256:d3cb35fa38f1fa4d9489e2fd361472ba6cf55c58656f07b1fe53d7061a8f6551
  name: PCA_1
  path: PCA_d3cb35.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 205457
  saved_at: '2026-01-07T12:34:22.529718+00:00'
  step: 4
- hash: sha256:e11e8f5020e0fe735403ed9bad6a198b74157f0197e602f13b48b3fca1ba5437
  name: AutoGluon_1.pkl
  path: TabularPredictor_e11e8f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 14193
  saved_at: '2026-01-07T12:36:31.084359+00:00'
  step: 5
- hash: sha256:dc3bb33b50174341b06311ffaba8a9f01ced13928c77d0523996d9639879a05b
  name: AutoGluon_2.pkl
  path: TabularPredictor_dc3bb3.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 14175
  saved_at: '2026-01-07T12:36:31.084681+00:00'
  step: 5
- hash: sha256:30bc225fca42db11cea3f3299190118bc9da315af93af2eba965280fb549e215
  name: AutoGluon_3.pkl
  path: TabularPredictor_30bc22.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 14184
  saved_at: '2026-01-07T12:36:31.084973+00:00'
  step: 5
predictions: []
