uid: c92e0e56-d661-4a45-a46e-ca1830ad0e16
pipeline_id: 0001_SOTA_c52e86
name: SOTA_c52e86
dataset: cattle_manure_mgo_ks
created_at: '2025-12-12T07:47:16.367150+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - y_processing: sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.StandardScaler
  - nirs4all.operators.transforms.nirs.SavitzkyGolay
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - sklearn.preprocessing._data.StandardScaler
  - sklearn.preprocessing._data.PowerTransformer
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:125d94dee500492a3bdb8dd8b9fa106b8b2b34e5f42944e4b15d55960ffb73d1
  name: ASLSBaseline_1
  path: ASLSBaseline_125d94.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2025-12-12T07:47:16.449835+00:00'
  step: 1
- hash: sha256:f21e7a5d8536841cdba33abae19cae617bd0e62e8ba235811d08b70a3ade32ab
  name: y_StandardScaler
  path: StandardScaler_f21e7a.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 448
  saved_at: '2025-12-12T07:47:16.587994+00:00'
  step: 4
- hash: sha256:df0e6280c238a24e3ec44b22bc9fcddcc1b0841f6575f06d1895df2a2a9f9e68
  name: StandardScaler_1
  path: StandardScaler_df0e62.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 21800
  saved_at: '2025-12-12T07:47:16.594372+00:00'
  step: 5
- hash: sha256:b4f4680c61f9eabc36df266ceebd221eecd430d08d865533e278a3d159ac507d
  name: SavitzkyGolay_1
  path: SavitzkyGolay_b4f468.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 137
  saved_at: '2025-12-12T07:47:16.606437+00:00'
  step: 6
- hash: sha256:1db9f9a5c127ba70f1a3c850c51f8c31351d192ca9288bef332a16093bc131d5
  name: PCA_1
  path: PCA_1db9f9.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 157683
  saved_at: '2025-12-12T07:47:16.686411+00:00'
  step: 7
- hash: sha256:aa283d53aea94e1aeb1f92ca04c3f881e60fecf4e1a17dbd5969fc572e87762a
  name: StandardScaler_1
  path: StandardScaler_aa283d.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1208
  saved_at: '2025-12-12T07:47:16.722169+00:00'
  step: 8
- hash: sha256:240cec9e317bfdf6b756d83c6eb6f5bc6c227fbaa0b8266ef8b6256547d93ed2
  name: PowerTransformer_1
  path: PowerTransformer_240cec.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 1679
  saved_at: '2025-12-12T07:47:16.784142+00:00'
  step: 9
- hash: sha256:7bdf19d338b083e2ab009c95e14698c7feaebd67af7181600da8e50d5db86b3e
  name: AutoGluon_1.pkl
  path: TabularPredictor_7bdf19.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 24476
  saved_at: '2025-12-12T07:47:27.895758+00:00'
  step: 10
- hash: sha256:ac9a673269ea2e3b9c1efaa9e89dc4f567bb4504855135d0e0f3206576052ee9
  name: AutoGluon_2.pkl
  path: TabularPredictor_ac9a67.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 24467
  saved_at: '2025-12-12T07:47:27.896308+00:00'
  step: 10
- hash: sha256:062487a5919abb91132647f83de837887d7ed84d58331a78bf24028375541db4
  name: AutoGluon_3.pkl
  path: TabularPredictor_062487.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 24485
  saved_at: '2025-12-12T07:47:27.896816+00:00'
  step: 10
- hash: sha256:e31f95d00ccc6712982de8d89e4c50d3f35db840365507beea173bb601a6c037
  name: TabPFN_1.pkl
  path: TabPFNRegressor_e31f95.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42153205
  saved_at: '2025-12-12T07:47:55.199828+00:00'
  step: 11
- hash: sha256:ba5bbd9a04c77d79b559168b83913b3d6d89911be349ebb53832b72ef5b5fa34
  name: TabPFN_2.pkl
  path: TabPFNRegressor_ba5bbd.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42161903
  saved_at: '2025-12-12T07:47:55.249985+00:00'
  step: 11
- hash: sha256:c4a2a005e0030d031f8af2532ce1b7a97ca2ee0a3cd229aa7ed8ccbd242e8005
  name: TabPFN_3.pkl
  path: TabPFNRegressor_c4a2a0.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42161909
  saved_at: '2025-12-12T07:47:55.298085+00:00'
  step: 11
- hash: sha256:1bb51c254c191154e0c50fb0f8d5c701555f32343f3ae2af6173903582fe412c
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_1bb51c.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42153232
  saved_at: '2025-12-12T07:48:56.051393+00:00'
  step: 12
- hash: sha256:8d1d68a9ab41ee97201edde1673cc2edcdfb99da9786fbef5e7accea37aa3af8
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_8d1d68.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42161940
  saved_at: '2025-12-12T07:48:56.098799+00:00'
  step: 12
- hash: sha256:db217621c720d13c9e300dc6e27c10fa6a25b71fe5d81dbb945ea53d2744bb65
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_db2176.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 42161948
  saved_at: '2025-12-12T07:48:56.146361+00:00'
  step: 12
predictions: []
