schema_version: '2.0'
uid: c21d8874-ea31-401a-89f2-051609b57a31
pipeline_id: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81
name: PLS_PP_SELECTION_NO_SAVE_00ef81
dataset: beer_originalextract_60_ks
created_at: '2026-01-08T17:32:57.725283+00:00'
pipeline:
  steps:
  - feature_augmentation: null
  - feature_augmentation: null
  - y_processing: sklearn.preprocessing._data.MinMaxScaler
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
  - feature_augmentation:
    - null
    - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
      params:
        window_length: 15
    - null
    - nirs4all.operators.transforms.nirs.AreaNormalization
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
    name: PLS_optuna
    finetune_params:
      n_trials: 25
      sample: tpe
      approach: grouped
      eval_mode: avg
      model_params:
        n_components:
        - int
        - 1
        - 25
generator_choices:
- _or_: null
- _or_: null
- _cartesian_:
  - null
  - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
    params:
      window_length: 15
  - null
  - nirs4all.operators.transforms.nirs.AreaNormalization
metadata: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$f03a08201cd6:all
    content_hash: sha256:b84d6b12f30fc7926d40e9fdcd72a809060d088b245b5c12dba5b6dd442d1bd0
    path: encoder_MinMaxScaler_b84d6b12f30f.joblib
    chain_path: s3.y_MinMaxScaler[sub=1]
    source_index: null
    pipeline_id: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81
    branch_path: []
    step_index: 3
    substep_index: 1
    fold_id: null
    artifact_type: encoder
    class_name: MinMaxScaler
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 420
    created_at: '2026-01-08T17:32:57.751063+00:00'
    params: {}
    version: 3
  - artifact_id: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$8fbc483aec3b:all
    content_hash: sha256:c90a6e998d89e802fdc8ae5af3e9cd7288130360151139484ffc6499b3403f5a
    path: transformer_SavitzkyGolay_c90a6e998d89.joblib
    chain_path: s5.SavitzkyGolay[src=0,sub=0]
    source_index: 0
    pipeline_id: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81
    branch_path: []
    step_index: 5
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: SavitzkyGolay
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 137
    created_at: '2026-01-08T17:32:57.763944+00:00'
    params: {}
    version: 3
  - artifact_id: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$732fceb1b1a4:all
    content_hash: sha256:3381c200ece0f7e7ac9f3c9a70feb2bc950b0271d9a3c4d8bfc727bd6a3bfbb5
    path: transformer_AreaNormalization_3381c200ece0.joblib
    chain_path: s5.AreaNormalization[src=0,sub=1]
    source_index: 0
    pipeline_id: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81
    branch_path: []
    step_index: 5
    substep_index: 1
    fold_id: null
    artifact_type: transformer
    class_name: AreaNormalization
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 103
    created_at: '2026-01-08T17:32:57.766523+00:00'
    params: {}
    version: 3
  - artifact_id: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$9f79d59455ab:0
    content_hash: sha256:7c8f54ec316ee3a89b1303b6ffbe1029adf69cc6c78182ed41d4e88e7d1fe48c
    path: model_PLSRegression_7c8f54ec316e.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 117962
    created_at: '2026-01-08T17:32:58.497834+00:00'
    params: {}
    version: 3
  - artifact_id: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$9f79d59455ab:1
    content_hash: sha256:84436d8039fd55c54708a13648c249eb18218765694f212b86f43325a6d078bc
    path: model_PLSRegression_84436d8039fd.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 118261
    created_at: '2026-01-08T17:32:58.502221+00:00'
    params: {}
    version: 3
  - artifact_id: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$9f79d59455ab:2
    content_hash: sha256:d820110b2c3e0bfcc79d9bcbfddc70379ea2ab85d35c385fa46bb9d749f8084b
    path: model_PLSRegression_d820110b2c3e.joblib
    chain_path: s6.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81
    branch_path: []
    step_index: 6
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLS_optuna
    depends_on: []
    format: joblib
    format_version: sklearn==1.6.1
    nirs4all_version: 0.6.2
    size_bytes: 118229
    created_at: '2026-01-08T17:32:58.505159+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  8a49ebb9-068:
    trace_id: 8a49ebb9-068
    pipeline_uid: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81
    created_at: '2026-01-08T17:32:57.726279+00:00'
    steps:
    - step_index: 1
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 2.4979114532470703
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 2
      operator_type: feature_augmentation
      operator_class: None
      operator_config:
        feature_augmentation: null
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 1.798391342163086
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 3
      operator_type: y_processing
      operator_class: MinMaxScaler
      operator_config:
        y_processing: sklearn.preprocessing._data.MinMaxScaler
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$f03a08201cd6:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$f03a08201cd6:all
        by_source: {}
        by_chain:
          s3.y_MinMaxScaler[sub=1]: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$f03a08201cd6:all
        metadata:
          class_name: MinMaxScaler
          name: y_MinMaxScaler_1
      branch_path: []
      branch_name: ''
      duration_ms: 23.90575408935547
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.y_MinMaxScaler[sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 4
      operator_type: config
      operator_class: dict
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 5.524873733520508
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 576
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 1
        - 576
    - step_index: 5
      operator_type: feature_augmentation
      operator_class: None, SavitzkyGolay, None (+1)
      operator_config:
        feature_augmentation:
        - null
        - class: nirs4all.operators.transforms.nirs.SavitzkyGolay
          params:
            window_length: 15
        - null
        - nirs4all.operators.transforms.nirs.AreaNormalization
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$8fbc483aec3b:all
        - 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$732fceb1b1a4:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$8fbc483aec3b:all
            - 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$732fceb1b1a4:all
        by_source:
          0:
          - 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$8fbc483aec3b:all
          - 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$732fceb1b1a4:all
        by_chain:
          s5.SavitzkyGolay[src=0,sub=0]: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$8fbc483aec3b:all
          s5.AreaNormalization[src=0,sub=1]: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$732fceb1b1a4:all
        metadata:
          class_name: AreaNormalization
          name: AreaNormalization_2
      branch_path: []
      branch_name: ''
      duration_ms: 16.08729362487793
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s5.SavitzkyGolay[src=0,sub=0]
      - s5.AreaNormalization[src=0,sub=1]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 576
      output_shape:
      - 60
      - 1728
      input_features_shape:
      - - 60
        - 1
        - 576
      output_features_shape:
      - - 60
        - 3
        - 576
    - step_index: 6
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
        name: PLS_optuna
        finetune_params:
          n_trials: 25
          sample: tpe
          approach: grouped
          eval_mode: avg
          model_params:
            n_components:
            - int
            - 1
            - 25
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$9f79d59455ab:0
        - 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$9f79d59455ab:1
        - 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$9f79d59455ab:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$9f79d59455ab:0
          1: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$9f79d59455ab:1
          2: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$9f79d59455ab:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$9f79d59455ab:0
            - 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$9f79d59455ab:1
            - 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$9f79d59455ab:2
        by_source: {}
        by_chain:
          s6.PLSRegression[sub=0]: 0130_PLS_PP_SELECTION_NO_SAVE_00ef81$9f79d59455ab:2
        metadata:
          class_name: PLSRegression
          custom_name: PLS_optuna
      branch_path: []
      branch_name: ''
      duration_ms: 754.3206214904785
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s6.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 60
      - 1728
      output_shape:
      - 60
      - 1728
      input_features_shape:
      - - 60
        - 3
        - 576
      output_features_shape:
      - - 60
        - 3
        - 576
    model_step_index: 6
    fold_weights: null
    preprocessing_chain: raw|SG|AreaNormalization
    metadata:
      dataset: beer_originalextract_60_ks
      config_name: PLS_PP_SELECTION_NO_SAVE_00ef81
      n_steps: 6
      n_artifacts: 6
