uid: ce13de78-5fd2-4b43-b9b7-642a94ae83c7
pipeline_id: 0001_SOTA_13da21
name: SOTA_13da21
dataset: biscuit_flour_40_randomsplit
created_at: '2026-01-07T10:20:25.198668+00:00'
version: '1.0'
pipeline:
  steps:
  - nirs4all.operators.transforms.nirs.ASLSBaseline
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 1
        random_state: 42
    group: ID
  - split:
      class: nirs4all.operators.splitters.splitters.SPXYGFold
      params:
        n_splits: 3
        random_state: 42
    group: ID
  - class: sklearn.decomposition._pca.PCA
    params:
      n_components: 0.99
      whiten: true
      random_state: 42
  - model:
      framework: autogluon
      params:
        presets: extreme_quality
        time_limit: 3600
        num_bag_folds: 5
        random_state: 42
    name: AutoGluon
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN
  - model:
      class: tabpfn.regressor.TabPFNRegressor
      params:
        n_estimators: 16
        model_path: tabpfn-v2.5-regressor-v2.5_real.ckpt
        device: cpu
        ignore_pretraining_limits: true
        random_state: 42
    name: TabPFN-real
generator_choices: []
metadata: {}
artifacts:
- hash: sha256:26b2ddd51689b4d62afd0d8120bf3701bb34aecf8f7c42b134bb6c3d9b5f3096
  name: ASLSBaseline_1
  path: ASLSBaseline_26b2dd.joblib
  format: joblib
  format_version: ''
  nirs4all_version: 0.5.1
  size: 216
  saved_at: '2026-01-07T10:20:25.217193+00:00'
  step: 1
- hash: sha256:208b4abf19bc85c19bc2aeddeadeadb109e02fb19046691ad6cdfafa02e578a4
  name: PCA_1
  path: PCA_208b4a.joblib
  format: joblib
  format_version: sklearn==1.6.1
  nirs4all_version: 0.5.1
  size: 21824
  saved_at: '2026-01-07T10:20:25.234390+00:00'
  step: 4
- hash: sha256:267a89dc1e95c75258b143aa26a4363c9eb799b7eaf47d4927de022e8e63fef5
  name: AutoGluon_1.pkl
  path: TabularPredictor_267a89.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12296
  saved_at: '2026-01-07T10:20:36.766185+00:00'
  step: 5
- hash: sha256:cc76fdbb1c936d99eef0e76d374cc93d6f0f49798eab813238fce9a1117d8c29
  name: AutoGluon_2.pkl
  path: TabularPredictor_cc76fd.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12296
  saved_at: '2026-01-07T10:20:36.766536+00:00'
  step: 5
- hash: sha256:9eebc802954ab5bfc8ea881f26effbc4bacf47fe96f57443e29cd29598bd7664
  name: AutoGluon_3.pkl
  path: TabularPredictor_9eebc8.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 12296
  saved_at: '2026-01-07T10:20:36.766858+00:00'
  step: 5
- hash: sha256:006d898575231078043cb43b312385dcf817ec15c536a6ff9db6c11e125924e4
  name: TabPFN_1.pkl
  path: TabPFNRegressor_006d89.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 40992779
  saved_at: '2026-01-07T10:20:41.985772+00:00'
  step: 6
- hash: sha256:9b0c3849f0df4b90c0d2bff884932fc99515288bcc59ad979c8055aa6882302d
  name: TabPFN_2.pkl
  path: TabPFNRegressor_9b0c38.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 40994379
  saved_at: '2026-01-07T10:20:42.051024+00:00'
  step: 6
- hash: sha256:b7bb7f9f143a1ec406c4b1adc03308833a840d670ccd2a33a0a5c73f1e8faf57
  name: TabPFN_3.pkl
  path: TabPFNRegressor_b7bb7f.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 40994379
  saved_at: '2026-01-07T10:20:42.115229+00:00'
  step: 6
- hash: sha256:97fe58a50b45637d9590ca2e5076d6284a0731899a69c6e37126f2f6a3bceede
  name: TabPFN-real_1.pkl
  path: TabPFNRegressor_97fe58.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 40992816
  saved_at: '2026-01-07T10:20:53.321119+00:00'
  step: 7
- hash: sha256:48a84e6b52583211ba094dd22c7b78a9b1aa8783edd110dae31dc08b75d6a019
  name: TabPFN-real_2.pkl
  path: TabPFNRegressor_48a84e.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 40994416
  saved_at: '2026-01-07T10:20:53.438539+00:00'
  step: 7
- hash: sha256:4876b76116322b3fe04dd96cfd628a97dc017df16a8d8bafc5ca1e81e91f74d6
  name: TabPFN-real_3.pkl
  path: TabPFNRegressor_4876b7.pkl
  format: cloudpickle
  format_version: ''
  nirs4all_version: 0.5.1
  size: 40994416
  saved_at: '2026-01-07T10:20:53.504445+00:00'
  step: 7
predictions: []
